// ---------------------------------------------------------------------------
// Learner-facing trust indicator for one question: which specification it is
// matched to, whether the content has been checked by a person, where it came
// from, and when it was last reviewed.
//
// A projection over the existing provenance system. It defines no trust rule:
//   tier            ← trustTier (trust-label → trustedAssessmentContent, isFlagship)
//   specification   ← SPEC_MANIFEST (spec.ts) + the topic's own SpecPoint refs
//   last reviewed   ← the question's HumanVerificationRecord, shown only when
//                     the tier is "trusted" (an approval that does not pass the
//                     repo's own validation is never displayed as a review)
//   note            ← trustNoteFor
//
// Honesty: a reference subject or an unreviewed question can never read as
// verified, and AI-generated content says so even when it is practice-safe.
// Pure domain: no React, no storage, no clock.
// ---------------------------------------------------------------------------

import { shortDate } from "./proof-of-improvement";
import { specFor } from "./spec";
import { trustNoteFor, trustTier, type TrustTier } from "./trust-label";
import type { Question, Subject, Topic } from "./types";

const BOARD_NAME: Record<string, string> = { wjec: "WJEC", aqa: "AQA", edexcel: "Edexcel", ocr: "OCR" };

export const TRUST_STATUS_LABEL: Record<TrustTier, string> = {
  trusted: "Checked by a subject expert",
  reference: "Reference material, not checked against the specification",
  unverified: "Not yet checked by a person",
  insufficient: "Not enough checked questions",
};

export interface TrustIndicator {
  tier: TrustTier;
  status: string;
  tone: "success" | "review" | "neutral";
  /** e.g. "WJEC A Level Physics", with the board's spec code. */
  specification: { title: string; code: string | null; refs: string[]; matched: boolean } | null;
  origin: string;
  /** Only for trusted content with a valid human review. */
  lastReviewed: string | null;
  /** One sentence when trust changes what the learner should do. */
  note: string | null;
}

function originOf(question: Pick<Question, "origin" | "source">, tier: TrustTier): string {
  if (question.origin === "ai" || question.source === "generated") {
    return tier === "trusted" ? "Generated by AI, then reviewed by a person" : "Generated by AI and not reviewed by a person";
  }
  if (question.origin === "past-paper" || question.source === "past-paper") return "From a past paper";
  if (question.source === "licensed") return "Licensed exam-board material";
  if (question.source === "import" || question.source === "unreviewed") return "Imported and not reviewed";
  if (question.source === "adapted") return "Adapted from exam-board material";
  return "Written for Revise";
}

export function buildTrustIndicator(input: {
  question: Question;
  subject?: Pick<Subject, "id" | "name" | "specCode" | "contentTier"> | null;
  topics?: ReadonlyArray<Pick<Topic, "id" | "specRef" | "specPoints">>;
}): TrustIndicator {
  const { question } = input;
  const tier = trustTier(question);
  const manifest = specFor(question.subjectId);
  const topicById = new Map((input.topics ?? []).map((t) => [t.id, t] as const));
  const wanted = new Set(question.specPointIds ?? []);
  const refs: string[] = [];
  for (const topicId of question.topicIds) {
    const topic = topicById.get(topicId);
    if (!topic) continue;
    const points = (topic.specPoints ?? []).filter((p) => wanted.has(p.id)).map((p) => p.ref);
    for (const ref of points.length ? points : topic.specRef ? [topic.specRef] : []) if (!refs.includes(ref)) refs.push(ref);
  }
  const subjectName = input.subject?.name ?? null;
  const specification = manifest || subjectName
    ? {
        title: [manifest ? BOARD_NAME[manifest.boardId] ?? manifest.boardId.toUpperCase() : null, manifest?.level ?? null, subjectName].filter(Boolean).join(" "),
        code: manifest?.specCode ?? input.subject?.specCode ?? null,
        refs: refs.slice(0, 3),
        // A reference subject reuses another outline: never call it a specification match.
        matched: tier !== "reference" && input.subject?.contentTier !== "reference" && refs.length > 0,
      }
    : null;
  const review = question.humanVerification;
  const lastReviewed = tier === "trusted" && review?.status === "approved" && review.reviewedAt ? shortDate(review.reviewedAt.slice(0, 10)) : null;
  return {
    tier,
    status: TRUST_STATUS_LABEL[tier],
    tone: tier === "trusted" ? "success" : tier === "reference" ? "neutral" : "review",
    specification,
    origin: originOf(question, tier),
    lastReviewed,
    note: trustNoteFor(question, "proof"),
  };
}
