// Authored AQA GCSE question bank for the four core subjects.
import { defineQuestions } from "./authoring";

const BIOLOGY = "aqa-gcse-biology";
const CHEMISTRY = "aqa-gcse-chemistry";
const MATHS = "aqa-gcse-maths";
const PHYSICS = "aqa-gcse-physics";

const metadata = {
  source: "authored" as const,
  verification: "checked" as const,
  reviewer: "authored/AQA-2024-v1-review",
  lastChecked: "2026-08-18",
  specVersion: "2024-1.0",
};

export const aqaGcseQuestions = defineQuestions([
  {
    ...metadata,
    slug: "aqa-gcse-biology-magnification",
    subjectId: BIOLOGY,
    topics: ["cell-structure"],
    kind: "calculation",
    stem: "A cell image is 36 mm wide. The actual width of the cell is 18 μm.",
    difficulty: 2,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the magnification of the image.",
        marks: 3,
        scheme: [
          "Converts 36 mm to 36 000 μm",
          "Uses magnification = image size ÷ actual size",
          "Magnification = 2 000",
        ],
        specPointIds: ["aqa-gcse-biology.cell-structure.sp-03"],
        learningClaims: ["calculate magnification using consistent units"],
        answer: "36 mm = 36 000 μm. Magnification = 36 000 ÷ 18 = 2 000×.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-osmosis-water-potential",
    subjectId: BIOLOGY,
    topics: ["membranes-transport"],
    kind: "structured",
    stem: "Potato cylinders are placed in solutions with different water potentials. A cylinder gains mass in a solution with a water potential of −100 kPa and loses mass in a solution with a water potential of −400 kPa.",
    difficulty: 3,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Explain why the cylinder gains mass in the −100 kPa solution.",
        marks: 3,
        scheme: [
          "The solution has a higher (less negative) water potential than the cell contents",
          "Water moves down the water-potential gradient by osmosis",
          "Water crosses the partially permeable cell membrane into the cells",
        ],
        specPointIds: ["aqa-gcse-biology.membranes-transport.sp-03"],
        learningClaims: ["explain osmosis using a water-potential gradient"],
        answer: "The −100 kPa solution has a higher, less negative water potential than the potato cells. Water therefore moves into the cells down the water-potential gradient by osmosis through the partially permeable membrane, increasing the mass.",
      },
      {
        prompt: "State what the water potential of the cells is likely to be at the solution where there is no change in mass.",
        marks: 1,
        scheme: ["It is equal to the water potential of the solution"],
        specPointIds: ["aqa-gcse-biology.membranes-transport.sp-03"],
        learningClaims: ["identify the isotonic point from a mass-change investigation"],
        answer: "At zero mass change there is no net movement of water, so the cell and solution have equal water potentials.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-enzyme-inhibition",
    subjectId: BIOLOGY,
    topics: ["enzymes"],
    kind: "structured",
    stem: "An enzyme reaction reaches the same maximum rate without an inhibitor and with inhibitor X. With inhibitor X, a higher substrate concentration is needed to reach the maximum rate.",
    difficulty: 3,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Identify inhibitor X and explain the evidence.",
        marks: 3,
        scheme: [
          "X is a competitive inhibitor",
          "It competes with substrate for the active site",
          "Increasing substrate concentration outcompetes it, so Vmax is unchanged",
        ],
        specPointIds: ["aqa-gcse-biology.enzymes.sp-04"],
        learningClaims: ["distinguish competitive inhibition from non-competitive inhibition"],
        answer: "X is a competitive inhibitor. It competes with substrate for the active site, so more substrate is needed to achieve a given rate. At a sufficiently high substrate concentration the substrate outcompetes the inhibitor, so the same Vmax is reached.",
      },
      {
        prompt: "Explain why increasing temperature above the optimum reduces the rate.",
        marks: 3,
        scheme: [
          "Bonds maintaining the enzyme's tertiary structure are disrupted",
          "The active site changes shape and is no longer complementary",
          "Fewer enzyme-substrate complexes form and the enzyme is denatured",
        ],
        specPointIds: ["aqa-gcse-biology.enzymes.sp-03"],
        learningClaims: ["explain how temperature affects enzyme activity"],
        answer: "Above the optimum, increased molecular vibration disrupts bonds maintaining the enzyme's tertiary structure. The active site changes shape, so fewer enzyme-substrate complexes form and the enzyme is denatured.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-protein-synthesis",
    subjectId: BIOLOGY,
    topics: ["nucleic-acids"],
    kind: "extended",
    stem: "A gene contains the instructions for a polypeptide. Explain how the information in the gene is used to make the polypeptide.",
    difficulty: 4,
    aos: ["AO1"],
    parts: [
      {
        prompt: "Describe transcription and translation, including the roles of mRNA, tRNA and the ribosome.",
        marks: 6,
        scheme: [
          "The DNA base sequence is used as a template to make a complementary mRNA strand",
          "mRNA leaves the nucleus and attaches to a ribosome",
          "The ribosome reads the mRNA in codons",
          "tRNA molecules carry specific amino acids and have complementary anticodons",
          "Amino acids are joined by peptide bonds",
          "The polypeptide folds into a protein with a specific shape",
        ],
        specPointIds: ["aqa-gcse-biology.nucleic-acids.sp-02"],
        learningClaims: ["describe transcription and translation in protein synthesis"],
        answer: "During transcription, one DNA strand acts as a template for a complementary mRNA strand. The mRNA leaves the nucleus and attaches to a ribosome. The ribosome reads its codons; tRNA molecules with complementary anticodons bring specific amino acids. The amino acids are joined by peptide bonds, and the resulting polypeptide folds into a protein.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-photosynthesis-limiting-factor",
    subjectId: BIOLOGY,
    topics: ["photosynthesis"],
    kind: "structured",
    stem: "The rate of photosynthesis increases as light intensity rises, then becomes constant even when the light intensity is increased further.",
    difficulty: 3,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Explain the shape of the graph.",
        marks: 3,
        scheme: [
          "At low light intensity, light is the limiting factor",
          "Increasing light supplies more energy for the light-dependent reactions",
          "At higher intensity another factor such as carbon dioxide concentration or temperature becomes limiting",
        ],
        specPointIds: ["aqa-gcse-biology.photosynthesis.sp-04"],
        learningClaims: ["explain a limiting-factor graph for photosynthesis"],
        answer: "At low light intensity, light limits the rate, so increasing it increases the rate of photosynthesis. Once light is no longer limiting, another factor such as carbon dioxide concentration or temperature limits the rate, producing a plateau.",
      },
      {
        prompt: "State one variable that should be controlled when investigating this relationship.",
        marks: 1,
        scheme: ["Carbon dioxide concentration, temperature, plant species or leaf area"],
        specPointIds: ["aqa-gcse-biology.photosynthesis.sp-05"],
        learningClaims: ["identify a control variable in a photosynthesis investigation"],
        answer: "Temperature should be controlled, because changing it would also change enzyme activity and the rate of photosynthesis.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-blood-glucose",
    subjectId: BIOLOGY,
    topics: ["homeostasis"],
    kind: "structured",
    stem: "A person's blood glucose concentration rises after a meal containing carbohydrate.",
    difficulty: 3,
    aos: ["AO1", "AO2"],
    parts: [
      {
        prompt: "Explain how the body returns blood glucose concentration towards its normal level.",
        marks: 4,
        scheme: [
          "The pancreas detects the rise in blood glucose concentration",
          "Beta cells release insulin",
          "Cells increase glucose uptake and the liver converts glucose to glycogen",
          "Blood glucose concentration falls towards the set point by negative feedback",
        ],
        specPointIds: ["aqa-gcse-biology.homeostasis.sp-02"],
        learningClaims: ["explain insulin control of blood glucose concentration"],
        answer: "The pancreas detects the rise in blood glucose and beta cells release insulin. Insulin causes body cells to take up more glucose and causes the liver to convert glucose to glycogen for storage. Blood glucose therefore falls back towards its normal level by negative feedback.",
      },
    ],
  },

  {
    ...metadata,
    slug: "aqa-gcse-chemistry-isotopes",
    subjectId: CHEMISTRY,
    topics: ["atomic-structure"],
    kind: "mcq",
    stem: "Which statement about two isotopes of the same element is correct?",
    options: [
      "They have the same number of neutrons",
      "They have the same number of protons but different numbers of neutrons",
      "They have different numbers of protons but the same number of electrons",
      "They have different atomic numbers",
    ],
    correctIndex: 1,
    difficulty: 1,
    aos: ["AO1"],
    parts: [
      {
        prompt: "Select the correct option.",
        marks: 1,
        scheme: ["Isotopes have the same proton number and different neutron numbers"],
        specPointIds: ["aqa-gcse-chemistry.atomic-structure.sp-01"],
        learningClaims: ["define isotopes in terms of proton and neutron number"],
        answer: "Isotopes are atoms of the same element, so they have the same number of protons, but they have different numbers of neutrons.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-moles-calculation",
    subjectId: CHEMISTRY,
    topics: ["moles"],
    kind: "calculation",
    stem: "Calcium carbonate has a relative formula mass of 100.0. A sample has a mass of 5.00 g.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the amount of calcium carbonate in the sample and the amount of hydrochloric acid needed for complete reaction.\n\nCaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂",
        marks: 4,
        scheme: [
          "Amount of CaCO₃ = mass ÷ Mr = 5.00 ÷ 100.0",
          "Amount of CaCO₃ = 0.0500 mol",
          "Uses the 1:2 stoichiometric ratio",
          "Amount of HCl = 0.100 mol",
        ],
        specPointIds: ["aqa-gcse-chemistry.moles.sp-01"],
        learningClaims: ["calculate moles from mass and use a balanced equation"],
        answer: "n(CaCO₃) = 5.00 ÷ 100.0 = 0.0500 mol. The equation requires twice as many moles of HCl, so n(HCl) = 2 × 0.0500 = 0.100 mol.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-ionic-bonding",
    subjectId: CHEMISTRY,
    topics: ["bonding"],
    kind: "extended",
    stem: "Sodium chloride is an ionic compound with a high melting point. Explain how its structure and bonding account for this property.",
    difficulty: 3,
    aos: ["AO1", "AO2"],
    parts: [
      {
        prompt: "Explain the formation of sodium chloride and its high melting point.",
        marks: 5,
        scheme: [
          "A sodium atom loses one electron to form Na⁺",
          "A chlorine atom gains one electron to form Cl⁻",
          "The ions form a giant lattice with a regular arrangement",
          "There are strong electrostatic attractions between oppositely charged ions",
          "A large amount of energy is needed to overcome these attractions",
        ],
        specPointIds: ["aqa-gcse-chemistry.bonding.sp-01"],
        learningClaims: ["explain ionic bonding and the properties of a giant ionic lattice"],
        answer: "Sodium transfers one electron to chlorine, forming Na⁺ and Cl⁻ ions. The ions arrange in a giant regular lattice. Strong electrostatic attractions act between oppositely charged ions throughout the lattice, so much energy is needed to overcome them and melt the compound.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-energetics",
    subjectId: CHEMISTRY,
    topics: ["energetics"],
    kind: "calculation",
    stem: "A reaction heats 100 g of water from 20 °C to 35 °C. The specific heat capacity of water is 4.18 J g⁻¹ °C⁻¹.",
    difficulty: 2,
    calculator: true,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the energy transferred to the water.",
        marks: 3,
        scheme: [
          "Uses q = mcΔT",
          "Substitutes 100 × 4.18 × 15",
          "q = 6 270 J or 6.27 kJ",
        ],
        specPointIds: ["aqa-gcse-chemistry.energetics.sp-01"],
        learningClaims: ["calculate energy transferred using q = mcΔT"],
        answer: "q = mcΔT = 100 × 4.18 × (35 − 20) = 6 270 J = 6.27 kJ.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-acid-titration",
    subjectId: CHEMISTRY,
    topics: ["acids-bases"],
    kind: "calculation",
    stem: "25.0 cm³ of 0.100 mol dm⁻³ sodium hydroxide neutralises 20.0 cm³ of hydrochloric acid.\n\nHCl + NaOH → NaCl + H₂O",
    difficulty: 3,
    calculator: true,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the concentration of the hydrochloric acid.",
        marks: 4,
        scheme: [
          "Moles of NaOH = 0.100 × 0.0250 = 0.00250 mol",
          "The mole ratio is 1:1, so moles of HCl = 0.00250 mol",
          "Converts 20.0 cm³ to 0.0200 dm³",
          "Concentration = 0.00250 ÷ 0.0200 = 0.125 mol dm⁻³",
        ],
        specPointIds: ["aqa-gcse-chemistry.acids-bases.sp-01"],
        learningClaims: ["use a titration equation to calculate an acid concentration"],
        answer: "n(NaOH) = 0.100 × 0.0250 = 0.00250 mol. The ratio is 1:1, so n(HCl) = 0.00250 mol. 20.0 cm³ = 0.0200 dm³, giving c(HCl) = 0.00250 ÷ 0.0200 = 0.125 mol dm⁻³.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-hydrocarbons",
    subjectId: CHEMISTRY,
    topics: ["hydrocarbons"],
    kind: "extended",
    stem: "Crude oil is separated into fractions and used to make fuels and polymers. Compare an alkane with an alkene and explain how an alkene can form a polymer.",
    difficulty: 3,
    aos: ["AO1", "AO2"],
    parts: [
      {
        prompt: "Describe the chemical difference between an alkane and an alkene and explain addition polymerisation.",
        marks: 5,
        scheme: [
          "Alkanes contain only carbon-carbon single bonds",
          "Alkenes contain a carbon-carbon double bond and are unsaturated",
          "The double bond opens when monomers react",
          "Many monomers join to form a long-chain polymer",
          "No small molecule is eliminated in addition polymerisation",
        ],
        specPointIds: ["aqa-gcse-chemistry.hydrocarbons.sp-01"],
        learningClaims: ["distinguish alkanes and alkenes and describe addition polymerisation"],
        answer: "Alkanes contain only C–C single bonds and are saturated. Alkenes contain a C=C double bond and are unsaturated. In addition polymerisation the double bond opens and many alkene monomers join into a long-chain polymer; no small molecule is eliminated.",
      },
    ],
  },

  {
    ...metadata,
    slug: "aqa-gcse-maths-proof-consecutive-product",
    subjectId: MATHS,
    topics: ["proof"],
    kind: "extended",
    stem: "Prove that the product of two consecutive integers is always even.",
    difficulty: 2,
    calculator: false,
    aos: ["AO1", "AO2"],
    parts: [
      {
        prompt: "Give a proof using an integer n.",
        marks: 3,
        scheme: [
          "Represents consecutive integers as n and n + 1",
          "One of any two consecutive integers is even",
          "An even factor makes n(n + 1) divisible by 2",
        ],
        specPointIds: ["aqa-gcse-maths.proof.sp-01"],
        learningClaims: ["use algebraic representation in a proof about consecutive integers"],
        answer: "Let the integers be n and n + 1. One of two consecutive integers must be even, so either n = 2k or n + 1 = 2k for some integer k. Therefore n(n + 1) has a factor of 2 and is always even.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-quadratic-equation",
    subjectId: MATHS,
    topics: ["algebra"],
    kind: "calculation",
    stem: "Solve the equation x² − 7x + 12 = 0.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Find both values of x.",
        marks: 3,
        scheme: [
          "Factorises as (x − 3)(x − 4) = 0",
          "Sets each factor equal to zero",
          "x = 3 or x = 4",
        ],
        specPointIds: ["aqa-gcse-maths.algebra.sp-01"],
        learningClaims: ["solve a quadratic equation by factorisation"],
        answer: "x² − 7x + 12 = (x − 3)(x − 4), so x = 3 or x = 4.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-trigonometry",
    subjectId: MATHS,
    topics: ["trigonometry"],
    kind: "calculation",
    stem: "A right-angled triangle has a hypotenuse of 10 cm and an angle of 35°.",
    difficulty: 2,
    calculator: true,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the side opposite the 35° angle, giving your answer to 3 significant figures.",
        marks: 3,
        scheme: [
          "Chooses sin 35° = opposite ÷ 10",
          "Rearranges to opposite = 10 sin 35°",
          "Opposite = 5.74 cm",
        ],
        specPointIds: ["aqa-gcse-maths.trigonometry.sp-01"],
        learningClaims: ["use sine in a right-angled triangle"],
        answer: "sin 35° = opposite ÷ 10, so opposite = 10 sin 35° = 5.74 cm to 3 significant figures.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-probability-without-replacement",
    subjectId: MATHS,
    topics: ["probability"],
    kind: "calculation",
    stem: "A bag contains 3 red counters and 2 blue counters. Two counters are taken at random without replacement.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Find the probability that both counters are red.",
        marks: 3,
        scheme: [
          "Probability of red first = 3/5",
          "Probability of red second given red first = 2/4",
          "Multiplies to give 3/10",
        ],
        specPointIds: ["aqa-gcse-maths.probability.sp-01"],
        learningClaims: ["calculate a dependent probability without replacement"],
        answer: "P(two red) = 3/5 × 2/4 = 6/20 = 3/10.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-statistical-sample",
    subjectId: MATHS,
    topics: ["statistical-sampling"],
    kind: "structured",
    stem: "A random sample of 50 light bulbs contains 7 defective bulbs.",
    difficulty: 2,
    aos: ["AO1", "AO2", "AO3"],
    parts: [
      {
        prompt: "Use the sample to estimate the proportion of defective bulbs in the full production run.",
        marks: 2,
        scheme: [
          "Uses defective ÷ total",
          "Estimate = 7/50 = 0.14 or 14%",
        ],
        specPointIds: ["aqa-gcse-maths.statistical-sampling.sp-01"],
        learningClaims: ["use a random sample to estimate a population proportion"],
        answer: "Estimated proportion = 7 ÷ 50 = 0.14, so about 14% of the bulbs are defective.",
      },
      {
        prompt: "Explain why a random sample is preferable to selecting the first 50 bulbs made.",
        marks: 2,
        scheme: [
          "Every bulb has an equal chance of selection",
          "It reduces selection bias and makes the estimate more representative",
        ],
        specPointIds: ["aqa-gcse-maths.statistical-sampling.sp-01"],
        learningClaims: ["explain why random sampling reduces selection bias"],
        answer: "Random sampling gives each bulb an equal chance of selection, reducing selection bias and making the sample more representative of the whole production run.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-kinematics",
    subjectId: MATHS,
    topics: ["kinematics"],
    kind: "calculation",
    stem: "A car increases its speed uniformly from 5 m s⁻¹ to 17 m s⁻¹ in 6 seconds.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the acceleration and the distance travelled.",
        marks: 4,
        scheme: [
          "Acceleration = (17 − 5) ÷ 6 = 2 m s⁻²",
          "Uses average speed = (5 + 17) ÷ 2",
          "Average speed = 11 m s⁻¹",
          "Distance = 11 × 6 = 66 m",
        ],
        specPointIds: ["aqa-gcse-maths.kinematics.sp-01"],
        learningClaims: ["calculate acceleration and distance for uniform acceleration"],
        answer: "a = (17 − 5) ÷ 6 = 2 m s⁻². Average speed = (5 + 17) ÷ 2 = 11 m s⁻¹, so distance = 11 × 6 = 66 m.",
      },
    ],
  },

  {
    ...metadata,
    slug: "aqa-gcse-physics-kinematics",
    subjectId: PHYSICS,
    topics: ["kinematics-dynamics"],
    kind: "calculation",
    stem: "A car accelerates uniformly from rest to 18 m s⁻¹ in 9.0 s.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the acceleration and the distance travelled.",
        marks: 4,
        scheme: [
          "a = (v − u) ÷ t = 18 ÷ 9.0",
          "a = 2.0 m s⁻²",
          "Uses s = ½(u + v)t or s = ½at²",
          "s = 81 m",
        ],
        specPointIds: ["aqa-gcse-physics.kinematics-dynamics.sp-01"],
        learningClaims: ["apply constant-acceleration equations"],
        answer: "a = (18 − 0) ÷ 9.0 = 2.0 m s⁻². s = ½(0 + 18) × 9.0 = 81 m.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-energy-efficiency",
    subjectId: PHYSICS,
    topics: ["energy-power"],
    kind: "calculation",
    stem: "A 50 kg load is lifted vertically through 8.0 m in 10 s. The motor takes in 500 W. Use g = 9.81 N kg⁻¹.",
    difficulty: 3,
    calculator: true,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the useful power and the efficiency of the motor.",
        marks: 4,
        scheme: [
          "Useful energy = mgh = 50 × 9.81 × 8.0",
          "Useful power = energy ÷ time = 392.4 W",
          "Efficiency = useful power ÷ input power",
          "Efficiency = 0.785 or 78.5%",
        ],
        specPointIds: ["aqa-gcse-physics.energy-power.sp-01"],
        learningClaims: ["calculate useful power and efficiency from gravitational energy"],
        answer: "Useful energy = mgh = 50 × 9.81 × 8.0 = 3 924 J. Useful power = 3 924 ÷ 10 = 392.4 W. Efficiency = 392.4 ÷ 500 = 0.785, or 78.5%.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-hookes-law",
    subjectId: PHYSICS,
    topics: ["materials"],
    kind: "calculation",
    stem: "A spring has a spring constant of 200 N m⁻¹ and is stretched by 3.0 cm within its limit of proportionality.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the force on the spring and the elastic strain energy stored.",
        marks: 4,
        scheme: [
          "Converts 3.0 cm to 0.030 m",
          "Uses F = kx to obtain F = 6.0 N",
          "Uses E = ½kx² or E = ½Fx",
          "Elastic strain energy = 0.090 J",
        ],
        specPointIds: ["aqa-gcse-physics.materials.sp-01"],
        learningClaims: ["apply Hooke's law and calculate elastic strain energy"],
        answer: "x = 0.030 m. F = kx = 200 × 0.030 = 6.0 N. E = ½kx² = ½ × 200 × 0.030² = 0.090 J.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-wave-equation",
    subjectId: PHYSICS,
    topics: ["waves"],
    kind: "calculation",
    stem: "An ultrasound wave has a frequency of 2.5 MHz and a wavelength of 1.5 mm in a material.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the speed of the ultrasound wave.",
        marks: 3,
        scheme: [
          "Converts 2.5 MHz to 2.5 × 10⁶ Hz and 1.5 mm to 1.5 × 10⁻³ m",
          "Uses v = fλ",
          "v = 3.75 × 10³ m s⁻¹",
        ],
        specPointIds: ["aqa-gcse-physics.waves.sp-01"],
        learningClaims: ["use v = fλ with unit conversions"],
        answer: "v = fλ = (2.5 × 10⁶)(1.5 × 10⁻³) = 3.75 × 10³ m s⁻¹.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-series-circuit",
    subjectId: PHYSICS,
    topics: ["electric-circuits"],
    kind: "calculation",
    stem: "A 6.0 Ω resistor and a 3.0 Ω resistor are connected in series to a 12 V supply.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the current in the circuit and the total power supplied.",
        marks: 4,
        scheme: [
          "Series resistance = 6.0 + 3.0 = 9.0 Ω",
          "I = V ÷ R = 12 ÷ 9.0 = 1.33 A",
          "Uses P = VI or P = V²/R",
          "P = 16 W",
        ],
        specPointIds: ["aqa-gcse-physics.electric-circuits.sp-01"],
        learningClaims: ["calculate current and power in a series circuit"],
        answer: "Rtotal = 9.0 Ω. I = 12 ÷ 9.0 = 1.33 A. P = VI = 12 × 1.33 ≈ 16 W (equivalently 12² ÷ 9.0).",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-half-life",
    subjectId: PHYSICS,
    topics: ["nuclear"],
    kind: "calculation",
    stem: "A radioactive sample has a half-life of 6.0 hours and an initial activity of 800 Bq.",
    difficulty: 2,
    calculator: false,
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the activity after 18 hours.",
        marks: 3,
        scheme: [
          "18 hours is three half-lives",
          "Halves 800 Bq three times",
          "Activity = 100 Bq",
        ],
        specPointIds: ["aqa-gcse-physics.nuclear.sp-01"],
        learningClaims: ["calculate activity after whole numbers of half-lives"],
        answer: "18 hours is 18 ÷ 6 = 3 half-lives. Activity = 800 × (1/2)³ = 100 Bq.",
      },
    ],
  },
]);
