// Authored AQA GCSE synoptic question bank spanning multiple topics per item.
import { defineQuestions } from "./authoring";

const BIOLOGY = "aqa-gcse-biology";
const CHEMISTRY = "aqa-gcse-chemistry";
const MATHS = "aqa-gcse-maths";
const PHYSICS = "aqa-gcse-physics";

const metadata = {
  source: "authored" as const,
  verification: "checked" as const,
  reviewer: "authored/AQA-2024-v1-review",
  lastChecked: "2026-08-18",
  specVersion: "2024-1.0",
};

export const aqaGcseSynopticQuestions = defineQuestions([
  {
    ...metadata,
    slug: "aqa-gcse-biology-synoptic-exercise",
    subjectId: BIOLOGY,
    topics: ["gas-exchange", "transport-animals", "respiration"],
    kind: "extended",
    stem: "During a sprint, a student's breathing rate, heart rate and cardiac output increase. Explain how these changes help the muscles release more energy for movement.",
    difficulty: 4,
    aos: ["AO1", "AO2"],
    parts: [
      {
        prompt: "Explain how ventilation and circulation increase oxygen delivery to the muscles.",
        marks: 5,
        scheme: [
          "Increased ventilation refreshes alveolar air",
          "A steep oxygen concentration gradient is maintained across the alveoli",
          "Oxygen diffuses into the blood and binds to haemoglobin",
          "Heart rate and/or stroke volume increase cardiac output",
          "More oxygenated blood is delivered to respiring muscle per minute",
        ],
        specPointIds: [
          "aqa-gcse-biology.gas-exchange.sp-03",
          "aqa-gcse-biology.transport-animals.sp-01",
        ],
        learningClaims: [
          "link ventilation with maintenance of an alveolar diffusion gradient",
          "explain how a concentration gradient drives oxygen diffusion",
          "relate oxygen diffusion to haemoglobin transport",
          "relate heart rate or stroke volume to cardiac output",
          "explain how cardiac output increases oxygen delivery to muscle",
        ],
        answer: "Faster ventilation refreshes the air in the alveoli, maintaining a steep oxygen concentration gradient so oxygen diffuses into the blood. Oxygen binds to haemoglobin. Heart rate and/or stroke volume increase cardiac output, so more oxygenated blood reaches the muscles each minute.",
      },
      {
        prompt: "Explain why anaerobic respiration may occur if the muscles need ATP faster than oxygen can be supplied.",
        marks: 4,
        scheme: [
          "Aerobic respiration cannot supply ATP quickly enough for the demand",
          "Anaerobic respiration releases energy without oxygen",
          "Glucose is converted to lactate in animal cells",
          "Lactate must later be removed using oxygen during recovery",
        ],
        specPointIds: ["aqa-gcse-biology.respiration.sp-01"],
        learningClaims: [
          "relate oxygen supply to the rate of aerobic ATP production",
          "describe anaerobic respiration as energy release without oxygen",
          "identify lactate as the product in animal cells",
          "explain why oxygen is needed after exercise to remove lactate",
        ],
        answer: "If oxygen delivery cannot meet the ATP demand, aerobic respiration cannot supply energy quickly enough. Muscle cells use anaerobic respiration, which releases some energy without oxygen and converts glucose to lactate. Oxygen is needed during recovery to remove the lactate.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-synoptic-glasshouse",
    subjectId: BIOLOGY,
    topics: ["photosynthesis", "transport-plants", "ecosystems"],
    kind: "structured",
    stem: "A grower increases light intensity and carbon dioxide concentration in a glasshouse. The plants are watered through their roots and harvested biomass is measured.",
    difficulty: 4,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Explain why increasing light intensity may increase biomass at first but eventually has little further effect.",
        marks: 4,
        scheme: [
          "Light supplies energy for the light-dependent reactions",
          "Increasing light can increase photosynthetic rate when light is limiting",
          "Another factor such as carbon dioxide concentration, temperature or enzyme activity becomes limiting",
          "Once light is no longer limiting, further increases do not increase carbon fixation or biomass",
        ],
        specPointIds: ["aqa-gcse-biology.photosynthesis.sp-04"],
        learningClaims: [
          "link light energy to the light-dependent reactions",
          "explain why light intensity can be a limiting factor",
          "identify a second limiting factor at higher light intensity",
          "explain why a non-limiting factor cannot increase biomass further",
        ],
        answer: "Light provides energy for the light-dependent reactions, so increasing it raises the rate while light is limiting. At higher intensity, carbon dioxide concentration, temperature or enzyme activity may become limiting. Further light then cannot increase carbon fixation or biomass.",
      },
      {
        prompt: "Explain how water reaches the leaves and how the grower could reduce water loss without stopping carbon dioxide uptake completely.",
        marks: 5,
        scheme: [
          "Water is absorbed by root hair cells and transported in xylem",
          "Transpiration creates a pull through the plant",
          "Water evaporates from mesophyll cells and diffuses through stomata",
          "Reducing temperature, air movement or exposed leaf area reduces the water-vapour gradient",
          "Stomata must remain sufficiently open for carbon dioxide to diffuse in",
        ],
        specPointIds: [
          "aqa-gcse-biology.transport-plants.sp-02",
          "aqa-gcse-biology.photosynthesis.sp-01",
          "aqa-gcse-biology.ecosystems.sp-01",
        ],
        learningClaims: [
          "link root uptake with xylem transport",
          "explain the transpiration pull through a plant",
          "describe the route of water vapour out of a leaf",
          "evaluate environmental changes that reduce transpiration",
          "balance reduced water loss with continued carbon dioxide uptake",
        ],
        answer: "Water enters root hair cells and moves into the xylem. Evaporation from mesophyll cells and diffusion through stomata creates a transpiration pull. The grower could reduce temperature or air movement, or reduce exposed leaf area, to reduce the water-vapour gradient. Stomata cannot be closed completely because carbon dioxide must still enter for photosynthesis.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-synoptic-cystic-fibrosis",
    subjectId: BIOLOGY,
    topics: ["nucleic-acids", "membranes-transport", "gas-exchange"],
    kind: "extended",
    stem: "A mutation changes the CFTR gene. The altered protein transports fewer chloride ions across epithelial cell membranes, and patients produce thick mucus in their airways.",
    difficulty: 4,
    aos: ["AO1", "AO2"],
    parts: [
      {
        prompt: "Explain how a change in the DNA base sequence can produce an altered CFTR protein.",
        marks: 5,
        scheme: [
          "A mutation changes the base sequence of the gene",
          "The altered sequence changes a DNA triplet or mRNA codon",
          "A different tRNA anticodon may bind",
          "A different amino acid sequence may be produced",
          "The protein folds differently and its transport function changes",
        ],
        specPointIds: ["aqa-gcse-biology.nucleic-acids.sp-01"],
        learningClaims: [
          "describe a mutation as a change in a DNA base sequence",
          "link a DNA sequence to an altered mRNA codon",
          "relate codons and anticodons to amino-acid selection",
          "explain how a base change can alter an amino-acid sequence",
          "link protein folding to protein function",
        ],
        answer: "The mutation changes the gene's DNA base sequence, which changes a triplet and the complementary mRNA codon. A different tRNA may therefore bring a different amino acid, changing the polypeptide's amino acid sequence. Its folding can change, producing a CFTR protein with altered transport function.",
      },
      {
        prompt: "Use membrane transport and gas exchange to explain why thick airway mucus makes breathing difficult.",
        marks: 4,
        scheme: [
          "Changed ion transport changes the movement of water across epithelial membranes",
          "Less water is present in the mucus, making it more viscous",
          "Mucus can block or narrow airways and reduce ventilation of alveoli",
          "Less ventilation reduces the oxygen concentration gradient and gas exchange",
        ],
        specPointIds: [
          "aqa-gcse-biology.membranes-transport.sp-02",
          "aqa-gcse-biology.gas-exchange.sp-03",
        ],
        learningClaims: [
          "link ion transport to water movement across a membrane",
          "explain how water content changes mucus viscosity",
          "link airway blockage to reduced ventilation",
          "link reduced ventilation to a smaller alveolar diffusion gradient",
        ],
        answer: "The altered ion transport changes the water movement associated with the epithelial surface, leaving less water in the mucus. It becomes thick and can narrow the airways, reducing ventilation of the alveoli. This reduces the oxygen concentration gradient and therefore gas exchange.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-biology-synoptic-antibiotic-resistance",
    subjectId: BIOLOGY,
    topics: ["genetics-inheritance", "biodiversity"],
    kind: "extended",
    stem: "A bacterial population contains a small number of cells resistant to an antibiotic. After treatment, the proportion of resistant bacteria rises sharply.",
    difficulty: 3,
    aos: ["AO1", "AO2", "AO3"],
    parts: [
      {
        prompt: "Explain how antibiotic treatment can increase the proportion of resistant bacteria without causing the resistance during treatment.",
        marks: 5,
        scheme: [
          "Random mutation or gene transfer produces variation in the population",
          "Some bacteria are resistant before the antibiotic is used",
          "The antibiotic kills susceptible bacteria but resistant bacteria survive",
          "Resistant bacteria reproduce and pass the resistance to offspring",
          "The resistant allele becomes more common by natural selection",
        ],
        specPointIds: [
          "aqa-gcse-biology.genetics-inheritance.sp-01",
          "aqa-gcse-biology.biodiversity.sp-04",
        ],
        learningClaims: [
          "link mutation or gene transfer to genetic variation",
          "recognise that resistant bacteria can pre-exist treatment",
          "explain differential survival during antibiotic selection",
          "link reproduction with inheritance of resistance",
          "explain an increase in allele frequency by natural selection",
        ],
        answer: "Mutation or gene transfer creates variation, so a few bacteria may already carry a resistance allele. The antibiotic kills susceptible cells while resistant cells survive. The survivors reproduce and pass on resistance, so the resistance allele becomes more common by natural selection.",
      },
      {
        prompt: "Suggest two ways of reducing the spread of antibiotic resistance.",
        marks: 2,
        scheme: [
          "Use antibiotics only when prescribed and complete the prescribed course",
          "Reduce transmission through hygiene, isolation, vaccination or infection control",
        ],
        specPointIds: ["aqa-gcse-biology.biodiversity.sp-04"],
        learningClaims: [
          "use antibiotics responsibly to reduce selection pressure",
          "reduce transmission of resistant bacteria with infection-control measures",
        ],
        answer: "Use antibiotics only when needed and complete the prescribed course, while reducing transmission with hygiene, isolation, vaccination or other infection-control measures.",
      },
    ],
  },

  {
    ...metadata,
    slug: "aqa-gcse-chemistry-synoptic-biofuel",
    subjectId: CHEMISTRY,
    topics: ["moles", "energetics", "hydrocarbons"],
    kind: "calculation",
    stem: "Ethanol burns according to the equation C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O. The enthalpy change of combustion is −1367 kJ mol⁻¹ and the relative formula mass of ethanol is 46.0.",
    difficulty: 4,
    calculator: true,
    aos: ["AO1", "AO2", "AO3"],
    parts: [
      {
        prompt: "Calculate the energy released when 0.460 g of ethanol burns completely.",
        marks: 4,
        scheme: [
          "Amount of ethanol = 0.460 ÷ 46.0 = 0.0100 mol",
          "Uses the enthalpy change per mole",
          "Energy = 0.0100 × 1367 kJ",
          "Energy released = 13.67 kJ, or −13.67 kJ for the system",
        ],
        specPointIds: [
          "aqa-gcse-chemistry.moles.sp-01",
          "aqa-gcse-chemistry.energetics.sp-01",
        ],
        learningClaims: [
          "calculate amount of substance from mass and relative formula mass",
          "interpret an enthalpy change per mole",
          "scale an enthalpy change by the amount of substance",
          "distinguish energy released from the sign of the system enthalpy change",
        ],
        answer: "n(ethanol) = 0.460 ÷ 46.0 = 0.0100 mol. Energy released = 0.0100 × 1367 = 13.67 kJ. The enthalpy change for the reacting system is −13.67 kJ.",
      },
      {
        prompt: "Explain why incomplete combustion is dangerous and state one change that favours complete combustion.",
        marks: 3,
        scheme: [
          "Incomplete combustion can produce carbon monoxide",
          "Carbon monoxide is poisonous because it binds to haemoglobin and reduces oxygen transport",
          "A plentiful supply of oxygen or better mixing promotes complete combustion",
        ],
        specPointIds: ["aqa-gcse-chemistry.hydrocarbons.sp-01"],
        learningClaims: [
          "identify carbon monoxide as a product of incomplete combustion",
          "link carbon monoxide to reduced oxygen transport by haemoglobin",
          "explain how oxygen supply or mixing affects combustion completeness",
        ],
        answer: "Incomplete combustion can form poisonous carbon monoxide. It binds strongly to haemoglobin, reducing the blood's ability to transport oxygen. Supplying more oxygen or improving mixing favours complete combustion to carbon dioxide.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-synoptic-haber-process",
    subjectId: CHEMISTRY,
    topics: ["kinetics", "equilibria", "energetics"],
    kind: "extended",
    stem: "The Haber process makes ammonia: N₂(g) + 3H₂(g) ⇌ 2NH₃(g), ΔH = −92 kJ mol⁻¹. An iron catalyst is used at high pressure and a compromise temperature.",
    difficulty: 4,
    aos: ["AO1", "AO2", "AO3"],
    parts: [
      {
        prompt: "Explain the effect of adding the iron catalyst on rate and equilibrium yield.",
        marks: 4,
        scheme: [
          "The catalyst provides an alternative reaction pathway",
          "The pathway has a lower activation energy",
          "Forward and reverse reactions are both faster",
          "The equilibrium position and equilibrium yield are unchanged",
        ],
        specPointIds: [
          "aqa-gcse-chemistry.kinetics.sp-01",
          "aqa-gcse-chemistry.equilibria.sp-01",
        ],
        learningClaims: [
          "link a catalyst to an alternative lower-activation-energy pathway",
          "explain why a lower activation energy increases reaction rate",
          "recognise that catalysts accelerate forward and reverse reactions",
          "distinguish reaching equilibrium faster from changing equilibrium yield",
        ],
        answer: "Iron provides an alternative pathway with lower activation energy, so both the forward and reverse reactions are faster and equilibrium is reached sooner. Because both directions are accelerated, the equilibrium position and final ammonia yield are unchanged.",
      },
      {
        prompt: "Explain why a lower temperature gives a higher equilibrium yield but is not used alone industrially.",
        marks: 4,
        scheme: [
          "The forward reaction is exothermic",
          "Lowering temperature shifts equilibrium in the exothermic forward direction",
          "The equilibrium ammonia yield increases",
          "Particles have less kinetic energy and fewer collisions exceed activation energy, so the rate is too slow or a compromise is required",
        ],
        specPointIds: [
          "aqa-gcse-chemistry.energetics.sp-01",
          "aqa-gcse-chemistry.equilibria.sp-01",
        ],
        learningClaims: [
          "identify the forward reaction as exothermic from a negative enthalpy change",
          "predict the temperature effect on an exothermic equilibrium",
          "link equilibrium position to ammonia yield",
          "link lower temperature to collision frequency and industrial rate",
        ],
        answer: "The forward reaction is exothermic, so lowering the temperature shifts equilibrium towards ammonia and increases the equilibrium yield. However, particles have less kinetic energy and fewer collisions exceed the activation energy, so the rate is too slow. Industry therefore uses a compromise temperature with a catalyst.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-synoptic-electrolysis",
    subjectId: CHEMISTRY,
    topics: ["atomic-structure", "redox", "periodicity"],
    kind: "structured",
    stem: "A student electrolyses molten sodium chloride using inert electrodes. Sodium forms at the cathode and chlorine forms at the anode.",
    difficulty: 3,
    aos: ["AO1", "AO2"],
    parts: [
      {
        prompt: "Write the half-equation at each electrode and identify the oxidation and reduction processes.",
        marks: 4,
        scheme: [
          "Cathode: Na⁺ + e⁻ → Na",
          "Anode: 2Cl⁻ → Cl₂ + 2e⁻",
          "Sodium ions are reduced by gaining electrons",
          "Chloride ions are oxidised by losing electrons",
        ],
        specPointIds: [
          "aqa-gcse-chemistry.redox.sp-01",
          "aqa-gcse-chemistry.periodicity.sp-01",
        ],
        learningClaims: [
          "write a reduction half-equation at the cathode",
          "write an oxidation half-equation at the anode",
          "identify reduction as electron gain",
          "identify oxidation as electron loss",
        ],
        answer: "At the cathode, Na⁺ + e⁻ → Na, so sodium ions are reduced by gaining electrons. At the anode, 2Cl⁻ → Cl₂ + 2e⁻, so chloride ions are oxidised by losing electrons.",
      },
      {
        prompt: "Explain why the electrolyte must be molten rather than solid for this process.",
        marks: 3,
        scheme: [
          "The compound must contain mobile ions to conduct electricity",
          "In a solid ionic lattice the ions are fixed in position",
          "Melting allows ions to move to the oppositely charged electrodes",
        ],
        specPointIds: [
          "aqa-gcse-chemistry.atomic-structure.sp-01",
          "aqa-gcse-chemistry.periodicity.sp-01",
        ],
        learningClaims: [
          "link electrical conduction in an electrolyte to mobile ions",
          "explain why ions cannot move through a solid ionic lattice",
          "link melting to ion movement towards charged electrodes",
        ],
        answer: "Electrolysis requires mobile ions to carry charge. In solid sodium chloride the ions are held in fixed lattice positions, but melting allows them to move to the oppositely charged electrodes.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-chemistry-synoptic-organic-analysis",
    subjectId: CHEMISTRY,
    topics: ["organic-basics", "carbonyls-acids", "spectroscopy"],
    kind: "extended",
    stem: "An unknown compound has molecular formula C₃H₆O. Its infrared spectrum has a strong absorption near 1710 cm⁻¹, and its proton NMR spectrum contains one singlet integrating to six hydrogen atoms.",
    difficulty: 4,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Deduce the structure of the compound and use both pieces of evidence to justify your answer.",
        marks: 5,
        scheme: [
          "The IR absorption near 1710 cm⁻¹ indicates a carbonyl group",
          "The formula has three carbon atoms and six hydrogen atoms",
          "One NMR signal integrating to six H means two equivalent methyl groups",
          "The structure is propanone, CH₃COCH₃",
          "The two methyl groups are equivalent because they are on either side of the carbonyl carbon",
        ],
        specPointIds: [
          "aqa-gcse-chemistry.organic-basics.sp-01",
          "aqa-gcse-chemistry.carbonyls-acids.sp-01",
          "aqa-gcse-chemistry.spectroscopy.sp-01",
        ],
        learningClaims: [
          "use molecular formula information when identifying an organic compound",
          "assign a strong 1710 cm⁻¹ absorption to a carbonyl group",
          "interpret NMR integration as the number of hydrogen atoms",
          "deduce propanone from combined formula and spectra",
          "explain why equivalent methyl groups give one NMR environment",
        ],
        answer: "The strong absorption near 1710 cm⁻¹ indicates a carbonyl group. C₃H₆O is consistent with a ketone, and one NMR signal integrating to six H shows that two equivalent methyl groups are present. The compound is propanone, CH₃COCH₃; the methyl groups are equivalent because they lie on either side of the carbonyl group.",
      },
      {
        prompt: "State the product when propanone reacts with hydrogen cyanide and name the reaction type.",
        marks: 3,
        scheme: [
          "The cyanide ion attacks the electrophilic carbonyl carbon",
          "The reaction is nucleophilic addition",
          "The product is 2-hydroxy-2-methylpropanenitrile",
        ],
        specPointIds: ["aqa-gcse-chemistry.carbonyls-acids.sp-01"],
        learningClaims: [
          "identify nucleophilic attack at a carbonyl carbon",
          "classify reaction of a carbonyl compound with HCN as nucleophilic addition",
          "name the hydroxynitrile product from propanone",
        ],
        answer: "CN⁻ attacks the electrophilic carbonyl carbon. This is nucleophilic addition and forms 2-hydroxy-2-methylpropanenitrile.",
      },
    ],
  },

  {
    ...metadata,
    slug: "aqa-gcse-maths-synoptic-quality-control",
    subjectId: MATHS,
    topics: ["statistical-sampling", "distributions", "probability"],
    kind: "structured",
    stem: "A factory claims that 10% of its components are faulty. An inspector takes a random sample of 20 components and finds 5 faulty.",
    difficulty: 4,
    calculator: true,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "State a suitable binomial model and explain why a random sample is needed.",
        marks: 3,
        scheme: [
          "X ~ B(20, 0.10) under the claim",
          "Each component is treated as a trial with two outcomes and constant probability",
          "Random sampling reduces selection bias and makes the sample more representative",
        ],
        specPointIds: [
          "aqa-gcse-maths.distributions.sp-01",
          "aqa-gcse-maths.statistical-sampling.sp-01",
          "aqa-gcse-maths.probability.sp-01",
        ],
        learningClaims: [
          "specify a binomial model from a claimed population proportion",
          "check the two-outcome and constant-probability assumptions",
          "link random sampling to reduced selection bias",
        ],
        answer: "Under the claim, X ~ B(20, 0.10). Each component is a trial with faulty/not faulty outcomes and the same probability of 0.10. Random selection reduces bias so that the sample is more representative of the production line.",
      },
      {
        prompt: "Set up the probability needed to judge whether 5 faulty components is unusually high, and state what comparison would be made.",
        marks: 3,
        scheme: [
          "Uses P(X ≥ 5) for X ~ B(20, 0.10)",
          "Compares the tail probability with the chosen significance level",
          "A small probability gives evidence against the 10% claim, but does not prove it false",
        ],
        specPointIds: [
          "aqa-gcse-maths.distributions.sp-03",
          "aqa-gcse-maths.statistical-sampling.sp-03",
        ],
        learningClaims: [
          "form an upper-tail binomial probability for observed faulty items",
          "compare a tail probability with a significance level",
          "interpret statistical evidence without claiming certainty",
        ],
        answer: "Calculate P(X ≥ 5) for X ~ B(20, 0.10) and compare it with the chosen significance level. If the probability is small, the result gives evidence against the 10% claim, but it does not prove the claim false.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-synoptic-projectile",
    subjectId: MATHS,
    topics: ["kinematics", "trigonometry", "forces"],
    kind: "calculation",
    stem: "A ball is projected at 20 m s⁻¹ at an angle of 30° above the horizontal. Ignore air resistance and use g = 9.8 m s⁻².",
    difficulty: 4,
    calculator: true,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Resolve the initial velocity into horizontal and vertical components.",
        marks: 4,
        scheme: [
          "Horizontal component = 20 cos 30°",
          "Horizontal component = 17.3 m s⁻¹",
          "Vertical component = 20 sin 30°",
          "Vertical component = 10.0 m s⁻¹",
        ],
        specPointIds: ["aqa-gcse-maths.trigonometry.sp-01"],
        learningClaims: [
          "resolve a velocity vector using cosine",
          "calculate a horizontal component",
          "resolve a velocity vector using sine",
          "calculate a vertical component",
        ],
        answer: "Horizontal component = 20 cos 30° = 17.3 m s⁻¹. Vertical component = 20 sin 30° = 10.0 m s⁻¹.",
      },
      {
        prompt: "Calculate the time taken to reach the highest point and explain which force determines the vertical acceleration.",
        marks: 4,
        scheme: [
          "At the highest point vertical velocity is zero",
          "Uses v = u + at: 0 = 10.0 − 9.8t",
          "t = 1.02 s",
          "The weight of the ball acts downward, giving acceleration 9.8 m s⁻² downward",
        ],
        specPointIds: [
          "aqa-gcse-maths.kinematics.sp-01",
          "aqa-gcse-maths.forces.sp-01",
        ],
        learningClaims: [
          "use zero vertical velocity at the highest point",
          "apply a constant-acceleration equation to vertical motion",
          "calculate time from a resolved velocity component",
          "link weight to downward vertical acceleration",
        ],
        answer: "At the highest point v = 0 vertically. Using 0 = 10.0 − 9.8t gives t = 10.0/9.8 = 1.02 s. The ball's weight acts downward, producing the vertical acceleration of 9.8 m s⁻² downward.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-synoptic-ramp",
    subjectId: MATHS,
    topics: ["coordinate-geometry", "trigonometry", "forces"],
    kind: "calculation",
    stem: "A straight access ramp joins the points (0, 0) and (6, 2), where distances are in metres. A 50 kg trolley rests on the ramp. Use g = 9.8 m s⁻².",
    difficulty: 4,
    calculator: true,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Calculate the gradient and angle of the ramp to the horizontal.",
        marks: 4,
        scheme: [
          "Gradient = change in y ÷ change in x = 2 ÷ 6 = 1/3",
          "Uses tan θ = 1/3",
          "θ = tan⁻¹(1/3)",
          "θ = 18.4°",
        ],
        specPointIds: [
          "aqa-gcse-maths.coordinate-geometry.sp-01",
          "aqa-gcse-maths.trigonometry.sp-01",
        ],
        learningClaims: [
          "calculate a gradient from two coordinate points",
          "relate gradient to the tangent of an angle",
          "rearrange tan θ to find an angle",
          "calculate the inclination of a ramp",
        ],
        answer: "Gradient = (2 − 0)/(6 − 0) = 1/3. Therefore tan θ = 1/3, so θ = tan⁻¹(1/3) = 18.4°.",
      },
      {
        prompt: "Calculate the component of the trolley's weight acting down the ramp.",
        marks: 3,
        scheme: [
          "Weight = mg = 50 × 9.8 = 490 N",
          "Down-ramp component = 490 sin 18.4°",
          "Down-ramp component ≈ 155 N",
        ],
        specPointIds: ["aqa-gcse-maths.forces.sp-01"],
        learningClaims: [
          "calculate weight from mass and gravitational field strength",
          "resolve weight using the ramp angle",
          "calculate the component of a force parallel to a slope",
        ],
        answer: "Weight = 50 × 9.8 = 490 N. The component down the ramp is 490 sin 18.4° ≈ 155 N.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-maths-synoptic-solar-output",
    subjectId: MATHS,
    topics: ["algebra", "sequences", "exponentials"],
    kind: "calculation",
    stem: "A solar panel initially produces 250 W. Its output decreases by 4% each year, so the output is multiplied by 0.96 annually.",
    difficulty: 3,
    calculator: true,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Write the output after n years and calculate the output after 5 years.",
        marks: 4,
        scheme: [
          "Recognises a geometric sequence with first term 250 and common ratio 0.96",
          "Output after n years = 250(0.96)ⁿ",
          "Substitutes n = 5",
          "Output ≈ 203.8 W",
        ],
        specPointIds: [
          "aqa-gcse-maths.sequences.sp-01",
          "aqa-gcse-maths.exponentials.sp-01",
          "aqa-gcse-maths.algebra.sp-01",
        ],
        learningClaims: [
          "identify a geometric sequence from repeated percentage change",
          "form an exponential model from an initial value and multiplier",
          "substitute a whole-number time into the model",
          "calculate a future output using repeated percentage decrease",
        ],
        answer: "The output follows the geometric model Pₙ = 250(0.96)ⁿ. After five years, P₅ = 250(0.96)⁵ ≈ 203.8 W.",
      },
      {
        prompt: "Explain why the model predicts a positive output for every finite number of years but tends towards zero in the long term.",
        marks: 3,
        scheme: [
          "0.96 is positive, so 250(0.96)ⁿ remains positive for finite n",
          "0.96 is less than 1, so repeated multiplication makes the value smaller",
          "The value approaches but never reaches zero as n increases",
        ],
        specPointIds: ["aqa-gcse-maths.exponentials.sp-01"],
        learningClaims: [
          "interpret the sign of an exponential model",
          "link a multiplier between zero and one to decay",
          "explain the long-term behaviour of an exponential sequence",
        ],
        answer: "Since 0.96 is positive, 250(0.96)ⁿ is positive for every finite n. Because the multiplier is less than 1, each year makes the output smaller; as n grows it approaches zero without reaching it.",
      },
    ],
  },

  {
    ...metadata,
    slug: "aqa-gcse-physics-synoptic-satellite",
    subjectId: PHYSICS,
    topics: ["fields", "kinematics-dynamics", "energy-power"],
    kind: "calculation",
    stem: "A satellite moves in a circular orbit of radius 6.8 × 10⁶ m at a constant speed of 7.8 × 10³ m s⁻¹.",
    difficulty: 4,
    calculator: true,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Calculate the centripetal acceleration and identify the force providing it.",
        marks: 4,
        scheme: [
          "Uses a = v²/r",
          "Substitutes (7.8 × 10³)²/(6.8 × 10⁶)",
          "a ≈ 8.9 m s⁻² towards the centre",
          "The gravitational force provides the centripetal force",
        ],
        specPointIds: [
          "aqa-gcse-physics.kinematics-dynamics.sp-01",
          "aqa-gcse-physics.fields.sp-04",
          "aqa-gcse-physics.energy-power.sp-01",
        ],
        learningClaims: [
          "use a = v²/r for circular motion",
          "substitute orbital speed and radius consistently",
          "calculate centripetal acceleration towards the orbit centre",
          "link gravitational force to circular orbital motion",
        ],
        answer: "a = v²/r = (7.8 × 10³)²/(6.8 × 10⁶) ≈ 8.9 m s⁻² towards the centre. The gravitational force supplies the centripetal force.",
      },
      {
        prompt: "Calculate the orbital period and explain why the satellite's speed can remain constant while it accelerates.",
        marks: 4,
        scheme: [
          "Orbital distance is 2πr",
          "Uses period = distance ÷ speed = 2π(6.8 × 10⁶)/(7.8 × 10³)",
          "Period ≈ 5.48 × 10³ s",
          "The acceleration changes the direction of velocity, not its magnitude",
        ],
        specPointIds: [
          "aqa-gcse-physics.kinematics-dynamics.sp-01",
          "aqa-gcse-physics.fields.sp-04",
        ],
        learningClaims: [
          "calculate circular distance from the orbit radius",
          "calculate period from distance and speed",
          "report an orbital period in seconds",
          "distinguish a change in velocity direction from a change in speed",
        ],
        answer: "The orbit length is 2πr, so T = 2π(6.8 × 10⁶)/(7.8 × 10³) ≈ 5.48 × 10³ s. The satellite accelerates because gravity continually changes the direction of its velocity, while its speed remains constant.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-synoptic-medical-imaging",
    subjectId: PHYSICS,
    topics: ["waves", "quantum", "nuclear"],
    kind: "structured",
    stem: "A hospital uses ultrasound to image soft tissue and a gamma-emitting tracer to investigate organ function.",
    difficulty: 4,
    aos: ["AO1", "AO2", "AO3"],
    parts: [
      {
        prompt: "Explain how ultrasound can produce an image of a boundary between two tissues.",
        marks: 4,
        scheme: [
          "Ultrasound is a mechanical wave and travels through the tissue",
          "Part of the wave is reflected at a boundary where acoustic properties change",
          "The probe detects the returning echo",
          "The time delay and known wave speed give the boundary depth",
        ],
        specPointIds: [
          "aqa-gcse-physics.waves.sp-01",
          "aqa-gcse-physics.waves.sp-03",
        ],
        learningClaims: [
          "identify ultrasound as a mechanical wave travelling through tissue",
          "link reflection to a change at a tissue boundary",
          "explain how a probe detects an echo",
          "link echo time and wave speed to depth",
        ],
        answer: "Ultrasound travels through the tissue and part of the wave is reflected where the acoustic properties change at a boundary. The probe detects the returning echo. Using the time delay and the wave speed allows the depth of the boundary to be calculated.",
      },
      {
        prompt: "Explain why a gamma tracer can be detected outside the body but must be used in small amounts.",
        marks: 4,
        scheme: [
          "Gamma radiation is penetrating electromagnetic radiation",
          "It can pass out of the body to reach an external detector",
          "The tracer is radioactive and ionising",
          "Ionising radiation can damage cells and DNA, so exposure and activity should be minimised",
        ],
        specPointIds: [
          "aqa-gcse-physics.quantum.sp-01",
          "aqa-gcse-physics.nuclear.sp-01",
        ],
        learningClaims: [
          "identify gamma radiation as penetrating electromagnetic radiation",
          "link penetration to external detection",
          "identify radioactive gamma emission as ionising",
          "link ionisation to biological risk and dose minimisation",
        ],
        answer: "Gamma radiation is penetrating electromagnetic radiation, so some can pass out of the body and be detected externally. The tracer is radioactive and its radiation is ionising, which can damage cells and DNA. Therefore the activity and exposure time should be kept as low as reasonably practicable.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-synoptic-battery-energy",
    subjectId: PHYSICS,
    topics: ["electric-circuits", "energy-power", "thermal"],
    kind: "calculation",
    stem: "A cell has an emf of 12 V and internal resistance 1.0 Ω. It supplies a 5.0 Ω heater.",
    difficulty: 4,
    calculator: true,
    aos: ["AO2", "AO3"],
    parts: [
      {
        prompt: "Calculate the current, the terminal potential difference and the power delivered to the heater.",
        marks: 5,
        scheme: [
          "Uses ε = I(R + r)",
          "I = 12/(5.0 + 1.0) = 2.0 A",
          "Terminal p.d. = IR = 2.0 × 5.0 = 10 V",
          "Heater power = I²R or VI",
          "Power delivered to heater = 20 W",
        ],
        specPointIds: [
          "aqa-gcse-physics.electric-circuits.sp-02",
          "aqa-gcse-physics.energy-power.sp-01",
        ],
        learningClaims: [
          "use emf and internal resistance to calculate circuit current",
          "calculate current in a circuit with internal resistance",
          "calculate terminal potential difference",
          "select a power equation for a resistive heater",
          "calculate useful electrical power delivered to a component",
        ],
        answer: "ε = I(R + r), so I = 12/(5.0 + 1.0) = 2.0 A. Terminal p.d. = IR = 2.0 × 5.0 = 10 V. Heater power = I²R = 2.0² × 5.0 = 20 W.",
      },
      {
        prompt: "Calculate the power dissipated inside the cell and explain where this energy goes.",
        marks: 3,
        scheme: [
          "Uses P = I²r",
          "P = 2.0² × 1.0 = 4.0 W",
          "Energy is dissipated as thermal energy in the internal resistance of the cell",
        ],
        specPointIds: [
          "aqa-gcse-physics.electric-circuits.sp-02",
          "aqa-gcse-physics.thermal.sp-01",
        ],
        learningClaims: [
          "calculate power loss in internal resistance",
          "substitute current and internal resistance into P = I²r",
          "link electrical energy dissipation to heating in the cell",
        ],
        answer: "Power dissipated inside the cell is P = I²r = 2.0² × 1.0 = 4.0 W. This energy is transferred as thermal energy in the cell's internal resistance.",
      },
    ],
  },
  {
    ...metadata,
    slug: "aqa-gcse-physics-synoptic-crumple-zone",
    subjectId: PHYSICS,
    topics: ["materials", "kinematics-dynamics", "momentum"],
    kind: "extended",
    stem: "A 1 200 kg car travels at 18 m s⁻¹ before a collision. A crumple zone increases the stopping time from 0.20 s to 0.80 s.",
    difficulty: 4,
    aos: ["AO1", "AO2", "AO3"],
    parts: [
      {
        prompt: "Calculate the average force on the car for each stopping time, assuming it stops completely.",
        marks: 5,
        scheme: [
          "Initial momentum = mv = 1 200 × 18 = 21 600 kg m s⁻¹",
          "Change in momentum has magnitude 21 600 kg m s⁻¹",
          "For 0.20 s, F = Δp/Δt = 108 000 N",
          "For 0.80 s, F = Δp/Δt = 27 000 N",
          "The longer stopping time gives the smaller average force",
        ],
        specPointIds: [
          "aqa-gcse-physics.momentum.sp-01",
          "aqa-gcse-physics.kinematics-dynamics.sp-01",
        ],
        learningClaims: [
          "calculate momentum from mass and velocity",
          "calculate the magnitude of momentum change when a car stops",
          "use force as rate of change of momentum for a short stop",
          "calculate average force for two stopping times",
          "compare force when stopping time changes",
        ],
        answer: "Initial momentum = 1 200 × 18 = 21 600 kg m s⁻¹, so the magnitude of Δp is 21 600 kg m s⁻¹. For 0.20 s, F = 21 600/0.20 = 108 000 N. For 0.80 s, F = 21 600/0.80 = 27 000 N. Increasing the stopping time reduces the average force.",
      },
      {
        prompt: "Explain how a crumple zone reduces injury risk using force, deformation and energy transfer.",
        marks: 4,
        scheme: [
          "The crumple zone deforms plastically or absorbs energy",
          "The car takes longer and travels further while stopping",
          "For the same change in momentum, the average force is reduced",
          "Less force is transferred to occupants, while some kinetic energy is dissipated as deformation and thermal energy",
        ],
        specPointIds: [
          "aqa-gcse-physics.materials.sp-03",
          "aqa-gcse-physics.momentum.sp-01",
        ],
        learningClaims: [
          "link plastic deformation to energy absorption",
          "link deformation distance and time to a longer stop",
          "link longer stopping time to lower force for a fixed momentum change",
          "explain energy transfer away from occupants during a collision",
        ],
        answer: "The crumple zone deforms and absorbs kinetic energy, increasing the distance and time over which the car stops. The change in momentum is the same, so the longer stopping time reduces the average force. Less force is transmitted to occupants and energy is dissipated through deformation and heating.",
      },
    ],
  },
]);
