import { defineQuestions } from "./authoring";
const S = "wjec-alevel-biology";
export const biologyExtraQuestions = defineQuestions([
  {
    slug: "bio-biomolecules-tests",
    subjectId: S,
    topics: ["biological-molecules"],
    stem: "You have solutions to test for starch and protein.",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1"],
    parts: [
      { prompt: "Describe the iodine test for starch and the positive result.", marks: 2, scheme: ["Add iodine/KI solution", "Blue-black if starch present"], specPointIds: ["wjec-alevel-biology.biological-molecules.sp-02"], learningClaims: ["describe iodine test for starch"], answer: "Add iodine in potassium iodide; starch forms a blue-black complex." },
      { prompt: "Describe the biuret test for protein.", marks: 2, scheme: ["Add NaOH then CuSO4 (biuret reagent)", "Lilac-purple if peptide bonds present"], specPointIds: ["wjec-alevel-biology.biological-molecules.sp-03"], learningClaims: ["describe biuret test for protein"], answer: "Add sodium hydroxide then copper(II) sulfate; protein gives lilac-purple." },
    ],
  },
  {
    slug: "bio-nucleic-acids-dna",
    subjectId: S,
    topics: ["nucleic-acids"],
    stem: "DNA replication is semi-conservative.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1"],
    parts: [
      { prompt: "Explain what semi-conservative means and outline helicase and polymerase roles.", marks: 5, scheme: ["Each new duplex has one old, one new strand", "Helicase breaks H-bonds and unwinds", "Each strand templates the other", "Polymerase adds complementary nucleotides via phosphodiester bonds", "Enzyme specificity / directionality"], specPointIds: ["wjec-alevel-biology.nucleic-acids.sp-03"], learningClaims: ["explain semi-conservative replication and enzyme roles"], answer: "Each daughter molecule keeps one parental strand. Helicase unwinds, breaking hydrogen bonds; polymerase extends a new strand by complementary base-pairing and phosphodiester bond formation." },
    ],
  },
  {
    slug: "bio-gas-exchange-mammals",
    subjectId: S,
    topics: ["gas-exchange"],
    stem: "A spirometer trace gave tidal volume 0.5 dm3 and vital capacity 4.8 dm3.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Define tidal volume and vital capacity.", marks: 2, scheme: ["Volume per breath at rest", "Maximum volume after maximal inspiration then maximal expiration"], specPointIds: ["wjec-alevel-biology.gas-exchange.sp-01"], learningClaims: ["define tidal volume and vital capacity"], answer: "Tidal volume is volume per resting breath; vital capacity is maximal exhalable volume after maximal inhalation." },
      { prompt: "Explain why the alveolar epithelium is adapted for efficient gas exchange (three features).", marks: 3, scheme: ["Thin (one cell), large surface area, rich capillary supply / short diffusion distance", "Moist surface dissolves gases", "Ventilation and perfusion maintain gradients"], specPointIds: ["wjec-alevel-biology.gas-exchange.sp-03"], learningClaims: ["explain adaptations of exchange surfaces"], answer: "Thin epithelium (short diffusion distance), huge total surface area folded into alveoli, dense capillary network and moist surface to dissolve gases; ventilation refreshes air, perfusion removes O2." },
    ],
  },
  {
    slug: "bio-transport-plants",
    subjectId: S,
    topics: ["transport-plants"],
    stem: "Translocation in phloem was investigated with aphids.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Outline mass flow in phloem.", marks: 4, scheme: ["Sucrose loaded at source lowers water potential", "Water enters by osmosis raising hydrostatic pressure", "Pressure drives flow to sink where sucrose removed", "Companion cells / sieve elements structural note"], specPointIds: ["wjec-alevel-biology.transport-plants.sp-02"], learningClaims: ["outline mass flow in phloem"], answer: "Active loading lowers source water potential; water enters by osmosis, raising pressure. Sucrose removal at sinks keeps the gradient, driving bulk flow through sieve tubes; companion cells support metabolism." },
    ],
  },
  {
    slug: "bio-transport-animals",
    subjectId: S,
    topics: ["transport-animals"],
    stem: "Mammalian circulation is described as closed and double.",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1"],
    parts: [
      { prompt: "Explain what double circulation means and state one advantage over single circulation.", marks: 3, scheme: ["Blood passes through heart twice per circuit (pulmonary and systemic)", "Higher pressure to systemic tissues / separation of oxygenated and deoxygenated", "O2 can be replenished without sacrificing systemic pressure"], specPointIds: ["wjec-alevel-biology.transport-animals.sp-01"], learningClaims: ["explain double circulation advantage"], answer: "Blood goes heart->lungs->heart->body. Pulmonary low-pressure protects lungs while systemic stays high-pressure for efficient delivery; oxygenation does not depress systemic pressure." },
    ],
  },
  {
    slug: "bio-ecosystems-succession",
    subjectId: S,
    topics: ["ecosystems"],
    stem: "A bare rock undergoes primary succession.",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1"],
    parts: [
      { prompt: "Describe the sequence and how biodiversity changes.", marks: 4, scheme: ["Pioneer species / lichens", "Soil formation enabling larger plants", "Seral stages toward climax community", "Biodiversity / complexity / biomass increase; stability rises"], specPointIds: ["wjec-alevel-biology.ecosystems.sp-02"], learningClaims: ["describe primary succession"], answer: "Lichens and mosses colonise bare rock, weathering it and forming soil that supports increasingly large plants through seral stages to a climax community with higher biodiversity and biomass." },
    ],
  },
  {
    slug: "bio-photosynthesis-limiting",
    subjectId: S,
    topics: ["photosynthesis"],
    stem: "Rate of photosynthesis was measured while varying light intensity.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Explain the shape of the rate vs light intensity curve.", marks: 3, scheme: ["Rate rises linearly when light is limiting", "Then plateaus when another factor (CO2 / temperature / RuBisCO) limits", "Compensation point / saturation concept"], specPointIds: ["wjec-alevel-biology.photosynthesis.sp-04"], learningClaims: ["explain limiting-factor curve for photosynthesis"], answer: "At low light, photon supply limits electron flow, so rate rises with light. Beyond saturation, light is no longer limiting; CO2, temperature or enzyme activity caps the rate." },
    ],
  },
  {
    slug: "bio-genetics-linkage",
    subjectId: S,
    topics: ["genetics-inheritance"],
    stem: "In fruit flies, wing length and body colour are linked on the same chromosome.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Explain why recombinant phenotypes are rarer than predicted by independent assortment.", marks: 3, scheme: ["Genes on same chromosome are linked", "Inherited together unless crossing over occurs", "Crossing over frequency depends on map distance; rarer when close"], specPointIds: ["wjec-alevel-biology.genetics-inheritance.sp-04"], learningClaims: ["explain linkage and crossing over"], answer: "Linked genes travel together; recombinants arise only by chiasma formation/crossing over in meiosis I. The closer they are, the fewer recombinant gametes." },
    ],
  },
]);
