import { defineQuestions } from "./authoring";
const S = "wjec-alevel-chemistry";
export const chemistryExtraQuestions = defineQuestions([
  {
    slug: "chem-redox-electrochem",
    subjectId: S,
    topics: ["redox"],
    stem: "A galvanic cell was made from Zn|Zn2+ (0.10 mol dm-3) and Cu|Cu2+ (1.0 mol dm-3). Edeg for Zn2+/Zn = -0.76 V, Cu2+/Cu = +0.34 V.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the standard cell potential Edeg cell.", marks: 2, scheme: ["Edeg = Edeg(cathode)-Edeg(anode)=0.34-(-0.76)", "1.10 V"], specPointIds: ["wjec-alevel-chemistry.redox.sp-04"], learningClaims: ["calculate standard cell potential"], answer: "Edeg = 0.34 - (-0.76)=1.10 V (Cu is cathode)." },
      { prompt: "Predict qualitatively how the cell potential changes if [Zn2+] is increased.", marks: 2, scheme: ["Increased [Zn2+] shifts Zn equilibrium toward Zn2+", "So oxidation is less favourable, E cell decreases (Nernst)"], specPointIds: ["wjec-alevel-chemistry.redox.sp-05"], learningClaims: ["predict concentration effect on cell potential"], answer: "Raising product concentration makes oxidation less favourable; the reaction quotient increases, so by Nernst E falls." },
    ],
  },
  {
    slug: "chem-periodicity-trends",
    subjectId: S,
    topics: ["periodicity"],
    stem: "Trends across period 3 were examined.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1","AO2"],
    parts: [
      { prompt: "Explain why atomic radius decreases across period 3.", marks: 2, scheme: ["Nuclear charge increases", "Electrons added to same shell so shielding barely changes; effective nuclear charge rises so electrons pulled in"], specPointIds: ["wjec-alevel-chemistry.periodicity.sp-01"], learningClaims: ["explain atomic radius trend across period"], answer: "Proton number rises, so nuclear charge and effective nuclear charge rise, pulling the outer shell closer; added electrons go to the same principal quantum shell so extra shielding is minimal." },
      { prompt: "Explain why ionisation energy generally rises across the period but shows a small dip at aluminium and sulfur.", marks: 4, scheme: ["Al outer electron in 3p higher energy than 3s so easier to remove", "S has paired electrons in 3p so repulsion lowers IE relative to P", "General rise is due to increasing Zeff and falling radius", "Structure of electron configuration / subshell stability"], specPointIds: ["wjec-alevel-chemistry.periodicity.sp-02"], learningClaims: ["explain deviations in ionisation energy trend"], answer: "IE tracks Zeff and radius. Al's outer electron is 3p (higher, more shielded than 3s) so its IE dips; S's 3p4 has a paired electron whose mutual repulsion lowers IE vs P (3p3 half-filled)." },
    ],
  },
  {
    slug: "chem-transition-complexes",
    subjectId: S,
    topics: ["transition-metals"],
    stem: "Aqueous copper(II) sulfate is blue; addition of excess ammonia gives a deep blue solution.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1","AO2"],
    parts: [
      { prompt: "Explain, in terms of d-orbitals, why transition metal complexes are coloured.", marks: 3, scheme: ["d orbitals split in ligand field into higher and lower sets", "Photon promotes electron across gap if energy matches", "Transmitted/reflected remainder is observed colour"], specPointIds: ["wjec-alevel-chemistry.transition-metals.sp-03"], learningClaims: ["explain colour in transition metal complexes via d-orbital splitting"], answer: "Ligands split the d-orbital set; a photon of the gap energy promotes an electron. The remaining transmitted wavelengths determine the observed colour." },
      { prompt: "Write the formula of the tetraamminecopper(II) complex formed.", marks: 1, scheme: ["[Cu(NH3)4(H2O)2]2+ or [Cu(NH3)4]2+ accepted"], specPointIds: ["wjec-alevel-chemistry.transition-metals.sp-04"], learningClaims: ["write formula of complex formed"], answer: "[Cu(NH3)4(H2O)2]2+ (often written [Cu(NH3)4]2+)." },
    ],
  },
  {
    slug: "chem-organic-isomerism",
    subjectId: S,
    topics: ["organic-basics"],
    stem: "But-2-ene exists as cis and trans isomers. C4H8O also shows functional group isomerism.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1","AO2"],
    parts: [
      { prompt: "Explain why cis/trans isomerism occurs in but-2-ene and how to distinguish the isomers.", marks: 3, scheme: ["Restricted rotation about C=C double bond", "Different spatial arrangement around C=C", "Physical properties differ e.g. polarity / boiling point / IR; NMR can distinguish"], specPointIds: ["wjec-alevel-chemistry.organic-basics.sp-02"], learningClaims: ["explain cis/trans isomerism due to restricted rotation"], answer: "The C=C prevents rotation, freezing two spatial arrangements (cis substituents same side, trans opposite). They differ in dipole moment and hence boiling point; NMR/IR differentiate them." },
      { prompt: "Give two functional group isomers of formula C4H8O that are neither aldehyde nor ketone.", marks: 2, scheme: ["Any two of: but-3-en-1-ol, methoxypropene (ether), methylcyclopropanol etc.", "Correct formulae and naming"], specPointIds: ["wjec-alevel-chemistry.organic-basics.sp-04"], learningClaims: ["give functional group isomers for given formula"], answer: "e.g. ethoxyethene (CH2=CH-O-C2H5, an ether) and but-3-en-1-ol (CH2=CH-CH2-CH2OH, an alcohol) both C4H8O." },
    ],
  },
  {
    slug: "chem-hydrocarbons-cracking",
    subjectId: S,
    topics: ["hydrocarbons"],
    stem: "Decane C10H22 was cracked thermally.",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1"],
    parts: [
      { prompt: "Give one use of cracking and state the conditions for thermal cracking.", marks: 3, scheme: ["Convert long alkanes to shorter alkanes/alkenes for fuels or feedstock", "High temperature 400-900 C", "High pressure; no catalyst (vs catalytic)"], specPointIds: ["wjec-alevel-chemistry.hydrocarbons.sp-03"], learningClaims: ["state use and conditions for thermal cracking"], answer: "Cracking makes shorter alkanes and alkenes from heavy fractions for petrol and chemical feedstock; thermal cracking uses ~400-900 degC and high pressure without a catalyst." },
    ],
  },
  {
    slug: "chem-carbonyls-mechanism",
    subjectId: S,
    topics: ["carbonyls-acids"],
    stem: "Propanone reacts with HCN in the presence of cyanide ion.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Describe the mechanism and name the product.", marks: 4, scheme: ["Nucleophilic addition", "CN- attacks carbonyl carbon", "Pi bond electrons move onto oxygen, then protonation", "Product 2-hydroxy-2-methylpropanenitrile"], specPointIds: ["wjec-alevel-chemistry.carbonyls-acids.sp-03"], learningClaims: ["describe nucleophilic addition to carbonyl"], answer: "CN- attacks the electrophilic carbonyl carbon (nucleophilic addition); the C=O pi pair shifts to oxygen which is then protonated, giving 2-hydroxy-2-methylpropanenitrile." },
    ],
  },
  {
    slug: "chem-aromatics-nitration",
    subjectId: S,
    topics: ["aromatics-nitrogen"],
    stem: "Benzene is nitrated with concentrated nitric and sulfuric acids.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1","AO2"],
    parts: [
      { prompt: "Describe the mechanism and the role of sulfuric acid.", marks: 4, scheme: ["Sulfuric acid generates NO2+ electrophile", "Electrophilic substitution not addition; aromaticity retained", "Sigma complex intermediate", "Deprotonation restores aromatic ring"], specPointIds: ["wjec-alevel-chemistry.aromatics-nitrogen.sp-01"], learningClaims: ["describe electrophilic substitution mechanism for benzene nitration"], answer: "H2SO4 protonates HNO3 to generate NO2+. Benzene undergoes electrophilic substitution via a sigma complex; deprotonation restores aromaticity to give nitrobenzene." },
    ],
  },
  {
    slug: "chem-spectroscopy-nmr",
    subjectId: S,
    topics: ["spectroscopy"],
    stem: "A compound C3H6O shows one singlet in its 1H NMR and a strong peak at ~1710 cm-1 in IR.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Deduce the structure.", marks: 3, scheme: ["1710 cm-1 = carbonyl (likely ketone)", "One singlet implies all H equivalent -> acetone", "Structure propanone CH3COCH3"], specPointIds: ["wjec-alevel-chemistry.spectroscopy.sp-04"], learningClaims: ["deduce structure from combined IR and NMR data"], answer: "1710 cm-1 indicates C=O (ketone range). A single 1H environment with integration 6H fits propanone (acetone) CH3-CO-CH3 where the two methyl groups are equivalent." },
    ],
  },
  {
    slug: "chem-kinetics-rate-equation",
    subjectId: S,
    topics: ["kinetics"],
    stem: "For the reaction, rate was found proportional to [A]^2 and independent of [B].",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Write the rate equation, the overall order and the units of k.", marks: 3, scheme: ["rate = k[A]2", "Overall order 2", "mol-1 dm3 s-1 (for rate mol dm-3 s-1)"], specPointIds: ["wjec-alevel-chemistry.kinetics.sp-01"], learningClaims: ["write rate equation and deduce units of rate constant"], answer: "rate = k[A]2. Overall order 2. For rate units mol dm-3 s-1 divided by (mol dm-3)2 gives k units mol-1 dm3 s-1." },
    ],
  },
  {
    slug: "chem-mcq-atomic-trend",
    subjectId: S,
    topics: ["atomic-structure"],
    kind: "mcq",
    stem: "Which element has the highest first ionisation energy in period 3?",
    options: ["Sodium", "Magnesium", "Chlorine", "Argon"],
    correctIndex: 3,
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1"],
    parts: [
      { prompt: "Select the correct option.", marks: 1, scheme: ["Argon has highest IE1 across period 3"], specPointIds: ["wjec-alevel-chemistry.atomic-structure.sp-04"], learningClaims: ["predict highest ionisation energy in period"], answer: "Argon — IE1 trends upward across the period due to rising effective nuclear charge, so the noble gas has the highest." },
    ],
  },
]);
