import type { AoCode, Question, QuestionKind } from "@/domain/types";
import { defineQuestion } from "./authoring";

/**
 * Original exam-style material for the core A-level catalogue. These are not
 * copied past-paper questions: each item is written against the current
 * authored curriculum and carries the same provenance as the existing bank.
 */

type Discipline = "biology" | "chemistry" | "maths" | "physics";

interface ExpansionPart {
  prompt: string;
  marks: number;
  scheme: string[];
  answer: string;
  claim: string;
  point?: number;
  aos?: AoCode[];
}

interface ExpansionItem {
  slug: string;
  topic: string;
  stem: string;
  parts: ExpansionPart[];
  kind?: QuestionKind;
  options?: string[];
  correctIndex?: number;
  difficulty?: 1 | 2 | 3 | 4 | 5;
  calculator?: boolean;
}

function part(
  prompt: string,
  marks: number,
  scheme: string[],
  answer: string,
  claim: string,
  point = 1,
  aos: AoCode[] = ["AO2"],
): ExpansionPart {
  return { prompt, marks, scheme, answer, claim, point, aos };
}

function buildQuestion(subjectId: string, item: ExpansionItem): Question {
  const prefix = `${subjectId}.${item.topic}`;
  return defineQuestion({
    slug: `authentic-expansion-${subjectId}-${item.slug}`,
    subjectId,
    topics: [item.topic],
    kind: item.kind,
    stem: item.stem,
    options: item.options,
    correctIndex: item.correctIndex,
    difficulty: item.difficulty,
    calculator: item.calculator,
    source: "authored",
    verification: "checked",
    reviewer: "authored/revise-expansion-review",
    lastChecked: "2026-08-18",
    specVersion: "2024-1.0",
    parts: item.parts.map((current) => ({
      prompt: current.prompt,
      marks: current.marks,
      scheme: current.scheme,
      answer: current.answer,
      aos: current.aos,
      specPointIds: [`${prefix}.sp-${String(current.point ?? 1).padStart(2, "0")}`],
      learningClaims: [current.claim],
    })),
  });
}

const biology: ExpansionItem[] = [
  {
    slug: "bio-reducing-sugar-test",
    topic: "biological-molecules",
    kind: "mcq",
    stem: "Which test gives a brick-red precipitate when a reducing sugar is present?",
    options: ["Biuret test", "Benedict's test", "Iodine test", "Emulsion test"],
    correctIndex: 1,
    difficulty: 2,
    parts: [part("Select the correct test and positive result.", 1, ["Benedict's reagent is heated and gives a brick-red precipitate when reducing sugar is present"], "Benedict's reagent is heated in a water bath; a brick-red precipitate is a positive result.", "identify the test for reducing sugar", 1, ["AO1"])],
  },
  {
    slug: "bio-triglyceride-structure",
    topic: "biological-molecules",
    stem: "A triglyceride and a phospholipid are both made from glycerol and fatty acids.",
    difficulty: 3,
    parts: [part("Explain one structural difference and one consequence for membranes.", 3, ["A triglyceride has three fatty acids; a phospholipid has two and a phosphate-containing group", "The phosphate group is polar/hydrophilic while the fatty acid tails are non-polar/hydrophobic", "Phospholipids form bilayers in water"], "A triglyceride has three fatty acid chains, whereas a phospholipid has two fatty acids and a phosphate-containing group. The phosphate is hydrophilic and the tails hydrophobic, so phospholipids arrange into a bilayer in water.", "compare triglyceride and phospholipid structure and relate it to bilayer formation", 2, ["AO2"])],
  },
  {
    slug: "bio-microscope-resolution",
    topic: "cell-structure",
    stem: "Two images show the same cell. Image A was made with a light microscope and image B with a transmission electron microscope.",
    difficulty: 3,
    parts: [part("Explain why image B can show more detail.", 3, ["The electron microscope uses electrons with a shorter wavelength", "Shorter wavelength gives greater resolving power", "Separate structures can be distinguished at a smaller distance"], "Electrons have a much shorter wavelength than visible light. The smaller wavelength gives the electron microscope greater resolving power, so structures that are close together can be distinguished.", "explain how wavelength affects microscope resolution", 2, ["AO2"])],
  },
  {
    slug: "bio-organelle-evidence",
    topic: "cell-structure",
    stem: "A cell contains many cristae and a high density of ribosomes.",
    difficulty: 2,
    parts: [part("Suggest how these features support the cell's activity.", 3, ["Cristae provide a large inner mitochondrial membrane surface", "This supports electron transport and ATP synthase", "Ribosomes synthesise proteins; a high density supports high protein demand"], "The cristae increase the inner mitochondrial membrane area for electron transport and ATP synthase, supporting ATP production. Ribosomes make proteins, so their abundance indicates a high rate of protein synthesis.", "link organelle structure to energy production and protein synthesis", 1, ["AO2"])],
  },
  {
    slug: "bio-water-potential",
    topic: "membranes-transport",
    stem: "A potato cylinder has a mass of 4.80 g before immersion and 5.04 g afterwards.",
    difficulty: 3,
    parts: [part("Calculate the percentage change in mass and state the direction of net water movement.", 3, ["Change = 0.24 g", "Percentage change = (0.24/4.80) × 100 = 5.0%", "Water moved into the potato cells by osmosis"], "The change is 5.04 − 4.80 = 0.24 g. Percentage change = (0.24/4.80) × 100 = 5.0%. Water moved into the cells because the external solution had a higher water potential.", "calculate percentage mass change and interpret osmosis", 2, ["AO2"] )],
  },
  {
    slug: "bio-active-transport",
    topic: "membranes-transport",
    stem: "Epithelial cells in the small intestine absorb glucose even when the glucose concentration is higher inside the cells than in the lumen.",
    difficulty: 3,
    parts: [part("Explain how this uptake occurs.", 4, ["Glucose is moved against its concentration gradient", "Sodium ions move down their electrochemical gradient through a co-transporter", "The sodium gradient is maintained by the sodium–potassium pump using ATP", "The carrier changes shape and transports glucose into the cell"], "The sodium–potassium pump uses ATP to move sodium out of the epithelial cell, maintaining a low internal sodium concentration. Sodium then enters down its electrochemical gradient through a co-transporter, carrying glucose into the cell against its concentration gradient.", "explain sodium-dependent co-transport of glucose", 3, ["AO2"])],
  },
  {
    slug: "bio-enzyme-temperature-data",
    topic: "enzymes",
    stem: "An enzyme has rates of 2, 5, 9, 14 and 6 arbitrary units at 15, 25, 35, 45 and 55 °C respectively.",
    difficulty: 3,
    parts: [
      part("State the optimum temperature in this investigation.", 1, ["45 °C gives the greatest rate"], "The optimum temperature recorded is 45 °C.", "identify an optimum from rate data", 1, ["AO2"]),
      part("Explain the fall in rate at 55 °C.", 3, ["High temperature breaks bonds maintaining tertiary structure", "The active site changes shape", "Fewer enzyme–substrate complexes form"], "At 55 °C, excess vibration disrupts bonds maintaining the enzyme's tertiary structure. The active site changes shape, so fewer enzyme–substrate complexes form and the rate decreases.", "explain enzyme denaturation above the optimum", 2, ["AO2"]),
    ],
  },
  {
    slug: "bio-competitive-inhibition",
    topic: "enzymes",
    stem: "The same enzyme reaction reaches the same maximum rate with and without inhibitor X, but the inhibited reaction needs more substrate to reach half the maximum rate.",
    difficulty: 4,
    parts: [part("Identify inhibitor X and explain the result.", 4, ["X is a competitive inhibitor", "It competes with substrate for the active site", "Increasing substrate concentration outcompetes X", "The maximum rate is unchanged but apparent affinity is lower"], "X is a competitive inhibitor. It competes with substrate molecules for the enzyme's active site. Increasing substrate concentration can outcompete X, so the same maximum rate is reached, but more substrate is needed at intermediate rates.", "interpret competitive inhibition from Vmax and substrate data", 1, ["AO3"])],
  },
  {
    slug: "bio-transcription-translation",
    topic: "nucleic-acids",
    stem: "A gene contains the base sequence TAC GGA CTT on its template strand.",
    difficulty: 3,
    parts: [part("State the complementary mRNA sequence and describe how it is used in translation.", 4, ["mRNA is AUG CCU GAA", "RNA polymerase forms the mRNA using complementary base pairing", "mRNA attaches to a ribosome", "tRNA anticodons pair with codons and peptide bonds form between amino acids"], "The complementary mRNA sequence is AUG CCU GAA. RNA polymerase makes the transcript, which binds to a ribosome. tRNA molecules pair their anticodons with the mRNA codons and the ribosome joins the amino acids by peptide bonds.", "relate complementary base pairing to transcription and translation", 2, ["AO2"])],
  },
  {
    slug: "bio-exercise-gas-exchange",
    topic: "gas-exchange",
    stem: "During intense exercise, ventilation and cardiac output both increase.",
    difficulty: 3,
    parts: [part("Explain how these changes help maintain oxygen delivery to muscles.", 4, ["Ventilation increases the movement of air into and out of alveoli", "A steeper oxygen concentration gradient is maintained", "Cardiac output increases through increased heart rate and/or stroke volume", "More oxygenated blood reaches respiring muscles per minute"], "Increased ventilation refreshes alveolar air and maintains a steep oxygen diffusion gradient. Increased cardiac output sends more oxygenated blood to the muscles each minute, supporting the increased rate of aerobic respiration.", "explain how ventilation and cardiac output support exercise", 2, ["AO2"])],
  },
  {
    slug: "bio-cardiac-output",
    topic: "transport-animals",
    stem: "A runner's heart rate is 160 beats per minute and stroke volume is 0.090 dm³ per beat.",
    difficulty: 2,
    parts: [part("Calculate the cardiac output in dm³ min⁻¹.", 2, ["Cardiac output = heart rate × stroke volume", "160 × 0.090 = 14.4 dm³ min⁻¹"], "Cardiac output = 160 × 0.090 = 14.4 dm³ min⁻¹.", "calculate cardiac output from heart rate and stroke volume", 1, ["AO2"])],
  },
  {
    slug: "bio-xerophyte-adaptation",
    topic: "transport-plants",
    stem: "A xerophyte has a thick waxy cuticle and stomata in pits.",
    difficulty: 3,
    parts: [part("Explain how these features reduce water loss.", 3, ["The waxy cuticle is waterproof and reduces evaporation from epidermal cells", "Pits trap still, humid air", "The water vapour gradient between the leaf and air is reduced"], "The thick cuticle reduces evaporation from the leaf surface. Sunken stomata trap a layer of humid, still air, reducing the water vapour gradient and therefore diffusion of water vapour out of the leaf.", "explain xerophyte adaptations that reduce transpiration", 2, ["AO2"])],
  },
  {
    slug: "bio-quadrat-sampling",
    topic: "biodiversity",
    stem: "A student estimates the abundance of a plant species across a meadow that contains a shaded edge and an open centre.",
    difficulty: 3,
    parts: [part("Describe a sampling strategy that would give representative data.", 4, ["Use a systematic or random method to place quadrats", "Use a transect or stratified sampling to include both habitats", "Use enough quadrats and keep their area constant", "Calculate a mean/percentage frequency and record environmental variables"], "Use stratified random quadrats so both the shaded edge and open centre are represented. Keep quadrat size constant, use enough repeats, and calculate abundance or percentage frequency for each habitat while recording light intensity.", "design representative quadrat sampling across a habitat", 1, ["AO3"])],
  },
  {
    slug: "bio-respiratory-quotient",
    topic: "respiration",
    stem: "A respiring seed consumes 18 units of oxygen and produces 18 units of carbon dioxide in one hour.",
    difficulty: 2,
    parts: [part("Calculate its respiratory quotient and identify the likely respiratory substrate.", 2, ["RQ = CO₂ produced/O₂ consumed", "RQ = 18/18 = 1.0; carbohydrate is likely"], "RQ = 18/18 = 1.0. An RQ of 1.0 indicates carbohydrate is the likely respiratory substrate.", "calculate respiratory quotient and infer substrate", 2, ["AO2"])],
  },
  {
    slug: "bio-calvin-cycle",
    topic: "photosynthesis",
    kind: "extended",
    stem: "A plant is supplied with carbon dioxide containing a carbon isotope and illuminated for several minutes.",
    difficulty: 4,
    parts: [part("Explain how the isotope can appear in triose phosphate during the light-independent reactions.", 4, ["Carbon dioxide combines with ribulose bisphosphate", "Rubisco catalyses the carboxylation", "An unstable six-carbon compound splits into GP", "GP is reduced to triose phosphate using ATP and reduced NADP"], "The labelled carbon dioxide is fixed when Rubisco catalyses its reaction with ribulose bisphosphate. The unstable six-carbon intermediate splits into GP, which is reduced to triose phosphate using ATP and reduced NADP from the light-dependent reactions.", "explain carbon fixation and reduction in the Calvin cycle", 3, ["AO2"])],
  },
  {
    slug: "bio-blood-glucose-feedback",
    topic: "homeostasis",
    stem: "Blood glucose concentration rises after a carbohydrate-rich meal.",
    difficulty: 3,
    parts: [part("Explain how negative feedback returns it towards the set point.", 4, ["Beta cells in the pancreas detect the increase", "Insulin is released into the blood", "Cells take up more glucose and liver cells convert glucose to glycogen", "Blood glucose falls towards the set point"], "Beta cells detect the raised blood glucose concentration and release insulin. Insulin increases glucose uptake by cells and stimulates glycogenesis in the liver. Blood glucose therefore falls back towards the set point.", "explain insulin control of blood glucose by negative feedback", 1, ["AO2"])],
  },
  {
    slug: "bio-pedigree-probability",
    topic: "genetics-inheritance",
    stem: "A recessive genetic condition affects one child of two unaffected parents.",
    difficulty: 3,
    parts: [part("State the likely genotypes of the parents and the probability that another child is affected.", 3, ["Both unaffected parents are heterozygous carriers", "Cross is Aa × Aa", "Probability of aa is 1/4 or 25%"], "The parents are most likely Aa and Aa. The offspring genotypes occur in a 1 AA : 2 Aa : 1 aa ratio, so the probability of another affected child is 1/4, or 25%.", "deduce carrier genotypes and probability for a recessive condition", 2, ["AO2"])],
  },
  {
    slug: "bio-mutation-consequence",
    topic: "genetics-inheritance",
    stem: "A single base substitution changes a codon in a gene but the resulting protein is unchanged.",
    difficulty: 3,
    parts: [part("Explain how the substitution can have no effect on the protein.", 3, ["The genetic code is degenerate", "The altered codon can still code for the same amino acid", "The amino acid sequence and protein folding/function are unchanged"], "The genetic code is degenerate, so different codons can code for the same amino acid. The substitution may therefore be a silent mutation and leave the amino acid sequence and protein function unchanged.", "explain a silent mutation using the degeneracy of the genetic code", 3, ["AO2"])],
  },
  {
    slug: "bio-energy-transfer",
    topic: "ecosystems",
    stem: "An ecosystem has a gross primary productivity of 18 000 kJ m⁻² year⁻¹ and plant respiratory loss of 7 000 kJ m⁻² year⁻¹.",
    difficulty: 2,
    parts: [part("Calculate the net primary productivity and explain why it is available to consumers.", 3, ["NPP = GPP − respiratory loss", "NPP = 11 000 kJ m⁻² year⁻¹", "It is the chemical energy stored in new plant biomass"], "NPP = 18 000 − 7 000 = 11 000 kJ m⁻² year⁻¹. It is the energy stored in plant biomass after plant respiration and is therefore available to herbivores when they feed.", "calculate NPP and relate it to energy available to consumers", 2, ["AO2"])],
  },
  {
    slug: "bio-practical-validity",
    topic: "biological-molecules",
    stem: "A student compares food samples using colour changes but uses different volumes of sample for each test.",
    difficulty: 3,
    parts: [part("Evaluate one limitation and describe an improvement.", 3, ["Different sample volumes make the colour intensity comparison unfair", "Use the same measured volume and concentration for every sample", "Repeat and compare against known positive and negative controls"], "Different sample volumes could change the intensity of the colour change, so the comparison is not valid. Use the same measured volume and concentration for each sample, with repeats and positive and negative controls.", "evaluate validity in a food-test investigation", 3, ["AO3"])],
  },
  {
    slug: "more-alevel-bio-cell-fractionation",
    topic: "cell-structure",
    stem: "A scientist homogenises liver tissue in a cold, isotonic buffer before centrifuging the homogenate at increasing speeds.",
    difficulty: 4,
    parts: [part("Explain the purpose of the buffer and how differential centrifugation separates organelles.", 4, ["Cold conditions reduce enzyme activity and limit damage to organelles", "An isotonic buffer prevents net water movement and osmotic lysis", "Homogenisation breaks cell membranes and releases organelles", "Increasing speeds pellet larger or denser organelles first, followed by smaller organelles"], "The buffer is kept cold to reduce enzyme activity and damage. It is isotonic so organelles do not gain or lose water by osmosis. Homogenisation releases the organelles, then successive centrifugation speeds pellet the largest or densest organelles before smaller ones.", "explain cell fractionation and ultracentrifugation", 5, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-bio-enzyme-kinetics",
    topic: "enzymes",
    stem: "An enzyme's rate reaches a plateau of 120 arbitrary units. At a substrate concentration of 4.0 mmol dm⁻³, the rate is 60 arbitrary units.",
    difficulty: 4,
    parts: [part("State Vmax and Km for this enzyme.", 3, ["Vmax is the plateau rate, 120 arbitrary units", "Half Vmax is 60 arbitrary units", "The substrate concentration at half Vmax is Km, so Km = 4.0 mmol dm⁻³"], "Vmax = 120 arbitrary units. Since 60 is half of Vmax and occurs at 4.0 mmol dm⁻³ substrate, Km = 4.0 mmol dm⁻³.", "interpret enzyme kinetics graphs including Vmax and Km", 5, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-bio-chi-squared-inheritance",
    topic: "genetics-inheritance",
    stem: "A cross is expected to produce a 3:1 phenotype ratio. The observed offspring are 82 purple and 18 white. Use a 5% critical value of 3.84 for one degree of freedom.",
    difficulty: 4,
    kind: "calculation",
    parts: [part("Calculate χ² and use the critical value to conclude whether the data fit the expected ratio.", 4, ["Expected values are 75 purple and 25 white", "χ² = (82−75)²/75 + (18−25)²/25", "χ² = 2.61", "2.61 is below 3.84, so do not reject the null hypothesis; the difference is not significant"], "The expected values are 75 and 25. χ² = 49/75 + 49/25 = 2.61. Since 2.61 is below 3.84, the null hypothesis is not rejected and the results are consistent with a 3:1 ratio.", "perform chi-squared tests for inheritance", 4, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-bio-mark-release-recapture",
    topic: "ecosystems",
    stem: "A student marks 60 woodlice, releases them, and later catches 50 woodlice, of which 15 are marked.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Estimate the population size and state one assumption of the method.", 3, ["Estimated population = number first caught × number second caught ÷ number marked recaptured", "N = (60 × 50)/15 = 200", "The marked animals must mix back into the population and marking must not affect survival or recapture"], "The estimated population is N = (60 × 50)/15 = 200 woodlice. This assumes the marked woodlice mix randomly back into the population and that marking does not affect their survival or chance of recapture.", "interpret population sampling and mark-release-recapture", 5, ["AO2", "AO3"])],
  },
];

const chemistry: ExpansionItem[] = [
  {
    slug: "chem-isotope-abundance",
    topic: "atomic-structure",
    stem: "An element has two isotopes of masses 35 and 37. A sample contains 75% of the lighter isotope.",
    difficulty: 2,
    calculator: true,
    parts: [part("Calculate the relative atomic mass.", 2, ["Uses weighted mean", "(35 × 75 + 37 × 25)/100 = 35.5"], "Relative atomic mass = (35 × 0.75) + (37 × 0.25) = 35.5.", "calculate a relative atomic mass from isotope abundances", 1, ["AO2"])],
  },
  {
    slug: "chem-titration-concentration",
    topic: "moles",
    stem: "25.00 cm³ of sodium hydroxide is neutralised by 20.40 cm³ of 0.125 mol dm⁻³ hydrochloric acid.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the concentration of the sodium hydroxide.", 3, ["Moles HCl = 0.125 × 0.02040 = 0.00255 mol", "The reaction ratio is 1:1, so moles NaOH = 0.00255 mol", "Concentration = 0.00255/0.02500 = 0.102 mol dm⁻³"], "n(HCl) = 0.125 × 0.02040 = 0.00255 mol. The equation is 1:1, so c(NaOH) = 0.00255/0.02500 = 0.102 mol dm⁻³.", "calculate concentration from a 1:1 acid-base titration", 2, ["AO2"])],
  },
  {
    slug: "chem-shape-polarity",
    topic: "bonding",
    stem: "The molecules BF₃ and NH₃ both contain three covalent bonds around the central atom.",
    difficulty: 3,
    parts: [part("Explain why BF₃ is non-polar but NH₃ is polar.", 4, ["BF₃ has three bonding pairs and no lone pair, so it is trigonal planar", "Its bond dipoles cancel by symmetry", "NH₃ has three bonding pairs and one lone pair, so it is pyramidal", "Its bond dipoles do not cancel"], "BF₃ is trigonal planar because boron has three bonding pairs and no lone pairs; its symmetrical bond dipoles cancel. NH₃ has a lone pair and is trigonal pyramidal, so the bond dipoles do not cancel and it has a net dipole.", "use electron-pair repulsion and symmetry to explain molecular polarity", 2, ["AO2"])],
  },
  {
    slug: "chem-calorimetry",
    topic: "energetics",
    stem: "A reaction heats 50.0 g of solution from 21.0 °C to 28.5 °C. The specific heat capacity is 4.18 J g⁻¹ K⁻¹ and 0.0200 mol reacts.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the molar enthalpy change, assuming no heat is lost.", 3, ["q = mcΔT = 50.0 × 4.18 × 7.5 = 1567.5 J", "The reaction released heat because the solution warmed", "ΔH = −1.5675/0.0200 = −78.4 kJ mol⁻¹"], "q = 50.0 × 4.18 × 7.5 = 1567.5 J. The reaction released this heat, so ΔH = −1.5675/0.0200 = −78.4 kJ mol⁻¹.", "calculate enthalpy change from calorimetry data", 2, ["AO2"])],
  },
  {
    slug: "chem-initial-rate",
    topic: "kinetics",
    stem: "Doubling the concentration of reactant A doubles the initial rate, while doubling B has no effect.",
    difficulty: 3,
    parts: [part("Write the rate equation and state the overall order.", 2, ["Rate = k[A]", "Overall order is one"], "The rate equation is rate = k[A]. The reaction is first order overall.", "deduce a rate equation from concentration changes", 1, ["AO2"])],
  },
  {
    slug: "chem-arrhenius-catalyst",
    topic: "kinetics",
    stem: "A catalyst is added to a reaction mixture.",
    difficulty: 3,
    parts: [part("Explain how the catalyst changes the reaction rate without changing the equilibrium position.", 3, ["It provides an alternative reaction pathway", "The pathway has a lower activation energy", "It lowers the activation energy for both forward and reverse reactions"], "The catalyst provides an alternative pathway with lower activation energy. Both the forward and reverse reactions are accelerated, so equilibrium is reached sooner but the equilibrium composition is unchanged.", "explain catalytic effect on rate and equilibrium", 2, ["AO2"])],
  },
  {
    slug: "chem-kc-interpretation",
    topic: "equilibria",
    stem: "For an exothermic reversible reaction, the equilibrium yield of products falls when the temperature is increased.",
    difficulty: 3,
    parts: [part("Explain this observation using Le Chatelier's principle.", 3, ["Increasing temperature adds heat", "The equilibrium shifts in the endothermic direction", "For an exothermic forward reaction this is the reverse direction, reducing product yield"], "Increasing temperature favours the endothermic direction because the system opposes the added heat. Since the forward reaction is exothermic, equilibrium shifts backwards and the product yield decreases.", "explain the temperature effect on an exothermic equilibrium", 1, ["AO2"])],
  },
  {
    slug: "chem-buffer-action",
    topic: "acids-bases",
    kind: "extended",
    stem: "A buffer contains ethanoic acid and sodium ethanoate.",
    difficulty: 4,
    parts: [part("Explain how the buffer resists a small addition of hydrochloric acid.", 3, ["Added H⁺ reacts with ethanoate ions", "Ethanoic acid is formed", "Most H⁺ is removed, so the pH changes only slightly"], "The added H⁺ reacts with ethanoate ions: CH₃COO⁻ + H⁺ → CH₃COOH. Most of the added hydrogen ions are removed from solution, so the pH falls only slightly.", "explain how a weak-acid buffer resists added acid", 2, ["AO2"])],
  },
  {
    slug: "chem-redox-disproportionation",
    topic: "redox",
    stem: "Chlorine reacts with cold aqueous sodium hydroxide to form chloride and chlorate(I) ions.",
    difficulty: 4,
    parts: [part("Explain why this is a disproportionation reaction.", 3, ["Chlorine starts at oxidation state 0", "Some chlorine is reduced to chloride at −1", "Some chlorine is oxidised to chlorate(I) at +1"], "Chlorine has oxidation state 0. It is reduced to chloride, −1, and another portion is oxidised to chlorate(I), +1, so the same element is both oxidised and reduced.", "identify disproportionation using oxidation states", 1, ["AO2"])],
  },
  {
    slug: "chem-periodicity-radius",
    topic: "periodicity",
    stem: "The atomic radius decreases across period 3.",
    difficulty: 2,
    parts: [part("Explain this trend.", 3, ["Nuclear charge increases across the period", "Electrons are added to the same principal shell, so shielding changes little", "Effective nuclear charge increases and attracts electrons more strongly"], "The number of protons increases while added electrons enter the same shell, so shielding changes only slightly. Effective nuclear charge rises and the outer electrons are pulled closer to the nucleus.", "explain the atomic-radius trend across a period", 1, ["AO2"])],
  },
  {
    slug: "chem-transition-colour",
    topic: "transition-metals",
    stem: "Aqueous copper(II) ions form a blue complex, while a different ligand produces a green complex.",
    difficulty: 3,
    parts: [part("Explain why changing the ligand can change the observed colour.", 3, ["Ligands cause the d-orbitals to split into different energy levels", "A photon is absorbed when an electron moves between the levels", "Changing ligand changes the energy gap and therefore the wavelength absorbed"], "Ligands create a ligand field that splits the d-orbitals. The absorbed photon promotes an electron across this gap. A different ligand changes the gap and the wavelength absorbed, so the complementary colour observed changes.", "explain ligand-dependent colour in transition-metal complexes", 3, ["AO2"])],
  },
  {
    slug: "chem-organic-isomerism",
    topic: "organic-basics",
    stem: "Two compounds have molecular formula C₃H₆O but different functional groups.",
    difficulty: 3,
    parts: [part("Give one aldehyde and one ketone that fit the formula, and name the type of isomerism.", 3, ["Propanal is an aldehyde with formula C₃H₆O", "Propanone is a ketone with formula C₃H₆O", "They are functional-group isomers"], "One pair is propanal, CH₃CH₂CHO, and propanone, CH₃COCH₃. They have the same molecular formula but different functional groups, so they are functional-group isomers.", "identify functional-group isomers from a molecular formula", 2, ["AO2"])],
  },
  {
    slug: "chem-alkene-addition",
    topic: "hydrocarbons",
    stem: "Propene reacts with hydrogen bromide to form a major and a minor product.",
    difficulty: 3,
    parts: [part("Name the mechanism and explain why 2-bromopropane is the major product.", 4, ["The mechanism is electrophilic addition", "The pi bond attacks Hδ+ and a carbocation forms", "The secondary carbocation is more stable than a primary carbocation", "Bromide attacks the more stable intermediate to give 2-bromopropane"], "This is electrophilic addition. The alkene pi bond attacks the hydrogen, giving the more stable secondary carbocation when H adds to the terminal carbon. Bromide then attacks the carbocation, producing mainly 2-bromopropane.", "explain regioselectivity in electrophilic addition", 2, ["AO2"])],
  },
  {
    slug: "chem-ester-hydrolysis",
    topic: "carbonyls-acids",
    stem: "Ethyl ethanoate is heated under reflux with aqueous sodium hydroxide.",
    difficulty: 3,
    parts: [part("State the products and explain why the reaction is effectively complete.", 3, ["Ethanol and sodium ethanoate are formed", "Hydroxide attacks the ester carbonyl and the tetrahedral intermediate collapses", "The carboxylate salt is not readily re-esterified under these conditions"], "The products are ethanol and sodium ethanoate. Hydroxide attacks the carbonyl and the intermediate breaks down; formation of the stable carboxylate ion prevents the reverse esterification, so the reaction is effectively complete.", "explain alkaline ester hydrolysis and its products", 2, ["AO2"])],
  },
  {
    slug: "chem-nitration-benzene",
    topic: "aromatics-nitrogen",
    stem: "Benzene is nitrated using concentrated nitric acid and concentrated sulfuric acid.",
    difficulty: 3,
    parts: [part("Describe the role of sulfuric acid and name the mechanism.", 3, ["Sulfuric acid protonates nitric acid", "The nitronium ion, NO₂⁺, is generated", "Benzene undergoes electrophilic substitution and aromaticity is restored"], "Sulfuric acid protonates nitric acid, enabling formation of the nitronium ion, NO₂⁺. Benzene undergoes electrophilic substitution through a sigma complex, then loses H⁺ to restore aromaticity.", "describe electrophile generation and nitration of benzene", 1, ["AO2"])],
  },
  {
    slug: "chem-ir-identification",
    topic: "spectroscopy",
    stem: "An unknown compound has a strong infrared absorption near 1715 cm⁻¹ and no broad absorption between 2500 and 3300 cm⁻¹.",
    difficulty: 3,
    parts: [part("What functional group is indicated, and which additional spectrum would distinguish an aldehyde from a ketone?", 3, ["The absorption indicates a carbonyl group, C=O", "Absence of the broad acid O–H range makes a carboxylic acid unlikely", "Use proton NMR: an aldehyde proton appears around 9–10 ppm"], "The absorption indicates a carbonyl group. A proton NMR spectrum would distinguish the compounds: an aldehyde has a characteristic proton signal around 9–10 ppm, whereas a ketone does not.", "interpret IR and proton NMR data to identify a carbonyl compound", 2, ["AO2"])],
  },
  {
    slug: "chem-percentage-yield",
    topic: "moles",
    stem: "A reaction has a theoretical yield of 12.5 g and produces 9.40 g of purified product.",
    difficulty: 2,
    kind: "calculation",
    parts: [part("Calculate the percentage yield and give one chemical reason why it is below 100%.", 3, ["Percentage yield = actual/theoretical × 100", "9.40/12.5 × 100 = 75.2%", "Some reactants may undergo side reactions or product may be lost during purification"], "Percentage yield = (9.40/12.5) × 100 = 75.2%. It may be below 100% because a side reaction occurs or some product is lost during transfer, filtration or purification.", "calculate percentage yield and evaluate an organic synthesis", 1, ["AO2", "AO3"])],
  },
  {
    slug: "chem-equilibrium-pressure",
    topic: "equilibria",
    stem: "For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the pressure is increased at constant temperature.",
    difficulty: 3,
    parts: [part("Predict the effect on the equilibrium yield of ammonia and explain it.", 2, ["Ammonia yield increases", "The equilibrium shifts to the side with fewer gas molecules, opposing the pressure increase"], "The ammonia yield increases. The equilibrium shifts towards the products because there are two moles of gas on the right and four on the left.", "predict pressure effects on a gaseous equilibrium", 2, ["AO2"])],
  },
  {
    slug: "chem-electrode-potential",
    topic: "redox",
    stem: "A cell uses Zn²⁺/Zn with E° = −0.76 V and Cu²⁺/Cu with E° = +0.34 V.",
    difficulty: 2,
    kind: "calculation",
    parts: [part("Calculate E°cell and identify the electrode where reduction occurs.", 2, ["E°cell = E°cathode − E°anode", "0.34 − (−0.76) = +1.10 V; reduction occurs at copper"], "E°cell = 0.34 − (−0.76) = +1.10 V. Copper is the cathode, where Cu²⁺ is reduced.", "calculate standard cell potential and identify the cathode", 1, ["AO2"])],
  },
  {
    slug: "chem-kc-calculation",
    topic: "equilibria",
    kind: "calculation",
    stem: "At equilibrium, [A] = 0.20 mol dm⁻³, [B] = 0.10 mol dm⁻³ and [C] = 0.40 mol dm⁻³ for A(g) + B(g) ⇌ C(g).",
    difficulty: 3,
    parts: [part("Calculate Kc and include its units.", 3, ["Kc = [C]/([A][B])", "Kc = 0.40/(0.20×0.10) = 20", "Units are dm³ mol⁻¹"], "Kc = 0.40/(0.20 × 0.10) = 20 dm³ mol⁻¹.", "calculate an equilibrium constant from concentrations", 2, ["AO2"])],
  },
  {
    slug: "more-alevel-chem-titration-significant-figures",
    topic: "moles",
    stem: "A 25.00 cm³ sample of sodium hydroxide is titrated with 0.1000 mol dm⁻³ hydrochloric acid. The mean titre is 24.60 cm³. The reaction is 1:1.",
    difficulty: 3,
    kind: "calculation",
    calculator: true,
    parts: [part("Calculate the concentration of the sodium hydroxide solution.", 3, ["Moles of HCl = 0.1000 × 24.60/1000 = 2.460 × 10⁻³ mol", "The 1:1 equation gives the same amount of NaOH", "c(NaOH) = 2.460 × 10⁻³/0.02500 = 0.09840 mol dm⁻³"], "Moles of HCl = 0.1000 × 0.02460 = 2.460 × 10⁻³ mol. The same amount of NaOH is present, so its concentration is 2.460 × 10⁻³/0.02500 = 0.09840 mol dm⁻³.", "perform titration calculations including appropriate significant figures", 6, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-chem-calorimetry-validity",
    topic: "energetics",
    stem: "A student burns a fuel beneath a beaker of water to estimate its enthalpy change, but the apparatus is open and some heat warms the surroundings.",
    difficulty: 3,
    parts: [part("Suggest two changes that would improve the calorimetry investigation and explain why they help.", 3, ["Use a lid or draught shield to reduce heat loss to the surroundings", "Stir the water and measure the maximum temperature consistently so the water is at a uniform temperature", "Repeat the measurement and calculate a mean to reduce random error"], "A lid or draught shield reduces heat loss. Stirring gives a uniform water temperature, and repeats allow a mean value to be calculated, reducing random error.", "describe calorimetry experiments and their sources of error", 5, ["AO1", "AO3"])],
  },
  {
    slug: "more-alevel-chem-industrial-compromise",
    topic: "equilibria",
    stem: "The Haber process uses an exothermic reaction between nitrogen and hydrogen to make ammonia. Industry must balance yield, rate, cost and safety.",
    difficulty: 4,
    parts: [part("Explain why industrial conditions are a compromise rather than the conditions that give the maximum equilibrium yield.", 4, ["High pressure increases ammonia yield because there are fewer gas molecules on the product side", "Very high pressure is expensive and creates safety and engineering problems", "A lower temperature favours the exothermic forward reaction but gives a slow rate", "A catalyst allows a faster rate at a moderate temperature but does not change the equilibrium position"], "High pressure favours ammonia because four moles of gas become two, but very high pressure is expensive and hazardous. A low temperature gives a higher yield for the exothermic reaction but is too slow. A catalyst gives a useful rate at a compromise temperature without changing the equilibrium yield.", "explain the compromise conditions in industrial processes", 5, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-chem-propanal-spectra",
    topic: "spectroscopy",
    stem: "An organic compound has formula C₃H₆O. Its IR spectrum has a strong absorption at about 1715 cm⁻¹. Its proton NMR has a triplet for 3H, a quartet for 2H and a singlet near δ 9.8 for 1H.",
    difficulty: 4,
    parts: [part("Deduce the structure and use the spectra to justify your answer.", 4, ["The IR absorption indicates a carbonyl group", "A signal near δ 9.8 indicates an aldehyde proton", "The triplet and quartet indicate a CH₃CH₂ group", "The structure is propanal, CH₃CH₂CHO"], "The absorption near 1715 cm⁻¹ shows a carbonyl group, while the signal near δ 9.8 identifies an aldehyde proton. The triplet and quartet show a CH₃CH₂ group, so the structure is propanal, CH₃CH₂CHO.", "combine spectroscopic data to determine structure", 4, ["AO2", "AO3"])],
  },
];

const maths: ExpansionItem[] = [
  {
    slug: "maths-proof-counterexample",
    topic: "proof",
    stem: "A student claims that n² + n + 41 is prime for every positive integer n.",
    difficulty: 3,
    calculator: false,
    parts: [part("Disprove the claim with a counter-example and explain why one example is sufficient.", 3, ["For n = 40, n² + n + 41 = 1681", "1681 = 41², so it is not prime", "A universal claim is disproved by one valid counter-example"], "For n = 40, the expression is 40² + 40 + 41 = 1681 = 41², which is not prime. One counter-example is enough to disprove a statement quantified over every positive integer.", "use a counter-example to disprove a universal claim", 1, ["AO2"])],
  },
  {
    slug: "maths-quadratic-inequality",
    topic: "algebra",
    stem: "Solve the inequality x² − 5x + 6 < 0.",
    difficulty: 2,
    calculator: false,
    parts: [part("Give the solution set.", 3, ["Factorises as (x − 2)(x − 3)", "Roots are 2 and 3", "The quadratic is negative between the roots: 2 < x < 3"], "(x − 2)(x − 3) < 0, so the solution is 2 < x < 3.", "solve a quadratic inequality", 2, ["AO2"])],
  },
  {
    slug: "maths-circle-tangent",
    topic: "coordinate-geometry",
    stem: "The circle has equation (x − 2)² + (y + 1)² = 25. The point P(5, 3) lies on it.",
    difficulty: 3,
    calculator: false,
    parts: [part("Find the equation of the tangent at P.", 4, ["Centre is (2, −1)", "Gradient of radius CP is (3 − (−1))/(5 − 2) = 4/3", "Tangent gradient is −3/4", "y − 3 = −3/4(x − 5)"], "The centre is (2, −1), so the radius gradient is 4/3. The tangent gradient is −3/4, giving y − 3 = −3/4(x − 5).", "find a tangent to a circle using perpendicular gradients", 2, ["AO2"])],
  },
  {
    slug: "maths-geometric-series",
    topic: "sequences",
    stem: "A geometric sequence has first term 12 and common ratio 0.75.",
    difficulty: 2,
    calculator: false,
    parts: [part("Find the sum to infinity and state why it exists.", 2, ["S∞ = a/(1 − r)", "S∞ = 12/0.25 = 48 because |r| < 1"], "S∞ = 12/(1 − 0.75) = 48. The sum exists because |0.75| < 1.", "calculate a convergent geometric sum to infinity", 1, ["AO2"])],
  },
  {
    slug: "maths-trig-equation",
    topic: "trigonometry",
    stem: "Solve 2 cos² x − 1 = 0 for 0 ≤ x ≤ 2π.",
    difficulty: 3,
    calculator: false,
    parts: [part("Give all solutions in radians.", 3, ["2cos²x = 1, so cos²x = 1/2", "cos x = ±1/√2", "x = π/4, 3π/4, 5π/4, 7π/4"], "cos²x = 1/2, so cos x = ±1/√2. The solutions in [0, 2π] are x = π/4, 3π/4, 5π/4 and 7π/4.", "solve a trigonometric equation over a full interval", 2, ["AO2"])],
  },
  {
    slug: "maths-exponential-half-life",
    topic: "exponentials",
    stem: "A medication concentration is modelled by C = 80e^(−0.12t), where t is in hours.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Find the time taken for the concentration to fall to 20 units.", 3, ["20 = 80e^(−0.12t), so 0.25 = e^(−0.12t)", "ln(0.25) = −0.12t", "t = 11.6 hours"], "0.25 = e^(−0.12t), so t = ln(0.25)/(−0.12) = 11.6 hours to 3 significant figures.", "solve an exponential decay model using logarithms", 3, ["AO2"])],
  },
  {
    slug: "maths-stationary-point",
    topic: "differentiation",
    kind: "extended",
    stem: "The curve y = x³ − 6x² + 9x + 2 has stationary points.",
    difficulty: 4,
    calculator: false,
    parts: [part("Find the stationary points and classify them.", 5, ["dy/dx = 3x² − 12x + 9", "3(x − 1)(x − 3) = 0, so x = 1 or 3", "Coordinates are (1, 6) and (3, 2)", "d²y/dx² = 6x − 12", "At x=1 it is negative (maximum); at x=3 it is positive (minimum)"], "dy/dx = 3x² − 12x + 9 = 3(x − 1)(x − 3), so x = 1 or 3. The points are (1, 6) and (3, 2). Since d²y/dx² = 6x − 12, (1, 6) is a maximum and (3, 2) a minimum.", "find and classify stationary points with first and second derivatives", 2, ["AO2"])],
  },
  {
    slug: "maths-area-between-curves",
    topic: "integration",
    stem: "The curves y = 2x and y = x² meet at x = 0 and x = 2.",
    difficulty: 3,
    calculator: false,
    parts: [part("Find the area enclosed by the curves.", 4, ["Area = ∫₀²(2x − x²) dx", "Antiderivative is x² − x³/3", "Substitution gives 4 − 8/3", "Area = 4/3 square units"], "The line is above the parabola between the intersections, so area = [x² − x³/3]₀² = 4 − 8/3 = 4/3 square units.", "calculate area between two curves", 2, ["AO2"])],
  },
  {
    slug: "maths-vector-collinearity",
    topic: "vectors",
    stem: "A = (1, 2, −1), B = (4, 0, 2) and C = (10, −4, 8).",
    difficulty: 3,
    calculator: false,
    parts: [part("Determine whether A, B and C are collinear.", 3, ["AB = (3, −2, 3)", "AC = (9, −6, 9)", "AC = 3AB, so the points are collinear"], "AB = (3, −2, 3) and AC = (9, −6, 9) = 3AB. Therefore the three points are collinear.", "test collinearity using displacement vectors", 1, ["AO2"])],
  },
  {
    slug: "maths-newton-raphson",
    topic: "numerical",
    stem: "Use xₙ₊₁ = xₙ − f(xₙ)/f′(xₙ) to solve x³ − x − 1 = 0, starting with x₀ = 1.",
    difficulty: 4,
    kind: "calculation",
    parts: [part("Calculate x₁ and x₂.", 3, ["f′(x) = 3x² − 1", "x₁ = 1 − (−1)/2 = 1.5", "x₂ = 1.5 − (1.875−1.5)/(6.75−1) = 1.4348"], "f′(x) = 3x² − 1. x₁ = 1 − (−1)/2 = 1.5. Then x₂ = 1.5 − 0.375/5.75 = 1.4348 (approximately).", "apply Newton-Raphson iteration", 2, ["AO2"])],
  },
  {
    slug: "maths-hypothesis-test",
    topic: "statistical-sampling",
    stem: "A manufacturer claims that 30% of its components fail a stress test. In a sample of 20, six fail.",
    difficulty: 3,
    parts: [part("State suitable hypotheses for a two-tailed test of the claim.", 2, ["H₀: p = 0.30", "H₁: p ≠ 0.30"], "H₀: p = 0.30 and H₁: p ≠ 0.30, where p is the population failure probability.", "formulate null and alternative hypotheses for a proportion", 2, ["AO1"])],
  },
  {
    slug: "maths-conditional-probability",
    topic: "probability",
    stem: "P(A) = 0.4, P(B) = 0.5 and P(A ∩ B) = 0.2.",
    difficulty: 2,
    calculator: false,
    parts: [part("Find P(A|B) and state whether A and B are independent.", 3, ["P(A|B) = P(A∩B)/P(B)", "P(A|B) = 0.2/0.5 = 0.4", "P(A)P(B) = 0.20, so the events are independent"], "P(A|B) = 0.2/0.5 = 0.4. Since P(A)P(B) = 0.4 × 0.5 = 0.2 = P(A∩B), A and B are independent.", "calculate conditional probability and test independence", 1, ["AO2"])],
  },
  {
    slug: "maths-binomial-tail",
    topic: "distributions",
    stem: "X has a binomial distribution with n = 12 and p = 0.3.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Write an expression for P(X ≥ 4) and evaluate it to three significant figures.", 3, ["P(X ≥ 4) = 1 − P(X ≤ 3)", "Uses binomial probabilities with n=12 and p=0.3", "P(X ≥ 4) ≈ 0.507"], "P(X ≥ 4) = 1 − [P(X=0)+P(X=1)+P(X=2)+P(X=3)] ≈ 0.507.", "evaluate a binomial upper-tail probability", 2, ["AO2"])],
  },
  {
    slug: "maths-normal-standardise",
    topic: "distributions",
    stem: "The mass of a component is normally distributed with mean 52 g and standard deviation 4 g.",
    difficulty: 2,
    kind: "calculation",
    parts: [part("Find P(M > 60).", 3, ["Standardise: z = (60−52)/4 = 2", "P(Z > 2) = 1 − 0.9772", "Probability = 0.0228"], "z = (60 − 52)/4 = 2. Therefore P(M > 60) = P(Z > 2) = 1 − 0.9772 = 0.0228.", "standardise a normal variable and find a tail probability", 1, ["AO2"])],
  },
  {
    slug: "maths-kinematics-suvat",
    topic: "kinematics",
    stem: "A cyclist starts from rest and accelerates uniformly at 2.4 m s⁻² for 12 seconds.",
    difficulty: 2,
    kind: "calculation",
    parts: [part("Find the final speed and distance travelled.", 3, ["v = u + at = 0 + 2.4×12 = 28.8 m s⁻¹", "s = ut + ½at²", "s = 172.8 m"], "v = 28.8 m s⁻¹. The distance is s = 0 + 0.5 × 2.4 × 12² = 172.8 m.", "apply SUVAT equations to uniform acceleration", 1, ["AO2"])],
  },
  {
    slug: "maths-forces-equilibrium",
    topic: "forces",
    stem: "A 6 kg crate rests on a rough horizontal surface. A horizontal force of 18 N is applied and the crate is on the point of moving.",
    difficulty: 3,
    parts: [part("Find the coefficient of friction.", 3, ["At limiting equilibrium friction = 18 N", "Normal reaction R = 6g", "μ = friction/R = 18/(6g) = 0.306"], "At limiting equilibrium, μR = 18. With R = 6g, μ = 18/(6 × 9.8) = 0.306.", "apply limiting friction and equilibrium", 2, ["AO2"])],
  },
  {
    slug: "maths-binomial-coefficient",
    topic: "sequences",
    stem: "Expand (1 + 2x)^5 up to and including the term in x².",
    difficulty: 2,
    calculator: false,
    parts: [part("Give the expansion.", 3, ["First term 1", "5(2x) = 10x", "10(2x)² = 40x²"], "(1 + 2x)^5 = 1 + 10x + 40x² + terms in x³ and higher.", "use binomial coefficients to expand a power", 2, ["AO2"])],
  },
  {
    slug: "maths-related-rates",
    topic: "differentiation",
    stem: "The radius r of a circular ripple increases at 0.20 m s⁻¹.",
    difficulty: 4,
    parts: [part("Find the rate of increase of its area when r = 3 m.", 3, ["A = πr², so dA/dr = 2πr", "dr/dt = 0.20", "dA/dt = 2π(3)(0.20) = 1.2π m² s⁻¹"], "dA/dt = (dA/dr)(dr/dt) = 2πr × 0.20. At r = 3, dA/dt = 1.2π m² s⁻¹.", "use the chain rule for a connected rate of change", 4, ["AO2", "AO3"])],
  },
  {
    slug: "maths-momentum-impulse",
    topic: "forces",
    stem: "A 0.50 kg ball travelling at 8 m s⁻¹ rebounds in the opposite direction at 6 m s⁻¹.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the magnitude of the impulse on the ball.", 2, ["Change in velocity is −6 − 8 = −14 m s⁻¹", "Impulse magnitude = m|Δv| = 0.50×14 = 7.0 N s"], "Taking the initial direction as positive, Δv = −6 − 8 = −14 m s⁻¹. The impulse magnitude is 0.50 × 14 = 7.0 N s.", "calculate impulse from a reversal of velocity", 3, ["AO2"])],
  },
  {
    slug: "maths-vector-line-intersection",
    topic: "vectors",
    stem: "The lines r = (1, 2, 0) + λ(2, −1, 1) and r = (7, −1, 3) + μ(−1, 1, 0) are given.",
    difficulty: 4,
    calculator: false,
    parts: [part("The lines r = (1, 2, 0) + λ(2, −1, 1) and r = (7, −1, 3) + μ(−1, 1, 0) are given. Determine whether they intersect.", 4, ["Equating third components gives λ = 3", "First component gives 1 + 2λ = 7 − μ, so μ = 0", "Second component then gives 2 − λ = −1 + μ", "With λ=3 and μ=0 both sides give −1, so the lines intersect at (7, −1, 3)"], "The third components give λ = 3. The first components then give 7 = 7 − μ, so μ = 0. The second components agree at −1, so the lines intersect at (7, −1, 3).", "solve a three-dimensional vector line intersection", 3, ["AO2"])],
  },
  {
    slug: "more-alevel-maths-sqrt2-proof",
    topic: "proof",
    difficulty: 4,
    calculator: false,
    stem: "Let √2 be written as a fraction a/b in lowest terms.",
    parts: [part("Show by contradiction that √2 is irrational.", 4, ["Assume √2 = a/b where a and b are coprime integers", "Squaring gives a² = 2b², so a is even", "Writing a = 2k gives b² = 2k², so b is even", "Both a and b are even, contradicting that they are coprime"], "Assume √2 = a/b in lowest terms. Then a² = 2b², so a is even; write a = 2k. Substitution gives b² = 2k², so b is even too. This contradicts lowest terms, so √2 is irrational.", "construct proofs by contradiction including irrationality and infinity of primes", 2, ["AO1", "AO2"])],
  },
  {
    slug: "more-alevel-maths-separable-differential-equation",
    topic: "integration",
    difficulty: 4,
    calculator: false,
    stem: "A curve is described by the differential equation dy/dx = 2xy and passes through (0, 3).",
    parts: [part("Solve dy/dx = 2xy given that y = 3 when x = 0.", 4, ["Separate variables: dy/y = 2x dx", "Integrate to give ln y = x² + C", "Use y = 3 at x = 0 to find C = ln 3", "Therefore y = 3e^(x²)"], "Separating gives dy/y = 2x dx. Integration gives ln y = x² + C. At x = 0, y = 3, so C = ln 3 and y = 3e^(x²).", "form and solve simple differential equations", 4, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-maths-binomial-hypothesis",
    topic: "distributions",
    kind: "calculation",
    difficulty: 4,
    calculator: true,
    stem: "A manufacturer claims that 10% of its components are defective. In a random sample of 20 components, 5 are defective. Test H₀: p = 0.10 against H₁: p > 0.10 at the 5% significance level.",
    parts: [part("Calculate the p-value and state the conclusion.", 4, ["Under H₀, X has distribution B(20, 0.10)", "p-value = P(X ≥ 5) = 0.0432", "0.0432 is below 0.05, so reject H₀", "There is significant evidence that the defective proportion is greater than 10%"], "Under H₀, X ~ B(20, 0.10). P(X ≥ 5) = 0.0432, which is below 0.05, so reject H₀. There is significant evidence that more than 10% of the components are defective.", "conduct hypothesis tests for binomial proportion", 3, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-maths-variable-acceleration",
    topic: "kinematics",
    kind: "calculation",
    difficulty: 4,
    calculator: false,
    stem: "A particle has acceleration a = 6t − 4 m s⁻². At t = 0, its velocity is 3 m s⁻¹ and its displacement is zero.",
    parts: [part("Find v and s in terms of t, then find v and s when t = 2 s.", 4, ["Integrating acceleration gives v = 3t² − 4t + C", "v(0) = 3 gives v = 3t² − 4t + 3", "Integrating v and using s(0) = 0 gives s = t³ − 2t² + 3t", "At t = 2, v = 7 m s⁻¹ and s = 6 m"], "Integrating a gives v = 3t² − 4t + C; using v(0) = 3 gives v = 3t² − 4t + 3. Integrating again gives s = t³ − 2t² + 3t, so v(2) = 7 m s⁻¹ and s(2) = 6 m.", "use calculus to relate displacement velocity and acceleration", 4, ["AO2", "AO3"])],
  },
];

const physics: ExpansionItem[] = [
  {
    slug: "physics-projectile-components",
    topic: "kinematics-dynamics",
    stem: "A ball is projected horizontally at 12 m s⁻¹ from a platform 5.0 m above level ground. Take g = 9.8 m s⁻².",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the time to hit the ground and the horizontal range.", 4, ["5.0 = ½gt²", "t = 1.01 s", "Horizontal speed remains 12 m s⁻¹", "Range = 12×1.01 = 12.1 m"], "Vertically, 5.0 = 4.9t², so t = 1.01 s. Horizontal motion is uniform, giving range = 12 × 1.01 = 12.1 m.", "resolve projectile motion into independent components", 2, ["AO2"])],
  },
  {
    slug: "physics-terminal-speed",
    topic: "kinematics-dynamics",
    stem: "A falling object reaches terminal speed.",
    difficulty: 3,
    parts: [part("Explain why its acceleration becomes zero.", 3, ["Drag increases with speed", "At terminal speed drag equals weight", "Resultant force is zero, so acceleration is zero"], "As the object speeds up, drag increases. At terminal speed drag equals the object's weight, so the resultant force and therefore acceleration are zero.", "explain terminal speed using resultant force", 1, ["AO2"])],
  },
  {
    slug: "physics-efficiency",
    topic: "energy-power",
    stem: "A motor takes in 600 J of electrical energy each second and delivers 420 J of useful mechanical energy each second.",
    difficulty: 2,
    kind: "calculation",
    parts: [part("Calculate the motor's efficiency and its wasted power.", 3, ["Useful power = 420 W and input power = 600 W", "Efficiency = 420/600 = 0.70 or 70%", "Wasted power = 600 − 420 = 180 W"], "Efficiency = 420/600 = 0.70 = 70%. The wasted power is 600 − 420 = 180 W.", "calculate efficiency and wasted power", 1, ["AO2"])],
  },
  {
    slug: "physics-stress-strain",
    topic: "materials",
    stem: "A wire of original length 2.00 m and cross-sectional area 1.5 × 10⁻⁶ m² extends by 1.2 mm under a force of 90 N.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the Young modulus of the wire.", 3, ["Stress = F/A = 6.0 × 10⁷ Pa", "Strain = extension/original length = 0.0012/2.00 = 6.0 × 10⁻⁴", "E = stress/strain = 1.0 × 10¹¹ Pa"], "Stress = 90/(1.5 × 10⁻⁶) = 6.0 × 10⁷ Pa. Strain = 0.0012/2.00 = 6.0 × 10⁻⁴. Young modulus = 1.0 × 10¹¹ Pa.", "calculate Young modulus from stress and strain", 2, ["AO2"])],
  },
  {
    slug: "physics-standing-wave",
    topic: "waves",
    stem: "A string fixed at both ends has length 0.80 m and vibrates in its third harmonic at 180 Hz.",
    difficulty: 3,
    parts: [part("Calculate the wave speed on the string.", 3, ["Third harmonic has three half-wavelengths in the length", "0.80 = 3λ/2, so λ = 0.533 m", "v = fλ = 96 m s⁻¹"], "For the third harmonic, L = 3λ/2, so λ = 2(0.80)/3 = 0.533 m. The wave speed is v = 180 × 0.533 = 96 m s⁻¹.", "relate harmonic mode, wavelength and wave speed", 2, ["AO2"])],
  },
  {
    slug: "physics-photoelectric-work-function",
    topic: "quantum",
    stem: "Light of frequency 8.0 × 10¹⁴ Hz ejects photoelectrons from a metal with maximum kinetic energy 1.2 × 10⁻¹⁹ J. Use h = 6.63 × 10⁻³⁴ J s.",
    difficulty: 4,
    kind: "calculation",
    parts: [part("Calculate the work function of the metal.", 3, ["Photon energy E = hf = 5.304 × 10⁻¹⁹ J", "hf = work function + maximum kinetic energy", "φ = 4.10 × 10⁻¹⁹ J"], "hf = 6.63 × 10⁻³⁴ × 8.0 × 10¹⁴ = 5.304 × 10⁻¹⁹ J. Therefore φ = 5.304 × 10⁻¹⁹ − 1.2 × 10⁻¹⁹ = 4.10 × 10⁻¹⁹ J.", "apply the photoelectric equation to find a work function", 2, ["AO2"])],
  },
  {
    slug: "physics-electric-resistivity",
    topic: "electric-circuits",
    stem: "A metal wire has resistance 4.0 Ω, length 2.0 m and cross-sectional area 0.50 mm².",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the resistivity of the metal.", 2, ["A = 0.50 × 10⁻⁶ m²", "ρ = RA/L = 4.0×0.50×10⁻⁶/2.0 = 1.0×10⁻⁶ Ω m"], "ρ = RA/L = 4.0 × (0.50 × 10⁻⁶)/2.0 = 1.0 × 10⁻⁶ Ω m.", "calculate resistivity from resistance, length and area", 2, ["AO2"])],
  },
  {
    slug: "physics-internal-resistance",
    topic: "electric-circuits",
    stem: "A cell has emf 1.50 V and internal resistance 0.80 Ω. It supplies a current of 0.50 A.",
    difficulty: 3,
    parts: [part("Calculate the terminal potential difference.", 2, ["Lost volts = Ir = 0.50×0.80 = 0.40 V", "Terminal p.d. = ε − Ir = 1.10 V"], "The lost volts are Ir = 0.50 × 0.80 = 0.40 V. Terminal p.d. = 1.50 − 0.40 = 1.10 V.", "calculate terminal p.d. allowing for internal resistance", 1, ["AO2"])],
  },
  {
    slug: "physics-momentum-explosion",
    topic: "momentum",
    stem: "A 2.0 kg trolley at rest explodes into a 1.2 kg part moving east at 5.0 m s⁻¹ and a second part.",
    difficulty: 3,
    parts: [part("Find the velocity of the second part.", 3, ["Initial momentum is zero", "1.2×5.0 + 0.8v = 0", "v = −7.5 m s⁻¹, so 7.5 m s⁻¹ west"], "Conservation of momentum gives 0 = (1.2 × 5.0) + 0.8v. Thus v = −7.5 m s⁻¹, or 7.5 m s⁻¹ west.", "apply conservation of momentum to an explosion", 1, ["AO2"])],
  },
  {
    slug: "physics-shm-condition",
    topic: "circular-shm",
    stem: "A mass oscillates about an equilibrium position with displacement x.",
    difficulty: 2,
    parts: [part("State the condition that proves the motion is simple harmonic.", 2, ["Acceleration is proportional to displacement", "Acceleration is directed towards equilibrium: a = −ω²x"], "The acceleration must be proportional to displacement and opposite in direction: a = −ω²x.", "state the defining condition for simple harmonic motion", 3, ["AO1"])],
  },
  {
    slug: "physics-resonance-damping",
    topic: "circular-shm",
    stem: "A driven oscillator is tested with different driving frequencies, first with light damping and then with heavy damping.",
    difficulty: 3,
    parts: [part("Compare the two amplitude–frequency graphs.", 3, ["Both have a maximum near the natural frequency", "Heavy damping reduces the maximum amplitude", "Heavy damping broadens the response and shifts the peak slightly lower"], "Both responses peak near the natural frequency. Heavy damping gives a lower, broader peak, with the maximum usually shifted to a slightly lower frequency.", "explain damping effects on a resonance curve", 2, ["AO2"])],
  },
  {
    slug: "physics-orbital-speed",
    topic: "fields",
    kind: "extended",
    stem: "A satellite moves in a circular orbit of radius r around a planet of mass M.",
    difficulty: 4,
    parts: [part("Show that its orbital speed is v = √(GM/r).", 3, ["Gravitational force is GMm/r²", "Centripetal force is mv²/r", "Equating gives GMm/r² = mv²/r, so v² = GM/r"], "The gravitational force provides the centripetal force: GMm/r² = mv²/r. Cancelling m and rearranging gives v² = GM/r, hence v = √(GM/r).", "derive orbital speed by equating gravitational and centripetal forces", 4, ["AO2"])],
  },
  {
    slug: "physics-induced-emf",
    topic: "fields",
    stem: "A coil of 200 turns has flux linkage that changes from 0.040 Wb turns to 0.010 Wb turns in 0.015 s.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the magnitude of the induced emf.", 2, ["Change in flux linkage = 0.030 Wb turns", "emf = Δ(NΦ)/Δt = 0.030/0.015 = 2.0 V"], "The magnitude of the change in flux linkage is 0.030 Wb turns, so emf = 0.030/0.015 = 2.0 V.", "calculate induced emf from a change in flux linkage", 2, ["AO2"])],
  },
  {
    slug: "physics-ideal-gas",
    topic: "thermal",
    stem: "A sealed gas has pressure 1.2 × 10⁵ Pa, volume 0.020 m³ and temperature 300 K. Use R = 8.31 J mol⁻¹ K⁻¹.",
    difficulty: 3,
    kind: "calculation",
    parts: [part("Calculate the amount of gas.", 2, ["Use pV = nRT", "n = pV/RT = (1.2×10⁵×0.020)/(8.31×300) = 0.963 mol"], "n = pV/RT = (1.2 × 10⁵ × 0.020)/(8.31 × 300) = 0.963 mol.", "use the ideal gas equation", 1, ["AO2"])],
  },
  {
    slug: "physics-specific-heat",
    topic: "thermal",
    stem: "A 0.40 kg block receives 12 kJ of energy and its temperature rises by 15 K.",
    difficulty: 2,
    kind: "calculation",
    parts: [part("Calculate the specific heat capacity of the block.", 2, ["Use Q = mcΔT", "c = 12000/(0.40×15) = 2000 J kg⁻¹ K⁻¹"], "c = Q/(mΔT) = 12000/(0.40 × 15) = 2000 J kg⁻¹ K⁻¹.", "calculate specific heat capacity", 2, ["AO2"])],
  },
  {
    slug: "physics-radioactive-half-life",
    topic: "nuclear",
    stem: "A radioactive source has an initial activity of 640 kBq and a half-life of 6.0 hours.",
    difficulty: 2,
    kind: "calculation",
    parts: [part("Find its activity after 18 hours.", 2, ["18 hours is three half-lives", "Activity = 640/2³ = 80 kBq"], "18 hours is three half-lives, so activity = 640 × (1/2)³ = 80 kBq.", "apply repeated half-life reduction", 2, ["AO2"])],
  },
  {
    slug: "physics-binding-energy",
    topic: "nuclear",
    stem: "The binding energy per nucleon of nucleus X is 8.2 MeV and it contains 56 nucleons.",
    difficulty: 2,
    parts: [part("Calculate its total binding energy and explain why this does not equal the energy released in every nuclear reaction involving X.", 3, ["Total binding energy = 8.2×56 = 459.2 MeV", "Binding energy is the energy needed to separate the nucleus into nucleons", "Reaction energy depends on the change in total binding energy between products and reactants"], "The total binding energy is 8.2 × 56 = 459.2 MeV. A reaction releases or absorbs the difference between the total binding energies of the products and reactants, not the whole binding energy of X.", "distinguish total binding energy from energy released in a reaction", 4, ["AO2"])],
  },
  {
    slug: "physics-particle-conservation",
    topic: "nuclear",
    stem: "In beta-minus decay a neutron changes into a proton.",
    difficulty: 3,
    parts: [part("State the other particles emitted and explain how charge is conserved.", 3, ["An electron and an electron antineutrino are emitted", "Neutron charge 0 becomes proton charge +1 and electron charge −1", "The antineutrino has zero charge"], "A neutron changes into a proton and emits an electron and an electron antineutrino. The final charges are +1 and −1, giving zero overall, while the antineutrino is neutral.", "apply charge and lepton-number conservation to beta-minus decay", 2, ["AO2"])],
  },
  {
    slug: "physics-polarisation",
    topic: "waves",
    stem: "A beam of light passes through a polarising filter and an analyser.",
    difficulty: 3,
    parts: [part("Explain why the observation of polarisation shows that light is a transverse wave.", 3, ["Polarisation restricts oscillations to one direction", "Only transverse oscillations can be restricted in this way", "Longitudinal waves oscillate parallel to propagation and cannot be polarised"], "Polarisation selects one direction of oscillation perpendicular to the direction of travel. This is possible for transverse waves but not longitudinal waves, whose oscillations are parallel to their direction of travel.", "use polarisation as evidence that light is transverse", 3, ["AO2"])],
  },
  {
    slug: "physics-de-broglie",
    topic: "quantum",
    kind: "calculation",
    stem: "An electron travels at 2.0 × 10⁶ m s⁻¹. Its mass is 9.11 × 10⁻³¹ kg and h = 6.63 × 10⁻³⁴ J s.",
    difficulty: 3,
    parts: [part("Calculate its de Broglie wavelength.", 2, ["Momentum p = mv = 1.822 × 10⁻²⁴ kg m s⁻¹", "λ = h/p = 3.64 × 10⁻¹⁰ m"], "p = mv = 9.11 × 10⁻³¹ × 2.0 × 10⁶ = 1.822 × 10⁻²⁴ kg m s⁻¹. λ = h/p = 3.64 × 10⁻¹⁰ m.", "calculate a matter-wave wavelength using de Broglie's relation", 1, ["AO2"])],
  },
  {
    slug: "more-alevel-physics-filament-lamp",
    topic: "electric-circuits",
    difficulty: 3,
    stem: "The I–V graph for a filament lamp becomes less steep as the current increases.",
    parts: [part("Explain what this shows about the lamp's resistance and why the resistance changes.", 3, ["The gradient dI/dV decreases as current increases", "Since resistance is dV/dI, the resistance increases", "The filament gets hotter and increased lattice-ion vibrations cause more electron collisions"], "The decreasing gradient means dI/dV is smaller, so dV/dI and therefore resistance are larger. The current heats the filament; greater lattice-ion vibration causes more collisions and increases resistance.", "interpret I-V characteristics for ohmic conductors filament lamps and diodes", 5, ["AO2", "AO3"])],
  },
  {
    slug: "more-alevel-physics-critical-angle",
    topic: "waves",
    kind: "calculation",
    calculator: true,
    difficulty: 3,
    stem: "Light travels from glass of refractive index 1.50 towards an air boundary.",
    parts: [part("Calculate the critical angle and state the conditions for total internal reflection.", 3, ["sin C = 1/n = 1/1.50", "C = 41.8°", "The light must travel from a denser to a less dense medium and the incidence angle must exceed C"], "sin C = 1/1.50, so C = 41.8°. Total internal reflection occurs when light travels from the denser glass into the less dense air at an incidence angle greater than the critical angle.", "state conditions for total internal reflection and apply the critical-angle relation", 4, ["AO2"])],
  },
  {
    slug: "more-alevel-physics-field-potential",
    topic: "fields",
    kind: "calculation",
    calculator: true,
    difficulty: 4,
    stem: "A uniform electric field has strength 4.0 × 10⁴ N C⁻¹ between two parallel plates separated by 3.0 cm.",
    parts: [part("Calculate the potential difference between the plates and state how potential changes in the field direction.", 3, ["Use E = ΔV/d", "ΔV = Ed = 4.0 × 10⁴ × 0.030 = 1.2 × 10³ V", "Electric potential decreases in the direction of the electric field"], "ΔV = Ed = 4.0 × 10⁴ × 0.030 = 1.2 × 10³ V. Electric potential decreases in the direction of the field.", "define electric and gravitational potential and relate field strength to potential gradient", 3, ["AO2"])],
  },
  {
    slug: "more-alevel-physics-kinetic-energy",
    topic: "thermal",
    kind: "calculation",
    calculator: true,
    difficulty: 3,
    stem: "A gas is at a temperature of 300 K. Use k = 1.38 × 10⁻²³ J K⁻¹.",
    parts: [part("Calculate the mean translational kinetic energy of a molecule and state what happens to it if the absolute temperature doubles.", 3, ["Use ½m⟨c²⟩ = 3/2 kT", "Mean kinetic energy = 3/2 × 1.38 × 10⁻²³ × 300 = 6.21 × 10⁻²¹ J", "Mean kinetic energy is directly proportional to absolute temperature, so it doubles"], "The mean translational kinetic energy is (3/2)kT = (3/2)(1.38 × 10⁻²³)(300) = 6.21 × 10⁻²¹ J. It doubles when the absolute temperature doubles.", "use half m c squared average equals three halves kT to link temperature and molecular kinetic energy", 5, ["AO2"])],
  },
];

const catalogues: Record<Discipline, ExpansionItem[]> = { biology, chemistry, maths, physics };
const supportedSubjects = ["wjec-alevel", "aqa-alevel"] as const;

export const authenticExpansionQuestions: Question[] = (Object.entries(catalogues) as Array<[Discipline, ExpansionItem[]]>).flatMap(
  ([discipline, items]) => supportedSubjects.flatMap((qualification) => {
    const subjectId = `${qualification}-${discipline}`;
    return items.map((item) => buildQuestion(subjectId, item));
  }),
);
