import { defineQuestions } from "./authoring";
const S = "wjec-alevel-maths";
export const mathsExtraQuestions = defineQuestions([
  {
    slug: "maths-sequences-recurrence",
    subjectId: S,
    topics: ["sequences"],
    stem: "A sequence is defined by u_{n+1}=3u_n+2 with u_1=1.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1"],
    parts: [
      { prompt: "Find u_3.", marks: 2, scheme: ["u_2=5", "u_3=17"], specPointIds: ["wjec-alevel-maths.sequences.sp-02"], learningClaims: ["evaluate terms of a recurrence relation"], answer: "u_2=3(1)+2=5, u_3=3(5)+2=17." },
    ],
  },
  {
    slug: "maths-exponentials-growth",
    subjectId: S,
    topics: ["exponentials"],
    stem: "A population grows as P=100e^{0.03t} where t is years.",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Find the time to double.", marks: 3, scheme: ["200=100e^{0.03t}", "ln2=0.03t", "t=23.1 years"], specPointIds: ["wjec-alevel-maths.exponentials.sp-03"], learningClaims: ["solve exponential equation using logarithms"], answer: "200=100e^{0.03t} so 2=e^{0.03t}, 0.03t=ln2, t=23.1 years." },
    ],
  },
  {
    slug: "maths-numerical-newton-raphson",
    subjectId: S,
    topics: ["numerical"],
    stem: "f(x)=x^3-2x-5 has a root near x=2. Use one iteration of Newton-Raphson with x_1=2.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Compute x_2.", marks: 3, scheme: ["f(2)=-1, f'(2)=10", "x_2=2-f/f'=2.1", "Comment on accuracy"], specPointIds: ["wjec-alevel-maths.numerical.sp-02"], learningClaims: ["apply Newton-Raphson iteration"], answer: "f(2)=-1, f'(x)=3x^2-2 so f'(2)=10. x_2=2-(-1)/10=2.1." },
    ],
  },
  {
    slug: "maths-probability-conditional",
    subjectId: S,
    topics: ["probability"],
    stem: "P(A)=0.6, P(B)=0.4, P(A cap B)=0.2.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Find P(A|B) and determine if A and B are independent.", marks: 3, scheme: ["P(A|B)=P(A cap B)/P(B)=0.5", "If independent P(A cap B)=P(A)P(B)=0.24 not 0.2", "So not independent"], specPointIds: ["wjec-alevel-maths.probability.sp-02"], learningClaims: ["apply conditional probability and test independence"], answer: "P(A|B)=0.2/0.4=0.5. Independent would require 0.24, so dependent." },
    ],
  },
  {
    slug: "maths-distributions-normal",
    subjectId: S,
    topics: ["distributions"],
    stem: "Heights are normally distributed with mean 170 cm and SD 8 cm. Use standard tables where P(Z<1)=0.8413.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Find P(X>178).", marks: 3, scheme: ["Z=(178-170)/8=1", "P(Z>1)=1-0.8413=0.1587", "15.9 percent"], specPointIds: ["wjec-alevel-maths.distributions.sp-03"], learningClaims: ["standardise and use normal tables"], answer: "Z=1, so P(Z>1)=0.1587 about 15.9 percent." },
    ],
  },
  {
    slug: "maths-kinematics-suvat",
    subjectId: S,
    topics: ["kinematics"],
    stem: "A particle starts from rest and accelerates at 3 m s^{-2} for 5 s.",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Find the final velocity and the distance travelled.", marks: 3, scheme: ["v=u+at=15 m s-1", "s=ut+0.5at^2=37.5 m", "Or v^2=u^2+2as"], specPointIds: ["wjec-alevel-maths.kinematics.sp-01"], learningClaims: ["apply SUVAT equations"], answer: "v=0+3*5=15 m/s. s=0.5*3*25=37.5 m." },
    ],
  },
  {
    slug: "maths-proof-contradiction",
    subjectId: S,
    topics: ["proof"],
    stem: "Prove by contradiction that \\sqrt{2} is irrational.",
    difficulty: 4,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO1","AO2"],
    parts: [
      { prompt: "Give the proof.", marks: 4, scheme: ["Assume sqrt2=p/q in lowest terms", "Then 2q^2=p^2 so p even", "Then q even so common factor 2", "Contradiction so irrational"], specPointIds: ["wjec-alevel-maths.proof.sp-03"], learningClaims: ["prove irrationality by contradiction"], answer: "Assume sqrt2=p/q coprime. Then p^2=2q^2 so p even, p=2k gives 4k^2=2q^2 so q even; contradicts coprimality." },
    ],
  },
  {
    slug: "maths-statistical-sampling-hypothesis",
    subjectId: S,
    topics: ["statistical-sampling"],
    stem: "A claim is made that 30% of students prefer online revision. In a sample of 20, 9 prefer online. Test at 5% significance whether the proportion differs from 30% (two-tailed).",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "State the hypotheses and give the critical region calculation outline.", marks: 3, scheme: ["H0: p=0.3, H1: p !=0.3", "Under H0 X~Bin(20,0.3)", "Need two-tailed critical region / p-value"], specPointIds: ["wjec-alevel-maths.statistical-sampling.sp-03"], learningClaims: ["formulate hypotheses for a binomial test"], answer: "H0: p=0.3, H1: p!=0.3. Under H0 X~Bin(20,0.3); find P(X>=9). Compare to 0.025 each tail." },
    ],
  },
  {
    slug: "maths-integration-area",
    subjectId: S,
    topics: ["integration"],
    stem: "Find the area between y=x^2 and y=2x.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the area.", marks: 4, scheme: ["Intersections at x=0,2", "Area=integral_0^2 (2x-x^2)dx", "=[x^2-x^3/3]_0^2=4-8/3=4/3", "Positive"], specPointIds: ["wjec-alevel-maths.integration.sp-04"], learningClaims: ["calculate area between curves by integration"], answer: "Intersections x(x-2)=0 at 0,2. Area integral 0 to 2 (2x-x^2)dx = [x^2-x^3/3]0^2=4-8/3=4/3." },
    ],
  },])
