import { depthQuestions, type PhysicsDepthItem, type PhysicsDepthPart } from "./physics-depth-50-common";

const p = (
  demand: PhysicsDepthPart["demand"], family: string, context: string, move: string,
  prompt: string, marks: number, scheme: string[], answer: string,
): PhysicsDepthPart => ({ demand, family, context, move, prompt, marks, scheme, answer });

/** Wave and quantum depth packs for the remaining high-value optical skills. */
const ITEMS: PhysicsDepthItem[] = [
  {
    topic: "waves", point: 5,
    parts: [
      p("recall", "deep:waves5:definition", "deep:waves5:definition:polariser", "define polarisation as restriction of oscillation direction", "Define polarisation of a wave.", 2, ["Polarisation restricts oscillations to one direction or plane", "Only transverse waves can be polarised"], "Polarisation is the restriction of oscillations to one direction. A longitudinal wave cannot be polarised because its oscillation is along its propagation direction."),
      p("recall", "deep:waves5:evidence", "deep:waves5:evidence:light", "state why polarisation is evidence that light is transverse", "State why observing polarisation supports the transverse-wave model of light.", 2, ["A polariser selects one oscillation direction", "Selection is possible only when oscillations are perpendicular to propagation"], "A polariser can select one transverse oscillation direction, which is evidence that light's oscillations are perpendicular to its travel."),
      p("explanation", "deep:waves5:crossed", "deep:waves5:crossed:filters", "explain extinction through crossed polarisers", "Explain why two ideal polarisers with perpendicular transmission axes transmit no light when placed one after the other.", 3, ["The first polariser leaves oscillations along its transmission axis", "The second axis is at 90° to that oscillation", "The electric-field component along the second axis is zero, so ideal transmitted intensity is zero"], "After the first filter the field has one direction. A perpendicular second axis has no component to transmit, so an ideal pair extinguishes the beam."),
      p("explanation", "deep:waves5:rotate", "deep:waves5:rotate:three-filters", "explain why an intermediate polariser can restore transmission", "Two crossed polarisers are dark. Explain how inserting a third polariser at 45° can make the detector register light.", 3, ["The first polariser sets one direction", "The 45° polariser transmits a component and rotates the surviving direction", "The final polariser now has a non-zero component along its axis"], "The intermediate filter projects the first direction onto 45° and leaves a field along that new axis. The final crossed filter is no longer crossed with that field, so a component passes."),
      p("application", "deep:waves5:axis-data", "deep:waves5:axis-data:stress-film", "infer a transmission axis from intensity measurements", "A polariser is rotated in front of a fixed analyser. The maximum detector reading occurs at 20° and the minimum at 110°. What is the analyser's transmission-axis direction relative to the incident polarisation?", 2, ["Maximum occurs when axes are parallel", "The incident polarisation is therefore 20° from the reference axis (modulo 180°); 110° is the perpendicular minimum"], "The 20° setting aligns the axes, while 110° is 90° away and gives the minimum. Polarisation axes repeat every 180°."),
      p("application", "deep:waves5:component", "deep:waves5:component:camera", "use vector projection to predict qualitative transmitted intensity", "Unpolarised light passes an ideal first polariser and then a second at 60°. Compare the transmitted intensity with that for a 30° separation.", 3, ["The first ideal polariser transmits half the unpolarised intensity", "The second transmits a squared projection proportional to cos²θ", "cos²60° is one third of cos²30°, so the 60° arrangement transmits one third as much after the first filter"], "After the first filter the intensity is I₀/2. The analyser gives a cos²θ factor, so 60° transmits one third of the 30° case."),
      p("misconception", "deep:waves5:longitudinal", "deep:waves5:longitudinal:slinky", "reject the claim that any wave can be polarised", "A student says a sound wave can be polarised by turning a polarising filter. Correct the claim using the direction of particle motion.", 3, ["Sound in air is longitudinal", "Particles oscillate parallel to propagation, leaving no perpendicular direction to select", "Polarisation applies to transverse waves; a mechanical transverse wave could be polarised"], "Air sound has back-and-forth motion along its travel direction, so a filter cannot select a transverse orientation. Polarisation is possible for transverse waves."),
      p("misconception", "deep:waves5:intensity-frequency", "deep:waves5:intensity-frequency:laser", "separate polarisation angle from frequency and wavelength", "Rotating a polariser reduces a laser's intensity. A student concludes that its frequency has changed. Explain the error.", 3, ["The polariser changes the electric-field component transmitted", "Frequency is set by the source and is unchanged by an ideal polariser", "In a fixed medium wavelength also remains unchanged because v = fλ"], "The filter removes a component of the field, changing intensity only. It does not alter the source frequency or the wavelength in the same medium."),
      p("calculation", "deep:waves5:malus", "deep:waves5:malus:display", "calculate intensity after an analyser using a squared projection", "Linearly polarised light of intensity 8.0 W m⁻² meets an analyser at 30°. Calculate the transmitted intensity for an ideal analyser.", 2, ["Use I = I₀ cos²θ", "I = 8.0×cos²30° = 6.0 W m⁻²"], "I = 8.0×0.75 = 6.0 W m⁻²."),
      p("calculation", "deep:waves5:polariser-chain", "deep:waves5:polariser-chain:camera", "chain ideal polariser losses and analyser projection", "Unpolarised light of 12 W m⁻² passes an ideal polariser, then an analyser at 60°. Calculate the final intensity.", 3, ["The first polariser gives 12/2 = 6.0 W m⁻²", "The analyser factor is cos²60° = 0.25", "Final intensity = 1.5 W m⁻²"], "The first filter leaves 6.0 W m⁻². The 60° analyser transmits one quarter, giving 1.5 W m⁻²."),
      p("transfer", "deep:waves5:photoelastic", "deep:waves5:photoelastic:bridge", "transfer polarisation to stress-induced birefringence", "A transparent bridge model is placed between crossed polarisers and bright coloured bands appear under load. Explain how polarisation reveals the stress pattern.", 3, ["Stress makes an initially isotropic material birefringent", "Different paths acquire different phases/polarisation directions", "The analyser converts those changes into intensity/colour variations that map relative stress"], "The load changes the material's optical response with direction. Phase and polarisation differences are converted by the analyser into bright bands, revealing where stress is concentrated."),
      p("transfer", "deep:waves5:antenna", "deep:waves5:antenna:radio", "transfer orientation selection to a transverse electromagnetic receiver", "A radio antenna receives a maximum signal when parallel to the transmitter. Explain the common reasoning with a polariser and one limitation of the analogy.", 3, ["The received electric-field component along the antenna drives current", "Rotating it projects the transverse field onto a new direction", "The antenna also has circuit, orientation and multipath effects beyond an ideal polariser"], "Only the field component along the antenna induces current, like a polariser selecting one direction. Real gain, reflections and circuitry make the response non-ideal."),
      p("synoptic", "deep:waves5:polarisation-diffraction", "deep:waves5:polarisation-diffraction:experiment", "combine polarisation evidence with diffraction measurements", "Design a short experiment that distinguishes a transverse light effect from a diffraction effect, using polariser rotation and slit width as independent changes.", 4, ["Rotate a polariser while keeping slit geometry fixed and record intensity", "Change slit width while keeping polariser axes fixed and record angular spreading/interference", "Polarisation changes selected field direction/intensity; diffraction changes spatial distribution", "Control wavelength and source alignment so the effects are not confounded"], "Run separate rotations and slit-width scans. A polariser changes field selection at fixed geometry, whereas diffraction changes the spatial pattern; keep wavelength and alignment controlled."),
      p("synoptic", "deep:waves5:uncertainty", "deep:waves5:uncertainty:lab", "evaluate polarisation data with background and uncertainty", "A detector reads 0.20 mW background and 1.20 mW with parallel polarisers, 0.30 mW with crossed polarisers. Explain how to report the extinction ratio and one systematic check.", 4, ["Subtract background: parallel 1.00 mW, crossed 0.10 mW", "Extinction ratio = 0.10/1.00 = 0.10 (10%)", "Non-zero crossed signal can be leakage or imperfect alignment", "Rotate through several angles and check detector linearity/background drift"], "After background subtraction the ratio is 0.10. Repeat angle scans and check leakage, alignment and detector drift before attributing the residual to the source."),
    ],
  },
  {
    topic: "waves", point: 6,
    parts: [
      p("recall", "deep:waves6:snell", "deep:waves6:snell:boundary", "state Snell law with angle convention", "State Snell's law and define the angles used.", 2, ["n₁ sin θ₁ = n₂ sin θ₂", "Angles are measured from the normal to the boundary"], "For rays crossing a boundary, n₁sinθ₁ = n₂sinθ₂, with both angles measured from the normal."),
      p("recall", "deep:waves6:frequency", "deep:waves6:frequency:laser", "state what is preserved on refraction", "State which wave quantity is unchanged when light refracts at a stationary boundary.", 2, ["Frequency is unchanged because it is set by the source", "Speed and wavelength change together so v = fλ remains true"], "The source fixes frequency. The speed changes in the new medium and wavelength changes in the same ratio."),
      p("explanation", "deep:waves6:normal", "deep:waves6:normal:glass", "explain bending towards the normal from speed reduction", "Explain why a ray entering glass from air bends towards the normal.", 3, ["Glass has the larger refractive index and lower wave speed", "The frequency is unchanged", "Using v = fλ, the wavelength decreases; the boundary geometry gives a smaller refracted angle"], "The speed falls in glass while frequency stays fixed, so wavelength shortens. Snell's law then gives a smaller angle to the normal."),
      p("explanation", "deep:waves6:wavefronts", "deep:waves6:wavefronts:water", "explain refraction with a wavefront construction", "A water wavefront enters shallow water obliquely. Explain how unequal speeds across the front rotate it.", 3, ["The section entering shallow water first slows", "The rest of the front catches up while still moving faster", "The wavefront rotates and the ray normal bends towards the normal"], "One end slows before the other, so the front pivots. The propagation direction, normal to the front, turns towards the normal in the slower region."),
      p("application", "deep:waves6:angle-air-glass", "deep:waves6:angle-air-glass:block", "apply Snell law to find a refracted angle", "A ray in air enters glass of refractive index 1.50 at 40° to the normal. Calculate the refracted angle.", 2, ["sin θ₂ = sin40°/1.50", "θ₂ = 25.4°"], "sinθ₂ = 0.6428/1.50, so θ₂ ≈ 25.4°."),
      p("application", "deep:waves6:index-from-angles", "deep:waves6:index-from-angles:prism", "infer refractive index from measured incident and refracted angles", "A ray enters a block at 55° and refracts at 34°. Estimate the block's refractive index relative to air.", 2, ["n = sin55°/sin34°", "n ≈ 1.49"], "The relative index is sin55°/sin34° ≈ 1.49."),
      p("misconception", "deep:waves6:frequency-change", "deep:waves6:frequency-change:pool", "correct the claim that refraction changes frequency", "A student says the wavelength becomes shorter in glass because the frequency increases. Correct the explanation.", 3, ["Frequency remains fixed at the boundary", "The speed decreases in glass", "Since v = fλ, wavelength decreases because speed decreases"], "Frequency does not jump at the boundary. Glass reduces speed, so wavelength shortens to keep v = fλ with the same f."),
      p("misconception", "deep:waves6:angle-surface", "deep:waves6:angle-surface:periscope", "correct measuring angles from the surface instead of the normal", "A ray diagram uses 30° to the surface in air and 20° to the surface in glass. A student inserts these directly into Snell's law. Explain the error.", 3, ["Snell angles are measured from the normal", "The angles to the normal are 60° and 70°", "Use n₁sin60° = n₂sin70°, not the surface angles"], "The complementary angles to the normal are 60° and 70°. Using 30° and 20° directly reverses the geometry."),
      p("calculation", "deep:waves6:critical", "deep:waves6:critical:fibre", "calculate a critical angle from refractive index", "Calculate the critical angle for a glass-air boundary when the glass refractive index is 1.50.", 2, ["sin C = 1/1.50", "C = 41.8°"], "sinC = 2/3, so C ≈ 41.8°."),
      p("calculation", "deep:waves6:depth", "deep:waves6:depth:sonar", "combine refraction geometry with a measured path length", "A ray in a liquid of index 1.33 travels 0.80 m at 25° to the normal. Find the component of this path normal to the boundary.", 2, ["Normal component = 0.80 cos25°", "Component = 0.725 m"], "The normal component is 0.80cos25° ≈ 0.725 m."),
      p("transfer", "deep:waves6:fibre", "deep:waves6:fibre:communications", "transfer Snell and total internal reflection to an optical fibre", "Explain how a fibre guides light through a curved core and name one condition that limits the bend.", 3, ["The core has higher refractive index than the cladding", "Rays strike the core-cladding boundary above the critical angle and undergo total internal reflection", "A tight bend can make the incidence angle fall below critical, causing leakage"], "A high-index core traps rays by total internal reflection. Bending changes incidence geometry; if it falls below C, power leaks into the cladding."),
      p("transfer", "deep:waves6:atmosphere", "deep:waves6:atmosphere:mirage", "transfer refraction to a continuously varying index", "A hot road produces a mirage as light curves through layers of air. Explain why applying one sharp-boundary Snell angle is only an approximation.", 3, ["Temperature changes density and refractive index gradually", "Each thin layer gives a small change in direction", "The full ray path is a sequence/continuous limit of refractions, not one interface"], "The index varies continuously with height, so the ray bends through many differential changes. A single Snell interface only approximates one layer."),
      p("synoptic", "deep:waves6:prism-dispersion", "deep:waves6:prism-dispersion:spectrum", "combine Snell law with wavelength-dependent index", "A prism spreads white light. Explain how wavelength-dependent refractive index changes the refracted angles and why the emerging colours remain at one frequency each.", 4, ["The source frequency of each spectral component is preserved at each boundary", "Refractive index varies with wavelength, so Snell law gives different angles", "Speed and wavelength inside the prism change for each component", "On exit the components separate spatially but do not change frequency"], "Each colour keeps its source frequency. Dispersion makes n(λ) different, so each obeys Snell's law at a different angle; its speed and wavelength change in the glass, then separate on exit."),
      p("synoptic", "deep:waves6:uncertainty", "deep:waves6:uncertainty:prism", "evaluate a refractive-index result against angle uncertainty", "A block gives n = 1.50 from angles 40°±1° and 25°±1°. State why the index uncertainty is asymmetric in angle space and one way to improve it.", 3, ["n = sin40°/sin25° is non-linear in each angle", "Equal ±1° changes do not produce equal changes in sinθ or the ratio", "Use repeated readings with a finer protractor/goniometer and propagate extrema or a derivative"], "Because sine is non-linear, the upper and lower angle combinations change the ratio by different amounts. Repeat with a goniometer and calculate bounds from the extrema."),
    ],
  },
];

export const physicsDepthNearCompleteWavesQuestions = depthQuestions(ITEMS);
