import type { LearningDemand } from "@/domain/types";
import { depthQuestions, type PhysicsDepthItem, type PhysicsDepthPart } from "./physics-depth-50-common";

const p = (
  demand: LearningDemand,
  family: string,
  context: string,
  move: string,
  prompt: string,
  marks: number,
  scheme: string[],
  answer: string,
): PhysicsDepthPart => ({ demand, family, context, move, prompt, marks, scheme, answer });

const ITEMS: PhysicsDepthItem[] = [
  {
    topic: "orbits-universe", point: 2,
    parts: [
      p("recall", "depth50:orbit2:kepler", "depth50:orbit2:kepler:planet", "state Kepler's third-law relationship", "State Kepler's third law for objects orbiting the same central mass.", 2, ["T² is proportional to r³ for circular orbits around the same central mass", "Equivalently T²/r³ is constant"], "For the same central mass, T² ∝ r³, so T²/r³ is constant."),
      p("recall", "depth50:orbit2:geostationary", "depth50:orbit2:geostationary:earth", "recall the orbital conditions for a geostationary satellite", "State three conditions required for a satellite to appear geostationary above Earth.", 2, ["Circular orbit in the equatorial plane", "Period equal to Earth's rotation and motion west to east (same angular speed)"], "It must be in a circular equatorial orbit, move west to east, and have a period equal to Earth's rotation."),
      p("application", "depth50:orbit2:period-ratio", "depth50:orbit2:period-ratio:exoplanet", "apply Kepler scaling to compare two orbital periods", "A planet orbits at four times Earth's orbital radius around the same star. How does its period compare with Earth's?", 2, ["T² ∝ r³, so T₂/T₁ = (r₂/r₁)^(3/2)", "T₂/T₁ = 4^(3/2) = 8, so its period is eight years if Earth's is one year"], "The period ratio is 4^(3/2) = 8, so the planet takes eight times as long."),
      p("application", "depth50:orbit2:geostat-radius", "depth50:orbit2:geostat-radius:satellite", "solve the geostationary radius from gravitational and centripetal acceleration", "Explain how the radius of a geostationary orbit is found from GM/r² = 4π²r/T².", 2, ["Set gravitational acceleration equal to centripetal acceleration for T = 24 h", "Rearrange to r³ = GMT²/(4π²), so r = [GMT²/(4π²)]^(1/3)"], "For a 24 h period set GM/r² = 4π²r/T². Rearranging gives r³ = GMT²/(4π²), hence r = [GMT²/(4π²)]^(1/3)."),
      p("misconception", "depth50:orbit2:gravity-zero", "depth50:orbit2:gravity-zero:astronaut", "reject the claim that apparent weightlessness means no gravitational field", "Astronauts in low Earth orbit feel weightless. Why does this not mean Earth's gravitational field is zero?", 2, ["Gravity remains the centripetal force and provides the continuous inward acceleration", "The astronaut and spacecraft are in free fall together, so there is no supporting contact force"], "Earth's gravity supplies the centripetal acceleration. The astronaut and spacecraft free-fall together, so no support force is felt even though g is substantial."),
      p("misconception", "depth50:orbit2:altitude-speed", "depth50:orbit2:altitude-speed:satellite", "correct the claim that a higher circular orbit requires a higher speed", "A student says a satellite must move faster at greater radius to avoid falling. Correct the reasoning.", 2, ["For a circular orbit v = √(GM/r)", "Increasing r lowers the required orbital speed even though the period increases"], "The circular speed is v = √(GM/r), so a larger radius needs a lower speed; its longer period follows from T² ∝ r³."),
      p("calculation", "depth50:orbit2:period", "depth50:orbit2:period:moon", "calculate an orbital period from radius and central mass", "A moon orbits a planet of mass 6.0 × 10²⁴ kg at radius 4.2 × 10⁸ m. Calculate its circular period. Take G = 6.67 × 10⁻¹¹.", 3, ["T = 2π√(r³/GM)", "T = 2π√[(4.2×10⁸)³/(6.67×10⁻¹¹×6.0×10²⁴)]", "T = 2.10 × 10⁶ s (24.3 d)"], "T = 2π√(r³/GM) = 2.10×10⁶ s, about 24.3 days."),
      p("transfer", "depth50:orbit2:escape", "depth50:orbit2:escape:probe", "transfer circular-orbit reasoning to the limiting escape condition", "A probe is raised from a circular orbit to the escape threshold. Which orbital assumption changes, and why is escape speed greater than the circular speed at the same radius?", 2, ["A bound circular orbit has kinetic energy balanced with negative gravitational potential energy; escape has zero total energy at infinity", "At the same radius v_escape = √2 v_circular because extra kinetic energy is needed to reach zero energy at infinity"], "Escape changes the bound circular-orbit condition to total energy zero at infinity. At the same radius v_escape = √2 times the circular speed because extra kinetic energy is required."),
      p("transfer", "depth50:orbit2:tidal", "depth50:orbit2:tidal:moon", "transfer orbital period scaling to a tidal-locking explanation", "Why does a tidally locked moon rotate once per orbit, and which Kepler relationship links its orbital radius to the locking period?", 2, ["Tidal locking makes the rotation period equal to the orbital period, keeping one face pointed at the planet", "For a given central mass the orbital period follows T² ∝ r³"], "Tidal locking synchronises rotation and orbit, so one face remains pointed at the planet. The orbital period at a given radius follows T² ∝ r³."),
      p("synoptic", "depth50:orbit2:geostat-energy", "depth50:orbit2:geostat-energy:launch", "combine orbital energy and period when comparing transfer manoeuvres", "A satellite is moved from a low circular orbit to a higher geostationary orbit. Explain why both its gravitational potential energy and orbital period increase while its circular speed decreases.", 3, ["Increasing radius makes gravitational potential less negative, so gravitational potential energy increases", "T² ∝ r³, so the orbital period increases strongly", "v = √(GM/r), so the circular speed decreases despite the energy increase"], "At larger radius gravitational potential energy is less negative and therefore higher. Kepler's law makes the period increase, while v = √(GM/r) makes circular speed decrease."),
      p("synoptic", "depth50:orbit2:stationkeeping", "depth50:orbit2:stationkeeping:geostat", "synthesise ideal geostationary conditions with real perturbations", "A communications satellite must keep its antenna pointed at one longitude. Explain the ideal orbit choice and one reason station-keeping is still required.", 3, ["Choose a circular equatorial west-to-east orbit with period equal to Earth's rotation", "Lunar/solar gravity, radiation pressure and Earth's non-uniform field perturb the longitude", "Small planned thruster impulses restore the orbit and consume propellant"], "The ideal choice is circular, equatorial, west to east and one Earth-rotation period. Real lunar/solar, radiation and field perturbations cause drift, so station-keeping burns are required."),
    ],
  },
  {
    topic: "orbits-universe", point: 3,
    parts: [
      p("recall", "depth50:orbit3:redshift", "depth50:orbit3:redshift:spectrum", "define cosmological redshift from spectral-line displacement", "Define redshift for light from a distant galaxy and state the sign of its wavelength change.", 2, ["Redshift is an increase in observed wavelength compared with the laboratory wavelength", "It is commonly expressed z = (λ_obs − λ₀)/λ₀ and is positive for recession"], "Redshift is the fractional increase in wavelength, z = (λobs−λ₀)/λ₀, and is positive when a galaxy's lines move to longer wavelength."),
      p("recall", "depth50:orbit3:hubble", "depth50:orbit3:hubble:galaxies", "state Hubble's law and its variables", "State Hubble's law and identify the quantities measured for a galaxy.", 2, ["Recession speed v is proportional to distance d: v = H₀d", "v is inferred from redshift and d from an independent distance indicator"], "Hubble's law is v = H₀d. Recession speed comes from redshift and distance from an independent indicator such as a standard candle."),
      p("explanation", "depth50:orbit3:expansion", "depth50:orbit3:expansion:balloon", "explain why redshift supports expansion rather than motion from one centre", "Why do redshifts from galaxies in all directions support an expanding universe?", 2, ["In an expanding metric, separations between unbound galaxies increase in every direction", "The measured recession speed grows with distance, consistent with Hubble's law rather than a single local explosion centre"], "Expansion increases separations in every direction. The recession speed increasing with distance follows Hubble's law and does not require a special central point in the observed universe."),
      p("explanation", "depth50:orbit3:standard-candle", "depth50:orbit3:standard-candle:supernova", "explain how a standard candle supplies distance for Hubble data", "How does a Type Ia supernova help determine a galaxy's distance for a Hubble-law plot?", 2, ["Its calibrated intrinsic luminosity allows inverse-square comparison with observed brightness", "Distance follows from observed flux and known luminosity, then the redshift gives recession speed"], "A calibrated intrinsic luminosity is compared with observed flux using the inverse-square law to find distance. The spectrum supplies redshift and hence recession speed."),
      p("misconception", "depth50:orbit3:redshift-speed", "depth50:orbit3:redshift-speed:galaxy", "reject the claim that redshift is directly a distance measurement", "A student reads a larger redshift as a larger distance without using Hubble's law. What is missing?", 2, ["Redshift primarily gives a recession speed (with a model and calibration)", "Distance requires Hubble's law or an independent distance ladder and carries uncertainty"], "Redshift gives a recession speed after calibration, not distance by itself. Distance needs Hubble's law or an independent distance indicator with uncertainty."),
      p("misconception", "depth50:orbit3:peculiar", "depth50:orbit3:peculiar:cluster", "separate local peculiar velocity from cosmological recession", "Why can a nearby galaxy's measured redshift give a poor Hubble-law distance?", 2, ["Its peculiar velocity from local gravitational interactions may be comparable to the Hubble recession speed", "The total redshift mixes the cosmological component with local motion"], "A nearby galaxy can have a large peculiar velocity from its group or cluster. The observed redshift then mixes local motion with cosmic expansion, making v = H₀d less reliable."),
      p("calculation", "depth50:orbit3:hubble-distance", "depth50:orbit3:hubble-distance:survey", "calculate distance from a measured recession speed and Hubble constant", "A galaxy has recession speed 4200 km s⁻¹. Using H₀ = 70 km s⁻¹ Mpc⁻¹, estimate its distance.", 2, ["d = v/H₀", "d = 4200/70 = 60 Mpc"], "d = 4200/70 = 60 Mpc."),
      p("calculation", "depth50:orbit3:redshift", "depth50:orbit3:redshift:line", "calculate redshift from a rest and observed wavelength", "A spectral line with rest wavelength 500 nm is observed at 505 nm. Calculate z and the low-speed recession estimate.", 3, ["z = (505 − 500)/500 = 0.010", "For small z, v ≈ cz", "v ≈ 3.0×10⁸ × 0.010 = 3.0×10⁶ m s⁻¹ (3000 km s⁻¹)"], "z = 5/500 = 0.010. At small redshift v ≈ cz = 3.0×10⁶ m s⁻¹, or 3000 km s⁻¹."),
      p("transfer", "depth50:orbit3:distance-ladder", "depth50:orbit3:distance-ladder:cepheid", "transfer calibration-chain reasoning to a multi-rung distance ladder", "Why are Cepheid variables and supernovae used together rather than assuming every supernova has the same luminosity without calibration?", 2, ["Cepheids calibrate distances to galaxies where supernovae occur", "Those distances calibrate the supernova luminosity, which can then extend the distance range"], "Cepheids provide an independently calibrated distance to host galaxies. They set the supernova luminosity scale, allowing supernovae to measure much larger distances."),
      p("synoptic", "depth50:orbit3:lookback", "depth50:orbit3:lookback:galaxy", "combine redshift with light-travel time and evolution limits", "A high-redshift galaxy is observed as it was billions of years ago. Explain why comparing its brightness directly with a nearby galaxy can bias a distance inference.", 3, ["The observation is a look-back in time, so the galaxy's intrinsic luminosity and stellar population may have evolved", "Standard-candle calibration may not transfer unchanged without correcting for evolution and selection", "Use a calibrated population or independent distance indicator and include the model uncertainty"], "A high-redshift galaxy is seen at an earlier evolutionary stage, so its intrinsic luminosity may differ. Standard-candle calibration needs evolution and selection corrections or an independent indicator with uncertainty."),
      p("synoptic", "depth50:orbit3:expansion-rate", "depth50:orbit3:expansion-rate:survey", "connect a fitted Hubble gradient to a changing expansion rate", "A Hubble plot uses recession speeds and distances with large uncertainties. Explain how the gradient is estimated and why a single straight line may be inadequate at large redshift.", 3, ["Fit v against d with uncertainties; the gradient estimates H₀", "At large redshift the low-speed v ≈ cz approximation and linear distance relation can fail", "Use a relativistic/cosmological distance-redshift model and compare residuals"], "Fit the velocity-distance data with uncertainties; the gradient estimates H₀. At high redshift, v ≈ cz and a straight line can fail, so a cosmological distance-redshift model and residual check are needed."),
    ],
  },
  {
    topic: "orbits-universe", point: 4,
    parts: [
      p("recall", "depth50:orbit4:random-systematic", "depth50:orbit4:random-systematic:astronomy", "distinguish random and systematic uncertainty in an astronomical measurement", "Define random uncertainty and systematic error for a repeated astronomical measurement.", 2, ["Random uncertainty causes scatter that can be reduced by repeats or averaging", "Systematic error shifts results consistently and is not removed by averaging"], "Random uncertainty produces scatter and can be reduced by repeats. Systematic error shifts every result and survives averaging."),
      p("recall", "depth50:orbit4:model-limit", "depth50:orbit4:model-limit:orbit", "identify assumptions behind a simple circular-orbit model", "State two assumptions in using a circular Kepler orbit to predict a satellite period.", 2, ["The central mass dominates and can be treated as spherical/point-like", "The orbit is circular with negligible drag and perturbing bodies"], "The central mass is treated as dominant and spherical, and the orbit is circular with negligible drag and perturbations."),
      p("explanation", "depth50:orbit4:peculiar-uncertainty", "depth50:orbit4:peculiar-uncertainty:galaxy", "explain why peculiar velocities broaden a Hubble relation", "Why do peculiar velocities produce scatter around a Hubble-law best-fit line, especially for nearby galaxies?", 2, ["Observed velocity is cosmological recession plus a local random component", "The local component is a larger fraction of v at small d, increasing vertical scatter"], "Measured velocity combines Hubble recession with local peculiar motion. At small distances the local component is a larger fraction, so points scatter further from the line."),
      p("explanation", "depth50:orbit4:calibration", "depth50:orbit4:calibration:candle", "explain how calibration uncertainty propagates into a cosmic distance", "A standard candle's luminosity is uncertain. Explain how that affects the inferred distance and Hubble constant.", 2, ["Distance follows d ∝ √(L/F), so luminosity uncertainty changes the distance scale", "Since H₀ = v/d, the same calibration bias produces an opposite systematic bias in H₀"], "Because d ∝ √(L/F), uncertainty in intrinsic luminosity changes every inferred distance. With v fixed, H₀ = v/d shifts in the opposite direction, giving a systematic calibration uncertainty."),
      p("application", "depth50:orbit4:residuals", "depth50:orbit4:residuals:survey", "use residuals to diagnose a model failure", "A plot of v against d curves upward at the largest distances. Give one evidence-based check before claiming Hubble's law fails.", 2, ["Check redshift calibration, selection effects and whether the distance indicators remain valid at that range", "Compare residuals with a model including measurement uncertainty and known cosmological corrections"], "First audit calibration, selection and distance-indicator validity. Then compare residuals with uncertainties and a model including relevant cosmological corrections before rejecting Hubble's law."),
      p("application", "depth50:orbit4:orbit-perturbation", "depth50:orbit4:orbit-perturbation:probe", "decide when a two-body approximation is insufficient", "A probe's predicted orbit differs from tracking data when it passes near a moon. Which model limitation is implicated and what refinement is needed?", 2, ["The single-central-mass approximation omits the moon's gravitational perturbation", "Use a multi-body numerical model or include the moon's force over the encounter"], "The one-body model omits the moon's force. Include the moon in a multi-body or numerical integration model for the close encounter."),
      p("misconception", "depth50:orbit4:uncertainty-average", "depth50:orbit4:uncertainty-average:telescope", "reject the claim that averaging removes calibration bias", "A telescope's wavelength scale is offset by 0.4 nm. Why will averaging many spectra not remove the resulting redshift bias?", 2, ["The offset is systematic and appears in every spectrum", "Averaging reduces random scatter but leaves the calibration shift"], "The 0.4 nm offset is systematic, so every spectrum is biased. Averaging reduces scatter only; calibration is needed to remove the shift."),
      p("misconception", "depth50:orbit4:precision-accuracy", "depth50:orbit4:precision-accuracy:parallax", "distinguish a tight cluster from a true value", "A parallax result has tiny quoted random uncertainty but disagrees with independent distances. What should be suspected?", 2, ["The result may be precise but inaccurate because of an unrecognised systematic error", "Check calibration, reference-frame assumptions and model fit rather than quoting the small scatter as validation"], "Small scatter indicates precision, not accuracy. Suspect a systematic calibration or reference-frame/model error and compare with independent evidence."),
      p("calculation", "depth50:orbit4:parallax", "depth50:orbit4:parallax:star", "convert a parallax angle into a distance with uncertainty", "A star's parallax is 0.050 ± 0.005 arcsec. Estimate its distance in parsecs and the approximate percentage uncertainty.", 2, ["d = 1/p = 1/0.050 = 20 pc", "For small uncertainty, percentage uncertainty in d is approximately 0.005/0.050 × 100 = 10%"], "d = 1/0.050 = 20 pc. The fractional uncertainty is about 0.005/0.050 = 10%, so d ≈ 20 ± 2 pc."),
      p("calculation", "depth50:orbit4:orbit-uncertainty", "depth50:orbit4:orbit-uncertainty:satellite", "propagate radius uncertainty into circular speed", "A satellite radius is r = (7.00 ± 0.10) × 10⁶ m. For v = √(GM/r), estimate the percentage uncertainty in v from the radius alone.", 2, ["v ∝ r^(−1/2)", "Percentage uncertainty in v is half the fractional radius uncertainty: 0.5×0.10/7.00×100 = 0.71%"], "Since v ∝ r^−1/2, the speed uncertainty is half the radius fraction: 0.5(0.10/7.00)×100 = 0.71%."),
      p("transfer", "depth50:orbit4:uncertainty-transfer", "depth50:orbit4:uncertainty-transfer:exoplanet", "transfer uncertainty reasoning to an exoplanet mass inference", "A transit depth gives a planet radius while a radial-velocity amplitude gives a mass. Why should the reported density include both uncertainties and model assumptions?", 2, ["Density ρ = M/(4πR³/3) is sensitive to both M and especially R", "Inclination, stellar radius and orbital model uncertainties can dominate even when the fitted curves look precise"], "Density depends on M and R³, so both measurement uncertainties must be propagated. Stellar radius, inclination and orbital-model assumptions can add systematic uncertainty."),
      p("transfer", "depth50:orbit4:interferometry", "depth50:orbit4:interferometry:star", "transfer resolution and uncertainty to an angular-size measurement", "An interferometer measures a star's angular diameter with a calibration uncertainty in baseline. How does that uncertainty affect the inferred physical radius?", 2, ["Physical radius combines angular diameter with distance, so baseline calibration uncertainty propagates through the angular size", "Quote the radius with both angular and distance uncertainties and check whether the source is resolved"], "Baseline calibration affects the angular diameter, which combines with distance to give physical radius. Propagate both uncertainties and verify that the star is genuinely resolved."),
      p("synoptic", "depth50:orbit4:model-comparison", "depth50:orbit4:model-comparison:cosmology", "synthesise fit quality, uncertainty and model limits before selecting a cosmological claim", "Two expansion models fit a galaxy data set: model A has a slightly smaller residual sum but ignores peculiar velocities; model B has larger residuals within uncertainty and includes them. Which evidence is needed before choosing A?", 3, ["Compare residuals relative to measurement uncertainty, not raw size alone", "Check whether omitted peculiar velocities create structured residuals or biased parameters", "Use an independent data set or model-selection criterion that penalises unsupported complexity/omissions"], "Raw residual sum is insufficient. Compare normalised residuals with uncertainties, inspect structure caused by omitted peculiar velocities, and test on independent data or a justified model-selection criterion."),
      p("synoptic", "depth50:orbit4:geostat-limit", "depth50:orbit4:geostat-limit:earth", "combine orbital assumptions with perturbation and station-keeping limits", "A geostationary satellite drifts in longitude over months. Explain why the ideal geostationary conditions remain useful but are not sufficient for a real prediction.", 3, ["The ideal model fixes period, equatorial plane and circular motion to match Earth's rotation", "Lunar/solar gravity, radiation pressure and Earth's non-uniform field perturb the orbit", "Station-keeping burns and updated tracking data are needed; their propellant and measurement uncertainties should be included"], "The ideal period, equatorial plane and circular orbit explain the intended fixed longitude. Real perturbations from the Moon, Sun, radiation and Earth's field cause drift, so station-keeping and updated tracking with uncertainty are required."),
      p("synoptic", "depth50:orbit4:distance-consistency", "depth50:orbit4:distance-consistency:galaxy", "cross-check independent distance indicators before trusting a grade-level inference", "A galaxy's supernova distance and redshift imply H₀ = 68 ± 4, while a Cepheid calibration gives 74 ± 2 for the same sample. What should an investigation report?", 3, ["Quote both estimates with their methods and uncertainties rather than selecting the preferred value silently", "Check shared calibration, peculiar velocity, selection and model assumptions for systematic differences", "Use a larger or independent sample to test whether the intervals and sources of error are consistent"], "Report both values and uncertainties, then audit shared calibration, peculiar velocity, selection and model assumptions. A larger independent sample is needed to decide whether the discrepancy is systematic or statistical."),
    ],
  },
];

export const physicsDepth50OrbitsQuestions = depthQuestions(ITEMS);
