import { defineQuestions } from "./authoring";
const S = "wjec-alevel-physics";
export const physicsExtraQuestions = defineQuestions([
  {
    slug: "phys-thermal-specific-heat",
    subjectId: S,
    topics: ["thermal"],
    stem: "A 0.20 kg block of metal is heated from 20 degC to 80 degC requiring 4800 J.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the specific heat capacity.", marks: 3, scheme: ["Q=mcDeltaT", "4800=0.20*c*60", "c=400 J kg-1 K-1"], specPointIds: ["wjec-alevel-physics.thermal.sp-01"], learningClaims: ["calculate specific heat capacity"], answer: "4800=0.20*c*60 so c=400 J/kg K." },
    ],
  },
  {
    slug: "phys-thermal-ideal-gas",
    subjectId: S,
    topics: ["thermal"],
    stem: "An ideal gas at 300 K occupies 0.02 m3 at 1.0e5 Pa.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the amount in moles (R=8.31).", marks: 3, scheme: ["pV=nRT", "n=pV/RT=1.0e5*0.02/(8.31*300)", "0.80 mol"], specPointIds: ["wjec-alevel-physics.thermal.sp-04"], learningClaims: ["apply pV=nRT"], answer: "n=1e5*0.02/(8.31*300)=0.80 mol." },
    ],
  },
  {
    slug: "phys-momentum-impulse",
    subjectId: S,
    topics: ["momentum"],
    stem: "A tennis ball of mass 0.06 kg strikes a wall at 20 m s-1 and rebounds at 15 m s-1. Contact time is 10 ms.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the average force on the ball.", marks: 4, scheme: ["Change in momentum = m(v-u) with sign: 0.06*(-15-20)=-2.1 kg m s-1", "Impulse = F*t", "F=210 N (magnitude)", "Direction away from wall"], specPointIds: ["wjec-alevel-physics.momentum.sp-03"], learningClaims: ["calculate impulse and average force from momentum change"], answer: "Delta p=0.06*(-15-20)=-2.1 kg m/s. F*t=delta p so |F|=2.1/0.01=210 N away from wall." },
    ],
  },
  {
    slug: "phys-fields-gravitational",
    subjectId: S,
    topics: ["fields"],
    stem: "The gravitational field strength at Earth's surface is 9.81 N kg-1. Radius of Earth 6.37e6 m, mass 5.97e24 kg, G=6.67e-11.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Show that g=GM/r2 gives ~9.8 N kg-1.", marks: 3, scheme: ["g=6.67e-11*5.97e24/(6.37e6)^2", "Numerator 3.98e14 /4.06e13", "9.81 N kg-1"], specPointIds: ["wjec-alevel-physics.fields.sp-01"], learningClaims: ["verify gravitational field strength expression"], answer: "g=GM/r2=6.67e-11*5.97e24/(6.37e6)^2=9.81 N/kg." },
    ],
  },
  {
    slug: "phys-fields-capacitor",
    subjectId: S,
    topics: ["fields"],
    stem: "A capacitor of 470 uF is charged to 12 V.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the charge and the energy stored.", marks: 4, scheme: ["Q=CV=5.64e-3 C", "E=0.5CV^2 or 0.5QV", "0.0338 J", "Unit check"], specPointIds: ["wjec-alevel-physics.fields.sp-05"], learningClaims: ["calculate charge and energy stored in capacitor"], answer: "Q=470e-6*12=5.64e-3 C. E=0.5*CV2=0.5*470e-6*144=0.0338 J." },
    ],
  },
  {
    slug: "phys-nuclear-binding",
    subjectId: S,
    topics: ["nuclear"],
    stem: "Masses: proton 1.00728 u, neutron 1.00867 u, He-4 nucleus 4.00150 u (1 u = 931.5 MeV/c2).",
    difficulty: 4,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the binding energy per nucleon for He-4.", marks: 4, scheme: ["Mass defect =2*1.00728+2*1.00867-4.00150=0.0304 u", "Energy=0.0304*931.5=28.3 MeV", "Per nucleon ~7.1 MeV", "Explain whether positive or negative mass defect sign"], specPointIds: ["wjec-alevel-physics.nuclear.sp-03"], learningClaims: ["calculate binding energy per nucleon from mass defect"], answer: "Defect 0.0304 u =28.3 MeV total, /4=7.1 MeV/nucleon." },
    ],
  },
  {
    slug: "phys-waves-doppler",
    subjectId: S,
    topics: ["waves"],
    stem: "A stationary observer hears a 400 Hz source moving away at 20 m s-1. Speed of sound 340 m s-1.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the observed frequency.", marks: 3, scheme: ["f'=f*v/(v+vs)", "400*340/360=378 Hz", "Lower than emitted"], specPointIds: ["wjec-alevel-physics.waves.sp-07"], learningClaims: ["apply Doppler shift formula"], answer: "f'=f*v/(v+vs)=400*340/360=378 Hz." },
    ],
  },
  {
    slug: "phys-kinematics-suvat",
    subjectId: S,
    topics: ["kinematics-dynamics"],
    stem: "A car accelerates from rest at 2.5 m s-2 for 6 s.",
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Find the final velocity and distance travelled.", marks: 3, scheme: ["v=u+at=15 m s-1", "s=ut+0.5at^2=45 m", "Or v average method"], specPointIds: ["wjec-alevel-physics.kinematics-dynamics.sp-03"], learningClaims: ["apply constant acceleration equations"], answer: "v=2.5*6=15 m/s. s=0.5*2.5*36=45 m." },
    ],
  },
  {
    slug: "phys-circular-banked",
    subjectId: S,
    topics: ["circular-shm"],
    stem: "A car of mass 1000 kg rounds a bend of radius 80 m at 20 m s-1.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      { prompt: "Calculate the required centripetal force.", marks: 2, scheme: ["F=mv2/r=5000 N", "Towards centre of circle"], specPointIds: ["wjec-alevel-physics.circular-shm.sp-04"], learningClaims: ["calculate centripetal force requirement"], answer: "F=1000*400/80=5000 N toward centre." },
    ],
  },
]);
