import type { LearningDemand, Question } from "@/domain/types";
import { defineQuestion } from "./authoring";

/**
 * Original drafts for the Physics quality queue, not reproduced WJEC items.
 * Reference: WJEC A200QS specification v3, Unit 1.2 Motion.
 * Internal sp-02 groups two separately diagnosable operations: slope and area.
 * Family IDs describe methods, not question wording or changed numbers.
 * No review approval is supplied by this authoring module.
 */
function graph(slug: string, skill: "gradient" | "area", demand: LearningDemand,
  family: string, context: string, reasoning: string, prompt: string, scheme: string[], answer: string): Question {
  const learning = { familyId: `motion-graph:${family}`, contextId: `motion-graph:${context}`,
    demand, reasoningMoves: [reasoning] };
  return defineQuestion({
    slug: `physics-motion-graph-${slug}`, subjectId: "wjec-alevel-physics", topics: ["kinematics-dynamics"],
    stem: prompt, kind: demand === "calculation" ? "calculation" : "short",
    source: "generated", verification: "unverified", reviewer: null, lastChecked: null,
    difficulty: demand === "recall" ? 1 : demand === "transfer" || demand === "synoptic" ? 4 : 3,
    learning: { ...learning, expectedMinutes: scheme.length * 1.25 },
    parts: [{ prompt, marks: scheme.length, scheme, answer, learning,
      capabilityIds: [`phys.motion.graph-${skill}`],
      specPointIds: ["wjec-alevel-physics.kinematics-dynamics.sp-02"],
      aos: demand === "recall" ? ["AO1"] : demand === "synoptic" || demand === "transfer" ? ["AO2", "AO3"] : ["AO2"] }],
  });
}

export const physicsMotionGraphQuestions: Question[] = [
  graph("tangent-definition", "gradient", "recall", "local-tangent", "position-record",
    "identify instantaneous velocity as the local tangent gradient",
    "State how instantaneous velocity at a specified time is obtained from a curved displacement-time graph, and state its SI unit.",
    ["Draw a tangent at the specified time and determine its gradient.", "The SI unit is m s^-1."],
    "Draw the tangent at that instant and divide a displacement change along the tangent by its corresponding time change. This gradient is the instantaneous velocity, in m s^-1."),
  graph("acceleration-axis", "gradient", "recall", "axis-meaning", "graph-labels",
    "select the ordinate whose time gradient represents acceleration",
    "Which has acceleration as its gradient: a speed-distance graph, a displacement-time graph or a velocity-time graph? State the gradient's SI unit and explain the choice using the definition of acceleration.",
    ["Choose the velocity-time graph.", "Acceleration is change in velocity per unit time, with unit m s^-2."],
    "Choose velocity against time: acceleration is the rate of change of velocity. Dividing a velocity change in m s^-1 by a time change in s gives m s^-2."),
  graph("offset-origin", "gradient", "explanation", "coordinate-invariance", "two-position-sensors",
    "distinguish a displacement offset from a change in velocity",
    "Two stationary sensors record the same trolley using the same clock and positive direction. Their displacement-time curves differ by a constant 2.0 m vertically. Explain whether they disagree about the trolley's velocity or acceleration.",
    ["A constant displacement offset leaves the tangent gradients unchanged, so both give the same velocity.", "The velocity-time histories are identical, so both give the same acceleration."],
    "Changing the spatial origin adds a constant displacement. It changes no displacement difference over a time interval, so tangent gradients and velocities are identical. Their rates of change of velocity, and hence accelerations, are also identical."),
  graph("negative-velocity", "gradient", "explanation", "sign-speed", "reversing-lift",
    "use velocity and acceleration signs together to infer whether speed increases",
    "A lift's velocity-time graph is below the time axis and slopes upwards towards zero. Explain its direction of motion, the sign of its acceleration and whether it is speeding up.",
    ["Negative velocity means motion in the negative direction.", "An upward gradient means positive acceleration.", "Speed decreases because the magnitude of the negative velocity decreases."],
    "It travels in the chosen negative direction. The upward slope gives positive acceleration, opposite to its velocity. Its speed falls as the velocity approaches zero."),
  graph("tangent-not-secant", "gradient", "application", "local-tangent", "camera-track",
    "choose tangent differences instead of origin coordinates to measure instantaneous velocity",
    "At t = 4.0 s a curved displacement-time trace has displacement 9.0 m. Its tangent passes through (2.0 s, 3.0 m) and (6.0 s, 15.0 m). Determine the instantaneous velocity at 4.0 s and explain why 9.0/4.0 is not a valid method.",
    ["Use the tangent gradient (15.0 - 3.0)/(6.0 - 2.0).", "The instantaneous velocity is 3.0 m s^-1.", "9.0/4.0 is a slope from the origin, not the specified tangent; even average velocity requires an initial displacement."],
    "The tangent slope is (15 - 3)/(6 - 2) = 3.0 m s^-1. Dividing the trace's coordinates does not calculate its local slope. It would describe an origin-to-point secant only if the motion started at zero displacement."),
  graph("match-graph-segments", "gradient", "application", "piecewise-slope", "shuttle-position",
    "translate successive straight displacement segments into a signed velocity history",
    "A shuttle's displacement-time graph joins (0 s, 1 m), (2 s, 5 m), (5 s, 5 m) and (7 s, -1 m) by straight lines. Give the velocity on each open interval and identify the interval of greatest speed. Ignore the idealised corners.",
    ["From 0 to 2 s the velocity is +2 m s^-1.", "From 2 to 5 s the velocity is zero; from 5 to 7 s it is -3 m s^-1.", "The greatest speed is 3 m s^-1 in the final interval."],
    "The successive gradients are (5 - 1)/2 = +2 m s^-1, (5 - 5)/3 = 0, and (-1 - 5)/2 = -3 m s^-1. Speed is the magnitude, so the final interval is fastest."),
  graph("crossing-curves", "gradient", "misconception", "height-versus-slope", "two-cyclists",
    "separate equal position from equal instantaneous velocity at a graph intersection",
    "Two cyclists' displacement-time curves cross at t = 8 s. A student concludes that their velocities are equal then. Assess this conclusion and state the additional graphical evidence needed.",
    ["The crossing shows equal displacement at the same time, not equal velocity.", "Equal velocities require equal tangent gradients at the intersection."],
    "The cyclists occupy the same position at 8 s. Their velocities depend on the slopes of their own tangents there. The velocities are equal only if those slopes are equal; crossing alone gives no such evidence."),
  graph("turning-point", "gradient", "misconception", "stationary-not-equilibrium", "vertical-ball",
    "distinguish zero slope from zero rate of change of slope",
    "At the top of a ball's vertical flight its displacement-time curve has a horizontal tangent. A student says both velocity and acceleration must therefore be zero. Evaluate each claim, neglecting air resistance.",
    ["The horizontal tangent gives zero instantaneous velocity.", "Acceleration remains downward at g because the gradient continues to change through the turning point."],
    "Velocity is zero at that instant because the tangent is horizontal. Acceleration is not zero: gravity still acts and velocity changes from upward to downward. The displacement curve remains curved, consistent with acceleration -g for upward positive."),
  graph("scaled-axes", "gradient", "calculation", "axis-scale-conversion", "ultrasound-trace",
    "convert both graph-axis scales before interpreting a measured gradient",
    "On a displacement-time graph, one horizontal square is 20 ms and one vertical square is 4.0 mm. A tangent rises three squares while running across five. Calculate the velocity in m s^-1, showing the axis conversions.",
    ["The displacement change is 12 mm = 0.012 m.", "The time change is 100 ms = 0.100 s.", "Velocity is 0.012/0.100 = 0.12 m s^-1."],
    "Three vertical squares represent 3 × 4.0 = 12 mm = 0.012 m. Five horizontal squares represent 100 ms = 0.100 s. The tangent gradient is 0.012/0.100 = 0.12 m s^-1."),
  graph("gradient-uncertainty", "gradient", "calculation", "slope-uncertainty", "photogate-fit",
    "bound an acceleration estimate using allowed endpoint velocities",
    "A straight velocity-time fit spans t = 1.0 s to 5.0 s; timing uncertainty is negligible. Its endpoint velocities are 3.0 ± 0.2 m s^-1 and 11.0 ± 0.2 m s^-1. Determine the central acceleration and the extreme allowed range using these endpoint bounds.",
    ["Central acceleration is (11.0 - 3.0)/4.0 = 2.0 m s^-2.", "Minimum acceleration uses (10.8 - 3.2)/4.0 = 1.9 m s^-2.", "Maximum acceleration uses (11.2 - 2.8)/4.0 = 2.1 m s^-2."],
    "The central gradient is 8.0/4.0 = 2.0 m s^-2. Pair the lower final velocity with the higher initial velocity for the minimum: 7.6/4 = 1.9 m s^-2. Reverse the bounds for the maximum: 8.4/4 = 2.1 m s^-2."),
  graph("clock-drift", "gradient", "transfer", "time-calibration", "faulty-logger",
    "propagate a multiplicative time-axis error into velocity and acceleration",
    "A logger reports t_display = 1.02 t_true. Displacement readings are correct. It computes velocity from the displacement-time gradient and acceleration from that computed velocity-time gradient. State the multiplicative error in each result and whether each is too large or too small.",
    ["Computed velocity is true velocity divided by 1.02.", "Computed acceleration is true acceleration divided by 1.02 squared.", "Both magnitudes are underestimated, because each time differentiation introduces the time-scale factor."],
    "Every displayed time interval is 1.02 times the real interval. The computed velocity is therefore v_true/1.02. Differentiating that velocity against the same stretched time axis gives a_true/(1.02)^2. Both non-zero magnitudes are too small."),
  graph("echo-round-trip", "gradient", "transfer", "indirect-position", "sonar-robot",
    "convert a round-trip signal-time slope into a target's velocity",
    "A stationary sonar records round-trip echo time T against laboratory time t for a slowly moving target. Sound speed is 340 m s^-1 and target speed is much smaller than this, so use x = 340T/2. The graph gradient is dT/dt = -0.012. Determine the target's radial velocity and interpret its sign.",
    ["Differentiate x = 340T/2 to obtain velocity = 170 dT/dt.", "The radial velocity is -2.04 m s^-1.", "The negative sign means decreasing distance: the target approaches the sonar."],
    "Using the supplied slow-motion model, v = (340/2)(-0.012) = -2.04 m s^-1. The factor two accounts for the outward and returning sound paths. The range is decreasing, so the target approaches."),
  graph("graph-to-resultant", "gradient", "synoptic", "force-from-slope", "loaded-lift",
    "infer support force from a signed velocity gradient and weight",
    "A 500 kg lift has upward velocity falling linearly from 4.0 to 1.0 m s^-1 in 2.0 s. Take upward as positive and g = 9.8 m s^-2. Determine its acceleration and cable tension, assuming only tension and weight act.",
    ["Acceleration is (1.0 - 4.0)/2.0 = -1.5 m s^-2.", "Tension minus weight equals ma: T - 4900 = -750.", "The tension is 4150 N, below the weight."],
    "The velocity-time slope gives a = -1.5 m s^-2. With upward positive, T - mg = ma, so T = 500(9.8 - 1.5) = 4150 N. The lift is moving up but accelerating down, so tension is below its weight."),
  graph("curvature-power", "gradient", "synoptic", "power-from-curvature", "ideal-linear-motor",
    "combine graph-derived velocity and acceleration to obtain instantaneous mechanical power",
    "An ideal horizontal motor moves a 2.0 kg trolley without resistance. Its displacement is x = 0.50 t^3 metres, with t in seconds. Using graph-gradient ideas or differentiation, find the motor's mechanical power at t = 2.0 s.",
    ["Velocity is the displacement gradient: v = 1.50 t^2, giving 6.0 m s^-1.", "Acceleration is the velocity gradient: a = 3.0 t, giving 6.0 m s^-2.", "Force is ma = 12 N and power is Fv = 72 W."],
    "Differentiate displacement to obtain v = 1.50 t^2 and differentiate again to obtain a = 3.0 t. At 2.0 s both have numerical value 6.0 in their respective SI units. F = 2.0 × 6.0 = 12 N and P = 12 × 6.0 = 72 W."),
  graph("signed-area-definition", "area", "recall", "signed-integral", "velocity-record",
    "identify displacement as signed area rather than total geometrical area",
    "State how displacement between two times is found from a velocity-time graph. Explain how areas below the time axis are treated.",
    ["Find the signed area between the graph and time axis over the interval.", "Areas below the axis contribute negative displacement."],
    "Add the signed areas over the interval. Area above the axis contributes positively and area below it negatively; the result is displacement."),
  graph("acceleration-area-definition", "area", "recall", "initial-condition", "acceleration-record",
    "identify the integration constant needed to recover velocity from acceleration area",
    "What does the signed area under an acceleration-time graph represent? What additional information is required to obtain the final velocity?",
    ["The signed area represents change in velocity.", "Add the initial velocity to obtain the final velocity."],
    "Acceleration-time area gives the change in velocity, not necessarily the velocity itself. Add the velocity at the beginning of the chosen interval to obtain the final velocity."),
  graph("round-trip-distance", "area", "explanation", "distance-versus-displacement", "out-and-back-run",
    "explain why cancellation of signed areas does not imply no travel",
    "A runner's velocity-time graph has equal areas above and below the time axis over a complete run. Explain what this shows about final position and total distance, without assuming the runner stayed still.",
    ["The signed areas cancel, so net displacement is zero and the runner returns to the initial position.", "Distance is the sum of the area magnitudes and is positive for non-zero motion."],
    "Equal and opposite signed areas give zero displacement: the final position equals the start. The runner still travelled. Adding the absolute areas, rather than cancelling them, gives the positive distance."),
  graph("same-end-speeds", "area", "explanation", "shape-not-endpoints", "two-launches",
    "show that equal endpoint velocities and duration do not determine displacement",
    "Two trolleys start at rest and reach 8 m s^-1 after 4 s. Trolley A accelerates uniformly. Trolley B's velocity-time curve stays strictly below A's straight line between the endpoints. Compare their displacements and explain why the endpoint-average-speed formula fails for B.",
    ["B has smaller velocity-time area and therefore smaller displacement.", "The formula (u + v)t/2 requires a straight velocity-time graph, or constant acceleration, which B does not have."],
    "Every interior velocity for B is below A's, so its graph encloses less area and it travels less far. Averaging just the starting and final velocities gives the trapezium area under a straight joining line; it does not describe B's curved trace."),
  graph("reversal-triangles", "area", "application", "zero-crossing-area", "braking-shuttle",
    "split a velocity-time interval at reversal before calculating distance",
    "A shuttle's velocity falls linearly from +6 m s^-1 at 0 s to -3 m s^-1 at 6 s. Determine when it reverses, its displacement and its distance travelled over the six seconds.",
    ["The constant gradient is -1.5 m s^-2, so velocity reaches zero at 4 s.", "Signed area is 12 - 3 = 9 m displacement.", "Distance is the sum of magnitudes, 12 + 3 = 15 m."],
    "The slope is (-3 - 6)/6 = -1.5 m s^-2 and zero velocity occurs after 6/1.5 = 4 s. The positive triangle has area 0.5 × 4 × 6 = 12 m and the negative triangle has magnitude 0.5 × 2 × 3 = 3 m. Displacement is 9 m; distance is 15 m."),
  graph("minimum-cruise-time", "area", "application", "inverse-area-design", "conveyor-stroke",
    "infer an unknown graph interval from a prescribed total displacement",
    "A conveyor accelerates uniformly from rest to 0.80 m s^-1 in 2.0 s, runs at that speed, then decelerates uniformly to rest in 1.0 s. It must travel 4.4 m without reversal. Find the required constant-speed duration.",
    ["Acceleration and deceleration areas total 0.80 + 0.40 = 1.20 m.", "The constant-speed section must cover 4.4 - 1.2 = 3.2 m.", "Its duration is 3.2/0.80 = 4.0 s."],
    "The two triangular areas are 0.5 × 2.0 × 0.80 = 0.80 m and 0.5 × 1.0 × 0.80 = 0.40 m. This leaves 3.2 m for the rectangular cruising area. Its width is 3.2/0.80 = 4.0 s."),
  graph("negative-area-speed", "area", "misconception", "velocity-change-not-speed", "backward-cart",
    "distinguish a signed velocity change from a change in speed",
    "A cart initially moves at -5 m s^-1. Its acceleration-time graph has signed area +2 m s^-1 over the next interval. A student says its speed increases by 2 m s^-1. Correct the claim with initial and final speeds.",
    ["Final velocity is -5 + 2 = -3 m s^-1.", "Speed decreases from 5 to 3 m s^-1; acceleration area is a velocity change, not a speed change."],
    "Add the signed velocity change: v = -5 + 2 = -3 m s^-1. The cart still moves backwards, but its speed falls from 5 to 3 m s^-1. A positive velocity change need not increase speed."),
  graph("area-units", "area", "misconception", "dimensional-area", "squared-paper",
    "use axis dimensions to reject interpreting graph area as physical square metres",
    "A student reports the area under a velocity-time graph as 12 m² because 'an area always has square units'. Explain the error and give the physical meaning and correct unit of a signed numerical area of 12 on axes labelled m s^-1 and s.",
    ["Graph area has the product of the axis units, (m s^-1) s = m.", "The signed area represents +12 m displacement, not a physical surface area."],
    "The plotted area is not a physical surface. Its units come from multiplying velocity by time: m s^-1 × s = m. A signed area of +12 means displacement +12 m."),
  graph("trapezium-data", "area", "calculation", "numerical-integration", "logger-table",
    "estimate displacement from unequally spaced velocity data and state the interpolation assumption",
    "A logger records (time/s, velocity/m s^-1): (0, 0), (1, 2), (3, 4), (6, 2). Estimate displacement using straight segments between readings. State why the estimate need not be exact.",
    ["The successive trapezium areas are 1 m, 6 m and 9 m.", "Total estimated displacement is 16 m.", "The estimate assumes velocity varies linearly between samples; unrecorded curvature can change the true area."],
    "For each interval use its own width: 1(0 + 2)/2 = 1 m, 2(2 + 4)/2 = 6 m and 3(4 + 2)/2 = 9 m. Total displacement is 16 m. Straight-line interpolation between the readings is an assumption, so a curved true trace could give a different area."),
  graph("accelerometer-offset", "area", "calculation", "bias-accumulation", "inertial-navigation",
    "integrate a constant sensor bias to predict drift despite zero true acceleration",
    "A stationary instrument starts with a correct velocity estimate of zero. Its acceleration sensor has a constant bias of +0.040 m s^-2. Software integrates the reading for 25 s. Calculate the resulting velocity error and explain why more frequent sampling alone will not remove it.",
    ["The spurious acceleration-time area is 0.040 × 25 = 1.0 m s^-1.", "The estimated velocity is too positive by 1.0 m s^-1.", "A systematic offset remains in every sample, so sampling more often does not remove its accumulated area."],
    "The true change in velocity is zero, but the biased graph has rectangular area 0.040 × 25 = 1.0 m s^-1. Software therefore reports a velocity 1.0 m s^-1 too positive. Finer sampling still integrates the same constant bias."),
  graph("distance-bound", "area", "transfer", "area-bounds", "sparse-telemetry",
    "bound an integral from monotonicity without inventing an interpolation law",
    "Only two reliable speed readings survive: 2 m s^-1 at 0 s and 6 m s^-1 at 5 s. Independent evidence establishes that speed increased monotonically throughout. Give lower and upper bounds on distance, and assess whether 20 m is established by these data.",
    ["Speed stays between 2 and 6 m s^-1, giving distance bounds 10 m and 30 m.", "20 m is the straight-line interpolation estimate.", "Monotonicity alone does not establish constant acceleration, so 20 m is not determined uniquely."],
    "The area lies between rectangles 2 × 5 = 10 m and 6 × 5 = 30 m. Joining the endpoints by a straight line would give 20 m, but many monotonic curves have different areas. The available evidence does not select that straight line."),
  graph("belt-relative-motion", "area", "transfer", "reference-frame-area", "moving-walkway",
    "combine a signed relative-velocity area with displacement of the reference frame",
    "A walkway moves east at 0.60 m s^-1. Over 10 s a traveller's velocity relative to the walkway rises linearly from 0 to 1.2 m s^-1 eastward. Find the traveller's displacement relative to the building, and identify what the relative-velocity graph's area alone measures.",
    ["The relative-velocity triangle gives 6.0 m relative to the walkway.", "The walkway moves 6.0 m east in the same time.", "The traveller's building-frame displacement is 12 m east."],
    "The triangle under relative velocity has area 0.5 × 10 × 1.2 = 6.0 m. This is displacement relative to the belt. The belt itself moves 0.60 × 10 = 6.0 m east, giving total displacement 12 m east relative to the building."),
  graph("work-from-velocity-area", "area", "synoptic", "work-from-area", "horizontal-drag",
    "combine path length from absolute velocity area with dissipative work",
    "A trolley moves horizontally with velocity +2.0 m s^-1 for 3.0 s, then -1.0 m s^-1 for 2.0 s. Ignore the brief reversal interval. A constant 4.0 N resistive force opposes its motion. Find its displacement and the work done by resistance.",
    ["Signed area gives displacement 6.0 - 2.0 = 4.0 m.", "Distance travelled is 6.0 + 2.0 = 8.0 m.", "Resistance does negative work on both legs, totalling -4.0 × 8.0 = -32 J."],
    "The signed areas give 4.0 m displacement, but their magnitudes add to 8.0 m of travel. Resistance opposes each leg, so its work is -4.0(6.0 + 2.0) = -32 J. Using net displacement would incorrectly cancel dissipation on the return leg."),
  graph("impulse-bridge", "area", "synoptic", "mass-weighted-area", "force-sensor-check",
    "cross-check impulse using mass times an acceleration-time area",
    "A 0.50 kg cart's acceleration-time trace is triangular, rising from zero to 8.0 m s^-2 and returning to zero over a total 0.40 s. A separate sensor claims the resultant impulse is 1.6 N s. Test this claim using the acceleration trace; assume constant mass.",
    ["Acceleration-time area gives velocity change 0.5 × 0.40 × 8.0 = 1.6 m s^-1.", "Impulse is mass times velocity change, 0.50 × 1.6 = 0.80 N s.", "The claimed 1.6 N s is inconsistent; it confuses the velocity-change numerical value with impulse."],
    "The triangle gives a velocity change of 1.6 m s^-1. Impulse equals change in momentum, so for constant mass it is 0.50 × 1.6 = 0.80 N s. The claimed value is twice the required impulse."),
];
