import type { LearningDemand, Question } from "@/domain/types";
import { defineQuestion } from "./authoring";

/** Original AI-authored drafts, not WJEC questions or human-approved content.
 * WJEC Physics v3 (October 2023), 4.1(i)-(j). Supplied extensions test application
 * of RC reasoning. Reused methods keep their family, including across batches.
 */
function rcItem(slug: string, demand: LearningDemand, familyId: string, context: string,
  reasoning: string, prompt: string, scheme: string[], answer: string): Question {
  const learning = { familyId, contextId: `capacitor-rc:${context}`, demand, reasoningMoves: [reasoning] };
  return defineQuestion({
    slug: `physics-rc-${slug}`, subjectId: "wjec-alevel-physics", topics: ["capacitance"],
    kind: demand === "calculation" ? "calculation" : "short", stem: prompt,
    source: "generated", verification: "unverified", reviewer: null, lastChecked: null,
    difficulty: demand === "recall" ? 1 : ["transfer", "synoptic"].includes(demand) ? 4 : 3,
    learning: { ...learning, expectedMinutes: scheme.length * 1.25 },
    parts: [{ prompt, marks: scheme.length, scheme, answer,
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"], capabilityIds: ["phys.capacitance.sp-04"],
      aos: demand === "recall" ? ["AO1"] : ["transfer", "synoptic"].includes(demand) ? ["AO2", "AO3"] : ["AO2"], learning }],
  });
}

export const physicsCapacitorRcQuestions: Question[] = [
  rcItem("time-constant", "recall", "capacitor-rc:exponential-fraction", "discharge-definition",
    "define the time constant using a remaining fraction rather than a completion time",
    "An ideal capacitor discharges through a fixed resistor. State the expression for the time constant and define it in terms of the charge remaining on one plate.",
    ["The time constant is RC.", "After this time the charge magnitude is 1/e (about 37%) of its initial value."],
    "The time constant is RC. It is the time for the charge magnitude to fall to 1/e, approximately 37%, of its initial value."),
  rcItem("current-area", "recall", "capacitor-rc:current-integral", "current-time-record",
    "identify transferred charge from the area under a current-time record",
    "A data logger records the magnitude of current during capacitor discharge. State what the area under its current-time graph between two times represents, and give the SI unit of this area.",
    ["The magnitude of charge transferred through the resistor between the two times.", "Coulomb (C), equivalent to A s."],
    "The area is the magnitude of charge transferred through the resistor in that interval. Its unit is A s, or coulombs."),
  rcItem("charging-feedback", "explanation", "capacitor-rc:circuit-feedback", "series-charger",
    "link accumulating charge to capacitor voltage and the declining resistor voltage",
    "An initially uncharged capacitor is connected in series with a resistor to a constant-voltage supply. Explain why the charging current decreases even though the supply voltage stays constant. Assume ideal components with fixed R and C.",
    ["Accumulating charge raises the capacitor voltage since V_C = Q/C.", "The resistor voltage is V_supply - V_C and therefore decreases.", "Current I = (V_supply - V_C)/R decreases because R is fixed."],
    "Charge builds up, so V_C = Q/C rises. The resistor receives only V_supply - V_C, which falls. Since its resistance is fixed, I = (V_supply - V_C)/R decreases towards zero."),
  rcItem("meter-loading", "explanation", "capacitor-rc:parallel-loading", "voltmeter-comparison",
    "recognise the measuring instrument as a second discharge path",
    "A capacitor discharges through a resistor R. Its voltage is recorded first with an ideal voltmeter, then in a separate identical trial with a voltmeter of finite resistance R_m. Explain how the second voltmeter changes the measured time constant. Assume no other leakage.",
    ["The finite-resistance voltmeter is connected in parallel with R.", "The discharge resistance is R_eff = R R_m/(R + R_m), which is less than R.", "The time constant R_eff C is smaller, so the voltage decays faster."],
    "The voltmeter draws current and gives the capacitor a second discharge path. Its resistance is in parallel with R, giving R_eff = R R_m/(R + R_m) < R. The time constant is therefore below RC and the measured decay is faster."),
  rcItem("threshold-timer", "application", "capacitor-rc:charging-threshold", "trigger-circuit",
    "solve a charging threshold from the fraction still missing from the final voltage",
    "An initially uncharged 100 μF capacitor charges through 22 kΩ from an ideal 9.0 V supply. A trigger draws negligible current and switches when the capacitor reaches 6.0 V. Calculate the delay. Assume constant R and C and show your method.",
    ["RC = 22 × 10^3 × 100 × 10^-6 = 2.2 s.", "6.0/9.0 = 1 - exp(-t/RC), hence exp(-t/RC) = 1/3.", "t = RC ln(3) = 2.42 s, or 2.4 s; allow follow-through from a stated positive RC with this logarithmic factor and seconds."],
    "RC = 2.2 s. Using V/V_supply = 1 - exp(-t/RC), the missing fraction at the trigger is 1 - 6/9 = 1/3. Thus t = -2.2 ln(1/3) = 2.42 s, approximately 2.4 s."),
  rcItem("sampling-window", "application", "capacitor-rc:time-scale-design", "data-logger-settings",
    "choose acquisition settings that resolve the decay and its late tail",
    "A capacitor-resistor pair has R = 47 kΩ and C = 220 μF. Logger A samples every 0.20 s for 60 s; logger B samples every 5.0 s for 10 s. Choose the better setting to estimate the discharge time constant and test exponential behaviour. Justify using both the sampling interval and the total recording time.",
    ["RC = 10.34 s, approximately 10 s.", "A resolves the decay with about 52 samples per time constant; B has only about two intervals per time constant.", "A records about 5.8 time constants whereas B stops at about one, so A also records the late decay; choose A."],
    "RC = 47000 × 220 × 10^-6 = 10.34 s. Choose A: its 0.20 s interval gives roughly 52 readings per time constant, rather than B's roughly two intervals. A also covers 60/10.34 = 5.8 time constants; B covers less than one, limiting a test of the tail."),
  rcItem("one-tau-not-empty", "misconception", "capacitor-rc:exponential-fraction", "finish-time-claim",
    "test a finite completion claim against the exponential remaining charge",
    "A student says a capacitor with RC = 4.0 s is completely discharged after 4.0 s. Use the ideal exponential model to assess the claim, state the fraction remaining then, and explain why an instrument can nevertheless display zero at a later finite time.",
    ["At t = RC, Q/Q0 = exp(-1) = 0.368, approximately 37%, so it is not completely discharged.", "The ideal exponential approaches zero but remains positive at every finite time.", "A finite-resolution instrument may round a small non-zero voltage or charge reading to zero."],
    "After 4.0 s the remaining fraction is exp(-1) = 0.368, not zero. In the ideal model the charge approaches zero asymptotically. A later displayed zero can mean that the remaining signal is below the instrument's resolution."),
  rcItem("equal-drops", "misconception", "capacitor-rc:ratio-test", "discharge-table",
    "distinguish a constant fractional loss from a constant absolute loss",
    "During discharge through a constant resistance the capacitor voltage is 8.0 V at 0 s, 4.0 V at 3.0 s and 2.0 V at 6.0 s. A student predicts 0 V at 9.0 s by subtracting another 2.0 V. Explain the error and predict the voltage at 9.0 s using the model supported by the readings.",
    ["Equal 3.0 s intervals give the same ratio, 1/2, rather than the same absolute decrease.", "As voltage falls the discharge current falls, so less charge is lost in each successive equal interval.", "The next voltage is 2.0 × 1/2 = 1.0 V."],
    "The voltage halves every 3.0 s; the absolute decreases are 4.0 V and then 2.0 V. Since I = V/R falls, the capacitor loses progressively less charge per interval. The next value is 2.0/2 = 1.0 V, not zero."),
  rcItem("log-gradient", "calculation", "capacitor-rc:log-linearisation", "discharge-fit",
    "infer capacitance from a dimensionally defined logarithmic slope",
    "A capacitor discharges through a 150 kΩ resistor. A straight-line fit of ln(V/(1 V)) against t in seconds has gradient -0.080 s^-1. Assume negligible meter loading and leakage. Calculate the time constant and capacitance, explaining how the gradient relates to RC.",
    ["ln(V/(1 V)) = ln(V0/(1 V)) - t/(RC), so gradient = -1/(RC).", "RC = 1/0.080 = 12.5 s.", "C = 12.5/(150 × 10^3) = 8.33 × 10^-5 F, or 83 μF; allow follow-through from a positive time constant divided by 150 kΩ with correct capacitance units."],
    "Taking logarithms gives gradient -1/(RC). Hence RC = -1/(-0.080) = 12.5 s. Then C = 12.5/150000 = 8.33 × 10^-5 F, approximately 83 μF. The intercept is not needed."),
  rcItem("unknown-supply", "calculation", "capacitor-rc:unknown-asymptote", "two-charging-readings",
    "eliminate an unknown final voltage using two equally spaced charging observations",
    "An initially uncharged capacitor charges through a fixed resistor from a constant but unknown supply voltage V_s. Its voltage is 3.0 V at t = 2.0 s and 4.5 V at t = 4.0 s. Using V = V_s(1 - exp(-t/RC)), determine V_s and RC. Show how you use both readings.",
    ["Set x = exp(-2.0/RC): 3.0 = V_s(1 - x) and 4.5 = V_s(1 - x²).", "Divide to obtain 1.5 = 1 + x, so x = 0.50; accept an equivalent simultaneous solution.", "V_s = 3.0/(1 - 0.50) = 6.0 V.", "RC = -2.0/ln(0.50) = 2.89 s, or 2.9 s; allow follow-through for 0 < x < 1."],
    "Write x = exp(-2.0/RC). The readings give 3.0 = V_s(1 - x) and 4.5 = V_s(1 - x²). Their ratio is 1.5 = (1 - x²)/(1 - x) = 1 + x, so x = 0.50. Therefore V_s = 6.0 V and RC = -2.0/ln(0.50) = 2.89 s."),
  rcItem("nonzero-start", "transfer", "capacitor-rc:offset-equilibrium", "precharged-sensor",
    "apply exponential relaxation to displacement from a non-zero final voltage",
    "A 10 μF capacitor initially at 2.0 V is connected through 100 kΩ to an ideal 10 V supply of the same polarity. For this circuit V(t) = V_final + (V_initial - V_final) exp(-t/RC). Find the time to reach 6.0 V. Explain why using 6.0/10 as the exponentially decaying fraction would be incorrect.",
    ["RC = 1.0 s and the equation becomes 6.0 = 10 - 8.0 exp(-t/RC).", "The remaining gap fraction is (10 - 6.0)/(10 - 2.0) = 1/2.", "t = RC ln(2) = 0.693 s, or 0.69 s; accept equivalent logarithmic rearrangements.", "It is the gap to the final voltage that decays from its initial gap; V/V_final is neither that gap fraction nor initially one."],
    "RC = 100000 × 10 × 10^-6 = 1.0 s. Substitution gives 6 = 10 - 8 exp(-t/1.0), so exp(-t/1.0) = 4/8 = 1/2 and t = 0.693 s. The decaying quantity is 10 - V, initially 8 V. The ratio 6/10 ignores both the non-zero starting voltage and the final-voltage offset."),
  rcItem("infer-leakage", "transfer", "capacitor-rc:parallel-loading", "unexpected-fast-decay",
    "infer an unobserved parallel leakage path from a shortened measured time constant",
    "A capacitor independently measured as 100 μF is discharged through a 200 kΩ resistor. Its measured time constant is 12 s. Assume the only cause of the discrepancy is a constant leakage resistance R_L across the capacitor; the voltmeter is ideal. Calculate R_L and explain why the result should not be interpreted as a changed capacitance.",
    ["The effective resistance is τ/C = 12/(100 × 10^-6) = 120 kΩ.", "The discharge paths are parallel: 1/R_L = 1/(120 kΩ) - 1/(200 kΩ).", "R_L = 300 kΩ; allow equivalent parallel-resistance algebra.", "The additional path lowers effective resistance while the independently measured capacitance stays 100 μF under the stated model."],
    "R_eff = 12/0.000100 = 120000 Ω. The resistor and leakage path are parallel, so 1/R_L = 1/120000 - 1/200000 and R_L = 300000 Ω. The faster decay is explained by the added current path; changing C contradicts the stipulated explanation and independent measurement."),
  rcItem("resistor-power", "synoptic", "capacitor-energy:exponential-energy", "thermal-pulse",
    "combine exponential voltage with the squared-voltage dependence of resistor power",
    "A capacitor initially at 12 V discharges through a 2.0 kΩ resistor with RC = 6.0 s. At what time does the resistor power first fall to 18 mW? Use V = V0 exp(-t/RC) and explain why power does not have the same time constant as voltage.",
    ["Initial power P0 = V0²/R = 144/2000 = 0.072 W, or 72 mW.", "P/P0 = (V/V0)² = exp(-2t/RC).", "18/72 = 1/4 gives t = (6.0/2) ln(4) = 4.16 s, or 4.2 s; accept finding the threshold voltage 6.0 V then its halving time.", "Power is proportional to voltage squared, so its exponential time constant is RC/2 = 3.0 s."],
    "Initially P0 = 12²/2000 = 0.072 W. The target is one quarter of this. Because P = V²/R, P/P0 = exp(-2t/6.0). Thus t = 3.0 ln(4) = 4.16 s. Equivalently the voltage must halve to 6.0 V. Squaring V halves the power time constant to 3.0 s."),
  rcItem("count-transferred-electrons", "synoptic", "capacitor-rc:current-integral", "charge-counter",
    "connect an exponential charge change over a late interval to a particle count",
    "A 20 μF capacitor initially at 5.0 V discharges with RC = 2.0 s. Calculate the number of electrons passing a cross-section of the discharge wire between t = 2.0 s and t = 4.0 s. Take the magnitude of electron charge as 1.60 × 10^-19 C. Explain why the charge remaining at 4.0 s alone is insufficient.",
    ["Initial plate charge magnitude Q0 = CV0 = 1.0 × 10^-4 C.", "Transferred charge magnitude is Q(2.0) - Q(4.0) = Q0[exp(-1) - exp(-2)] = 2.33 × 10^-5 C.", "N = ΔQ/e = 1.45 × 10^14 electrons, approximately 1.5 × 10^14; allow follow-through from a stated positive transferred charge using e.", "The count concerns charge that passed during the interval, so both endpoint charges are needed; the final charge is still on the capacitor."],
    "Q0 = 20 × 10^-6 × 5.0 = 1.0 × 10^-4 C. The charge lost between the endpoints is 1.0 × 10^-4[exp(-1) - exp(-2)] = 2.3254 × 10^-5 C. Dividing by 1.60 × 10^-19 C gives 1.4534 × 10^14 electrons. Q(4.0) alone is the remaining plate charge, not the charge that passed during the specified interval."),
];
