import { depthQuestions, type PhysicsDepthItem, type PhysicsDepthPart } from "./physics-depth-50-common";

const p = (
  demand: PhysicsDepthPart["demand"], family: string, context: string, move: string,
  prompt: string, marks: number, scheme: string[], answer: string,
): PhysicsDepthPart => ({ demand, family, context, move, prompt, marks, scheme, answer });

/** Completion of the practical-investigations planning capability. */
const ITEMS: PhysicsDepthItem[] = [
  {
    topic: "practical-investigations", point: 1,
    parts: [
      p("recall", "completion:practical1:variables", "completion:practical1:variables:plan", "identify independent dependent and control variables", "Define independent, dependent and control variables in a Physics investigation.", 3, ["Independent variable is deliberately changed", "Dependent variable is measured as the response", "Control variables are kept constant so the test is fair"], "The independent variable is changed, the dependent variable is measured and controls are held constant."),
      p("recall", "completion:practical1:safety", "completion:practical1:safety:hazard", "state a risk-control-residual-risk sequence", "State the three linked steps used to manage a practical hazard.", 3, ["Identify the hazard", "State a control or precaution that reduces likelihood or severity", "State the residual risk and an emergency response if relevant"], "Identify the hazard, specify a control and record the residual risk/response."),
      p("explanation", "completion:practical1:fair-test", "completion:practical1:fair-test:pendulum", "explain why controls isolate a causal relationship", "Explain why the mass of a pendulum bob should be controlled when investigating period against length.", 3, ["Changing mass at the same time would introduce a second cause", "A fair test changes length while keeping other relevant variables fixed", "The period model predicts no mass dependence, so variation would add noise or reveal a flaw"], "Keeping mass fixed isolates length as the intended cause. Uncontrolled mass variation would add noise or confound the test."),
      p("explanation", "completion:practical1:repeat", "completion:practical1:repeat:wire", "explain why repeats do not replace a range of independent values", "A student repeats one current reading ten times instead of taking several voltages. Explain why this is weak evidence for an I-V relationship.", 3, ["Repeats at one point estimate scatter but do not test the relationship across a range", "Several independent values reveal gradient, curvature and limits", "Repeat selected points to estimate random uncertainty as well as spanning the range"], "Repeats at one point only estimate scatter. A range of independent voltages is needed to reveal the I-V relationship, with repeats for uncertainty."),
      p("application", "completion:practical1:method", "completion:practical1:method:resistivity", "choose apparatus and sequence for a resistivity experiment", "Plan the essential measurement sequence for finding a wire's resistivity from R = rho L/A.", 3, ["Measure length and diameter at several positions with appropriate instruments", "Measure V and I for a low-power range and calculate R from a slope or V/I", "Convert all dimensions to metres and combine R, L and cross-sectional area"], "Measure length and diameter carefully, obtain resistance from a controlled V-I set and substitute SI values into rho = RA/L."),
      p("application", "completion:practical1:control", "completion:practical1:control:gas", "apply control choices to a gas-law investigation", "Plan how to investigate pressure against temperature for a fixed mass of gas while keeping volume controlled.", 3, ["Use a sealed rigid vessel with a calibrated pressure sensor and thermometer", "Allow thermal equilibrium at each temperature before recording p", "Use a water bath or controlled heater and avoid changing the gas amount"], "Use a sealed rigid vessel, control its volume and amount, wait for thermal equilibrium and record p and kelvin T with calibrated sensors."),
      p("misconception", "completion:practical1:accuracy", "completion:practical1:accuracy:meter", "correct confusing accuracy with precision", "A student says ten identical readings prove a meter is accurate. Correct the statement.", 2, ["Identical readings show repeatability/precision", "Accuracy requires comparison with a traceable standard or calibration"], "Repeated identical values show precision, not accuracy. Accuracy needs calibration against a known standard."),
      p("misconception", "completion:practical1:zero", "completion:practical1:zero:balance", "correct assuming zero error cancels in a difference", "A balance has a +0.20 g zero error. A student says it cancels when measuring a mass difference. Explain when it does and does not cancel.", 2, ["It cancels only if the same zero offset is present in both readings and the subtraction is explicit", "It does not cancel if the tare changes, ranges differ or a single absolute mass is reported"], "A constant offset cancels in a carefully paired difference, but not in an absolute mass or if the measurement conditions change."),
      p("calculation", "completion:practical1:uncertainty", "completion:practical1:uncertainty:meter", "calculate percentage uncertainty from resolution", "A ruler with 1 mm divisions measures a length of 120 mm using a ±0.5 mm reading uncertainty. Calculate the percentage uncertainty.", 2, ["Percentage uncertainty = 0.5/120×100", "= 0.42%"], "The percentage uncertainty is about 0.42%."),
      p("calculation", "completion:practical1:gradient", "completion:practical1:gradient:graph", "calculate a best-fit gradient with units", "A graph of extension x against force F passes through (2.0 N, 4.0 mm) and (8.0 N, 16.0 mm). Calculate the gradient and state its physical meaning.", 3, ["Gradient = (16−4) mm/(8−2) N = 2.0 mm N^-1", "Convert if needed: 2.0×10^-3 m N^-1", "The inverse gradient is the spring constant, k = 500 N m^-1"], "The gradient is 2.0 mm N^-1 = 2.0×10^-3 m N^-1. Its inverse gives k = 500 N m^-1."),
      p("transfer", "completion:practical1:fieldwork", "completion:practical1:fieldwork:magnet", "transfer planning controls to a magnetic-field mapping", "Plan a fair test of magnetic field strength against distance from a bar magnet and name one confounding variable.", 3, ["Use a fixed orientation Hall probe and measure along one defined axis", "Control probe angle, magnet position and ambient magnetic fields", "Repeat distances and randomise/alternate the order to reveal drift"], "Fix the probe orientation and magnet geometry, control background fields and repeat distances. Temperature or alignment drift could confound the trend."),
      p("transfer", "completion:practical1:simulation", "completion:practical1:simulation:uncertainty", "transfer experimental design to a simulated data collection", "A simulation produces exact values with no noise. Explain which parts of a real uncertainty plan still matter before trusting its conclusions.", 3, ["Model assumptions and parameter calibration can still be wrong", "Numerical precision is not physical accuracy", "Validate the simulation against an independent analytic result or real benchmark"], "A noiseless simulation can still be biased by assumptions or calibration. Check dimensions, limiting cases and an independent benchmark."),
      p("synoptic", "completion:practical1:design", "completion:practical1:design:pendulum", "combine variables, uncertainty and model choice in a complete plan", "Design a pendulum investigation to test T^2 proportional to length. Include variables, range, repeats, graph, uncertainty and one model limitation.", 4, ["Change length over a broad safe range; control bob, amplitude and pivot", "Time many oscillations and repeat each length; use mean T and spread", "Plot T^2 against l; a straight line through/near the origin tests the model and gradient gives 4pi^2/g", "Keep amplitude small and discuss pivot friction, reaction time and string length definition"], "Vary length, control bob and small amplitude, time many cycles with repeats, plot T² against l and use the gradient for g. Discuss pivot friction and length measurement as limitations."),
      p("synoptic", "completion:practical1:decision", "completion:practical1:decision:thermal", "combine safety, data quality and a stop decision", "A thermal experiment's sensor begins reading 15 degrees C above a reference while the heater is on. State the immediate safety/data action and how the investigation can resume.", 4, ["Stop heating or isolate the apparatus if the sensor fault creates an unsafe condition", "Mark affected readings as invalid/provisional rather than silently correcting them", "Check calibration, wiring and thermal contact against the reference", "Resume only after the fault is understood and record the correction/uncertainty"], "Stop or isolate the setup, preserve the affected data as provisional, diagnose the sensor against a reference and resume only after calibration and safety are restored."),
    ],
  },
];

export const physicsDepthCompletionPracticalQuestions = depthQuestions(ITEMS);
