// GENERATED from src/content/sources/capacitors.json — do not edit by hand.
// Regenerate: node scripts/generate-content.mjs capacitors
import { defineQuestion } from "./authoring";
import type { Question } from "@/domain/types";

export const physicsCapacitorEnergyQuestions: Question[] = [
  defineQuestion({
    slug: "physics-energy-charge-energy-definition",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "State the equation for energy U stored in a capacitor in terms of its charge Q and potential difference V. State what Q represents when the two plates carry equal and opposite charges.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 1,
    learning: {"familyId":"capacitor-energy:charge-work","contextId":"capacitor-energy:charged-plates","demand":"recall","reasoningMoves":["recall the energy relation using separated plate charge"],"expectedMinutes":2.5},
    parts: [{
      prompt: "State the equation for energy U stored in a capacitor in terms of its charge Q and potential difference V. State what Q represents when the two plates carry equal and opposite charges.",
      marks: 2,
      scheme: ["U = QV/2.","Q is the magnitude of charge on either plate, not the net charge of both plates."],
      answer: "U = QV/2. Q is the magnitude on one plate; the plates carry +Q and -Q and their net charge is zero.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO1"],
      learning: {"familyId":"capacitor-energy:charge-work","contextId":"capacitor-energy:charged-plates","demand":"recall","reasoningMoves":["recall the energy relation using separated plate charge"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-graph-energy-recall",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "For a graph of potential difference V on the vertical axis against charge Q on the horizontal axis, state which geometrical quantity gives the energy transferred in charging from zero. State its SI unit.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 1,
    learning: {"familyId":"capacitor-energy:charging-graph","contextId":"capacitor-energy:voltage-charge-plot","demand":"recall","reasoningMoves":["recall a graphical representation of charging work"],"expectedMinutes":2.5},
    parts: [{
      prompt: "For a graph of potential difference V on the vertical axis against charge Q on the horizontal axis, state which geometrical quantity gives the energy transferred in charging from zero. State its SI unit.",
      marks: 2,
      scheme: ["The area under the V against Q graph from zero to the final charge.","Joule (J), equivalent to V C."],
      answer: "The area under the V-Q graph gives the energy. Its unit is V C = J.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO1"],
      learning: {"familyId":"capacitor-energy:charging-graph","contextId":"capacitor-energy:voltage-charge-plot","demand":"recall","reasoningMoves":["recall a graphical representation of charging work"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-why-half-qv",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A capacitor has constant capacitance. Explain why the stored energy is QV/2 rather than QV when it is charged from zero to potential difference V. Refer to the work needed to transfer successive small amounts of charge.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:charging-graph","contextId":"capacitor-energy:incremental-charging","demand":"explanation","reasoningMoves":["explain the factor one half using the increasing charging voltage"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A capacitor has constant capacitance. Explain why the stored energy is QV/2 rather than QV when it is charged from zero to potential difference V. Refer to the work needed to transfer successive small amounts of charge.",
      marks: 3,
      scheme: ["The capacitor voltage rises from zero as charge is transferred.","For constant capacitance V is proportional to Q, so the mean voltage during charging is V/2.","Work is the area under the V-Q graph, or final charge times mean voltage, giving QV/2."],
      answer: "The first small amount of charge is moved through almost zero voltage. Later charge is moved through a larger voltage. Since V = Q/C is linear, the mean voltage is V/2 and the total work is Q(V/2), the triangular area under the V-Q graph.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:charging-graph","contextId":"capacitor-energy:incremental-charging","demand":"explanation","reasoningMoves":["explain the factor one half using the increasing charging voltage"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-energy-when-separated",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "An ideal air-spaced parallel-plate capacitor is charged, disconnected and then its plate separation is doubled. Neglect leakage and edge effects. Explain the change in stored energy and where the extra energy comes from.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:isolated-geometry","contextId":"capacitor-energy:movable-air-plates","demand":"explanation","reasoningMoves":["identify the fixed charge and account for mechanical work on an isolated capacitor"],"expectedMinutes":5},
    parts: [{
      prompt: "An ideal air-spaced parallel-plate capacitor is charged, disconnected and then its plate separation is doubled. Neglect leakage and edge effects. Explain the change in stored energy and where the extra energy comes from.",
      marks: 4,
      scheme: ["The magnitude of charge on each isolated plate remains fixed.","C is inversely proportional to separation, so capacitance halves.","U = Q²/(2C), so the stored energy doubles.","External work is done separating the attracting plates and increases electric field energy."],
      answer: "Disconnection fixes Q. Doubling the separation halves C, so Q²/(2C) doubles. Pulling the plates apart against their attraction requires external mechanical work, which supplies the increase in field energy.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:isolated-geometry","contextId":"capacitor-energy:movable-air-plates","demand":"explanation","reasoningMoves":["identify the fixed charge and account for mechanical work on an isolated capacitor"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-choose-pulse-bank",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A pulse driver needs at least 0.40 J stored energy. Available capacitors are A: 2200 μF rated at 16 V, and B: 1000 μF rated at 35 V. A supply can be set to any voltage up to 30 V. Which single capacitor can meet the requirement without exceeding its rating? Justify quantitatively.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:voltage-limit","contextId":"capacitor-energy:pulse-driver","demand":"application","reasoningMoves":["combine a required energy with the rated voltage constraint"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A pulse driver needs at least 0.40 J stored energy. Available capacitors are A: 2200 μF rated at 16 V, and B: 1000 μF rated at 35 V. A supply can be set to any voltage up to 30 V. Which single capacitor can meet the requirement without exceeding its rating? Justify quantitatively.",
      marks: 3,
      scheme: ["A stores at most 0.2816 J at its 16 V rating; alternatively, storing 0.40 J requires 19.1 V, above its rating.","B stores 0.45 J at the 30 V supply limit; alternatively, 0.40 J requires 28.3 V, within both limits.","Only B is suitable."],
      answer: "The voltage limit matters as well as capacitance. A stores at most 0.2816 J at 16 V. B stores 0.45 J at the supply limit of 30 V, below its 35 V rating. Only B can store at least 0.40 J.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:voltage-limit","contextId":"capacitor-energy:pulse-driver","demand":"application","reasoningMoves":["combine a required energy with the rated voltage constraint"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-usable-voltage-window",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A 2.0 F capacitor supplies a data logger as its voltage falls from 5.0 V to a 3.0 V cutoff. An ideal converter delivers the released energy to the logger, which consumes 0.50 W constantly. Calculate the operating time before cutoff.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:energy-window","contextId":"capacitor-energy:backup-logger","demand":"application","reasoningMoves":["subtract residual energy at the cutoff instead of spending the full initial store"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A 2.0 F capacitor supplies a data logger as its voltage falls from 5.0 V to a 3.0 V cutoff. An ideal converter delivers the released energy to the logger, which consumes 0.50 W constantly. Calculate the operating time before cutoff.",
      marks: 3,
      scheme: ["Usable energy = 0.5 C (V_initial² - V_final²); accept subtracting separately calculated stores.","Usable energy = 0.5 × 2.0 × (25 - 9) = 16 J.","Time = energy/power = 16/0.50 = 32 s; allow follow-through for correctly dividing a positive stated energy by 0.50 W, with seconds."],
      answer: "Energy remains in the capacitor at cutoff. The released energy is 0.5 × 2.0 × (5.0² - 3.0²) = 16 J. At 0.50 W the logger operates for 32 s.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:energy-window","contextId":"capacitor-energy:backup-logger","demand":"application","reasoningMoves":["subtract residual energy at the cutoff instead of spending the full initial store"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-same-energy-half-voltage",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A designer says: 'If the charging voltage is halved, doubling the capacitance preserves the stored energy.' Assess this statement and give the capacitance change actually required.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:voltage-limit","contextId":"capacitor-energy:low-voltage-redesign","demand":"misconception","reasoningMoves":["test a linear scaling claim against the squared-voltage dependence"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A designer says: 'If the charging voltage is halved, doubling the capacitance preserves the stored energy.' Assess this statement and give the capacitance change actually required.",
      marks: 3,
      scheme: ["U is proportional to CV².","Doubling C and halving V gives U_new/U_old = 2 × (1/2)² = 1/2.","C must be quadrupled to preserve the energy at half the voltage."],
      answer: "The claim is false. U_new = 0.5(2C)(V/2)² = U_old/2. Since voltage is squared, four times the capacitance is needed at half the voltage.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:voltage-limit","contextId":"capacitor-energy:low-voltage-redesign","demand":"misconception","reasoningMoves":["test a linear scaling claim against the squared-voltage dependence"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-neutral-does-not-mean-empty",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "An isolated capacitor has charges +30 μC and -30 μC on its plates and a potential difference of 20 V. A student argues that Q = 0, so U = QV/2 = 0. Explain the error, explain physically why energy is stored despite zero net charge, and calculate the energy stored.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:charge-work","contextId":"capacitor-energy:neutral-terminal-pair","demand":"misconception","reasoningMoves":["distinguish net charge from separated charge and the field energy"],"expectedMinutes":3.75},
    parts: [{
      prompt: "An isolated capacitor has charges +30 μC and -30 μC on its plates and a potential difference of 20 V. A student argues that Q = 0, so U = QV/2 = 0. Explain the error, explain physically why energy is stored despite zero net charge, and calculate the energy stored.",
      marks: 3,
      scheme: ["Q in the energy formula is the magnitude on one plate, 30 μC, rather than the zero net charge.","Separating opposite charges requires work, stored as electric field energy; accept a non-zero field between the oppositely charged plates storing energy.","U = 0.5 × 30 × 10^-6 × 20 = 3.0 × 10^-4 J."],
      answer: "Q in U = QV/2 is not the sum of the two plate charges. Use Q = 30 μC. The separated charges create an electric field storing 3.0 × 10^-4 J even though the capacitor's total charge is zero.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:charge-work","contextId":"capacitor-energy:neutral-terminal-pair","demand":"misconception","reasoningMoves":["distinguish net charge from separated charge and the field energy"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-infer-capacitance-from-slope",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "calculation",
    stem: "An experiment gives stored energies 0.010 J and 0.040 J at V² = 100 V² and 400 V² respectively. A straight line through these points and the origin models U against V². Calculate the capacitance from its gradient and give the answer in μF.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:energy-gradient","contextId":"capacitor-energy:energy-voltage-squared-data","demand":"calculation","reasoningMoves":["identify capacitance from the slope of an energy against squared-voltage graph"],"expectedMinutes":3.75},
    parts: [{
      prompt: "An experiment gives stored energies 0.010 J and 0.040 J at V² = 100 V² and 400 V² respectively. A straight line through these points and the origin models U against V². Calculate the capacitance from its gradient and give the answer in μF.",
      marks: 3,
      scheme: ["Gradient = (0.040 - 0.010)/(400 - 100) = 1.0 × 10^-4 J V^-2.","From U = 0.5 C V², gradient = C/2.","C = 2.0 × 10^-4 F = 200 μF."],
      answer: "The gradient is 0.030/300 = 1.0 × 10^-4 J V^-2. Since U = (C/2)V², C is twice the gradient: 2.0 × 10^-4 F, or 200 μF.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:energy-gradient","contextId":"capacitor-energy:energy-voltage-squared-data","demand":"calculation","reasoningMoves":["identify capacitance from the slope of an energy against squared-voltage graph"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-infer-voltage-from-charge-energy",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "calculation",
    stem: "A capacitor stores 0.018 J when the magnitude of charge on each plate is 600 μC. Calculate its potential difference and capacitance. Show each rearrangement and include SI units.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-energy:inverse-charge-energy","contextId":"capacitor-energy:unknown-charged-component","demand":"calculation","reasoningMoves":["rearrange the charge-energy relation before deducing capacitance"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A capacitor stores 0.018 J when the magnitude of charge on each plate is 600 μC. Calculate its potential difference and capacitance. Show each rearrangement and include SI units.",
      marks: 3,
      scheme: ["V = 2U/Q; accept an equivalent rearrangement of U = QV/2.","V = 2 × 0.018/(600 × 10^-6) = 60 V.","C = Q/V = (600 × 10^-6)/60 = 1.0 × 10^-5 F (10 μF); allow follow-through using a positive stated voltage and correct charge with capacitance units. Accept C = Q²/(2U)."],
      answer: "Rearrange U = QV/2 to give V = 2U/Q = 0.036/0.000600 = 60 V. Then C = Q/V = 0.000600/60 = 1.0 × 10^-5 F, or 10 μF. The factor two must be retained in the first step.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-energy:inverse-charge-energy","contextId":"capacitor-energy:unknown-charged-component","demand":"calculation","reasoningMoves":["rearrange the charge-energy relation before deducing capacitance"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-charge-sharing-loss",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A 4.0 μF capacitor initially at 12 V is connected in parallel, like terminals together, to an uncharged 8.0 μF capacitor. The supply is disconnected. A small resistance allows a final steady voltage to be reached. Calculate that voltage and the decrease in stored energy. Explain why charge conservation does not imply stored-energy conservation.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-energy:charge-redistribution","contextId":"capacitor-energy:switched-reservoirs","demand":"transfer","reasoningMoves":["conserve total separated charge while accounting for dissipated energy"],"expectedMinutes":6.25},
    parts: [{
      prompt: "A 4.0 μF capacitor initially at 12 V is connected in parallel, like terminals together, to an uncharged 8.0 μF capacitor. The supply is disconnected. A small resistance allows a final steady voltage to be reached. Calculate that voltage and the decrease in stored energy. Explain why charge conservation does not imply stored-energy conservation.",
      marks: 5,
      scheme: ["Initial charge = 4.0 × 10^-6 × 12 = 48 μC; total parallel capacitance is 12 μF.","Final voltage = 48/12 = 4.0 V.","Initial energy = 0.5 × 4.0 × 10^-6 × 12² = 288 μJ.","Final energy = 0.5 × 12 × 10^-6 × 4.0² = 96 μJ, so the decrease is 192 μJ.","The transient current dissipates energy in the resistance; total charge is conserved but capacitor energy alone is not."],
      answer: "The final common voltage is Q_total/C_total = 48 μC/12 μF = 4.0 V. Initially the store is 288 μJ; finally it is 96 μJ. The 192 μJ difference becomes internal energy during the charging current. Conservation of charge does not forbid energy transfer to the connecting resistance.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-energy:charge-redistribution","contextId":"capacitor-energy:switched-reservoirs","demand":"transfer","reasoningMoves":["conserve total separated charge while accounting for dissipated energy"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-harvester-plate-cycle",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A variable capacitor is charged to 6.0 V while its capacitance is 100 nF. It is then isolated and stretched so its capacitance falls to 40 nF. Leakage and other losses are negligible. Calculate its new voltage and the minimum mechanical work required for the change.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-energy:isolated-geometry","contextId":"capacitor-energy:variable-capacitance-harvester","demand":"transfer","reasoningMoves":["track energy through an isolated change of capacitance in a mechanical harvester"],"expectedMinutes":5},
    parts: [{
      prompt: "A variable capacitor is charged to 6.0 V while its capacitance is 100 nF. It is then isolated and stretched so its capacitance falls to 40 nF. Leakage and other losses are negligible. Calculate its new voltage and the minimum mechanical work required for the change.",
      marks: 4,
      scheme: ["Charge stays at Q = 100 × 10^-9 × 6.0 = 600 nC.","New voltage = Q/C = 600/40 = 15 V.","Initial energy = 1.8 μJ and final energy = 4.5 μJ.","Minimum mechanical work equals the energy increase = 2.7 μJ."],
      answer: "The isolated capacitor retains 600 nC. Reducing C to 40 nF raises V to 15 V. Initially U = 0.5 × 100 nF × 6.0² = 1.8 μJ; finally U = 0.5 × 40 nF × 15² = 4.5 μJ. External work of at least 2.7 μJ supplies the increase.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-energy:isolated-geometry","contextId":"capacitor-energy:variable-capacitance-harvester","demand":"transfer","reasoningMoves":["track energy through an isolated change of capacitance in a mechanical harvester"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-energy-half-life",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A capacitor discharges through a resistor with V = V0 exp(-t/RC). Show that the time for its stored energy to halve differs from the time for its voltage to halve. Calculate both times when RC = 8.0 s.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-energy:exponential-energy","contextId":"capacitor-energy:resistor-discharge","demand":"synoptic","reasoningMoves":["combine the exponential voltage law with the squared-voltage energy law"],"expectedMinutes":5},
    parts: [{
      prompt: "A capacitor discharges through a resistor with V = V0 exp(-t/RC). Show that the time for its stored energy to halve differs from the time for its voltage to halve. Calculate both times when RC = 8.0 s.",
      marks: 4,
      scheme: ["U/U0 = (V/V0)² = exp(-2t/RC).","For half energy, t = RC ln(2)/2 = 2.77 s (2.8 s to two significant figures).","For half voltage, t = RC ln(2) = 5.55 s (5.5 s to two significant figures).","The energy halves in half the voltage-halving time because energy is proportional to V²."],
      answer: "At fixed C, U/U0 = (V/V0)² = exp(-2t/RC). Setting this to 1/2 gives t = 8.0 ln(2)/2 = 2.77 s. Voltage halves at t = 8.0 ln(2) = 5.55 s. Squaring the voltage doubles the exponential decay constant for energy.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-energy:exponential-energy","contextId":"capacitor-energy:resistor-discharge","demand":"synoptic","reasoningMoves":["combine the exponential voltage law with the squared-voltage energy law"]},
    }],
  }),
  defineQuestion({
    slug: "physics-energy-capacitor-lift-budget",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A motor uses a 0.50 F capacitor as its voltage falls from 12 V to 8.0 V. Of the released electrical energy, 60% becomes gravitational potential energy of a 0.25 kg mass. Starting and finishing at rest, what maximum height can the mass gain? Take g = 9.81 m s^-2.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-energy:mechanical-energy-budget","contextId":"capacitor-energy:miniature-lifting-device","demand":"synoptic","reasoningMoves":["combine a capacitor voltage window with conversion efficiency and gravitational work"],"expectedMinutes":5},
    parts: [{
      prompt: "A motor uses a 0.50 F capacitor as its voltage falls from 12 V to 8.0 V. Of the released electrical energy, 60% becomes gravitational potential energy of a 0.25 kg mass. Starting and finishing at rest, what maximum height can the mass gain? Take g = 9.81 m s^-2.",
      marks: 4,
      scheme: ["Released capacitor energy = 0.5 × 0.50 × (12² - 8.0²) = 20 J.","Useful gravitational energy = 0.60 × 20 = 12 J.","Use mgh = 12 J.","h = 12/(0.25 × 9.81) = 4.89 m, approximately 4.9 m."],
      answer: "Only the energy between 12 V and the 8.0 V cutoff is available: 20 J. At 60% conversion efficiency the mass gains 12 J. With equal initial and final kinetic energy, h = 12/(0.25 × 9.81) = 4.89 m.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"],
      capabilityIds: ["phys.capacitance.sp-02"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-energy:mechanical-energy-budget","contextId":"capacitor-energy:miniature-lifting-device","demand":"synoptic","reasoningMoves":["combine a capacitor voltage window with conversion efficiency and gravitational work"]},
    }],
  })
];

export const physicsCapacitorRcQuestions: Question[] = [
  defineQuestion({
    slug: "physics-rc-time-constant",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "An ideal capacitor discharges through a fixed resistor. State the expression for the time constant and define it in terms of the charge remaining on one plate.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 1,
    learning: {"familyId":"capacitor-rc:exponential-fraction","contextId":"capacitor-rc:discharge-definition","demand":"recall","reasoningMoves":["define the time constant using a remaining fraction rather than a completion time"],"expectedMinutes":2.5},
    parts: [{
      prompt: "An ideal capacitor discharges through a fixed resistor. State the expression for the time constant and define it in terms of the charge remaining on one plate.",
      marks: 2,
      scheme: ["The time constant is RC.","After this time the charge magnitude is 1/e (about 37%) of its initial value."],
      answer: "The time constant is RC. It is the time for the charge magnitude to fall to 1/e, approximately 37%, of its initial value.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO1"],
      learning: {"familyId":"capacitor-rc:exponential-fraction","contextId":"capacitor-rc:discharge-definition","demand":"recall","reasoningMoves":["define the time constant using a remaining fraction rather than a completion time"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-current-area",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A data logger records the magnitude of current during capacitor discharge. State what the area under its current-time graph between two times represents, and give the SI unit of this area.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 1,
    learning: {"familyId":"capacitor-rc:current-integral","contextId":"capacitor-rc:current-time-record","demand":"recall","reasoningMoves":["identify transferred charge from the area under a current-time record"],"expectedMinutes":2.5},
    parts: [{
      prompt: "A data logger records the magnitude of current during capacitor discharge. State what the area under its current-time graph between two times represents, and give the SI unit of this area.",
      marks: 2,
      scheme: ["The magnitude of charge transferred through the resistor between the two times.","Coulomb (C), equivalent to A s."],
      answer: "The area is the magnitude of charge transferred through the resistor in that interval. Its unit is A s, or coulombs.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO1"],
      learning: {"familyId":"capacitor-rc:current-integral","contextId":"capacitor-rc:current-time-record","demand":"recall","reasoningMoves":["identify transferred charge from the area under a current-time record"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-charging-feedback",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "An initially uncharged capacitor is connected in series with a resistor to a constant-voltage supply. Explain why the charging current decreases even though the supply voltage stays constant. Assume ideal components with fixed R and C.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:circuit-feedback","contextId":"capacitor-rc:series-charger","demand":"explanation","reasoningMoves":["link accumulating charge to capacitor voltage and the declining resistor voltage"],"expectedMinutes":3.75},
    parts: [{
      prompt: "An initially uncharged capacitor is connected in series with a resistor to a constant-voltage supply. Explain why the charging current decreases even though the supply voltage stays constant. Assume ideal components with fixed R and C.",
      marks: 3,
      scheme: ["Accumulating charge raises the capacitor voltage since V_C = Q/C.","The resistor voltage is V_supply - V_C and therefore decreases.","Current I = (V_supply - V_C)/R decreases because R is fixed."],
      answer: "Charge builds up, so V_C = Q/C rises. The resistor receives only V_supply - V_C, which falls. Since its resistance is fixed, I = (V_supply - V_C)/R decreases towards zero.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:circuit-feedback","contextId":"capacitor-rc:series-charger","demand":"explanation","reasoningMoves":["link accumulating charge to capacitor voltage and the declining resistor voltage"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-meter-loading",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A capacitor discharges through a resistor R. Its voltage is recorded first with an ideal voltmeter, then in a separate identical trial with a voltmeter of finite resistance R_m. Explain how the second voltmeter changes the measured time constant. Assume no other leakage.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:parallel-loading","contextId":"capacitor-rc:voltmeter-comparison","demand":"explanation","reasoningMoves":["recognise the measuring instrument as a second discharge path"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A capacitor discharges through a resistor R. Its voltage is recorded first with an ideal voltmeter, then in a separate identical trial with a voltmeter of finite resistance R_m. Explain how the second voltmeter changes the measured time constant. Assume no other leakage.",
      marks: 3,
      scheme: ["The finite-resistance voltmeter is connected in parallel with R.","The discharge resistance is R_eff = R R_m/(R + R_m), which is less than R.","The time constant R_eff C is smaller, so the voltage decays faster."],
      answer: "The voltmeter draws current and gives the capacitor a second discharge path. Its resistance is in parallel with R, giving R_eff = R R_m/(R + R_m) < R. The time constant is therefore below RC and the measured decay is faster.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:parallel-loading","contextId":"capacitor-rc:voltmeter-comparison","demand":"explanation","reasoningMoves":["recognise the measuring instrument as a second discharge path"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-threshold-timer",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "An initially uncharged 100 μF capacitor charges through 22 kΩ from an ideal 9.0 V supply. A trigger draws negligible current and switches when the capacitor reaches 6.0 V. Calculate the delay. Assume constant R and C and show your method.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:charging-threshold","contextId":"capacitor-rc:trigger-circuit","demand":"application","reasoningMoves":["solve a charging threshold from the fraction still missing from the final voltage"],"expectedMinutes":3.75},
    parts: [{
      prompt: "An initially uncharged 100 μF capacitor charges through 22 kΩ from an ideal 9.0 V supply. A trigger draws negligible current and switches when the capacitor reaches 6.0 V. Calculate the delay. Assume constant R and C and show your method.",
      marks: 3,
      scheme: ["RC = 22 × 10^3 × 100 × 10^-6 = 2.2 s.","6.0/9.0 = 1 - exp(-t/RC), hence exp(-t/RC) = 1/3.","t = RC ln(3) = 2.42 s, or 2.4 s; allow follow-through from a stated positive RC with this logarithmic factor and seconds."],
      answer: "RC = 2.2 s. Using V/V_supply = 1 - exp(-t/RC), the missing fraction at the trigger is 1 - 6/9 = 1/3. Thus t = -2.2 ln(1/3) = 2.42 s, approximately 2.4 s.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:charging-threshold","contextId":"capacitor-rc:trigger-circuit","demand":"application","reasoningMoves":["solve a charging threshold from the fraction still missing from the final voltage"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-sampling-window",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A capacitor-resistor pair has R = 47 kΩ and C = 220 μF. Logger A samples every 0.20 s for 60 s; logger B samples every 5.0 s for 10 s. Choose the better setting to estimate the discharge time constant and test exponential behaviour. Justify using both the sampling interval and the total recording time.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:time-scale-design","contextId":"capacitor-rc:data-logger-settings","demand":"application","reasoningMoves":["choose acquisition settings that resolve the decay and its late tail"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A capacitor-resistor pair has R = 47 kΩ and C = 220 μF. Logger A samples every 0.20 s for 60 s; logger B samples every 5.0 s for 10 s. Choose the better setting to estimate the discharge time constant and test exponential behaviour. Justify using both the sampling interval and the total recording time.",
      marks: 3,
      scheme: ["RC = 10.34 s, approximately 10 s.","A resolves the decay with about 52 samples per time constant; B has only about two intervals per time constant.","A records about 5.8 time constants whereas B stops at about one, so A also records the late decay; choose A."],
      answer: "RC = 47000 × 220 × 10^-6 = 10.34 s. Choose A: its 0.20 s interval gives roughly 52 readings per time constant, rather than B's roughly two intervals. A also covers 60/10.34 = 5.8 time constants; B covers less than one, limiting a test of the tail.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:time-scale-design","contextId":"capacitor-rc:data-logger-settings","demand":"application","reasoningMoves":["choose acquisition settings that resolve the decay and its late tail"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-one-tau-not-empty",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A student says a capacitor with RC = 4.0 s is completely discharged after 4.0 s. Use the ideal exponential model to assess the claim, state the fraction remaining then, and explain why an instrument can nevertheless display zero at a later finite time.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:exponential-fraction","contextId":"capacitor-rc:finish-time-claim","demand":"misconception","reasoningMoves":["test a finite completion claim against the exponential remaining charge"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A student says a capacitor with RC = 4.0 s is completely discharged after 4.0 s. Use the ideal exponential model to assess the claim, state the fraction remaining then, and explain why an instrument can nevertheless display zero at a later finite time.",
      marks: 3,
      scheme: ["At t = RC, Q/Q0 = exp(-1) = 0.368, approximately 37%, so it is not completely discharged.","The ideal exponential approaches zero but remains positive at every finite time.","A finite-resolution instrument may round a small non-zero voltage or charge reading to zero."],
      answer: "After 4.0 s the remaining fraction is exp(-1) = 0.368, not zero. In the ideal model the charge approaches zero asymptotically. A later displayed zero can mean that the remaining signal is below the instrument's resolution.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:exponential-fraction","contextId":"capacitor-rc:finish-time-claim","demand":"misconception","reasoningMoves":["test a finite completion claim against the exponential remaining charge"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-equal-drops",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "During discharge through a constant resistance the capacitor voltage is 8.0 V at 0 s, 4.0 V at 3.0 s and 2.0 V at 6.0 s. A student predicts 0 V at 9.0 s by subtracting another 2.0 V. Explain the error and predict the voltage at 9.0 s using the model supported by the readings.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:ratio-test","contextId":"capacitor-rc:discharge-table","demand":"misconception","reasoningMoves":["distinguish a constant fractional loss from a constant absolute loss"],"expectedMinutes":3.75},
    parts: [{
      prompt: "During discharge through a constant resistance the capacitor voltage is 8.0 V at 0 s, 4.0 V at 3.0 s and 2.0 V at 6.0 s. A student predicts 0 V at 9.0 s by subtracting another 2.0 V. Explain the error and predict the voltage at 9.0 s using the model supported by the readings.",
      marks: 3,
      scheme: ["Equal 3.0 s intervals give the same ratio, 1/2, rather than the same absolute decrease.","As voltage falls the discharge current falls, so less charge is lost in each successive equal interval.","The next voltage is 2.0 × 1/2 = 1.0 V."],
      answer: "The voltage halves every 3.0 s; the absolute decreases are 4.0 V and then 2.0 V. Since I = V/R falls, the capacitor loses progressively less charge per interval. The next value is 2.0/2 = 1.0 V, not zero.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:ratio-test","contextId":"capacitor-rc:discharge-table","demand":"misconception","reasoningMoves":["distinguish a constant fractional loss from a constant absolute loss"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-log-gradient",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "calculation",
    stem: "A capacitor discharges through a 150 kΩ resistor. A straight-line fit of ln(V/(1 V)) against t in seconds has gradient -0.080 s^-1. Assume negligible meter loading and leakage. Calculate the time constant and capacitance, explaining how the gradient relates to RC.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:log-linearisation","contextId":"capacitor-rc:discharge-fit","demand":"calculation","reasoningMoves":["infer capacitance from a dimensionally defined logarithmic slope"],"expectedMinutes":3.75},
    parts: [{
      prompt: "A capacitor discharges through a 150 kΩ resistor. A straight-line fit of ln(V/(1 V)) against t in seconds has gradient -0.080 s^-1. Assume negligible meter loading and leakage. Calculate the time constant and capacitance, explaining how the gradient relates to RC.",
      marks: 3,
      scheme: ["ln(V/(1 V)) = ln(V0/(1 V)) - t/(RC), so gradient = -1/(RC).","RC = 1/0.080 = 12.5 s.","C = 12.5/(150 × 10^3) = 8.33 × 10^-5 F, or 83 μF; allow follow-through from a positive time constant divided by 150 kΩ with correct capacitance units."],
      answer: "Taking logarithms gives gradient -1/(RC). Hence RC = -1/(-0.080) = 12.5 s. Then C = 12.5/150000 = 8.33 × 10^-5 F, approximately 83 μF. The intercept is not needed.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:log-linearisation","contextId":"capacitor-rc:discharge-fit","demand":"calculation","reasoningMoves":["infer capacitance from a dimensionally defined logarithmic slope"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-unknown-supply",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "calculation",
    stem: "An initially uncharged capacitor charges through a fixed resistor from a constant but unknown supply voltage V_s. Its voltage is 3.0 V at t = 2.0 s and 4.5 V at t = 4.0 s. Using V = V_s(1 - exp(-t/RC)), determine V_s and RC. Show how you use both readings.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 3,
    learning: {"familyId":"capacitor-rc:unknown-asymptote","contextId":"capacitor-rc:two-charging-readings","demand":"calculation","reasoningMoves":["eliminate an unknown final voltage using two equally spaced charging observations"],"expectedMinutes":5},
    parts: [{
      prompt: "An initially uncharged capacitor charges through a fixed resistor from a constant but unknown supply voltage V_s. Its voltage is 3.0 V at t = 2.0 s and 4.5 V at t = 4.0 s. Using V = V_s(1 - exp(-t/RC)), determine V_s and RC. Show how you use both readings.",
      marks: 4,
      scheme: ["Set x = exp(-2.0/RC): 3.0 = V_s(1 - x) and 4.5 = V_s(1 - x²).","Divide to obtain 1.5 = 1 + x, so x = 0.50; accept an equivalent simultaneous solution.","V_s = 3.0/(1 - 0.50) = 6.0 V.","RC = -2.0/ln(0.50) = 2.89 s, or 2.9 s; allow follow-through for 0 < x < 1."],
      answer: "Write x = exp(-2.0/RC). The readings give 3.0 = V_s(1 - x) and 4.5 = V_s(1 - x²). Their ratio is 1.5 = (1 - x²)/(1 - x) = 1 + x, so x = 0.50. Therefore V_s = 6.0 V and RC = -2.0/ln(0.50) = 2.89 s.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2"],
      learning: {"familyId":"capacitor-rc:unknown-asymptote","contextId":"capacitor-rc:two-charging-readings","demand":"calculation","reasoningMoves":["eliminate an unknown final voltage using two equally spaced charging observations"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-nonzero-start",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A 10 μF capacitor initially at 2.0 V is connected through 100 kΩ to an ideal 10 V supply of the same polarity. For this circuit V(t) = V_final + (V_initial - V_final) exp(-t/RC). Find the time to reach 6.0 V. Explain why using 6.0/10 as the exponentially decaying fraction would be incorrect.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-rc:offset-equilibrium","contextId":"capacitor-rc:precharged-sensor","demand":"transfer","reasoningMoves":["apply exponential relaxation to displacement from a non-zero final voltage"],"expectedMinutes":5},
    parts: [{
      prompt: "A 10 μF capacitor initially at 2.0 V is connected through 100 kΩ to an ideal 10 V supply of the same polarity. For this circuit V(t) = V_final + (V_initial - V_final) exp(-t/RC). Find the time to reach 6.0 V. Explain why using 6.0/10 as the exponentially decaying fraction would be incorrect.",
      marks: 4,
      scheme: ["RC = 1.0 s and the equation becomes 6.0 = 10 - 8.0 exp(-t/RC).","The remaining gap fraction is (10 - 6.0)/(10 - 2.0) = 1/2.","t = RC ln(2) = 0.693 s, or 0.69 s; accept equivalent logarithmic rearrangements.","It is the gap to the final voltage that decays from its initial gap; V/V_final is neither that gap fraction nor initially one."],
      answer: "RC = 100000 × 10 × 10^-6 = 1.0 s. Substitution gives 6 = 10 - 8 exp(-t/1.0), so exp(-t/1.0) = 4/8 = 1/2 and t = 0.693 s. The decaying quantity is 10 - V, initially 8 V. The ratio 6/10 ignores both the non-zero starting voltage and the final-voltage offset.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-rc:offset-equilibrium","contextId":"capacitor-rc:precharged-sensor","demand":"transfer","reasoningMoves":["apply exponential relaxation to displacement from a non-zero final voltage"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-infer-leakage",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A capacitor independently measured as 100 μF is discharged through a 200 kΩ resistor. Its measured time constant is 12 s. Assume the only cause of the discrepancy is a constant leakage resistance R_L across the capacitor; the voltmeter is ideal. Calculate R_L and explain why the result should not be interpreted as a changed capacitance.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-rc:parallel-loading","contextId":"capacitor-rc:unexpected-fast-decay","demand":"transfer","reasoningMoves":["infer an unobserved parallel leakage path from a shortened measured time constant"],"expectedMinutes":5},
    parts: [{
      prompt: "A capacitor independently measured as 100 μF is discharged through a 200 kΩ resistor. Its measured time constant is 12 s. Assume the only cause of the discrepancy is a constant leakage resistance R_L across the capacitor; the voltmeter is ideal. Calculate R_L and explain why the result should not be interpreted as a changed capacitance.",
      marks: 4,
      scheme: ["The effective resistance is τ/C = 12/(100 × 10^-6) = 120 kΩ.","The discharge paths are parallel: 1/R_L = 1/(120 kΩ) - 1/(200 kΩ).","R_L = 300 kΩ; allow equivalent parallel-resistance algebra.","The additional path lowers effective resistance while the independently measured capacitance stays 100 μF under the stated model."],
      answer: "R_eff = 12/0.000100 = 120000 Ω. The resistor and leakage path are parallel, so 1/R_L = 1/120000 - 1/200000 and R_L = 300000 Ω. The faster decay is explained by the added current path; changing C contradicts the stipulated explanation and independent measurement.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-rc:parallel-loading","contextId":"capacitor-rc:unexpected-fast-decay","demand":"transfer","reasoningMoves":["infer an unobserved parallel leakage path from a shortened measured time constant"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-resistor-power",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A capacitor initially at 12 V discharges through a 2.0 kΩ resistor with RC = 6.0 s. At what time does the resistor power first fall to 18 mW? Use V = V0 exp(-t/RC) and explain why power does not have the same time constant as voltage.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-energy:exponential-energy","contextId":"capacitor-rc:thermal-pulse","demand":"synoptic","reasoningMoves":["combine exponential voltage with the squared-voltage dependence of resistor power"],"expectedMinutes":5},
    parts: [{
      prompt: "A capacitor initially at 12 V discharges through a 2.0 kΩ resistor with RC = 6.0 s. At what time does the resistor power first fall to 18 mW? Use V = V0 exp(-t/RC) and explain why power does not have the same time constant as voltage.",
      marks: 4,
      scheme: ["Initial power P0 = V0²/R = 144/2000 = 0.072 W, or 72 mW.","P/P0 = (V/V0)² = exp(-2t/RC).","18/72 = 1/4 gives t = (6.0/2) ln(4) = 4.16 s, or 4.2 s; accept finding the threshold voltage 6.0 V then its halving time.","Power is proportional to voltage squared, so its exponential time constant is RC/2 = 3.0 s."],
      answer: "Initially P0 = 12²/2000 = 0.072 W. The target is one quarter of this. Because P = V²/R, P/P0 = exp(-2t/6.0). Thus t = 3.0 ln(4) = 4.16 s. Equivalently the voltage must halve to 6.0 V. Squaring V halves the power time constant to 3.0 s.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-energy:exponential-energy","contextId":"capacitor-rc:thermal-pulse","demand":"synoptic","reasoningMoves":["combine exponential voltage with the squared-voltage dependence of resistor power"]},
    }],
  }),
  defineQuestion({
    slug: "physics-rc-count-transferred-electrons",
    subjectId: "wjec-alevel-physics",
    topics: ["capacitance"],
    kind: "short",
    stem: "A 20 μF capacitor initially at 5.0 V discharges with RC = 2.0 s. Calculate the number of electrons passing a cross-section of the discharge wire between t = 2.0 s and t = 4.0 s. Take the magnitude of electron charge as 1.60 × 10^-19 C. Explain why the charge remaining at 4.0 s alone is insufficient.",
    source: "generated",
    verification: "unverified",
    reviewer: null,
    lastChecked: null,
    difficulty: 4,
    learning: {"familyId":"capacitor-rc:current-integral","contextId":"capacitor-rc:charge-counter","demand":"synoptic","reasoningMoves":["connect an exponential charge change over a late interval to a particle count"],"expectedMinutes":5},
    parts: [{
      prompt: "A 20 μF capacitor initially at 5.0 V discharges with RC = 2.0 s. Calculate the number of electrons passing a cross-section of the discharge wire between t = 2.0 s and t = 4.0 s. Take the magnitude of electron charge as 1.60 × 10^-19 C. Explain why the charge remaining at 4.0 s alone is insufficient.",
      marks: 4,
      scheme: ["Initial plate charge magnitude Q0 = CV0 = 1.0 × 10^-4 C.","Transferred charge magnitude is Q(2.0) - Q(4.0) = Q0[exp(-1) - exp(-2)] = 2.33 × 10^-5 C.","N = ΔQ/e = 1.45 × 10^14 electrons, approximately 1.5 × 10^14; allow follow-through from a stated positive transferred charge using e.","The count concerns charge that passed during the interval, so both endpoint charges are needed; the final charge is still on the capacitor."],
      answer: "Q0 = 20 × 10^-6 × 5.0 = 1.0 × 10^-4 C. The charge lost between the endpoints is 1.0 × 10^-4[exp(-1) - exp(-2)] = 2.3254 × 10^-5 C. Dividing by 1.60 × 10^-19 C gives 1.4534 × 10^14 electrons. Q(4.0) alone is the remaining plate charge, not the charge that passed during the specified interval.",
      specPointIds: ["wjec-alevel-physics.capacitance.sp-04"],
      capabilityIds: ["phys.capacitance.sp-04"],
      aos: ["AO2","AO3"],
      learning: {"familyId":"capacitor-rc:current-integral","contextId":"capacitor-rc:charge-counter","demand":"synoptic","reasoningMoves":["connect an exponential charge change over a late interval to a particle count"]},
    }],
  })
];

