import { depthQuestions, type PhysicsDepthItem, type PhysicsDepthPart } from "./physics-depth-50-common";

const p = (
  demand: PhysicsDepthPart["demand"], family: string, context: string, move: string,
  prompt: string, marks: number, scheme: string[], answer: string,
): PhysicsDepthPart => ({ demand, family, context, move, prompt, marks, scheme, answer });

/**
 * Explicit completion pack for the remaining Unit 1.4 and Unit 2.5 cells.
 * Every pair is authored as a different physical decision or solution path;
 * these drafts stay unverified until a qualified reviewer approves the exact
 * fingerprint.
 */
const ITEMS: PhysicsDepthItem[] = [
  {
    topic: "energy-power", point: 5,
    parts: [
      p("recall", "completion:energy5:gravitational", "completion:energy5:gravitational:lift", "state the gravitational potential-energy relation and reference level", "State the equation for gravitational potential energy near Earth's surface and explain why a zero level must be chosen.", 2, ["E_p = mgh for a uniform gravitational field", "h is the vertical height measured from the chosen zero of potential energy"], "Near the surface E_p = mgh. The value of h is measured from whatever reference level has been defined as E_p = 0."),
      p("recall", "completion:energy5:elastic", "completion:energy5:elastic:spring", "state the elastic energy relation and its domain", "State the elastic strain-energy equation for a Hookean spring and identify the condition needed for using it.", 2, ["E_elastic = 1/2 kx^2 (or 1/2 Fx)", "The extension x must be within the Hooke's-law/proportional region"], "For a Hookean spring the stored energy is 1/2 kx^2. The relation assumes force is proportional to extension over the range used."),
      p("explanation", "completion:energy5:height-reference", "completion:energy5:height-reference:orbit", "explain why changing the datum changes individual energies but not energy differences", "A satellite calculation uses sea level as h = 0, while a second uses the launch pad as h = 0. Explain why both can predict the same speed change.", 3, ["Changing the datum adds the same constant to the potential-energy values", "The change in mgh between two positions is unchanged when the same datum is used consistently", "Conservation of energy depends on the difference in potential energy, so the predicted speed change agrees"], "A new zero shifts every gravitational potential energy by the same constant. The difference mgh_2 - mgh_1 is unchanged, so the kinetic-energy change and speed prediction are unchanged if one datum is used throughout."),
      p("explanation", "completion:energy5:elastic-work", "completion:energy5:elastic-work:launcher", "link the area under a force-extension graph to elastic energy", "Explain why the area under a force-extension graph is the elastic energy stored in a spring that is loaded quasistatically.", 3, ["A small extension dx requires work dW = F dx", "Summing/integrating F dx gives the area under the graph", "For a reversible elastic load that work is stored as elastic potential energy"], "Each small extension takes work F dx. Adding those strips gives the graph area; if the loading is reversible, that input work is stored as elastic potential energy."),
      p("application", "completion:energy5:lift", "completion:energy5:lift:crane", "apply mgh to a vertical lift while separating useful and wasted energy", "A crane raises a 240 kg load through 7.5 m. Calculate the increase in gravitational potential energy and the useful power if the lift takes 12 s. Use g = 9.81 m s^-2.", 3, ["ΔE_p = mgh = 240×9.81×7.5 = 1.77×10^4 J", "P_useful = ΔE_p/t = 1.77×10^4/12 = 1.47×10^3 W", "This is useful output power; motor input is larger if efficiency is below one"], "The load gains 1.77×10^4 J. Dividing by 12 s gives 1.47 kW of useful lifting power; losses make the motor's input power larger."),
      p("application", "completion:energy5:spring", "completion:energy5:spring:archery", "apply elastic energy to infer launch speed", "A 0.80 kg training bow stores 36 J when drawn. Ignoring losses, calculate the launch speed of the arrow and state one reason the measured speed is lower.", 3, ["Set 1/2 kx^2 or stored elastic energy equal to 1/2 mv^2", "v = sqrt(2×36/0.80) = 9.5 m s^-1", "Real losses include sound, bow motion and internal heating"], "Equating 36 J to 1/2mv^2 gives v = sqrt(72/0.80) = 9.5 m s^-1. A real bow transfers some energy to its limbs, sound and heat."),
      p("misconception", "completion:energy5:height-only", "completion:energy5:height-only:fall", "correct the claim that potential energy depends on path length", "A student says a box gains more gravitational potential energy if it is carried along a longer staircase. Correct the claim.", 2, ["For a uniform field the change is mg times vertical height, independent of path", "A longer path can require more work against friction, but it does not change the gravitational-energy increase"], "The gravitational increase is mgΔh, so only the vertical height matters. A longer route may waste more energy through friction, but it does not add gravitational potential energy."),
      p("misconception", "completion:energy5:elastic-force", "completion:energy5:elastic-force:rubber", "separate force from stored energy when extension changes", "A student doubles a spring's extension and says its stored energy doubles because E = Fx. Explain why the energy actually quadruples for a Hookean spring.", 2, ["For a Hookean spring F = kx, so the mean force during loading is 1/2kx", "E = 1/2kx^2, hence doubling x multiplies E by four"], "The force is not constant while the spring is loaded. With F = kx, the area is triangular: E = 1/2kx^2, so twice the extension gives four times the energy."),
      p("calculation", "completion:energy5:two-stage", "completion:energy5:two-stage:roller", "chain gravitational loss into elastic storage and solve for compression", "A 0.50 kg trolley rolls down a frictionless track from a point 0.80 m above a spring. The spring constant is 320 N m^-1. Find the maximum compression.", 4, ["Gravitational energy lost = mgh = 0.50×9.81×0.80 = 3.924 J", "At maximum compression the trolley is instantaneously at rest", "1/2kx^2 = 3.924", "x = sqrt(2×3.924/320) = 0.157 m"], "Energy conservation gives 3.924 J = 1/2(320)x^2, so x = 0.157 m. The trolley's kinetic energy is zero at maximum compression."),
      p("calculation", "completion:energy5:nonlinear", "completion:energy5:nonlinear:force-extension", "integrate a piecewise force-extension law rather than use a final force", "A spring's force rises linearly from 0 to 50 N over 0.12 m, then remains 50 N for a further 0.08 m. Calculate the stored work.", 3, ["First region is a triangle: 1/2×50×0.12 = 3.0 J", "Second region is a rectangle: 50×0.08 = 4.0 J", "Total stored work = 7.0 J"], "The two graph areas are 3.0 J and 4.0 J, so the total work stored is 7.0 J."),
      p("transfer", "completion:energy5:climbing", "completion:energy5:climbing:wheelchair", "transfer potential-energy accounting to a powered incline", "A powered wheelchair climbs a ramp at steady speed. Explain how its electrical energy budget can be used to estimate the fraction of input energy that becomes gravitational potential energy.", 3, ["Measure mass, vertical rise and time to obtain ΔE_p = mgh", "Measure electrical input power and multiply by the travel time", "Efficiency for the climb is mgh/(P_in t), with rolling and motor losses in the remainder"], "The useful store is mgh. The input is P_in t, so the climb efficiency is mgh/(P_in t); friction, rolling resistance and motor heating account for the difference."),
      p("transfer", "completion:energy5:elastic-calibration", "completion:energy5:elastic-calibration:force-sensor", "transfer elastic energy to sensor calibration and identify a systematic error", "A force sensor is used to measure spring energy from the area of an F-x graph. Explain how a zero offset would bias the energy and how to detect it.", 3, ["A constant force offset adds a rectangular area over the full extension", "The calculated energy is systematically too high or too low according to the offset sign", "Check the sensor at zero load and repeat with the extension direction reversed or a calibrated reference"], "An offset adds a false strip of area at every extension, producing a systematic energy error. Zero the sensor before loading and compare against a calibrated load or a reverse-direction check."),
      p("synoptic", "completion:energy5:pendulum", "completion:energy5:pendulum:impact", "combine gravitational, kinetic and elastic stores through a multi-stage event", "A pendulum bob falls 0.40 m, strikes a spring and compresses it by 0.10 m. The bob mass is 0.20 kg and k = 160 N m^-1. Decide whether the stated compression is consistent with a lossless model.", 4, ["Available gravitational energy = 0.20×9.81×0.40 = 0.785 J", "Spring energy at 0.10 m = 1/2×160×0.10^2 = 0.800 J", "The spring value is 0.015 J larger than the available gravitational energy", "The data cannot be lossless as stated; measurement uncertainty or an additional energy input/model error must be investigated"], "The fall supplies 0.785 J, whereas 0.10 m compression stores 0.800 J. A lossless model cannot create the extra 0.015 J, so the measurements or assumptions need checking."),
      p("synoptic", "completion:energy5:thermal-loss", "completion:energy5:thermal-loss:climbing-rope", "combine elastic recovery with efficiency and thermal evidence", "A climbing rope stores 120 J when stretched and returns 90 J on unloading. A climber rises 3.0 m with mass 60 kg. Explain what the 30 J hysteresis loss implies for the energy budget and whether the rope alone can lift the climber.", 4, ["Hysteresis dissipates 120−90 = 30 J, mainly as internal thermal energy", "The climber's gravitational gain is 60×9.81×3.0 = 1.77 kJ", "The rope's stored energy is far smaller than mgh", "An external source must supply most of the lift; the rope is an energy store/damper, not the complete power source"], "Thirty joules becomes heat during the cycle. Raising the climber needs about 1.77 kJ, much more than the rope's 120 J, so another energy source must do the lifting."),
    ],
  },
  {
    topic: "quantum", point: 5,
    parts: [
      p("recall", "completion:quantum5:debroglie", "completion:quantum5:debroglie:beam", "state the de Broglie relation and identify momentum", "State the de Broglie wavelength relation and identify the quantity that controls the wavelength.", 2, ["λ = h/p", "p is the particle momentum; for non-relativistic motion p = mv"], "A particle has de Broglie wavelength λ = h/p. Increasing its momentum makes the wavelength shorter."),
      p("recall", "completion:quantum5:diffraction", "completion:quantum5:diffraction:crystal", "state the evidence that electron diffraction gives for wave behaviour", "What observation in an electron-diffraction experiment is evidence for a wave nature?", 2, ["A regular crystal produces intensity maxima/minima at predictable angles", "The pattern obeys a diffraction/interference relation using a wavelength h/p"], "Sharp diffraction rings or spots at angles predicted by λ = h/p show that electrons interfere like waves."),
      p("explanation", "completion:quantum5:accelerating-potential", "completion:quantum5:accelerating-potential:electron-gun", "explain how an accelerating potential changes wavelength", "Explain why increasing the accelerating potential of an electron gun reduces the electron wavelength.", 3, ["Electrical work gives kinetic energy eV", "For non-relativistic electrons p = sqrt(2meV), so momentum increases with V", "Since λ = h/p, the wavelength decreases approximately as V^-1/2"], "The potential supplies eV of kinetic energy, raising p = sqrt(2meV). Because λ = h/p, a larger accelerating voltage produces a shorter wavelength."),
      p("explanation", "completion:quantum5:wave-particle", "completion:quantum5:wave-particle:interference", "explain why a diffraction pattern is compatible with local detection", "Electrons arrive as individual spots on a detector but build a diffraction pattern over time. Explain how this supports wave-particle duality.", 3, ["Each detection transfers a local, quantised event", "The probability distribution of many events follows wave interference", "The same experiment therefore shows particle detection and wave propagation/probability"], "Each electron is detected at one point, but many detections accumulate with the interference intensity distribution. Local quanta and wave-like probability are both required."),
      p("application", "completion:quantum5:electron-speed", "completion:quantum5:electron-speed:microscope", "apply kinetic energy and de Broglie equations in sequence", "Electrons are accelerated through 150 V. Calculate their speed and de Broglie wavelength. Use m_e = 9.11×10^-31 kg and h = 6.63×10^-34 J s.", 4, ["1/2 m v^2 = eV, so v = sqrt(2eV/m) = 7.26×10^6 m s^-1", "p = mv = 6.61×10^-24 kg m s^-1", "λ = h/p", "λ = 1.00×10^-10 m"], "The 150 eV electron has v ≈ 7.26×10^6 m s^-1 and p ≈ 6.61×10^-24 kg m s^-1, giving λ ≈ 1.00×10^-10 m."),
      p("application", "completion:quantum5:diffraction-angle", "completion:quantum5:diffraction-angle:nickel", "use a measured diffraction angle to infer wavelength and momentum", "A crystal plane spacing is 0.215 nm and first-order diffraction occurs at 21.5° to the planes. Use 2d sinθ = λ to find the wavelength and electron momentum.", 3, ["λ = 2d sinθ = 2×0.215×10^-9×sin21.5° = 1.58×10^-10 m", "p = h/λ", "p = 6.63×10^-34/1.58×10^-10 = 4.20×10^-24 kg m s^-1"], "The wavelength is 1.58×10^-10 m and the momentum inferred from h/λ is 4.20×10^-24 kg m s^-1."),
      p("misconception", "completion:quantum5:shorter-is-faster", "completion:quantum5:shorter-is-faster:electron", "correct the claim that a shorter wavelength means lower momentum", "A student says a shorter de Broglie wavelength means an electron is moving more slowly because the wave crests are closer together. Correct the claim.", 2, ["λ = h/p, so wavelength is inversely proportional to momentum", "A shorter wavelength means larger momentum (and, in this regime, greater speed)"], "The relation is inverse: a shorter wavelength means larger momentum, not smaller. For non-relativistic electrons that also means a greater speed."),
      p("misconception", "completion:quantum5:electron-waves", "completion:quantum5:electron-waves:single-electron", "distinguish matter-wave wavelength from an electron physically spreading as a wave", "A student says an electron must be a continuous smear of charge because it diffracts. Explain what the diffraction result actually tells us.", 2, ["The electron is detected as a local particle with charge e", "The wave description predicts the probability amplitudes and diffraction pattern, not a classical charge smear"], "Detection is local and quantised. The wavefunction's interference predicts where detections are likely; it does not mean a classical electron charge is spread through the apparatus."),
      p("calculation", "completion:quantum5:potential-wavelength", "completion:quantum5:potential-wavelength:electron-microscope", "recompute a power-of-ten wavelength from an accelerating voltage", "Find the de Broglie wavelength of an electron accelerated through 2.50 kV. Use λ = h/sqrt(2m_e eV), h = 6.63×10^-34 J s, m_e = 9.11×10^-31 kg and e = 1.60×10^-19 C.", 3, ["p = sqrt(2m_e eV) = sqrt(2×9.11×10^-31×1.60×10^-19×2500) = 2.70×10^-23 kg m s^-1", "λ = h/p", "λ = 2.46×10^-11 m"], "The momentum is 2.70×10^-23 kg m s^-1, so λ = 6.63×10^-34/(2.70×10^-23) = 2.46×10^-11 m."),
      p("calculation", "completion:quantum5:relativistic-check", "completion:quantum5:relativistic-check:diffraction", "use a classical speed estimate to decide whether a model is self-consistent", "An electron has λ = 5.0×10^-12 m. Estimate its momentum and classical speed, then state why the speed estimate must be checked before using non-relativistic kinetic energy.", 3, ["p = h/λ = 6.63×10^-34/(5.0×10^-12) = 1.33×10^-22 kg m s^-1", "v = p/m_e = 1.46×10^8 m s^-1", "This is about 0.49c, so relativistic corrections are becoming important"], "The wavelength gives p = 1.33×10^-22 kg m s^-1 and a classical v ≈ 1.46×10^8 m s^-1. At nearly half the speed of light, the non-relativistic approximation needs checking."),
      p("transfer", "completion:quantum5:neutron-diffraction", "completion:quantum5:neutron-diffraction:reactor", "transfer de Broglie reasoning to a different massive particle", "Thermal neutrons and electrons can have similar de Broglie wavelengths. Explain how their speeds and masses must differ and why neutrons can probe nuclei.", 3, ["λ = h/(mv), so equal λ means equal momentum, not equal speed", "A neutron's much larger mass means a much lower speed for the same momentum", "Its neutral charge lets it enter nuclei without electrostatic repulsion"], "Equal wavelength means equal momentum. Since a neutron is much more massive it travels more slowly at that momentum, and its lack of charge helps it penetrate matter and probe nuclei."),
      p("transfer", "completion:quantum5:macroscopic", "completion:quantum5:macroscopic:football", "explain why everyday objects do not show observable diffraction", "A football and an electron move at the same speed. Explain why the football's de Broglie wavelength is unmeasurably smaller.", 3, ["λ = h/(mv)", "At the same speed the football has enormously larger mass and momentum", "Its wavelength is far below any practical slit or detector scale, so diffraction is negligible"], "The football's mass makes mv vastly larger than the electron's. Its h/mv wavelength is therefore microscopic beyond measurement, so wave effects are invisible."),
      p("synoptic", "completion:quantum5:electron-optics", "completion:quantum5:electron-optics:resolution", "combine wavelength, diffraction and instrument resolution", "An electron microscope is raised from 10 kV to 40 kV. Predict the change in de Broglie wavelength and discuss one practical limit on the resolution improvement.", 4, ["For non-relativistic electrons λ ∝ V^-1/2", "Quadrupling V halves λ", "A shorter wavelength can improve diffraction-limited resolution", "Lens aberrations, sample damage and finite detector geometry may dominate instead"], "Quadrupling the voltage halves λ in the non-relativistic model, so the diffraction limit improves. Aberrations or sample damage can then set the practical resolution rather than the wavelength."),
      p("synoptic", "completion:quantum5:crystal-identification", "completion:quantum5:crystal-identification:unknown", "combine a diffraction measurement with model selection", "Two candidate crystal spacings are 0.18 nm and 0.24 nm. An electron beam has λ = 0.16 nm and a first-order maximum is measured at 20°. Decide which spacing is compatible with 2d sinθ = λ and explain why a second order helps.", 4, ["d = λ/(2 sin20°) = 0.234 nm", "The 0.24 nm candidate is compatible within the measurement precision", "The 0.18 nm candidate predicts a different angle", "A second-order peak supplies an independent nλ test and can expose a coincidental first-order match"], "The inferred spacing is 0.234 nm, selecting the 0.24 nm crystal. A second-order maximum gives a separate 2d sinθ = 2λ check, strengthening or rejecting the identification."),
    ],
  },
  {
    topic: "quantum", point: 6,
    parts: [
      p("recall", "completion:quantum6:levels", "completion:quantum6:levels:atom", "state that atomic energies are quantised", "State what is meant by discrete atomic energy levels.", 2, ["An electron in an atom can occupy only particular allowed energies", "Intermediate energies between allowed levels are not permitted for that bound electron"], "Bound electrons occupy discrete allowed energy levels rather than a continuum of energies."),
      p("recall", "completion:quantum6:spectra", "completion:quantum6:spectra:lamp", "distinguish emission and absorption line spectra", "Distinguish an emission line spectrum from an absorption line spectrum.", 2, ["Emission lines occur when excited electrons fall and emit photons", "Absorption lines occur when photons of particular energies lift electrons to higher levels"], "Emission produces bright lines from downward transitions; absorption produces dark lines when specific photon energies are removed from a continuous spectrum."),
      p("explanation", "completion:quantum6:photon-energy", "completion:quantum6:photon-energy:transition", "explain why line spectra contain only selected wavelengths", "Explain why an isolated gas produces lines rather than a continuous range of emitted wavelengths.", 3, ["A transition photon has E = hf = difference between two allowed levels", "Only certain level differences exist", "Therefore only corresponding frequencies/wavelengths are emitted"], "Each photon carries the difference between two allowed levels. Since only certain differences exist, only their frequencies appear as spectral lines."),
      p("explanation", "completion:quantum6:absorption", "completion:quantum6:absorption:starlight", "explain absorption lines in a cooler gas over a continuous source", "A cool gas lies between a hot continuous source and a spectrometer. Explain the dark lines observed.", 3, ["The hot source supplies a continuous range of photon energies", "Gas atoms absorb only photons matching allowed upward transitions", "Those wavelengths are missing from the transmitted spectrum; re-emission is in other directions"], "The continuous source contains all wavelengths, but the intervening atoms remove only transition-matching photons. Their re-emission is spread in directions, leaving dark lines in the forward spectrum."),
      p("application", "completion:quantum6:transition", "completion:quantum6:transition:neon", "apply a level diagram to determine emitted frequency", "An atom has levels at -5.0 eV and -2.0 eV. Calculate the photon frequency emitted in a transition from -2.0 eV to -5.0 eV. Use 1 eV = 1.60×10^-19 J and h = 6.63×10^-34 J s.", 3, ["Energy drop = 3.0 eV = 4.80×10^-19 J", "E = hf", "f = 4.80×10^-19/6.63×10^-34 = 7.24×10^14 Hz"], "The drop is 3.0 eV = 4.80×10^-19 J, so f = E/h = 7.24×10^14 Hz."),
      p("application", "completion:quantum6:series", "completion:quantum6:series:hydrogen", "infer a level difference from a measured wavelength", "A spectral line has wavelength 486 nm. Calculate the energy difference between the two levels in joules and electron volts.", 3, ["E = hc/λ = 6.63×10^-34×3.00×10^8/(486×10^-9) = 4.09×10^-19 J", "Convert by dividing by 1.60×10^-19 J eV^-1", "ΔE = 2.56 eV"], "The photon energy is 4.09×10^-19 J, equivalent to 2.56 eV."),
      p("misconception", "completion:quantum6:continuous-levels", "completion:quantum6:continuous-levels:neon", "correct the claim that any photon energy can be absorbed", "A student says an atom can absorb any photon provided it is energetic enough. Correct the statement.", 2, ["For a bound-bound transition the photon energy must equal an allowed level difference", "An above-threshold but mismatched photon is not absorbed in that transition; ionisation is a separate possibility"], "A bound atom absorbs a photon only when hf matches an allowed gap. A higher but mismatched energy is not accepted as a smaller transition; it might ionise the atom if sufficient."),
      p("misconception", "completion:quantum6:line-width", "completion:quantum6:line-width:gas", "distinguish line intensity from line position", "A student says a brighter spectral line has a larger photon energy. Explain what brightness and line position represent.", 2, ["Line position/wavelength gives the photon energy and level difference", "Brightness depends on the number of transitions/photons, not the energy of each photon"], "The line's wavelength fixes hf and hence the level gap. A brighter line means more photons or transitions, not a larger energy per photon."),
      p("calculation", "completion:quantum6:series-energy", "completion:quantum6:series-energy:unknown", "calculate a transition series from several level differences", "An atom has levels at 0, 2.0, 5.0 and 8.0 eV above the ground state. How many distinct photon energies can be emitted in downward transitions, and what is the largest wavelength?", 3, ["There are 4 choose 2 = 6 possible pairs of levels", "The smallest non-zero gap is 2.0 eV, which gives the lowest photon frequency", "Largest wavelength λ = hc/E = 1240 eV nm / 2.0 eV = 620 nm"], "Six level pairs can emit. The smallest gap is 2.0 eV, so the longest wavelength is about 620 nm."),
      p("calculation", "completion:quantum6:rydberg", "completion:quantum6:rydberg:hydrogen", "use a measured wavelength to identify a transition energy", "A hydrogen line is measured at 656 nm. Calculate its photon energy in eV and state whether it can be produced by a 1.8 eV transition.", 3, ["E = hc/λ = 3.03×10^-19 J", "E = 3.03×10^-19/(1.60×10^-19) = 1.89 eV", "A 1.8 eV transition would have a longer wavelength, so it cannot give 656 nm exactly"], "Using E = hc/λ gives 3.03×10^-19 J = 1.89 eV for the 656 nm photon. A 1.8 eV gap would not match that line; its wavelength would be about 689 nm."),
      p("transfer", "completion:quantum6:astronomy", "completion:quantum6:astronomy:redshift", "transfer line identification to Doppler-shift inference", "A known stellar absorption line at 500 nm is observed at 505 nm. Explain what can be inferred and why the atomic energy levels themselves need not have changed.", 3, ["The fractional wavelength shift is Δλ/λ = 5/500 = 0.010", "For a small Doppler shift the source recedes at about 0.010c", "The line identifies the same atomic transition; relative motion changes the observed frequency"], "The 1% redshift indicates recession at roughly 0.01c for a small-shift approximation. The transition energy is unchanged in the star's frame; motion changes what the observer measures."),
      p("transfer", "completion:quantum6:fluorescence", "completion:quantum6:fluorescence:security", "transfer level transitions to excitation and re-emission", "A fluorescent material absorbs ultraviolet photons and emits visible photons. Explain why the emitted photons have lower energy.", 3, ["UV photons promote electrons to high excited states", "Some energy is transferred non-radiatively to lattice vibrations before emission", "The remaining downward transition has lower energy and hence longer wavelength"], "The absorbed UV energy is partly lost to vibrations and other non-radiative processes. The later transition therefore emits lower-energy, longer-wavelength visible photons."),
      p("synoptic", "completion:quantum6:plasma-diagnostics", "completion:quantum6:plasma-diagnostics:fusion", "combine line ratios with population and temperature reasoning", "A fusion plasma shows stronger high-energy emission lines after heating. Explain what this suggests about populations and how line intensity must be interpreted cautiously.", 4, ["Heating raises the fraction of atoms/ions in excited states", "High-energy transitions become more populated and their lines can strengthen", "Line intensity also depends on density, transition probability and viewing path", "Line positions diagnose level energies; intensities need a population/model interpretation"], "Heating changes the excited-state populations, allowing more high-energy transitions. Intensity is not temperature alone: density, transition probabilities and geometry also matter."),
      p("synoptic", "completion:quantum6:absorption-emission", "completion:quantum6:absorption-emission:calibration", "combine emission and absorption evidence to test a material identity", "A gas produces emission lines at 434 nm and 486 nm. A lamp viewed through the gas shows dark lines at the same wavelengths. Explain why this agreement supports the identification and what it does not prove.", 4, ["The same wavelengths correspond to the same level differences", "Emission shows downward transitions; absorption shows matching upward transitions", "The agreement is a fingerprint supporting the gas identity", "It does not by itself determine abundance or temperature without intensity/calibration data"], "Matching bright and dark wavelengths are the same transition gaps seen in opposite directions, supporting the gas identification. Abundance and temperature require calibrated intensities and a population model."),
    ],
  },
  {
    topic: "quantum", point: 7,
    parts: [
      p("recall", "completion:quantum7:electronvolt", "completion:quantum7:electronvolt:definition", "define the electron volt and convert its unit", "Define one electron volt and state its value in joules.", 2, ["One electron volt is the energy transferred when a charge e moves through a potential difference of 1 V", "1 eV = 1.60×10^-19 J"], "An electron volt is the energy gained by one elementary charge through 1 V: 1 eV = 1.60×10^-19 J."),
      p("recall", "completion:quantum7:transition-rule", "completion:quantum7:transition-rule:atom", "state the photon-energy rule for a level transition", "State the relation between a photon energy and the energy-level difference in an atomic transition.", 2, ["hf = |E_high − E_low|", "Emission uses a downward transition; absorption uses an upward transition"], "The photon energy equals the magnitude of the level difference, hf = |ΔE|; the direction distinguishes emission from absorption."),
      p("explanation", "completion:quantum7:units", "completion:quantum7:units:calculator", "explain why electron volts are convenient but joules are required in SI calculations", "Explain why an atomic spectrum is often tabulated in eV but a calculation using h and c needs joules.", 3, ["eV is a convenient energy scale for microscopic charge transitions", "h and c are normally used with SI units, so E must be in joules", "Convert with 1 eV = 1.60×10^-19 J before substituting"], "Electron volts keep atomic energy numbers readable, whereas SI equations with h and c require joules. Use the conversion 1 eV = 1.60×10^-19 J before mixing the units."),
      p("explanation", "completion:quantum7:negative-levels", "completion:quantum7:negative-levels:hydrogen", "explain the sign convention for bound-state energies", "Hydrogen levels are shown as negative values with zero at ionisation. Explain the meaning of a more negative level and of a positive energy after ionisation.", 3, ["The zero is the separated electron-plus-ion reference", "A negative bound level has less energy than the separated state; more negative means more tightly bound", "Positive energy means the electron is free with kinetic energy above the ionisation reference"], "The zero corresponds to an electron infinitely far from the ion with no kinetic energy. Negative values are bound; a positive value is a free electron with excess kinetic energy."),
      p("application", "completion:quantum7:mev-joule", "completion:quantum7:mev-joule:detector", "convert a nuclear-scale energy and use it in a photon calculation", "A gamma ray has energy 2.40 MeV. Calculate its energy in joules and wavelength. Use h = 6.63×10^-34 J s and c = 3.00×10^8 m s^-1.", 3, ["E = 2.40×10^6×1.60×10^-19 = 3.84×10^-13 J", "λ = hc/E", "λ = 5.18×10^-13 m"], "The energy is 3.84×10^-13 J and λ = (6.63×10^-34×3.00×10^8)/(3.84×10^-13) = 5.18×10^-13 m."),
      p("application", "completion:quantum7:level-diagram", "completion:quantum7:level-diagram:led", "apply an energy gap to choose an emitted colour", "An LED has a band-gap energy of 2.1 eV. Estimate the wavelength of the emitted light and identify the region of the spectrum.", 3, ["E = 2.1×1.60×10^-19 = 3.36×10^-19 J", "λ = hc/E = 5.92×10^-7 m", "About 590 nm, in the visible yellow region"], "The gap is 3.36×10^-19 J, giving λ ≈ 5.92×10^-7 m = 592 nm, visible yellow light."),
      p("misconception", "completion:quantum7:ev-voltage", "completion:quantum7:ev-voltage:electron", "correct the claim that eV is a voltage", "A student writes eV = 4.0 V for an electron crossing a 4.0 V supply. Correct the units and meaning.", 2, ["4.0 V is a potential difference, not an energy", "An electron crossing 4.0 V gains 4.0 eV = 6.4×10^-19 J"], "The voltage is 4.0 V. The electron's energy gain is 4.0 eV, or 6.4×10^-19 J; eV denotes energy when e is the elementary charge."),
      p("misconception", "completion:quantum7:energy-direction", "completion:quantum7:energy-direction:absorption", "correct reversing the sign of an absorption transition", "A student calculates an absorption photon energy as E_low − E_high and obtains a negative value. Explain how to report it.", 2, ["Photon energy is a positive magnitude |E_high − E_low|", "Absorption raises the electron, so the atom's energy change is positive even if a signed bookkeeping difference is negative"], "Report the photon energy as the positive gap E_high−E_low. A negative sign from reversing the subtraction is a bookkeeping convention, not a negative photon energy."),
      p("calculation", "completion:quantum7:transition-chain", "completion:quantum7:transition-chain:laser", "chain two energy-level differences and convert the final result", "A laser transition drops from -1.2 eV to -3.8 eV. Calculate the photon energy in joules and its frequency.", 3, ["ΔE = 2.6 eV", "ΔE = 2.6×1.60×10^-19 = 4.16×10^-19 J", "f = ΔE/h = 6.27×10^14 Hz"], "The gap is 2.6 eV = 4.16×10^-19 J, so f = 4.16×10^-19/(6.63×10^-34) = 6.27×10^14 Hz."),
      p("calculation", "completion:quantum7:ionisation", "completion:quantum7:ionisation:photoelectron", "calculate residual kinetic energy after an energy-level transition", "An atom in a -7.0 eV state absorbs a 9.5 eV photon. Calculate the kinetic energy of the freed electron in eV and joules.", 3, ["Ionisation needs 7.0 eV; excess energy = 9.5−7.0 = 2.5 eV", "K = 2.5 eV", "K = 4.0×10^-19 J"], "The photon first supplies 7.0 eV to reach the zero ionisation level, leaving 2.5 eV = 4.0×10^-19 J as electron kinetic energy."),
      p("transfer", "completion:quantum7:mass-spectrometer", "completion:quantum7:mass-spectrometer:ion", "transfer eV conversion to an ion accelerated in a field", "A singly charged ion is accelerated through 12 kV. Explain its energy gain in eV and joules, and why the same voltage gives a different speed for different ions.", 3, ["A charge +e through 12 kV gains 12 keV", "Energy = 12×10^3×1.60×10^-19 = 1.92×10^-15 J", "For the same kinetic energy v depends on mass, v = sqrt(2K/m)"], "The ion gains 12 keV = 1.92×10^-15 J. Its speed depends on mass, so a heavier ion is slower at the same energy."),
      p("transfer", "completion:quantum7:threshold", "completion:quantum7:threshold:photocathode", "transfer energy-level thresholds to a photoelectric measurement", "A photocathode has work function 2.3 eV and is illuminated by 3.1 eV photons. Predict the maximum electron kinetic energy and explain how a stopping potential measures it.", 3, ["K_max = hf − φ = 3.1−2.3 = 0.8 eV", "The stopping potential satisfies eV_s = K_max", "Therefore V_s = 0.8 V for singly charged electrons"], "The excess is 0.8 eV. A reverse potential of 0.8 V supplies 0.8 eV per electron and just stops the fastest electrons."),
      p("synoptic", "completion:quantum7:energy-accounting", "completion:quantum7:energy-accounting:fluorescence", "combine eV conversion with non-radiative energy loss", "A phosphor absorbs 3.4 eV UV photons and emits 2.1 eV visible photons. Calculate the energy lost per photon in joules and explain where it goes.", 4, ["Loss = 3.4−2.1 = 1.3 eV", "1.3 eV = 2.08×10^-19 J", "The emitted photon has the lower energy gap", "The difference becomes lattice vibration/heat or other non-radiative transfers"], "Each photon loses 1.3 eV = 2.08×10^-19 J before emission. The difference is transferred to vibrations and other non-radiative channels."),
      p("synoptic", "completion:quantum7:calibration", "completion:quantum7:calibration:spectrum", "combine calibration, significant figures and a transition conclusion", "A spectrometer reports a line at 620.0 nm ± 0.5 nm. Calculate the transition energy in eV to 3 significant figures and state the dominant uncertainty source.", 4, ["E = hc/λ = 3.20×10^-19 J", "E = 3.20×10^-19/(1.60×10^-19) = 2.00 eV", "Relative wavelength uncertainty is 0.5/620 ≈ 0.081%, so energy has the same approximate fractional uncertainty", "The wavelength calibration/resolution dominates if constants are treated as exact"], "E = hc/λ gives 3.20×10^-19 J = 2.00 eV for the line. Since E is proportional to 1/λ, the 0.081% wavelength uncertainty gives about 0.081% energy uncertainty; calibration dominates under the stated assumptions."),
    ],
  },
];

export const physicsDepthCompletionEnergyQuantumQuestions = depthQuestions(ITEMS);
