import { depthQuestions, type PhysicsDepthItem, type PhysicsDepthPart } from "./physics-depth-50-common";

/**
 * Core WJEC Physics depth pack.  The prompts are written as separate
 * reasoning operations and contexts so the quality audit can reject a
 * number-swapped reskin.  They remain generated/unverified until a qualified
 * reviewer signs the exact content fingerprint.
 */
const p = (
  demand: PhysicsDepthPart["demand"],
  family: string,
  context: string,
  move: string,
  prompt: string,
  marks: number,
  scheme: string[],
  answer: string,
): PhysicsDepthPart => ({ demand, family, context, move, prompt, marks, scheme, answer });

const ITEMS: PhysicsDepthItem[] = [
  {
    topic: "kinematics-dynamics", point: 5,
    parts: [
      p("recall", "core:motion5:distance-displacement", "core:motion5:distance-displacement:walk", "distinguish scalar path length from signed change of position", "Define distance and displacement, and state which is a scalar and which is a vector.", 3, ["Distance is the total path length travelled", "Displacement is the straight-line change from initial to final position, with direction", "Distance is scalar; displacement is vector"], "Distance adds the whole path and has no direction. Displacement joins the start to the finish and carries a direction, so it is a vector."),
      p("recall", "core:motion5:average-instantaneous", "core:motion5:average-instantaneous:journey", "state average and instantaneous velocity as derivatives or ratios", "State formulae for average velocity and instantaneous velocity.", 2, ["Average velocity = total displacement / total time", "Instantaneous velocity is the gradient of a displacement-time graph (the limiting rate Δs/Δt)"], "Average velocity is total displacement divided by total time. Instantaneous velocity is the gradient of the tangent to a displacement-time graph."),
      p("explanation", "core:motion5:tangent-gradient", "core:motion5:tangent-gradient:cyclist", "explain why a tangent gradient gives velocity at one instant", "Explain why the tangent to a curved displacement-time graph gives the cyclist's velocity at that instant.", 3, ["The gradient is Δs/Δt, a rate of change of displacement", "A tangent uses an interval made arbitrarily small around the chosen time", "The limiting gradient is therefore instantaneous velocity, including its sign"], "Velocity is the rate at which displacement changes. Shrinking the two points around the chosen time turns the secant into a tangent, so its signed gradient is the instantaneous velocity."),
      p("explanation", "core:motion5:negative-acceleration", "core:motion5:negative-acceleration:lift", "separate negative acceleration from slowing by comparing velocity and acceleration signs", "A lift is moving upward but slowing as it approaches a floor. Explain why its acceleration is downward even though its velocity is upward.", 3, ["Upward velocity is positive for the chosen convention", "Slowing means acceleration is opposite to velocity", "Therefore acceleration is negative/downward; slowing is about opposite signs, not negative acceleration alone"], "Choose up as positive: the lift has positive velocity. To reduce its speed the acceleration must point down, giving a negative acceleration. A negative acceleration can also speed an object up if its velocity is already negative."),
      p("application", "core:motion5:out-and-back", "core:motion5:out-and-back:runner", "calculate average speed and average velocity for a reversing journey", "A runner travels 120 m east in 20 s, then 50 m west in 10 s. Calculate the average speed and average velocity for the whole journey.", 4, ["Total distance = 120 + 50 = 170 m", "Displacement = 120 − 50 = 70 m east", "Average speed = 170/30 = 5.67 m s⁻¹", "Average velocity = 70/30 = 2.33 m s⁻¹ east"], "The path length is 170 m and the signed displacement is 70 m east. Dividing by 30 s gives an average speed of 5.67 m s⁻¹ and an average velocity of 2.33 m s⁻¹ east."),
      p("application", "core:motion5:gradient-data", "core:motion5:gradient-data:position-sensor", "estimate an instantaneous velocity from two points on a local tangent", "A position sensor's tangent passes through (2.0 s, 3.4 m) and (2.4 s, 5.0 m). Estimate the instantaneous velocity at about 2.2 s.", 2, ["Use tangent gradient Δs/Δt = (5.0 − 3.4)/(2.4 − 2.0)", "v ≈ 4.0 m s⁻¹"], "The tangent gradient is (5.0−3.4)/(2.4−2.0) = 4.0 m s⁻¹, so the velocity near 2.2 s is about 4.0 m s⁻¹."),
      p("misconception", "core:motion5:zero-average-fallacy", "core:motion5:zero-average-fallacy:round-trip", "reject zero average velocity as evidence of no movement", "A student walks 200 m north and then 200 m south and says the average velocity proves they did not move. Correct the claim.", 3, ["The final displacement is zero, so average velocity is zero", "The distance travelled is 400 m, so average speed is non-zero", "Zero average velocity describes the endpoints, not the path or the time spent moving"], "The round trip has zero displacement and therefore zero average velocity, but 400 m of distance and a positive average speed. An endpoint ratio cannot erase motion between the endpoints."),
      p("misconception", "core:motion5:speed-velocity-sign", "core:motion5:speed-velocity-sign:reversing-car", "correct treating signed velocity as a speed", "A car's velocity changes from −8.0 m s⁻¹ to −3.0 m s⁻¹. A student says it has accelerated because the numerical value increased. Explain the error.", 3, ["Speed is the magnitude: it fell from 8.0 to 3.0 m s⁻¹", "Acceleration is Δv/Δt and must use the signed velocities", "The car is still moving in the negative direction but slowing"], "The signed value rose from −8 to −3, but the speed fell from 8.0 m s⁻¹ to 3.0 m s⁻¹. The direction remains negative; whether it slows follows the velocity and acceleration signs, not the size of the signed number alone."),
      p("calculation", "core:motion5:piecewise-average", "core:motion5:piecewise-average:delivery", "combine piecewise displacements and signed velocities over unequal intervals", "A delivery robot moves at +1.5 m s⁻¹ for 40 s, waits 20 s, then moves at −0.50 m s⁻¹ for 30 s. Find its displacement, distance and average velocity.", 4, ["Displacements: +60 m, 0, −15 m", "Net displacement = +45 m", "Distance = 60 + 15 = 75 m", "Average velocity = 45/90 = +0.50 m s⁻¹"], "The three signed displacements are +60, 0 and −15 m. Net displacement is +45 m, distance is 75 m, and over 90 s the average velocity is +0.50 m s⁻¹."),
      p("calculation", "core:motion5:acceleration-from-data", "core:motion5:acceleration-from-data:tram", "calculate acceleration and final velocity from a time-stamped velocity change", "A tram's velocity is +6.0 m s⁻¹ at 4.0 s and +18.0 m s⁻¹ at 10.0 s. Calculate its average acceleration and state whether its speed increased.", 3, ["a = (18.0 − 6.0)/(10.0 − 4.0)", "a = +2.0 m s⁻²", "Positive velocity and positive acceleration mean speed increased"], "The average acceleration is 12.0/6.0 = +2.0 m s⁻². Both velocity and acceleration are positive, so the tram's speed increases."),
      p("transfer", "core:motion5:radar-range-rate", "core:motion5:radar-range-rate:radar", "transfer signed rate reasoning to a changing range measurement", "A radar records a car's range falling from 80 m to 50 m in 5.0 s. Explain what the range gradient says and why it is not automatically the car's speed in every direction.", 3, ["Range gradient = Δrange/Δt = −6.0 m s⁻¹", "The negative sign means the car approaches the radar", "This is the radial component of velocity; sideways motion can give a different true speed"], "The range rate is (50−80)/5 = −6.0 m s⁻¹, so the car closes on the radar at 6.0 m s⁻¹ radially. A radar sees only the line-of-sight component; lateral motion is hidden from that one measurement."),
      p("transfer", "core:motion5:photo-finish", "core:motion5:photo-finish:athletics", "choose a measurement interval that estimates an instantaneous quantity without confusing average and instantaneous values", "An athletics camera samples a sprinter every 0.01 s. Explain how a short interval estimates instantaneous velocity and one limitation of making the interval even shorter.", 3, ["Use displacement divided by the short time interval as an average velocity", "As the interval shrinks the average approaches the instantaneous value", "Very short intervals make displacement comparable to resolution/noise, increasing percentage uncertainty"], "The camera's Δs/Δt over a small interval approximates the tangent gradient. A smaller interval improves temporal locality, but pixel resolution and timing noise then make Δs a tiny, uncertain difference."),
      p("synoptic", "core:motion5:energy-graph-link", "core:motion5:energy-graph-link:rollercoaster", "combine velocity sign interpretation with kinetic-energy dependence on speed", "A rollercoaster's velocity changes from +12 m s⁻¹ to −12 m s⁻¹ at a reversal. Compare its velocity, speed, momentum and kinetic energy before and after.", 4, ["Velocity reverses sign; speed magnitude is unchanged", "Momentum reverses direction because p = mv", "Kinetic energy is unchanged because it depends on v²", "The reversal requires an acceleration during the turn"], "The velocity changes from +12 to −12 m s⁻¹, but the speed remains 12 m s⁻¹. Momentum changes sign, while kinetic energy ½mv² is the same; an acceleration must act during the reversal even though the initial and final speeds match."),
      p("synoptic", "core:motion5:uncertainty-derivative", "core:motion5:uncertainty-derivative:tracking", "propagate position uncertainty into a finite-difference velocity estimate", "Two position readings are 1.20 ± 0.02 m and 1.80 ± 0.02 m, 0.50 ± 0.01 s apart. Calculate the velocity and an approximate percentage uncertainty.", 4, ["v = 0.60/0.50 = 1.2 m s⁻¹", "Percentage uncertainty in displacement = (0.02+0.02)/0.60 × 100 ≈ 6.7%", "Percentage uncertainty in time = 0.01/0.50 × 100 = 2.0%", "Total approximate percentage uncertainty ≈ 8.7%"], "The displacement difference is 0.60 m, so v = 1.2 m s⁻¹. Adding fractional uncertainties gives about 6.7% + 2.0% = 8.7%, so the finite-difference velocity is approximately 1.2 ± 0.1 m s⁻¹."),
    ],
  },
  {
    topic: "kinematics-dynamics", point: 6,
    parts: [
      p("recall", "core:motion6:projectile-components", "core:motion6:projectile-components:launch", "state the independent horizontal and vertical projectile assumptions", "State the acceleration and velocity assumptions used for an ideal projectile after launch.", 3, ["Horizontal acceleration is zero, so horizontal velocity is constant", "Vertical acceleration is −g (ignoring air resistance)", "Horizontal and vertical motions are independent but share the same time"], "After release, the ideal projectile has constant horizontal velocity and vertical acceleration g downward. The two component equations are independent, but both use the same elapsed time."),
      p("recall", "core:motion6:resolve-launch", "core:motion6:resolve-launch:angle", "resolve a launch speed into perpendicular components", "A projectile is launched at speed u at angle θ above the horizontal. State its initial horizontal and vertical components.", 2, ["u_x = u cos θ", "u_y = u sin θ"], "The horizontal component is u cosθ and the upward vertical component is u sinθ."),
      p("explanation", "core:motion6:gravity-only-vertical", "core:motion6:gravity-only-vertical:football", "explain why gravity changes vertical velocity but not horizontal velocity", "A football is kicked in still air. Explain why its horizontal component remains constant while its vertical component changes.", 3, ["Weight acts vertically downward", "There is no horizontal force in the ideal model, so horizontal acceleration is zero", "The vertical force gives acceleration −g and changes vertical velocity"], "Gravity has only a vertical component. With air resistance ignored, no horizontal resultant force changes the horizontal velocity, while weight supplies a constant downward acceleration."),
      p("explanation", "core:motion6:time-shared", "core:motion6:time-shared:cliff", "explain why component equations must use one common flight time", "A stone is thrown horizontally from a cliff. Explain why the time found from the vertical drop must also be used in the horizontal range calculation.", 3, ["The horizontal and vertical motions occur simultaneously", "The vertical equation determines when the stone reaches the ground", "During that same interval horizontal distance is x = u_x t"], "The stone does not complete one motion and then start the other: both run together. The vertical drop fixes the single impact time, and the horizontal displacement accumulated in that same time gives the range."),
      p("application", "core:motion6:launch-components", "core:motion6:launch-components:netball", "resolve a measured launch and predict component velocities at a later time", "A netball leaves a player's hands at 10 m s⁻¹ at 40° above horizontal. Calculate its initial components and its vertical velocity 0.60 s later. Take g = 9.81 m s⁻².", 4, ["u_x = 10 cos40° = 7.66 m s⁻¹", "u_y = 10 sin40° = 6.43 m s⁻¹", "v_y = u_y − gt = 6.43 − 9.81×0.60", "v_y ≈ 0.54 m s⁻¹ upward"], "The components are 7.66 m s⁻¹ horizontal and 6.43 m s⁻¹ upward. After 0.60 s, v_y = 6.43−5.886 ≈ 0.54 m s⁻¹ upward."),
      p("application", "core:motion6:horizontal-cliff", "core:motion6:horizontal-cliff:rescue", "chain vertical free-fall time to horizontal range", "A rescue package is launched horizontally at 8.0 m s⁻¹ from a 20 m cliff. Calculate the time to land and the horizontal range. Take g = 9.81 m s⁻².", 3, ["20 = ½gt² gives t = √(40/9.81) = 2.02 s", "Horizontal velocity remains 8.0 m s⁻¹", "Range x = 8.0×2.02 = 16.2 m"], "The vertical drop gives t = √(2h/g) = √(40/9.81) = 2.02 s. In that time the constant horizontal speed covers x = 8.0×2.02 ≈ 16.2 m."),
      p("misconception", "core:motion6:heavier-projectile", "core:motion6:heavier-projectile:two-balls", "reject mass as a cause of different ideal projectile trajectories", "Two balls leave the same point with the same horizontal speed, one twice the mass of the other. A student predicts the heavier ball lands later. Correct the prediction in the ideal model.", 3, ["Both have the same vertical acceleration g", "The mass cancels from the vertical equation of motion", "They have the same flight time and horizontal range; air resistance could break this in reality"], "Ignoring air resistance, both balls fall with acceleration g, independent of mass. Their vertical times and horizontal ranges match; only a real drag difference could separate them."),
      p("misconception", "core:motion6:apex-horizontal-zero", "core:motion6:apex-horizontal-zero:tennis", "reject the claim that zero vertical velocity means the projectile is stationary", "At the top of a tennis ball's path its vertical velocity is zero. Explain why its total velocity is not zero there.", 2, ["Only the vertical component is zero at the apex", "The horizontal component remains non-zero in the ideal model, so the ball continues forward"], "At the apex the upward component has fallen to zero, but the horizontal component is still constant. The velocity is therefore horizontal, not zero."),
      p("calculation", "core:motion6:range-level", "core:motion6:range-level:long-jump", "derive the time and range for a level projectile from components", "A jumper leaves level ground at 9.0 m s⁻¹ at 30°. Calculate the ideal time of flight and horizontal range. Take g = 9.81 m s⁻².", 4, ["u_y = 9.0 sin30° = 4.50 m s⁻¹", "For equal launch and landing heights, t = 2u_y/g = 0.917 s", "u_x = 9.0 cos30° = 7.79 m s⁻¹", "Range = u_x t = 7.14 m"], "The vertical component is 4.50 m s⁻¹, giving t = 2(4.50)/9.81 = 0.917 s. The horizontal component is 7.79 m s⁻¹, so range ≈ 7.14 m."),
      p("calculation", "core:motion6:height-from-time", "core:motion6:height-from-time:drone", "use a vertical component and time to calculate displacement and height", "A drone releases a package with vertical velocity 3.0 m s⁻¹ upward from 15 m. Find its height 0.80 s later, ignoring air resistance.", 3, ["Vertical displacement s = ut − ½gt² = 3.0×0.80 − ½×9.81×0.80²", "s = 2.40 − 3.14 = −0.74 m", "Height = 15 − 0.74 = 14.3 m"], "The package's vertical displacement is 3.0(0.80)−½(9.81)(0.80²) = −0.74 m. It is therefore at about 14.3 m, below the release point."),
      p("transfer", "core:motion6:wind-frame", "core:motion6:wind-frame:kayak", "transfer relative-velocity reasoning to a projectile in a moving medium", "A flare is fired at 12 m s⁻¹ at 50° from a boat moving at 4.0 m s⁻¹ east. Explain how to obtain its ground-frame horizontal component and why vertical motion is unchanged.", 3, ["The launch velocity relative to the boat has horizontal component 12 cos50°", "Ground horizontal component is 12 cos50° + 4.0 east", "The boat's horizontal translation does not alter the vertical component or g"], "Add velocities: the flare contributes 12cos50° horizontally relative to the boat, and the boat adds 4.0 m s⁻¹ east. The vertical component 12sin50° and acceleration g are unchanged by that horizontal frame shift."),
      p("transfer", "core:motion6:target-intercept", "core:motion6:target-intercept:water-polo", "use simultaneous component equations to test an interception claim", "A water-polo ball is thrown horizontally from a 2.0 m platform while a target moves horizontally away at constant speed. Explain the two independent checks needed to decide whether the ball hits the target.", 3, ["Use the vertical equation to find the ball's impact time", "Use horizontal positions at that same time for ball and target", "A hit requires both vertical impact height and horizontal positions to agree; matching range alone is insufficient"], "First calculate when the ball reaches the target's height from its vertical fall. Then compare the ball's horizontal position with the target's position at that same instant. Both coordinates must coincide; a horizontal match at the wrong time is not an interception."),
      p("synoptic", "core:motion6:energy-projectile", "core:motion6:energy-projectile:archery", "combine component motion with energy conservation and launch-angle trade-offs", "An arrow leaves a bow at fixed speed. Explain why changing the launch angle changes the peak height and range, and which energy quantity is unchanged at release.", 4, ["Initial kinetic energy ½mu² is unchanged if speed and mass are fixed", "The angle redistributes the same speed into u_x and u_y", "Larger u_y gives greater vertical rise; larger u_x gives more horizontal travel", "Range also depends on the shared flight time, so the maximum range angle is a model result (45° for level, no-drag ground)"], "The bow gives the same ½mu² at fixed speed, but the angle reallocates it between horizontal and vertical components. More vertical component buys height and time; more horizontal component buys distance per second. In the ideal level model these trade to a 45° maximum range, but drag and unequal heights change that result."),
      p("synoptic", "core:motion6:uncertainty-range", "core:motion6:uncertainty-range:experiment", "combine component equations with uncertainty and model limitations", "A projectile range is measured as 18.0 ± 0.3 m while the ideal model predicts 17.2 m. Explain whether this is evidence of failure and name one model limitation to investigate.", 3, ["Difference is 0.8 m, larger than the stated measurement uncertainty alone", "Check systematic uncertainty and launch-speed/angle uncertainties before rejecting the model", "Air resistance, launch-height/landing-height mismatch or wind could cause a physical deviation"], "The 0.8 m gap exceeds the quoted random uncertainty, but it is not by itself proof that the equations fail. Audit the launch measurements and systematic offsets, then test limitations such as drag, wind and unequal heights."),
    ],
  },
  {
    topic: "kinematics-dynamics", point: 8,
    parts: [
      p("recall", "core:motion8:impulse-definition", "core:motion8:impulse-definition:collision", "state impulse as area and momentum change", "Define impulse and state two equivalent equations for it.", 3, ["Impulse is force multiplied by the time for which it acts", "Impulse J = FΔt for constant force, or the area under a force-time graph", "Impulse equals change in momentum Δp"], "Impulse is the change in momentum. For a constant force J = FΔt; for a varying force it is the area under the force-time graph."),
      p("recall", "core:motion8:isolated-conservation", "core:motion8:isolated-conservation:collision", "state the condition for momentum conservation in a collision", "State the condition under which the total momentum of a collision system is conserved.", 2, ["The system must be isolated, with no resultant external impulse", "Total momentum before the interaction equals total momentum after it"], "Total momentum is conserved when the chosen system has no resultant external impulse. Internal forces may change individual momenta, but their vector sum remains constant."),
      p("explanation", "core:motion8:area-sign", "core:motion8:area-sign:rebound", "explain why a signed force-time area gives the correct rebound impulse", "A ball rebounds from a wall. Explain why the force-time area must be signed rather than treated as a positive size only.", 3, ["Momentum is a vector and the velocity reverses direction", "The force-time area has the sign of the momentum change", "Using magnitudes alone can halve or reverse the inferred impulse"], "The rebound changes the ball's signed velocity, so Δp includes the reversal. A signed area gives the direction of the impulse; an unsigned area loses the information that the wall pushed opposite to the incoming motion."),
      p("explanation", "core:motion8:force-time-shape", "core:motion8:force-time-shape:crumple", "explain how spreading the same impulse changes peak force", "Two car restraints deliver the same impulse but one has a longer force-time pulse. Explain why the longer pulse lowers peak force.", 3, ["The area under both curves is the same Δp", "For a longer duration the same area can be spread over a lower height", "Average force = Δp/Δt is smaller for the longer pulse; the peak can also be reduced"], "The area, and hence momentum change, is fixed. Increasing the time spreads that area, so the average force Δp/Δt falls and a suitably shaped pulse has a lower peak force."),
      p("application", "core:motion8:triangular-impulse", "core:motion8:triangular-impulse:hammer", "calculate impulse from a non-rectangular force-time graph", "A hammer strike has a triangular force-time pulse with peak 900 N and base 4.0 ms. Calculate the impulse.", 2, ["Impulse is triangle area = ½ × 900 × 4.0×10⁻³", "J = 1.8 N s"], "The triangular area is 0.5×900×0.004 = 1.8 N s."),
      p("application", "core:motion8:momentum-area", "core:motion8:momentum-area:rocket", "read a momentum-time graph to find force over a selected interval", "A rocket's momentum rises linearly from 2.0×10⁵ to 5.0×10⁵ kg m s⁻¹ in 6.0 s. Calculate the resultant force and state its direction.", 2, ["F = Δp/Δt = (5.0−2.0)×10⁵/6.0", "F = 5.0×10⁴ N in the positive momentum direction"], "The gradient is 3.0×10⁵/6.0 = 5.0×10⁴ N, directed along the increasing momentum."),
      p("misconception", "core:motion8:force-time-height-fallacy", "core:motion8:force-time-height-fallacy:tennis", "reject peak force alone as a measure of impulse", "A student says the taller force-time graph always gives the larger impulse. Explain the missing role of duration and area.", 3, ["Impulse is the entire area under the graph, not just its peak height", "A lower, wider pulse can have greater area than a narrow high pulse", "The area equals the momentum change"], "Peak force is only one coordinate. A wide pulse can enclose more area and therefore give a larger impulse than a taller but very short pulse."),
      p("misconception", "core:motion8:zero-force-rest", "core:motion8:zero-force-rest:orbit", "correct zero gradient as zero resultant force rather than zero momentum", "A horizontal section of a momentum-time graph is labelled 'zero momentum'. Correct the label.", 2, ["A horizontal section has zero gradient, so resultant force is zero", "The momentum itself is the non-zero height of the graph and remains constant"], "A flat momentum-time graph means momentum is constant, not zero. Its zero gradient means the resultant force is zero."),
      p("calculation", "core:motion8:rebound-impulse", "core:motion8:rebound-impulse:cricket", "calculate signed impulse and average force for a reversal", "A 0.16 kg cricket ball approaches at +18 m s⁻¹ and leaves at −12 m s⁻¹ after contact lasting 0.020 s. Find the impulse and average force.", 4, ["Δp = m(v−u) = 0.16(−12−18) = −4.8 kg m s⁻¹", "Impulse = −4.8 N s", "F_avg = Δp/Δt = −4.8/0.020", "F_avg = −240 N"], "The signed momentum change is 0.16(−30) = −4.8 kg m s⁻¹, so the impulse is −4.8 N s and the average force is −240 N, opposite the incoming direction."),
      p("calculation", "core:motion8:piecewise-force", "core:motion8:piecewise-force:braking", "sum signed areas from a piecewise force pulse", "A braking force is 0 to −4000 N for 0.10 s, then −4000 N for 0.20 s, then returns linearly to zero in 0.10 s. Calculate the impulse.", 4, ["First triangle area = −½×4000×0.10 = −200 N s", "Rectangle area = −4000×0.20 = −800 N s", "Final triangle area = −200 N s", "Total impulse = −1200 N s"], "Add the signed areas: -200 - 800 - 200 = -1200 N s. The middle rectangle contributes -800 N s."),
      p("transfer", "core:motion8:impact-absorber", "core:motion8:impact-absorber:helmet", "transfer impulse reasoning to a protective material choice", "A helmet liner increases impact time without changing the rider's momentum change. Explain how its material and thickness affect the force evidence on a force-time graph.", 3, ["The impulse area must remain the same Δp", "Increasing contact time lowers the average force and spreads the graph", "A deformable liner can absorb energy while keeping peak force below an injury threshold"], "The area is fixed by Δp, but a crushable liner lengthens the pulse and lowers its height. Its deformation also absorbs kinetic energy, so the rider sees a smaller peak force."),
      p("transfer", "core:motion8:force-platform", "core:motion8:force-platform:jump", "interpret a force-time trace to separate weight impulse from net impulse", "A force plate records an athlete's upward ground force during a jump. Explain why the area between the trace and the athlete's weight gives the change in vertical momentum.", 3, ["Resultant force is ground force minus weight", "The area of resultant force-time is Δp", "A ground-force area alone includes the impulse needed to support body weight, not just to accelerate it"], "Newton's second law applies to the resultant, so subtract mg from the ground-force trace before taking its area. The resulting area is the athlete's vertical momentum change."),
      p("synoptic", "core:motion8:variable-mass", "core:motion8:variable-mass:rocket-stage", "combine momentum-time gradients with changing mass and a stated system boundary", "A rocket ejects gas while its total momentum increases. Explain why F = Δp/Δt must be applied to the chosen system and how a staged mass drop changes the interpretation.", 4, ["Newton's law uses the momentum change of a defined system", "For a rocket plus expelled gas, external force controls total-system momentum", "For the rocket alone, expelled gas crosses the boundary and carries momentum away", "A sudden stage separation changes mass and therefore p = mv even if velocity is continuous; account for the impulse at the separation"], "The momentum equation is only meaningful after choosing the system. Rocket-plus-exhaust has its momentum changed by external forces; rocket-alone loses momentum through the exhaust flux. A stage drop changes mass, so p can jump or change slope and the separation impulse must be included."),
      p("synoptic", "core:motion8:energy-impulse", "core:motion8:energy-impulse:crash-data", "combine impulse area with work-energy to evaluate a crash pulse", "Two crash pulses have the same impulse but different peak force and stopping distance. Explain why impulse alone cannot predict the vehicle's deformation energy.", 4, ["Same impulse means same momentum change", "Work done depends on force over displacement, not only force over time", "The pulse shape, stopping distance and velocity history determine kinetic-energy loss and deformation work", "Therefore a lower peak force is safer evidence, but energy absorption must also be checked"], "Equal force-time areas give the same Δp, but energy transfer is the force-displacement area. Different stopping distances and force histories can absorb different amounts of deformation energy, so impulse alone is not an energy measure."),
    ],
  },
  {
    topic: "energy-power", point: 3,
    parts: [
      p("recall", "core:energy3:power-definition", "core:energy3:power-definition:winch", "state power as a rate and give its SI unit", "Define power and state its SI unit in terms of energy and time.", 2, ["Power is the rate of transfer of energy (or work done per unit time)", "Unit watt, W = J s⁻¹"], "Power is the rate at which energy is transferred: P = ΔE/Δt, measured in watts, where 1 W = 1 J s⁻¹."),
      p("recall", "core:energy3:force-speed", "core:energy3:force-speed:traction", "state the mechanical power relation for a parallel force", "State the relation between mechanical power, force and speed when force is parallel to motion.", 2, ["P = Fv", "It follows from work Fs divided by time, with v = s/t"], "For a force along the motion, P = Fv: work Fs divided by time becomes F(s/t) = Fv."),
      p("explanation", "core:energy3:constant-speed-power", "core:energy3:constant-speed-power:escalator", "explain how constant speed can require continuous power", "An escalator carries passengers upward at constant speed. Explain why the motor still supplies power even though the passengers have zero acceleration.", 3, ["Constant speed means resultant force is zero, not that individual forces are zero", "The motor's upward force transfers gravitational potential energy at a rate", "Power is force times velocity; energy is continually supplied despite no acceleration"], "The motor balances the passengers' weight while moving them upward, so resultant force and acceleration are zero. Its force still acts through a distance and transfers gravitational energy, requiring P = Fv continuously."),
      p("explanation", "core:energy3:efficiency-meaning", "core:energy3:efficiency-meaning:motor", "explain efficiency as a useful fraction and identify where non-useful power goes", "A motor is rated at 80% efficiency. Explain what the remaining 20% means for a 2.0 kW electrical input.", 3, ["Useful output power = 0.80×2.0 = 1.6 kW", "0.40 kW is transferred to non-useful stores", "Losses include heating, sound and mechanical friction"], "The useful mechanical output is 1.6 kW. The remaining 0.40 kW is not destroyed; it becomes internal energy, sound and other non-useful transfers."),
      p("application", "core:energy3:lift-power", "core:energy3:lift-power:warehouse", "calculate useful power from a steady lift", "A 250 kg load is raised vertically at 0.40 m s⁻¹. Calculate the useful power delivered to the load. Take g = 9.81 m s⁻².", 2, ["Force required at constant speed = mg = 250×9.81 = 2453 N", "P = Fv = 2453×0.40 = 981 W"], "At constant speed the useful lifting force is mg = 2453 N. Thus P = Fv = 2453×0.40 ≈ 981 W."),
      p("application", "core:energy3:efficiency-chain", "core:energy3:efficiency-chain:pump", "chain input power, efficiency and useful flow output", "A pump takes 5.0 kW and is 65% efficient. It raises water through 12 m. Calculate the mass flow rate. Take g = 9.81 m s⁻².", 4, ["Useful output power = 0.65×5000 = 3250 W", "P = ṁgh", "ṁ = 3250/(9.81×12)", "ṁ ≈ 27.6 kg s⁻¹"], "Only 3250 W reaches the water. From P = ṁgh, the flow rate is 3250/(9.81×12) ≈ 27.6 kg s⁻¹."),
      p("misconception", "core:energy3:power-energy-fallacy", "core:energy3:power-energy-fallacy:battery", "reject confusing a high power rating with a large stored energy", "A student says a 100 kW battery stores more energy than a 1 kW battery because its power rating is larger. Correct the claim.", 3, ["Power is the rate of transfer; energy is power multiplied by time", "A 100 kW device could deliver more quickly but have less total stored energy", "Capacity or run time is needed to compare stored energy"], "A power rating says how fast energy can be delivered, not how much is stored. Stored energy depends on power and duration (or a stated battery capacity), so a 1 kW battery can hold more total energy."),
      p("misconception", "core:energy3:efficiency-over-one", "core:energy3:efficiency-over-one:generator", "identify an impossible efficiency and trace unit errors", "A calculation gives a generator efficiency of 145%. Give two physical reasons this result should be rejected before reporting it.", 3, ["For a passive device useful output cannot exceed total input, so η ≤ 1 (100%)", "Check that input and output powers use the same units and time basis", "Check that useful and total quantities have not been interchanged or a stored-energy value treated as power"], "An efficiency above 100% contradicts conservation for a passive generator. Recheck units, the time interval and whether both quantities are powers; an energy divided by a power or a kW/W slip can create the false result."),
      p("calculation", "core:energy3:force-speed-calc", "core:energy3:force-speed-calc:car", "calculate tractive power and energy over a constant-speed interval", "A car's driving force is 2.4 kN at 18 m s⁻¹ for 40 s. Calculate the engine power at the wheels and the work done.", 4, ["P = Fv = 2400×18 = 4.32×10⁴ W", "P = 43.2 kW", "Work = Pt = 4.32×10⁴×40", "Work = 1.73×10⁶ J"], "The wheel power is 2400×18 = 43.2 kW. Over 40 s the work is Pt = 1.728×10⁶ J."),
      p("calculation", "core:energy3:electrical-efficiency", "core:energy3:electrical-efficiency:solar", "calculate efficiency from measured input and output rates", "A solar panel receives 800 W m⁻² over 2.0 m² and supplies 260 W electrically. Calculate its efficiency.", 3, ["Incident power = 800×2.0 = 1600 W", "η = output/input = 260/1600", "η = 0.163, or 16%"], "The incident power is 1600 W. Efficiency is 260/1600 = 0.1625, about 16%."),
      p("transfer", "core:energy3:rowing-power", "core:energy3:rowing-power:boat", "transfer power balance to a resistive steady-speed system", "A rower moves a boat at constant speed against water resistance. Explain how measuring the speed and resistance estimates useful power, and what an increasing resistance would do.", 3, ["At steady speed the thrust equals resistive force", "Useful power to the boat is P = F_resist v", "If resistance rises at the same speed, required power rises; if power is fixed, speed falls"], "At constant speed the rower's thrust balances drag, so the useful power is drag times speed. A larger drag demands more power; with a fixed power budget the boat must slow until Fv matches it."),
      p("transfer", "core:energy3:regenerative-brake", "core:energy3:regenerative-brake:tram", "transfer efficiency and power direction to regenerative braking", "During regenerative braking a tram's motors act as generators. Explain the power flow and why the electrical output is less than the lost kinetic-energy rate.", 3, ["The wheels drive the motor coils, inducing an emf and electrical power", "The electromagnetic torque opposes motion, removing kinetic energy", "Generator efficiency is below 100%, so some energy becomes heat and sound"], "The moving tram drives the coils, so mechanical kinetic energy flows into electrical storage. Lenz's law supplies a retarding torque; losses in the coils, electronics and bearings mean less electrical power emerges than the kinetic-energy loss rate."),
      p("synoptic", "core:energy3:power-time-profile", "core:energy3:power-time-profile:data", "combine power integration with efficiency and uncertainty", "A device draws 2.0 kW for 5 min at 75% efficiency, then 0.50 kW for 20 min at 90% efficiency. Calculate total useful energy output and explain which interval dominates.", 4, ["Input energies: 2.0×300 = 600 kJ; 0.50×1200 = 600 kJ", "Useful energies: 0.75×600 = 450 kJ; 0.90×600 = 540 kJ", "Total useful energy = 990 kJ", "The lower-power interval dominates useful output because it runs four times longer and has higher efficiency"], "Each interval receives 600 kJ. Useful outputs are 450 and 540 kJ, giving 990 kJ total; the long, efficient second interval contributes more despite its lower instantaneous power."),
      p("synoptic", "core:energy3:dimension-check", "core:energy3:dimension-check:engineering", "use dimensional analysis to audit a power equation", "A proposed relation for lifting power is P = mg/v. Use units and a limiting-case argument to decide whether it can be correct, then state the correct relation.", 3, ["mg/v has units N/(m s⁻¹) = N s m⁻¹, not W", "Power should increase with speed for the same lifting force", "Correct relation is P = mgv"], "mg has units of force; dividing by speed does not produce joules per second, and it predicts less power for a faster lift. The correct lifting power is P = mgv."),
    ],
  },
  {
    topic: "energy-power", point: 4,
    parts: [
      p("recall", "core:energy4:force-distance-area", "core:energy4:force-distance-area:graph", "state the graph-area definition of work", "State how work done is obtained from a force-displacement graph when the force varies.", 2, ["Work is the area under the force-displacement graph", "Signed area is used: force opposing displacement contributes negative work"], "Work is the signed area under the force-displacement graph. Regions below the displacement direction represent negative work."),
      p("recall", "core:energy4:work-energy-theorem", "core:energy4:work-energy-theorem:skater", "state the work-energy theorem for a resultant force", "State the work-energy theorem and identify the energy quantity that changes.", 2, ["The net work done on an object equals its change in kinetic energy", "The change is Δ(½mv²), using the resultant work including its sign"], "The net work on an object equals its change in kinetic energy, Δ(½mv²). Positive net work increases speed; negative net work reduces it."),
      p("explanation", "core:energy4:negative-area", "core:energy4:negative-area:brakes", "explain a negative force-displacement area as an energy transfer", "Explain why the area below the displacement axis for a braking force represents a loss of kinetic energy rather than negative total energy.", 3, ["The braking force opposes displacement, so its work is negative", "Negative work reduces the object's mechanical energy", "The energy is transferred to internal energy, sound and deformation; total energy remains conserved"], "The signed area is negative because the force removes mechanical energy. That energy is transferred into heating, sound and deformation; it is not destroyed or a negative amount of total energy."),
      p("explanation", "core:energy4:hysteresis-loop", "core:energy4:hysteresis-loop:rubber", "interpret the area between loading and unloading curves", "A rubber band has different loading and unloading force-extension curves. Explain what the enclosed area means and why the band warms.", 3, ["The loading area is work supplied; the unloading area is work recovered", "Their difference, the loop area, is energy dissipated per cycle", "Internal friction transfers that energy to thermal energy, warming the band"], "The gap between loading and unloading areas is work that cannot be recovered elastically. Internal molecular friction converts it to heat, so repeated cycles warm the rubber."),
      p("application", "core:energy4:trapezium-area", "core:energy4:trapezium-area:force-sensor", "calculate work from a linearly changing force", "A force rises uniformly from 20 N to 80 N while a trolley moves 3.0 m. Calculate the work done by the force.", 2, ["Area is trapezium = ½(F₁+F₂)s", "W = ½(20+80)×3.0 = 150 J"], "The area is 0.5(20+80)×3.0 = 150 J."),
      p("application", "core:energy4:piecewise-work", "core:energy4:piecewise-work:actuator", "sum rectangular and triangular regions with signs", "A robot actuator experiences +60 N for 0.50 m, then −20 N for 0.30 m. Calculate the net work.", 3, ["Positive work = 60×0.50 = 30 J", "Negative work = −20×0.30 = −6.0 J", "Net work = 24 J"], "The actuator adds 30 J and removes -6.0 J, giving 24 J net work."),
      p("misconception", "core:energy4:force-not-work", "core:energy4:force-not-work:wall", "reject force-times-time as work without displacement", "A student multiplies a 400 N force by 10 s and calls the result work. Explain the missing quantity and give the correct unit of work.", 2, ["Work requires force multiplied by displacement in the force direction", "Force multiplied by time is related to impulse, not work; work is measured in joules"], "400 N×10 s is an impulse-like product with units N s. Work needs a displacement, W = Fs, and is measured in joules."),
      p("misconception", "core:energy4:area-absolute", "core:energy4:area-absolute:drag", "reject taking absolute graph area when direction matters", "A force-displacement graph has +40 J of motor area and −25 J of drag area. A student reports 65 J of work. Correct the calculation.", 2, ["Signed areas must be added, not absolute values", "Net work = +40 − 25 = +15 J; the motor has increased kinetic energy by 15 J"], "The signed total is 40−25 = +15 J. Taking 65 J would erase the fact that drag removes energy."),
      p("calculation", "core:energy4:force-graph-energy", "core:energy4:force-graph-energy:climber", "calculate work and final speed from a force-displacement graph", "A 2.0 kg climber is pulled from rest by a force that rises linearly from 0 to 120 N over 4.0 m. Neglect resistance. Calculate the work and final speed.", 4, ["Work = triangle area = ½×120×4.0 = 240 J", "Work equals kinetic-energy gain", "½mv² = 240", "v = √(480/2.0) = 15.5 m s⁻¹"], "The force graph encloses 240 J. Equating this to ½mv² gives v = √(2×240/2.0) ≈ 15.5 m s⁻¹."),
      p("calculation", "core:energy4:loop-loss", "core:energy4:loop-loss:material-test", "calculate dissipated energy and efficiency from loading and unloading areas", "A material receives 12 J during loading and returns 9.0 J during unloading. Calculate the dissipated energy and the mechanical recovery efficiency.", 3, ["Dissipated energy = 12 − 9.0 = 3.0 J", "Efficiency = recovered/input = 9.0/12", "Efficiency = 75%"], "The loop loss is 3.0 J and the recovered fraction is 9/12 = 0.75, or 75%."),
      p("transfer", "core:energy4:force-distance-slope", "core:energy4:force-distance-slope:incline", "transfer graph-area reasoning to a variable slope force", "A sled is pulled up an incline where the pulling force increases with distance because the rope angle changes. Explain how a force-displacement graph lets you find work without assuming a constant force.", 3, ["At each position use the component of force along the displacement", "Plot that component against distance", "Integrate/sum the signed strip areas; the changing force is naturally included"], "Resolve the pull along the slope at each position, plot that component against distance and take its area. No single average force assumption is needed; the graph performs the sum of FΔs."),
      p("transfer", "core:energy4:compression", "core:energy4:compression:shock-absorber", "transfer area reasoning to compression work and stored energy", "A shock absorber's compression force rises with displacement and its rebound curve is lower. Explain how the graph separates energy stored from energy dissipated.", 3, ["Compression area is work input", "The rebound area is energy returned", "The difference between areas is dissipated as heat in the damper"], "The compression area records energy put into the absorber. The smaller rebound area is what returns to the vehicle; the gap is heat dissipated by the damper."),
      p("synoptic", "core:energy4:work-energy-uncertainty", "core:energy4:work-energy-uncertainty:braking-test", "combine signed graph area, kinetic energy and uncertainty", "A brake-test force-distance trace encloses 18.0 ± 0.6 kJ of negative work. The car's initial kinetic energy is 20.0 ± 0.5 kJ. Estimate the residual energy and its approximate absolute uncertainty, and state what the residual represents.", 4, ["Residual = 20.0 − 18.0 = 2.0 kJ", "For a difference, approximate absolute uncertainties add: 0.5 + 0.6 = 1.1 kJ", "Residual ≈ 2.0 ± 1.1 kJ", "It may be rolling kinetic energy, deformation, heat or unmeasured work"], "The trace removes 18.0 kJ from a 20.0 kJ kinetic store, leaving about 2.0 kJ. Adding absolute uncertainties gives roughly ±1.1 kJ; the remainder must be accounted for by remaining motion and other transfers."),
      p("synoptic", "core:energy4:force-model-check", "core:energy4:force-model-check:launcher", "audit a force-law model by comparing its predicted work area with measurements", "A launcher model predicts a triangular force-extension area of 40 J, but the measured loading curve encloses 34 J and the unloading curve 28 J. Give two physically different explanations for the discrepancy and one test for each.", 4, ["The model may overestimate stiffness/force; repeat with calibrated force and displacement sensors", "Energy may be dissipated through hysteresis or friction; compare loading and unloading curves and measure temperature", "A geometry or zero-offset error can alter area; check calibration and repeat from a different initial position", "The tests should distinguish measurement bias from a real non-conservative transfer"], "The model could be wrong about the force law or the sensors could be biased; the loading curve could also reveal real hysteresis. Calibrated repeats test measurement, while comparing loading/unloading and heat tests the physical dissipation mechanism."),
    ],
  },
];

export const physicsDepthNearCompleteCoreQuestions = depthQuestions(ITEMS);
