import { depthQuestions, type PhysicsDepthItem, type PhysicsDepthPart } from "./physics-depth-50-common";

const p = (
  demand: PhysicsDepthPart["demand"], family: string, context: string, move: string,
  prompt: string, marks: number, scheme: string[], answer: string,
): PhysicsDepthPart => ({ demand, family, context, move, prompt, marks, scheme, answer });

/**
 * Materials depth pack.  Each part uses a separate physical decision or
 * solution path; the exact content remains unverified until a subject expert
 * signs its fingerprint.
 */
const ITEMS: PhysicsDepthItem[] = [
  {
    topic: "materials", point: 2,
    parts: [
      p("recall", "deep:mat2:definitions", "deep:mat2:definitions:wire", "state stress, strain and Young modulus with symbols", "Define tensile stress, tensile strain and Young modulus, including their equations.", 3, ["Stress = force / cross-sectional area", "Strain = extension / original length", "Young modulus = stress / strain"], "Stress is F/A, strain is ΔL/L and the Young modulus is the ratio stress/strain in the elastic region."),
      p("recall", "deep:mat2:units", "deep:mat2:units:testing", "identify the units and dimension of elastic constants", "State the SI units of stress, strain and Young modulus, and explain why strain has no unit.", 3, ["Stress and Young modulus are measured in pascals (N m⁻²)", "Strain is dimensionless", "Strain is a ratio of two lengths"], "Stress and Young modulus have units Pa (N m⁻²). Strain is dimensionless because it is an extension divided by a length."),
      p("explanation", "deep:mat2:area-effect", "deep:mat2:area-effect:two-wires", "explain why equal force can produce different stress", "Two wires carry the same tensile force but have different diameters. Explain why their stresses differ.", 3, ["Stress is force divided by cross-sectional area", "A larger diameter gives a larger area", "For the same force the thicker wire therefore has lower stress"], "The force is shared over the cross-sectional area. Since area grows with diameter squared, the thicker wire experiences lower stress for the same force."),
      p("explanation", "deep:mat2:modulus-slope", "deep:mat2:modulus-slope:graph", "explain why Young modulus is a stress-strain gradient", "Explain why the initial gradient of a stress-strain graph gives Young modulus, whereas the gradient of a force-extension graph does not by itself.", 3, ["Young modulus is defined as stress/strain", "The initial straight-line gradient is Δstress/Δstrain", "Force-extension also depends on specimen area and original length, so it is not a material modulus alone"], "Young modulus uses stress and strain, so the initial stress-strain gradient is E. A force-extension gradient changes with the specimen's geometry as well as its material."),
      p("application", "deep:mat2:direct-calculation", "deep:mat2:direct-calculation:tie-rod", "calculate stress, strain and modulus from a loaded specimen", "A 4.0 mm diameter steel tie rod carries 2.0 kN and extends by 1.20 mm from a 1.60 m length. Calculate its stress, strain and Young modulus.", 4, ["Area = π(2.0×10⁻³)² = 1.26×10⁻⁵ m²", "Stress = 2000/area = 1.59×10⁸ Pa", "Strain = 0.00120/1.60 = 7.50×10⁻⁴", "E = stress/strain = 2.12×10¹¹ Pa"], "The area is 1.26×10⁻⁵ m². Stress is 1.59×10⁸ Pa, strain is 7.50×10⁻⁴ and E is about 2.12×10¹¹ Pa, consistent with steel."),
      p("application", "deep:mat2:geometry-change", "deep:mat2:geometry-change:film", "predict extension from modulus and specimen geometry", "A polymer strip has E = 2.0×10⁹ Pa, length 0.50 m and area 4.0×10⁻⁶ m². Find its extension under a 120 N tensile load.", 3, ["Stress = F/A = 3.0×10⁷ Pa", "Strain = stress/E = 1.5×10⁻²", "Extension = strain×length = 7.5×10⁻³ m"], "Stress is 3.0×10⁷ Pa, so strain is 0.015. Multiplying by 0.50 m gives an extension of 7.5 mm."),
      p("misconception", "deep:mat2:diameter-area", "deep:mat2:diameter-area:bolt", "correct using diameter instead of radius in area", "A student calculates a wire area as πd² and obtains a stress four times too small. Explain the error.", 3, ["The circular area is πr² = π(d/2)²", "Using πd² makes the area four times too large", "Stress F/A is then four times too small"], "The radius is half the diameter, so A = π(d/2)² = πd²/4. The student's area is four times too large and their stress is four times too small."),
      p("misconception", "deep:mat2:extension-force", "deep:mat2:extension-force:cord", "separate extension from strain and force", "A student says a longer wire must have a larger strain because it extends more under the same force. Correct the claim.", 3, ["Strain is extension divided by original length", "For the same material, area and stress, extension is proportional to original length", "A longer wire can extend more while having the same strain"], "Extension is an absolute change; strain normalises it by the original length. Two geometrically similar wires can have different extensions but the same strain."),
      p("calculation", "deep:mat2:two-specimens", "deep:mat2:two-specimens:lab", "compare moduli while carrying uncertainty through ratios", "Two specimens have stresses 120 and 150 MPa and strains 6.0×10⁻⁴ and 1.0×10⁻³. Calculate both Young moduli and identify which material is stiffer.", 3, ["E₁ = 120×10⁶/(6.0×10⁻⁴) = 2.0×10¹¹ Pa", "E₂ = 150×10⁶/(1.0×10⁻³) = 1.5×10¹¹ Pa", "The larger modulus E₁ means specimen 1 is stiffer"], "The moduli are 2.0×10¹¹ Pa and 1.5×10¹¹ Pa. Specimen 1 is stiffer because it needs more stress for each unit strain."),
      p("calculation", "deep:mat2:extension-data", "deep:mat2:extension-data:load-test", "extract a modulus from a linear force-extension data pair", "A wire of length 1.20 m and area 2.5×10⁻⁷ m² extends 0.60 mm when the force is 75 N. Calculate its Young modulus.", 3, ["Stress = 75/(2.5×10⁻⁷) = 3.0×10⁸ Pa", "Strain = 0.00060/1.20 = 5.0×10⁻⁴", "E = 6.0×10¹¹ Pa"], "Stress is 3.0×10⁸ Pa and strain is 5.0×10⁻⁴, giving E = 6.0×10¹¹ Pa."),
      p("transfer", "deep:mat2:bridge-selection", "deep:mat2:bridge-selection:cable", "transfer modulus and stress limits to a structural choice", "A bridge cable must carry a fixed load with limited extension. Explain why both Young modulus and cross-sectional area matter when selecting its material and size.", 3, ["Stress is F/A, so area controls the stress limit for the fixed load", "Strain = stress/E, so a larger E reduces extension at a given stress", "Check both allowable stress and extension, not just one property"], "Area reduces the working stress and E reduces the strain produced by that stress. The design must satisfy strength and extension limits together."),
      p("transfer", "deep:mat2:biological-tissue", "deep:mat2:biological-tissue:tendon", "transfer the stress-strain model to a non-metallic material", "A tendon is tested in tension and its stress-strain curve is initially curved. Explain how you would obtain a useful stiffness measure and why a single Young modulus may be misleading.", 3, ["Use a local gradient Δstress/Δstrain at the strain of interest", "The gradient changes as the curve is non-linear", "A single initial modulus would not describe behaviour at larger strains"], "Take a tangent gradient at the operating strain. Because the curve is non-linear, stiffness is strain-dependent and one initial value cannot represent the whole tendon response."),
      p("synoptic", "deep:mat2:graph-uncertainty", "deep:mat2:graph-uncertainty:wire", "combine graph gradient, dimensions and uncertainty in a modulus estimate", "A stress-strain graph has an initial gradient of (2.0±0.1)×10¹¹ Pa. The area was measured with 4% uncertainty. State the dominant effect on the Young-modulus uncertainty and one improvement.", 3, ["The gradient directly gives E, so its 5% uncertainty contributes", "Area uncertainty affects the stress values and therefore the gradient", "Repeat diameter measurements or use a micrometer to reduce area uncertainty"], "The 5% gradient uncertainty is already present, while area error can bias every stress value. Repeated micrometer measurements of diameter improve the modulus estimate."),
      p("synoptic", "deep:mat2:failure-model", "deep:mat2:failure-model:pressure-vessel", "combine modulus, stress concentration and model assumptions", "A thin pressure vessel passes the average-stress calculation but fails near a nozzle. Give two reasons the simple Young-modulus model did not predict the failure and a test for each.", 4, ["The local stress is concentrated around the nozzle rather than equal to the average; use strain gauges or finite-element mapping", "The material may leave the linear elastic range or contain a flaw; repeat a stress-strain test and inspect the surface", "The wall may experience multiaxial stress rather than the one-dimensional model", "Each test must distinguish geometry from material failure"], "The average formula ignores local concentration and assumes uniaxial linear elasticity. Map strain around the nozzle and test material samples beyond the working range to separate geometry from constitutive failure."),
    ],
  },
  {
    topic: "materials", point: 3,
    parts: [
      p("recall", "deep:mat3:hooke-law", "deep:mat3:hooke-law:spring", "state Hooke law and the spring constant", "State Hooke's law for an elastic spring and define the spring constant.", 2, ["For the proportional region F = kx", "k is force per unit extension, with unit N m⁻¹"], "Within the proportional region force is proportional to extension: F = kx. The spring constant k is F/x in N m⁻¹."),
      p("recall", "deep:mat3:limit", "deep:mat3:limit:load-frame", "identify the limit of proportionality on a force-extension graph", "What is meant by the limit of proportionality for a spring?", 2, ["It is the point beyond which force is no longer proportional to extension", "The graph stops being a straight line through the origin"], "It is the point where the force-extension graph first ceases to be a straight line through the origin; beyond it, k is not constant."),
      p("explanation", "deep:mat3:straight-line", "deep:mat3:straight-line:calibration", "explain the physical meaning of a straight force-extension region", "Explain why a straight force-extension graph through the origin indicates a constant spring constant.", 3, ["The gradient is ΔF/Δx", "A straight line has constant gradient", "Therefore the ratio F/x and k stay constant while the spring is proportional"], "The gradient is F/x. A straight line through the origin has one gradient, so the force per metre of extension remains constant."),
      p("explanation", "deep:mat3:series-parallel", "deep:mat3:series-parallel:suspension", "explain equivalent stiffness for springs in series and parallel", "Explain why two identical springs in series are less stiff while two in parallel are more stiff.", 3, ["In series the same force acts but extensions add", "In parallel the load is shared while the extension is common", "Hence k_series = k/2 and k_parallel = 2k for identical springs"], "Series springs add their extensions under one force, halving the effective stiffness. Parallel springs share the load at one extension, doubling the force per extension."),
      p("application", "deep:mat3:single-extension", "deep:mat3:single-extension:actuator", "calculate extension from a spring constant and force", "A spring has k = 240 N m⁻¹ and carries a 18 N load. Calculate its extension while it remains proportional.", 2, ["Use x = F/k", "x = 18/240 = 0.075 m"], "The extension is x = 18/240 = 0.075 m, or 75 mm."),
      p("application", "deep:mat3:network", "deep:mat3:network:valve", "calculate the stiffness of a mixed spring network", "Two 300 N m⁻¹ springs are in parallel, in series with a 150 N m⁻¹ spring. Find the effective spring constant.", 3, ["Parallel pair k = 300 + 300 = 600 N m⁻¹", "For series, 1/k_eff = 1/600 + 1/150", "k_eff = 120 N m⁻¹"], "The parallel pair is 600 N m⁻¹. The series reciprocal sum is 1/600+1/150, giving k_eff = 120 N m⁻¹."),
      p("misconception", "deep:mat3:force-extension-equal", "deep:mat3:force-extension-equal:two-springs", "reject equal extension as equal stiffness", "Two springs stretch by the same amount under different forces. A student says they have the same spring constant. Explain why this is not justified.", 3, ["k = F/x, so equal x does not imply equal F/x", "The applied forces may differ", "Need a force-extension gradient or paired force and extension data for each spring"], "Equal extensions say nothing about stiffness unless the forces are also equal. Compare F/x in the proportional region or use the graph gradients."),
      p("misconception", "deep:mat3:limit-elastic", "deep:mat3:limit-elastic:clip", "separate proportional and elastic limits", "A student claims that crossing the limit of proportionality means the spring has permanently deformed. Correct the claim.", 3, ["Beyond proportionality the graph may curve while the spring is still elastic", "Permanent deformation begins only beyond the elastic limit", "The proportional limit occurs first or at the same point"], "A curved force-extension response can still return to its original length. Permanent set is associated with exceeding the elastic limit, which is later than the proportional limit."),
      p("calculation", "deep:mat3:work-spring", "deep:mat3:work-spring:launcher", "calculate spring work from k and extension", "A 500 N m⁻¹ spring is compressed by 0.080 m. Calculate the work done and the force at maximum compression.", 3, ["Work = ½kx² = ½×500×0.080²", "Work = 1.60 J", "F = kx = 40 N"], "The stored work is 1.60 J and the maximum force is 40 N."),
      p("calculation", "deep:mat3:gradient", "deep:mat3:gradient:force-sensor", "extract k from two non-zero force-extension readings", "A spring has forces 4.0 N at 12 mm and 10.0 N at 30 mm. Assuming a straight proportional segment through the origin, calculate k and comment on the data.", 3, ["k = F/x = 4.0/0.012 = 333 N m⁻¹", "The second pair gives 10.0/0.030 = 333 N m⁻¹", "Matching ratios support proportional behaviour through the origin"], "Both points give k ≈ 333 N m⁻¹, so the ratios are consistent with a straight proportional segment."),
      p("transfer", "deep:mat3:temperature", "deep:mat3:temperature:rubber", "transfer Hooke reasoning to a temperature-dependent spring", "A rubber spring is less stiff when warm. Explain how you would test the change in k without confusing temperature effects with hysteresis.", 3, ["Control the extension range and apply the same loading rate", "Measure loading and unloading separately because the paths may differ", "Compare local gradients at the same temperature and extension"], "Use identical extension points and rates, record both loading and unloading curves and compare their local gradients after thermal equilibration."),
      p("transfer", "deep:mat3:energy-network", "deep:mat3:energy-network:seatbelt", "transfer equivalent stiffness to a compliant safety design", "A seat-belt retractor uses a spring network to limit force. Explain why a lower effective k can reduce peak force but increase required travel.", 3, ["For a given stored energy x must be larger when k is smaller", "The force F = kx rises more slowly", "The design must provide enough travel before the safe extension limit"], "Reducing k spreads the same energy over more extension and keeps F lower, but the belt needs sufficient travel and must stay within its elastic range."),
      p("synoptic", "deep:mat3:series-energy", "deep:mat3:series-energy:mass-spring", "combine network stiffness, period and energy", "A mass is attached to two identical springs in parallel. Explain how replacing the pair by one spring of equivalent k changes the period and stored energy calculation.", 4, ["Parallel springs give k_eff = 2k", "The small-oscillation period is T = 2π√(m/k_eff), so it is reduced by √2", "At a given extension total stored energy is ½k_eff x²", "The force is shared by the springs but energies add"], "The pair acts as 2k, so T is 2π√(m/2k), a factor 1/√2 of the single-spring period. Their individual ½kx² energies add to ½(2k)x²."),
      p("synoptic", "deep:mat3:nonlinear-audit", "deep:mat3:nonlinear-audit:damper", "audit a spring model against non-linear and dissipative evidence", "A force-extension test shows a curved loading path and a different unloading path. State two reasons the simple F = kx model fails and one measurement to distinguish them.", 4, ["The stiffness may change with extension, so the material is non-linear; calculate local gradients", "Hysteresis may dissipate energy, so loading and unloading differ; measure loop area or temperature", "The apparatus may have friction or zero offset; repeat with unloaded calibration", "A valid test must separate constitutive non-linearity from apparatus loss"], "A changing gradient is a non-linear constitutive response; a loading/unloading gap is dissipation. Local-gradient plots, loop-area/temperature measurements and a zero-offset calibration separate these causes."),
    ],
  },
  {
    topic: "materials", point: 5,
    parts: [
      p("recall", "deep:mat5:behaviour-terms", "deep:mat5:behaviour-terms:test", "define elastic plastic and fracture behaviour", "Define elastic deformation, plastic deformation and fracture in a tensile test.", 3, ["Elastic deformation is recovered when the load is removed", "Plastic deformation leaves a permanent extension", "Fracture is loss of continuity or breakage under load"], "Elastic strain is recovered, plastic strain remains after unloading, and fracture is the failure or break in the specimen."),
      p("recall", "deep:mat5:limits", "deep:mat5:limits:stress-strain", "distinguish proportional and elastic limits", "State the difference between the limit of proportionality and the elastic limit.", 2, ["The proportional limit is where stress stops being proportional to strain", "The elastic limit is the greatest stress with no permanent deformation"], "The proportional limit marks the end of a straight stress-strain relation. The elastic limit marks the end of fully recoverable deformation; it is usually higher."),
      p("explanation", "deep:mat5:ductile-brittle", "deep:mat5:ductile-brittle:materials", "explain how graph shape distinguishes ductile and brittle materials", "Explain why a ductile material and a brittle material show different useful behaviour in a stress-strain test.", 3, ["A ductile material has a substantial plastic region before fracture", "A brittle material has little or no plastic deformation", "Ductility gives warning through permanent extension; brittleness gives abrupt failure"], "Ductile materials continue to deform plastically and give warning before breaking. Brittle materials remain near elastic then fracture with little permanent extension."),
      p("explanation", "deep:mat5:yield-region", "deep:mat5:yield-region:metal", "interpret a yield plateau as plastic flow", "A metal's stress-strain graph becomes nearly horizontal after the yield point. Explain what the plateau means microscopically and for the specimen length.", 3, ["Additional strain occurs with little increase in stress", "Plastic deformation is occurring", "The specimen has a permanent extension if unloaded from the plateau"], "The material yields: dislocations move so strain grows without much extra stress. Removing the load leaves a permanent extension."),
      p("application", "deep:mat5:read-graph", "deep:mat5:read-graph:alloy", "identify limits and failure from a plotted sequence", "A stress-strain trace is straight to 0.4%, curves to 1.0%, then has a yield plateau and fractures at 8%. Label the proportional limit, elastic region boundary and fracture strain.", 3, ["Proportional limit is at about 0.4% strain", "The elastic limit is at the end of recoverable curved behaviour, before the yield plateau", "Fracture strain is 8%"], "The straight-line endpoint near 0.4% is the proportional limit. The elastic limit is the later point just before permanent yielding, and fracture occurs at 8% strain."),
      p("application", "deep:mat5:design-choice", "deep:mat5:design-choice:crash-frame", "choose a ductile response for energy absorption", "A vehicle crumple zone must absorb energy without breaking suddenly. Use the stress-strain behaviour to justify choosing a ductile alloy.", 3, ["Plastic deformation allows a large strain before fracture", "The area under the stress-strain curve is energy absorbed per unit volume", "A ductile alloy can absorb energy while avoiding abrupt fracture"], "A ductile alloy provides a large plastic strain and hence a large area under the curve. It absorbs crash energy progressively rather than snapping."),
      p("misconception", "deep:mat5:limit-confusion", "deep:mat5:limit-confusion:wire", "correct conflating the two limits", "A student marks the first curvature of a stress-strain graph as the elastic limit. Explain why that label is premature.", 3, ["First curvature identifies loss of proportionality", "The material can still return to its original length while the curve is non-linear", "Elastic limit requires evidence of permanent strain on unloading"], "The first curvature is the proportional limit only. The elastic limit is found by unloading and checking when a permanent extension first remains."),
      p("misconception", "deep:mat5:area-strength", "deep:mat5:area-strength:ceramic", "separate high strength from toughness", "A ceramic has a high fracture stress but a small area under its stress-strain curve. Explain why it may be strong but not tough.", 3, ["Strength refers to the maximum stress before failure", "Toughness is energy per volume, the total area under the curve", "Small strain gives a small area even if the peak stress is high"], "The ceramic withstands a high stress, so it is strong, but fractures at small strain. The small area means little energy is absorbed, so it is not tough."),
      p("calculation", "deep:mat5:gradient-data", "deep:mat5:gradient-data:metal", "calculate modulus and energy density from early graph data", "A specimen has stress 90 MPa at strain 0.00045 in the linear region. Calculate its Young modulus and elastic energy density up to that point.", 3, ["E = stress/strain = 90×10⁶/0.00045 = 2.0×10¹¹ Pa", "The graph area is triangular for a linear region", "Energy density = ½×90×10⁶×0.00045 = 2.03×10⁴ J m⁻³"], "The modulus is 2.0×10¹¹ Pa. The triangular area gives an elastic energy density of about 2.0×10⁴ J m⁻³."),
      p("calculation", "deep:mat5:plastic-work", "deep:mat5:plastic-work:strip", "calculate plastic energy from loading and unloading areas", "A strip has 18 kJ m⁻³ of loading energy density and returns 11 kJ m⁻³ on unloading. Calculate the dissipated density and recovery percentage.", 3, ["Dissipated density = 18 − 11 = 7 kJ m⁻³", "Recovery = 11/18", "Recovery ≈ 61%"], "The dissipated density is 7 kJ m⁻³ and the recovery is 11/18 ≈ 61%."),
      p("transfer", "deep:mat5:temperature-rate", "deep:mat5:temperature-rate:polymer", "transfer deformation classification to rate and temperature effects", "A polymer becomes more brittle when cooled and tested quickly. Explain how rate and temperature alter the interpretation of its stress-strain curve.", 3, ["Lower temperature or higher rate gives less molecular time to rearrange", "The plastic region can shrink and fracture strain can fall", "Compare curves at controlled rates and temperatures before assigning one intrinsic behaviour"], "Cooling or rapid loading restricts molecular motion, so the plastic region may contract and fracture become more abrupt. Behaviour must be reported with the test conditions."),
      p("transfer", "deep:mat5:fatigue", "deep:mat5:fatigue:aircraft", "transfer static stress-strain evidence to cyclic failure", "An aircraft spar is below its static elastic limit but fails after many cycles. Explain why a single tensile curve cannot rule out fatigue and what evidence is needed.", 3, ["Repeated cycles can initiate and grow cracks below the static failure stress", "The relevant variable is stress range and number of cycles", "Use an S-N or crack-growth test at the service stress range"], "Static strength does not capture crack accumulation. Measure lifetime versus stress range or monitor crack growth under repeated loading."),
      p("synoptic", "deep:mat5:toughness-design", "deep:mat5:toughness-design:helmet", "combine stress-strain area, fracture mode and design constraints", "Compare two helmet liners: one has a high peak stress and small plastic area; the other has a lower peak and larger area. Which is preferable and why might density still matter?", 4, ["The larger area represents more energy absorbed per unit volume", "The lower peak stress reduces transmitted force", "The second liner is preferable if its fracture strain and rate response remain safe", "Density and thickness determine total absorbed energy and mass, so compare energy per unit mass/volume"], "The lower peak and larger area give safer force and energy absorption. Total protection also depends on liner thickness and density, so compare the complete mass and volume design."),
      p("synoptic", "deep:mat5:contradictory-curve", "deep:mat5:contradictory-curve:quality", "audit a curve for contradictory labels and model assumptions", "A report labels the first curved point as both the proportional limit and a fracture point. State the inconsistency and the checks needed before accepting the report.", 3, ["The proportional limit is an early loss of linearity, not normally fracture", "Check the axis scales and whether the trace contains multiple specimens or cycles", "Repeat the test with unloading to locate the elastic limit and fracture separately"], "The labels describe different events and cannot share one ordinary point. Verify axes and trace identity, then repeat loading and unloading to separate proportional loss, permanent strain and fracture."),
    ],
  },
  {
    topic: "materials", point: 6,
    parts: [
      p("recall", "deep:mat6:energy-relations", "deep:mat6:energy-relations:cord", "state elastic strain energy and energy density equations", "State equations for elastic strain energy and elastic strain-energy density in a linear material.", 3, ["Elastic energy = ½FΔL (or ½kx²)", "Energy density = energy/volume", "For a uniform linear specimen, density = ½ stress × strain"], "The stored energy is ½FΔL = ½kx². Dividing by volume gives the energy density, ½σε, in the linear region."),
      p("recall", "deep:mat6:graph-area", "deep:mat6:graph-area:tester", "identify elastic energy as a force-extension area", "How is elastic strain energy found from a force-extension graph?", 2, ["It is the area under the loading graph up to the extension", "For a straight line from the origin the area is a triangle"], "Take the area under the force-extension curve. A linear spring gives the triangular area ½FΔL."),
      p("explanation", "deep:mat6:volume-cancellation", "deep:mat6:volume-cancellation:rod", "derive energy density from stress and strain", "Explain why the volume cancels when ½FΔL is rewritten as ½ stress × strain.", 3, ["Stress = F/A and strain = ΔL/L", "Volume of a uniform rod is AL", "½FΔL/(AL) = ½(F/A)(ΔL/L) = ½σε"], "Use V = AL. Substitution gives [½FΔL]/[AL] = ½(F/A)(ΔL/L), which is ½ stress times strain."),
      p("explanation", "deep:mat6:hysteresis-energy", "deep:mat6:hysteresis-energy:rubber", "explain why a hysteresis loop changes recoverable energy", "Explain how a hysteresis loop on a force-extension graph separates input energy from recoverable elastic energy.", 3, ["Loading area is work supplied", "Unloading area is work returned", "The enclosed difference is dissipated energy"], "The loading area is the input work and the unloading area is what returns. Their difference is energy dissipated as heat or internal friction."),
      p("application", "deep:mat6:linear-energy", "deep:mat6:linear-energy:fibre", "calculate stored energy and energy density for a stretched fibre", "A fibre of length 0.80 m and area 1.5×10⁻⁶ m² is stretched by 2.0 mm under 90 N. Calculate its stored elastic energy and energy density.", 4, ["Energy = ½FΔL = ½×90×0.0020 = 0.090 J", "Volume = AL = 1.5×10⁻⁶×0.80 = 1.2×10⁻⁶ m³", "Density = 0.090/(1.2×10⁻⁶)", "Density = 7.5×10⁴ J m⁻³"], "The stored energy is 0.090 J. The volume is 1.2×10⁻⁶ m³, so the density is 7.5×10⁴ J m⁻³."),
      p("application", "deep:mat6:graph-integration", "deep:mat6:graph-integration:load-cell", "sum trapezia to estimate energy under a non-linear graph", "A force-extension trace has points (0 mm,0 N), (2 mm,40 N), (5 mm,70 N). Estimate the work done using trapezia.", 3, ["First area = ½(0+40)×0.002 = 0.040 J", "Second area = ½(40+70)×0.003 = 0.165 J", "Total work ≈ 0.205 J"], "The two trapezia give 0.040 J and 0.165 J, so the estimated work is 0.205 J."),
      p("misconception", "deep:mat6:half-kx-fallacy", "deep:mat6:half-kx-fallacy:spring", "correct treating force times extension as stored energy", "A student calculates a spring's energy as kx rather than ½kx². Explain both missing factors.", 3, ["kx is the final force, not an energy", "Force changes from zero to kx, so the mean force is ½kx", "Multiplying mean force by x gives ½kx²"], "kx is a force. The average force during a linear stretch is half the final force, so energy is ½(kx)x = ½kx²."),
      p("misconception", "deep:mat6:energy-density-total", "deep:mat6:energy-density-total:foam", "distinguish total energy from energy density", "Two foam blocks have the same energy density but different volumes. A student says they absorb the same total energy. Correct the claim.", 3, ["Energy density is energy per unit volume", "Total energy = density × volume", "The larger block absorbs more total energy if both reach the same state"], "Equal energy per volume does not mean equal total energy. Multiplying by volume shows the larger block stores more energy."),
      p("calculation", "deep:mat6:modulus-density", "deep:mat6:modulus-density:rod", "calculate strain energy density from modulus and strain", "A rod has Young modulus 1.6×10¹¹ Pa and elastic strain 0.0015. Calculate its elastic energy density.", 2, ["u = ½Eε²", "u = ½×1.6×10¹¹×(0.0015)² = 1.8×10⁵ J m⁻³"], "Using u = ½Eε² gives 1.8×10⁵ J m⁻³."),
      p("calculation", "deep:mat6:uncertainty-energy", "deep:mat6:uncertainty-energy:experiment", "propagate independent force and extension uncertainties into energy", "A spring stores 2.4 J from F = 60±3 N and x = 0.080±0.004 m. Estimate the percentage uncertainty in ½Fx.", 3, ["Percentage uncertainty in F = 3/60×100 = 5%", "Percentage uncertainty in x = 0.004/0.080×100 = 5%", "For a product, approximate total = 10%"], "Each factor contributes 5%, so the approximate energy uncertainty is 10%, or about 2.4±0.2 J."),
      p("transfer", "deep:mat6:cable-energy", "deep:mat6:cable-energy:lift", "transfer energy-density reasoning to a lifting cable", "A lifting cable must store little elastic energy while carrying a load. Explain which combinations of E, length, area and force reduce its extension energy.", 3, ["At fixed force and length, larger area reduces stress and extension", "A larger Young modulus reduces strain", "Stored energy ½FΔL falls when extension is reduced; geometry and material both matter"], "Use a large-area, high-E cable and minimise its free length. These reduce strain and extension, hence the elastic energy stored under the load."),
      p("transfer", "deep:mat6:damper-loop", "deep:mat6:damper-loop:vehicle", "transfer loop-area analysis to a damping component", "A damper is tested through repeated force-extension cycles. Explain how loop area and temperature reveal whether the component is dissipating energy as designed.", 3, ["Each loop area is energy dissipated per cycle", "A rising temperature supports conversion to thermal energy", "Changes in loop area with frequency reveal rate dependence or damage"], "Integrate the closed loop for energy lost per cycle and monitor temperature. Repeating at different rates shows whether viscous effects or damage are changing the dissipation."),
      p("synoptic", "deep:mat6:impact-absorber", "deep:mat6:impact-absorber:helmet", "combine force-time and force-extension evidence for an absorber", "A helmet liner has a broad force-time pulse and a large force-extension loop. Explain how these two measurements support safe energy absorption, and what they do not prove.", 4, ["A broad pulse increases stopping time and lowers peak force for a given impulse", "A large force-extension loop shows energy dissipated per deformation cycle", "Together they support reduced transmitted force and energy absorption", "They do not prove safety without checking mass, head acceleration, repeatability and rate dependence"], "The time pulse spreads the impulse and the displacement loop absorbs mechanical energy. Safety still needs acceleration limits, geometry, mass, repeat tests and the relevant impact rate."),
      p("synoptic", "deep:mat6:model-limits", "deep:mat6:model-limits:composite", "audit a linear energy-density model for a composite", "A composite is analysed with u = ½Eε², but its stress-strain curve has two linear slopes and a hysteresis loop. State how the energy calculation must change.", 4, ["Use the actual area under the stress-strain curve rather than one ½Eε² triangle", "Integrate each linear segment with its own slope", "Subtract or compare unloading area to obtain recoverable versus dissipated energy", "Report the strain range and loading history because energy is path-dependent"], "The single triangle is invalid across two slopes and a loop. Integrate the measured loading curve segment by segment and use the unloading path to separate recoverable and dissipated energy."),
    ],
  },
];

export const physicsDepthNearCompleteMaterialsQuestions = depthQuestions(ITEMS);
