import type { LearningDemand, Question } from "@/domain/types";
import { defineQuestion } from "./authoring";

/** Original drafts for one audited capability. No human approval is implied.
 * Board crosswalk: WJEC Physics v3 (October 2023), 4.1(b), (c), (g).
 * Each family names the reasoning needed, not a numerical variant.
 */
function energyItem(slug: string, demand: LearningDemand, family: string, context: string,
  reasoning: string, prompt: string, scheme: string[], answer: string): Question {
  const learning = { familyId: `capacitor-energy:${family}`, contextId: `capacitor-energy:${context}`,
    demand, reasoningMoves: [reasoning] };
  return defineQuestion({
    slug: `physics-energy-${slug}`, subjectId: "wjec-alevel-physics", topics: ["capacitance"],
    kind: demand === "calculation" ? "calculation" : "short", stem: prompt,
    source: "generated", verification: "unverified", reviewer: null, lastChecked: null,
    difficulty: demand === "recall" ? 1 : ["transfer", "synoptic"].includes(demand) ? 4 : 3,
    learning: { ...learning, expectedMinutes: scheme.length * 1.25 },
    parts: [{ prompt, marks: scheme.length, scheme, answer,
      specPointIds: ["wjec-alevel-physics.capacitance.sp-02"], capabilityIds: ["phys.capacitance.sp-02"],
      aos: demand === "recall" ? ["AO1"] : ["transfer", "synoptic"].includes(demand) ? ["AO2", "AO3"] : ["AO2"], learning }],
  });
}

export const physicsCapacitorEnergyQuestions: Question[] = [
  energyItem("charge-energy-definition", "recall", "charge-work", "charged-plates",
    "recall the energy relation using separated plate charge",
    "State the equation for energy U stored in a capacitor in terms of its charge Q and potential difference V. State what Q represents when the two plates carry equal and opposite charges.",
    ["U = QV/2.", "Q is the magnitude of charge on either plate, not the net charge of both plates."],
    "U = QV/2. Q is the magnitude on one plate; the plates carry +Q and -Q and their net charge is zero."),
  energyItem("graph-energy-recall", "recall", "charging-graph", "voltage-charge-plot",
    "recall a graphical representation of charging work",
    "For a graph of potential difference V on the vertical axis against charge Q on the horizontal axis, state which geometrical quantity gives the energy transferred in charging from zero. State its SI unit.",
    ["The area under the V against Q graph from zero to the final charge.", "Joule (J), equivalent to V C."],
    "The area under the V-Q graph gives the energy. Its unit is V C = J."),
  energyItem("why-half-qv", "explanation", "charging-graph", "incremental-charging",
    "explain the factor one half using the increasing charging voltage",
    "A capacitor has constant capacitance. Explain why the stored energy is QV/2 rather than QV when it is charged from zero to potential difference V. Refer to the work needed to transfer successive small amounts of charge.",
    ["The capacitor voltage rises from zero as charge is transferred.", "For constant capacitance V is proportional to Q, so the mean voltage during charging is V/2.", "Work is the area under the V-Q graph, or final charge times mean voltage, giving QV/2."],
    "The first small amount of charge is moved through almost zero voltage. Later charge is moved through a larger voltage. Since V = Q/C is linear, the mean voltage is V/2 and the total work is Q(V/2), the triangular area under the V-Q graph."),
  energyItem("energy-when-separated", "explanation", "isolated-geometry", "movable-air-plates",
    "identify the fixed charge and account for mechanical work on an isolated capacitor",
    "An ideal air-spaced parallel-plate capacitor is charged, disconnected and then its plate separation is doubled. Neglect leakage and edge effects. Explain the change in stored energy and where the extra energy comes from.",
    ["The magnitude of charge on each isolated plate remains fixed.", "C is inversely proportional to separation, so capacitance halves.", "U = Q²/(2C), so the stored energy doubles.", "External work is done separating the attracting plates and increases electric field energy."],
    "Disconnection fixes Q. Doubling the separation halves C, so Q²/(2C) doubles. Pulling the plates apart against their attraction requires external mechanical work, which supplies the increase in field energy."),
  energyItem("choose-pulse-bank", "application", "voltage-limit", "pulse-driver",
    "combine a required energy with the rated voltage constraint",
    "A pulse driver needs at least 0.40 J stored energy. Available capacitors are A: 2200 μF rated at 16 V, and B: 1000 μF rated at 35 V. A supply can be set to any voltage up to 30 V. Which single capacitor can meet the requirement without exceeding its rating? Justify quantitatively.",
    ["A stores at most 0.2816 J at its 16 V rating; alternatively, storing 0.40 J requires 19.1 V, above its rating.", "B stores 0.45 J at the 30 V supply limit; alternatively, 0.40 J requires 28.3 V, within both limits.", "Only B meets 0.40 J while remaining within both limits, justified by the preceding energy or required-voltage comparison."],
    "The voltage limit matters as well as capacitance. A stores at most 0.2816 J at 16 V. B stores 0.45 J at the supply limit of 30 V, below its 35 V rating. Only B can store at least 0.40 J."),
  energyItem("usable-voltage-window", "application", "energy-window", "backup-logger",
    "subtract residual energy at the cutoff instead of spending the full initial store",
    "A 2.0 F capacitor supplies a data logger as its voltage falls from 5.0 V to a 3.0 V cutoff. An ideal converter delivers the released energy to the logger, which consumes 0.50 W constantly. Calculate the operating time before cutoff.",
    ["Usable energy = 0.5 C (V_initial² - V_final²); accept subtracting separately calculated stores.", "Usable energy = 0.5 × 2.0 × (25 - 9) = 16 J.", "Time = energy/power = 16/0.50 = 32 s; allow follow-through for correctly dividing a positive stated energy by 0.50 W, with seconds."],
    "Energy remains in the capacitor at cutoff. The released energy is 0.5 × 2.0 × (5.0² - 3.0²) = 16 J. At 0.50 W the logger operates for 32 s."),
  energyItem("same-energy-half-voltage", "misconception", "voltage-limit", "low-voltage-redesign",
    "test a linear scaling claim against the squared-voltage dependence",
    "A designer says: 'If the charging voltage is halved, doubling the capacitance preserves the stored energy.' Assess this statement and give the capacitance change actually required.",
    ["U is proportional to CV².", "Doubling C and halving V gives U_new/U_old = 2 × (1/2)² = 1/2.", "C must be quadrupled to preserve the energy at half the voltage."],
    "The claim is false. U_new = 0.5(2C)(V/2)² = U_old/2. Since voltage is squared, four times the capacitance is needed at half the voltage."),
  energyItem("neutral-does-not-mean-empty", "misconception", "charge-work", "neutral-terminal-pair",
    "distinguish net charge from separated charge and the field energy",
    "An isolated capacitor has charges +30 μC and -30 μC on its plates and a potential difference of 20 V. A student argues that Q = 0, so U = QV/2 = 0. Explain the error, explain physically why energy is stored despite zero net charge, and calculate the energy stored.",
    ["Q in the energy formula is the magnitude on one plate, 30 μC, rather than the zero net charge.", "Separating opposite charges requires work, stored as electric field energy; accept a non-zero field between the oppositely charged plates storing energy.", "U = 0.5 × 30 × 10^-6 × 20 = 3.0 × 10^-4 J."],
    "Q in U = QV/2 is not the sum of the two plate charges. Use Q = 30 μC. The separated charges create an electric field storing 3.0 × 10^-4 J even though the capacitor's total charge is zero."),
  energyItem("infer-capacitance-from-slope", "calculation", "energy-gradient", "energy-voltage-squared-data",
    "identify capacitance from the slope of an energy against squared-voltage graph",
    "An experiment gives stored energies 0.010 J and 0.040 J at V² = 100 V² and 400 V² respectively. A straight line through these points and the origin models U against V². Calculate the capacitance from its gradient and give the answer in μF.",
    ["Gradient = (0.040 - 0.010)/(400 - 100) = 1.0 × 10^-4 J V^-2.", "From U = 0.5 C V², gradient = C/2.", "C = 2.0 × 10^-4 F = 200 μF."],
    "The gradient is 0.030/300 = 1.0 × 10^-4 J V^-2. Since U = (C/2)V², C is twice the gradient: 2.0 × 10^-4 F, or 200 μF."),
  energyItem("infer-voltage-from-charge-energy", "calculation", "inverse-charge-energy", "unknown-charged-component",
    "rearrange the charge-energy relation before deducing capacitance",
    "A capacitor stores 0.018 J when the magnitude of charge on each plate is 600 μC. Calculate its potential difference and capacitance. Show each rearrangement and include SI units.",
    ["V = 2U/Q; accept an equivalent rearrangement of U = QV/2.", "V = 2 × 0.018/(600 × 10^-6) = 60 V.", "C = Q/V = (600 × 10^-6)/60 = 1.0 × 10^-5 F (10 μF); allow follow-through using a positive stated voltage and correct charge with capacitance units. Accept C = Q²/(2U)."],
    "Rearrange U = QV/2 to give V = 2U/Q = 0.036/0.000600 = 60 V. Then C = Q/V = 0.000600/60 = 1.0 × 10^-5 F, or 10 μF. The factor two must be retained in the first step."),
  energyItem("charge-sharing-loss", "transfer", "charge-redistribution", "switched-reservoirs",
    "conserve total separated charge while accounting for dissipated energy",
    "A 4.0 μF capacitor initially at 12 V is connected in parallel, like terminals together, to an uncharged 8.0 μF capacitor. The supply is disconnected. A small resistance allows a final steady voltage to be reached. Calculate that voltage and the decrease in stored energy. Explain why charge conservation does not imply stored-energy conservation.",
    ["Initial charge = 4.0 × 10^-6 × 12 = 48 μC; total parallel capacitance is 12 μF.", "Final voltage = 48/12 = 4.0 V.", "Initial energy = 0.5 × 4.0 × 10^-6 × 12² = 288 μJ.", "Final energy = 0.5 × 12 × 10^-6 × 4.0² = 96 μJ, so the decrease is 192 μJ.", "The transient current dissipates energy in the resistance; total charge is conserved but capacitor energy alone is not."],
    "The final common voltage is Q_total/C_total = 48 μC/12 μF = 4.0 V. Initially the store is 288 μJ; finally it is 96 μJ. The 192 μJ difference becomes internal energy during the charging current. Conservation of charge does not forbid energy transfer to the connecting resistance."),
  energyItem("harvester-plate-cycle", "transfer", "isolated-geometry", "variable-capacitance-harvester",
    "track energy through an isolated change of capacitance in a mechanical harvester",
    "A variable capacitor is charged to 6.0 V while its capacitance is 100 nF. It is then isolated and stretched so its capacitance falls to 40 nF. Leakage and other losses are negligible. Calculate its new voltage and the minimum mechanical work required for the change.",
    ["Charge stays at Q = 100 × 10^-9 × 6.0 = 600 nC.", "New voltage = Q/C = 600/40 = 15 V.", "Initial energy = 1.8 μJ and final energy = 4.5 μJ.", "Minimum mechanical work equals the energy increase = 2.7 μJ."],
    "The isolated capacitor retains 600 nC. Reducing C to 40 nF raises V to 15 V. Initially U = 0.5 × 100 nF × 6.0² = 1.8 μJ; finally U = 0.5 × 40 nF × 15² = 4.5 μJ. External work of at least 2.7 μJ supplies the increase."),
  energyItem("energy-half-life", "synoptic", "exponential-energy", "resistor-discharge",
    "combine the exponential voltage law with the squared-voltage energy law",
    "A capacitor discharges through a resistor with V = V0 exp(-t/RC). Show that the time for its stored energy to halve differs from the time for its voltage to halve. Calculate both times when RC = 8.0 s.",
    ["U/U0 = (V/V0)² = exp(-2t/RC).", "For half energy, t = RC ln(2)/2 = 2.77 s (2.8 s to two significant figures).", "For half voltage, t = RC ln(2) = 5.55 s (5.5 s to two significant figures).", "The energy halves in half the voltage-halving time because energy is proportional to V²."],
    "At fixed C, U/U0 = (V/V0)² = exp(-2t/RC). Setting this to 1/2 gives t = 8.0 ln(2)/2 = 2.77 s. Voltage halves at t = 8.0 ln(2) = 5.55 s. Squaring the voltage doubles the exponential decay constant for energy."),
  energyItem("capacitor-lift-budget", "synoptic", "mechanical-energy-budget", "miniature-lifting-device",
    "combine a capacitor voltage window with conversion efficiency and gravitational work",
    "A motor uses a 0.50 F capacitor as its voltage falls from 12 V to 8.0 V. Of the released electrical energy, 60% becomes gravitational potential energy of a 0.25 kg mass. Starting and finishing at rest, what maximum height can the mass gain? Take g = 9.81 m s^-2.",
    ["Released capacitor energy = 0.5 × 0.50 × (12² - 8.0²) = 20 J.", "Useful gravitational energy = 0.60 × 20 = 12 J.", "Use mgh = 12 J.", "h = 12/(0.25 × 9.81) = 4.89 m, approximately 4.9 m."],
    "Only the energy between 12 V and the 8.0 V cutoff is available: 20 J. At 60% conversion efficiency the mass gains 12 J. With equal initial and final kinetic energy, h = 12/(0.25 × 9.81) = 4.89 m."),
];
