import { depthQuestions, type PhysicsDepthItem, type PhysicsDepthPart } from "./physics-depth-50-common";

const p = (
  demand: PhysicsDepthPart["demand"], family: string, context: string, move: string,
  prompt: string, marks: number, scheme: string[], answer: string,
): PhysicsDepthPart => ({ demand, family, context, move, prompt, marks, scheme, answer });

const ITEMS: PhysicsDepthItem[] = [
  {
    topic: "waves", point: 8,
    parts: [
      p("recall", "deep:waves8:definition", "deep:waves8:definition:slit", "define diffraction and identify its wavefront consequence", "Define diffraction and state what happens to a wave as it passes through a narrow gap.", 2, ["Diffraction is the spreading/bending of waves around an aperture or obstacle", "The wavefronts spread into the region behind the gap"], "Diffraction is the spreading of a wave after an aperture or around an obstacle. A narrow gap produces wavefronts that fan into the shadow region."),
      p("recall", "deep:waves8:minimum", "deep:waves8:minimum:single-slit", "state the single-slit condition for a first minimum", "State the relation for the first minimum from a single slit of width a.", 2, ["a sin θ = λ for the first minimum", "θ is measured from the undeviated central direction"], "For the first minimum, a sinθ = λ, with θ measured from the central axis."),
      p("explanation", "deep:waves8:width", "deep:waves8:width:laser", "explain why a narrower slit gives greater angular spreading", "Explain why reducing a slit width increases the angular width of the central diffraction maximum.", 3, ["The first-minimum condition is a sinθ = λ", "For fixed wavelength, smaller a requires larger sinθ and θ", "The central maximum therefore spreads more widely"], "With λ fixed, decreasing a makes λ/a larger, so the first minimum occurs at a larger angle and the central maximum is wider."),
      p("explanation", "deep:waves8:obstacle", "deep:waves8:obstacle:sound", "explain why long-wavelength waves diffract around obstacles", "A low-frequency sound bends around a doorway more than a short-wavelength ultrasonic wave. Explain the difference.", 3, ["Diffraction is appreciable when aperture or obstacle size is comparable to wavelength", "Low-frequency sound has the longer wavelength", "It therefore spreads more around the doorway"], "The doorway is a similar size to the long sound wavelength, so diffraction is strong. The much shorter ultrasound wavelength sees the doorway as a large aperture and spreads less."),
      p("application", "deep:waves8:shadow", "deep:waves8:shadow:harbour", "predict how an aperture-to-wavelength ratio changes a pattern", "A harbour entrance is widened from 20 m to 40 m while the water wavelength stays 5.0 m. Predict how the angular spreading changes.", 2, ["The ratio a/λ doubles", "Diffraction becomes weaker and the angular spread/central maximum narrows"], "Doubling a at fixed λ halves λ/a, so the first-minimum angle and angular spreading decrease."),
      p("application", "deep:waves8:fringe", "deep:waves8:fringe:microwave", "interpret a measured diffraction pattern to identify the controlling dimension", "A microwave detector records the first minimum at 18° for a slit. Which change would move it to a larger angle: increasing wavelength or increasing slit width? Explain.", 3, ["Increasing wavelength increases sinθ = λ/a", "Increasing slit width decreases λ/a", "Therefore a larger wavelength moves the first minimum to a larger angle"], "For fixed a, a larger λ requires a larger θ. Widening the slit has the opposite effect."),
      p("misconception", "deep:waves8:separation", "deep:waves8:separation:double-slit", "distinguish single-slit width from double-slit separation", "A student uses the distance between two double slits as a in a single-slit diffraction calculation. Correct the error.", 3, ["Single-slit diffraction uses the width of one aperture", "Double-slit separation controls two-source interference fringe spacing", "Use the physical width of each slit for a sinθ = λ"], "The single-slit a is one slit width. The centre-to-centre separation belongs to the double-slit interference relation, not the single-slit minimum."),
      p("misconception", "deep:waves8:central-minimum", "deep:waves8:central-minimum:screen", "correct treating the central maximum as a minimum", "A student labels the brightest central band as the first minimum. Explain what the minima represent.", 2, ["The central direction has constructive superposition and maximum intensity", "A first minimum is where contributions cancel, at a sinθ = λ"], "The central band is the maximum. A minimum is a dark direction where the slit contributions cancel; the first occurs when a sinθ equals λ."),
      p("calculation", "deep:waves8:single-minimum", "deep:waves8:single-minimum:aperture", "calculate a slit width from a first-minimum angle", "A 633 nm laser has its first single-slit minimum at 12°. Calculate the slit width.", 2, ["a = λ/sin12°", "a = 3.05×10⁻⁶ m"], "a = 633×10⁻⁹/sin12° ≈ 3.05×10⁻⁶ m."),
      p("calculation", "deep:waves8:angular-width", "deep:waves8:angular-width:camera", "calculate the central maximum width on a screen", "A 500 nm laser passes through a 0.20 mm slit to a screen 2.0 m away. Estimate the distance from the centre to the first minimum using the small-angle approximation.", 3, ["θ ≈ λ/a = 500×10⁻⁹/(2.0×10⁻⁴) = 2.5×10⁻³ rad", "y ≈ Lθ = 2.0×2.5×10⁻³", "y ≈ 5.0 mm"], "The first-minimum angle is about 2.5×10⁻³ rad. Multiplying by 2.0 m gives y ≈ 5.0 mm from the centre."),
      p("calculation", "deep:waves8:calibration", "deep:waves8:calibration:bench", "fit a diffraction calibration line from several screen distances", "A fixed slit gives first-minimum distances 6.0 mm, 12.0 mm and 18.0 mm at screen distances 0.50 m, 1.00 m and 1.50 m. Calculate the mean ratio y/L and state what it represents.", 3, ["Each ratio y/L is 0.012 m m⁻¹ (using metres)", "The mean ratio is 0.012 rad in the small-angle limit", "It represents λ/a for that slit and wavelength"], "Converting the distances to metres gives y/L = 0.012 for each point, so the mean is 0.012 rad. In the small-angle model this gradient is λ/a."),
      p("transfer", "deep:waves8:acoustic", "deep:waves8:acoustic:concert", "transfer optical diffraction scaling to acoustic design", "A concert hall opening should spread bass sound but preserve high-frequency directionality. Explain how its dimensions should compare with the two wavelengths.", 3, ["Make the opening comparable to the bass wavelength for strong diffraction", "Make it many high-frequency wavelengths wide for weak diffraction", "The same aperture can therefore spread bass while keeping treble more directional"], "Choose an opening whose size is similar to the long bass wavelength but much larger than the short treble wavelength. The diffraction ratio differs for the two bands."),
      p("transfer", "deep:waves8:imaging", "deep:waves8:imaging:microscope", "transfer aperture-diffraction reasoning to resolution", "Explain why increasing a microscope objective's numerical aperture improves resolution but does not remove the wavelength limit.", 3, ["A larger aperture gives a larger angular range and a smaller diffraction spot", "Resolution still scales with wavelength", "Shorter wavelength or immersion medium can improve the remaining limit"], "A larger numerical aperture reduces the diffraction blur by accepting larger angles. Finite wavelength still sets a lower bound, so shorter λ or a higher-index medium can help further."),
      p("synoptic", "deep:waves8:diffraction-interference", "deep:waves8:diffraction-interference:grating", "combine single-slit envelope with multi-slit interference", "A grating's sharp interference peaks sit inside a single-slit diffraction envelope. Explain why increasing each slit width changes the envelope without changing the main peak spacing.", 4, ["Peak spacing is set by slit separation d through d sinθ = nλ", "The single-slit envelope is set by each slit width a through a sinθ = mλ", "Increasing a narrows the envelope while d unchanged keeps peak angles", "The observed pattern is the product of both effects"], "The multi-slit separation fixes the sharp peak angles, while each slit width fixes the broad envelope. Widening the slits narrows the envelope but leaves d and the peak spacing unchanged."),
      p("synoptic", "deep:waves8:uncertainty", "deep:waves8:uncertainty:bench", "evaluate a diffraction wavelength measurement with systematic checks", "A measured first-minimum angle is 10.0°±0.5° for a slit width known to 2%. State the dominant uncertainty route and one systematic check.", 3, ["λ = a sinθ, so angle uncertainty changes λ through the sine", "Propagate the angle bounds and the 2% width uncertainty", "Check wavelength calibration, slit uniformity and the zero-angle alignment"], "Use λ = a sinθ and calculate extrema because the sine is non-linear. Verify the laser wavelength and slit width, and align the undeviated centre before accepting the result."),
    ],
  },
  {
    topic: "quantum", point: 3,
    parts: [
      p("recall", "deep:quantum3:intensity", "deep:quantum3:intensity:photocell", "state how intensity changes photon rate and photoelectron number", "For monochromatic light above threshold, state what increasing intensity changes at a metal surface.", 2, ["Intensity increases the photon arrival rate per unit area", "It increases the number of emitted photoelectrons/photocurrent, not their maximum energy"], "At fixed frequency, brighter light delivers more photons each second, so the photocurrent rises. Each photon still has the same energy, so maximum electron kinetic energy is unchanged."),
      p("recall", "deep:quantum3:photon-energy", "deep:quantum3:photon-energy:led", "state the photon energy relation and link wavelength", "State the photon-energy equation in terms of frequency and wavelength.", 2, ["E = hf", "Using c = fλ, E = hc/λ"], "A photon has energy E = hf = hc/λ."),
      p("explanation", "deep:quantum3:threshold", "deep:quantum3:threshold:metal", "explain why intensity cannot overcome a below-threshold frequency", "Explain why no photoelectrons are emitted from a metal when the light frequency is below threshold, however intense the beam is.", 3, ["One photon transfers energy hf to one electron", "Below threshold hf is less than the work function", "More photons increase attempts but none supplies enough energy in a single interaction"], "Each electron receives one photon at a time. If hf is below the work function, no individual transfer can release an electron; increasing photon count does not increase the energy per photon."),
      p("explanation", "deep:quantum3:instantaneous", "deep:quantum3:instantaneous:vacuum", "explain instantaneous emission as a photon interaction", "A photocell responds almost immediately when above-threshold light is switched on. Explain why this supports the photon model over a continuous energy-wave accumulation model.", 3, ["Energy is delivered in discrete photons", "An electron can be emitted in one interaction when hf ≥ φ", "There is no need to accumulate sub-threshold energy over a long time"], "A single photon can supply the required work function and excess energy in one event, so emission begins without the delay expected from gradual accumulation of a weak continuous wave."),
      p("application", "deep:quantum3:photocurrent", "deep:quantum3:photocurrent:cell", "predict photocurrent and stopping-potential changes separately", "A light source's intensity doubles while its frequency is fixed above threshold. Predict the change in saturation photocurrent and stopping potential.", 2, ["Saturation photocurrent approximately doubles because photon rate doubles", "Stopping potential is unchanged because maximum kinetic energy hf−φ is unchanged"], "The current rises roughly in proportion to photon rate. The stopping potential is unchanged because the energy per photon has not changed."),
      p("application", "deep:quantum3:filter", "deep:quantum3:filter:experiment", "use a filter change to separate intensity from frequency effects", "A neutral-density filter reduces intensity without changing colour. State which photoelectric measurements should change and which should not.", 3, ["Photocurrent/saturation current decreases", "Stopping potential and maximum kinetic energy remain the same", "Threshold frequency remains a property of the metal"], "The filter reduces photon rate, so current falls. It does not change f, the stopping potential, or the metal's threshold frequency."),
      p("misconception", "deep:quantum3:brighter-faster", "deep:quantum3:brighter-faster:lamp", "reject the claim that brighter light gives more energetic electrons", "A student says brighter violet light ejects faster electrons than dim violet light. Correct the claim.", 3, ["Both sources have the same photon frequency and energy", "Brightness changes the number of photons/electrons", "Maximum kinetic energy depends on f and φ, not intensity"], "The photons have the same energy in both beams. Brightness changes how many electrons are emitted, while their maximum kinetic energy remains set by hf−φ."),
      p("misconception", "deep:quantum3:energy-sharing", "deep:quantum3:energy-sharing:two-metals", "correct treating photon energy as shared among many electrons", "A student says one high-intensity photon beam can share its total energy among several electrons below threshold. Explain why the model disallows this.", 3, ["Photoelectric absorption is treated as one photon-one electron", "Each photon must individually provide at least the work function", "Total beam energy cannot compensate for insufficient energy per photon"], "In the photon model one photon transfers its energy to one electron. A large total flux cannot pool sub-threshold photon energies into one emission event."),
      p("calculation", "deep:quantum3:photon-rate", "deep:quantum3:photon-rate:laser", "calculate photon rate from optical power", "A monochromatic laser has power 2.0 mW and wavelength 500 nm. Calculate the photon rate. Use h = 6.63×10⁻³⁴ J s and c = 3.00×10⁸ m s⁻¹.", 3, ["Photon energy E = hc/λ = 3.98×10⁻¹⁹ J", "Rate = power/energy", "Rate ≈ 5.0×10¹⁵ photons s⁻¹"], "Each photon carries 6.63×10⁻³⁴×3.00×10⁸/(500×10⁻⁹) ≈ 3.98×10⁻¹⁹ J. Dividing 2.0×10⁻³ W gives about 5.0×10¹⁵ photons s⁻¹."),
      p("calculation", "deep:quantum3:maximum-energy", "deep:quantum3:maximum-energy:cesium", "calculate maximum kinetic energy from photon energy and work function", "Ultraviolet photons have energy 5.0 eV and a metal work function of 2.3 eV. Calculate the maximum kinetic energy and stopping potential.", 3, ["K_max = hf−φ = 5.0−2.3 = 2.7 eV", "Stopping potential satisfies eV_s = K_max", "V_s = 2.7 V"], "The maximum kinetic energy is 2.7 eV. Since one electron gains e volts per volt, the stopping potential is 2.7 V."),
      p("transfer", "deep:quantum3:photodiode", "deep:quantum3:photodiode:camera", "transfer photon-rate reasoning to a sensor response", "A camera sensor receives twice the photon flux at the same wavelength. Explain how the signal and shot-noise limitation are expected to change qualitatively.", 3, ["The mean number of collected electrons and signal approximately double", "Independent counting noise grows as the square root of count", "Signal-to-shot-noise ratio therefore improves by about √2"], "Doubling flux doubles the mean signal. Poisson noise rises only by √2, so signal-to-shot-noise improves by roughly √2, assuming no saturation or read-noise limit."),
      p("transfer", "deep:quantum3:solar", "deep:quantum3:solar:cell", "transfer threshold and intensity reasoning to a solar cell spectrum", "A solar cell has a threshold frequency. Explain why adding more below-threshold infrared power does not increase its photocurrent, while visible photons can.", 3, ["Below threshold each infrared photon has hf < φ", "Those photons cannot eject charge carriers in the photoelectric model", "Above-threshold photons can create carriers; current then depends on their rate and collection"], "Infrared photons below threshold lack the per-photon energy to release carriers, regardless of their number. Above-threshold photons can produce carriers, so their flux and collection efficiency affect current."),
      p("synoptic", "deep:quantum3:data-line", "deep:quantum3:data-line:experiment", "combine intensity control with a stopping-potential data test", "A stopping-potential graph is flat as intensity changes but rises linearly with frequency. Explain how the two trends test the photon equation.", 4, ["Stopping potential tracks maximum kinetic energy", "K_max = hf−φ gives a linear frequency relation with slope h/e", "Intensity changes photon rate but not hf, so it should not change stopping potential", "The intercept identifies the threshold/work-function term"], "The frequency slope measures h/e and the intercept gives −φ/e. Flat stopping potential versus intensity confirms that intensity changes count, not energy per photon."),
      p("synoptic", "deep:quantum3:uncertainty", "deep:quantum3:uncertainty:phototube", "evaluate a threshold estimate with contact-potential and calibration checks", "A threshold frequency inferred from stopping potentials changes when the detector is replaced. Give two non-physics checks before claiming the metal work function changed.", 4, ["Check voltmeter zero and contact-potential offsets", "Check that the replacement surface is the same clean material and illumination geometry", "Repeat the frequency fit with background current and intensity controlled", "Only a reproducible intercept difference after calibration supports a changed work function"], "Instrument offsets and surface condition can shift the intercept. Calibrate the voltage, verify the surface and geometry, control background and repeat the fit before interpreting a work-function change."),
    ],
  },
  {
    topic: "quantum", point: 4,
    parts: [
      p("recall", "deep:quantum4:debroglie", "deep:quantum4:debroglie:electron", "state de Broglie wavelength in terms of momentum", "State de Broglie's relation for the wavelength associated with a particle.", 2, ["λ = h/p", "p is the particle momentum"], "The de Broglie wavelength is λ = h/p."),
      p("recall", "deep:quantum4:diffraction-evidence", "deep:quantum4:diffraction-evidence:crystal", "state the observation that evidences electron wave behaviour", "What observation in an electron-crystal experiment is evidence for a de Broglie wave?", 2, ["Electrons form a diffraction pattern or intensity maxima", "The pattern obeys a wavelength relation consistent with h/p"], "A diffraction pattern with angle-dependent maxima is observed. Its inferred wavelength agrees with h/p, showing wave behaviour."),
      p("explanation", "deep:quantum4:momentum", "deep:quantum4:momentum:beam", "explain why increasing momentum shortens the wavelength", "Explain why accelerating an electron makes its de Broglie wavelength shorter.", 3, ["λ = h/p", "For fixed h, increasing momentum decreases λ", "A faster or more energetic electron therefore has a smaller diffraction scale"], "Planck's constant is fixed, so λ varies inversely with p. Acceleration raises p and shortens the associated wavelength."),
      p("explanation", "deep:quantum4:duality", "deep:quantum4:duality:interference", "explain wave-particle duality from complementary evidence", "Explain how a single electron can produce particle-like detections but a wave-like diffraction pattern over many detections.", 3, ["Each detection is localised and discrete", "The probability amplitude propagates and interferes", "The accumulated distribution forms the diffraction pattern"], "Electrons arrive as individual localised events, yet the probability amplitudes interfere during propagation. Repeated detections build the wave-like diffraction distribution."),
      p("application", "deep:quantum4:momentum-from-lambda", "deep:quantum4:momentum-from-lambda:neutron", "calculate momentum from a measured matter wavelength", "A neutron has de Broglie wavelength 0.20 nm. Calculate its momentum using h = 6.63×10⁻³⁴ J s.", 2, ["p = h/λ", "p = 6.63×10⁻³⁴/(0.20×10⁻⁹) = 3.32×10⁻²⁴ kg m s⁻¹"], "The momentum is 3.32×10⁻²⁴ kg m s⁻¹."),
      p("application", "deep:quantum4:electron-diffraction", "deep:quantum4:electron-diffraction:voltage", "predict wavelength change from an accelerating-voltage change", "Electrons are accelerated through 4.0 kV and then 16 kV. By what factor does their non-relativistic de Broglie wavelength change?", 3, ["p ∝ √V for electrons accelerated through a potential difference", "λ = h/p ∝ 1/√V", "Increasing V by a factor 4 halves λ"], "The voltage quadruples, so momentum doubles and the de Broglie wavelength halves."),
      p("misconception", "deep:quantum4:mass-wavelength", "deep:quantum4:mass-wavelength:ball", "reject applying a photon energy relation to matter wavelength", "A student uses E = hc/λ to calculate the wavelength of a moving ball. Explain which relation is appropriate and why.", 3, ["E = hc/λ is the photon relation", "For a material particle use λ = h/p", "The ball's momentum is mv at non-relativistic speed"], "The moving ball is not a photon, so use λ = h/p with p = mv. The photon formula links energy and wavelength only for electromagnetic quanta."),
      p("misconception", "deep:quantum4:high-speed", "deep:quantum4:high-speed:electron", "identify the limit of the non-relativistic momentum approximation", "A student applies p = mv to an electron accelerated to a voltage where its speed is a substantial fraction of c. State the risk.", 3, ["p = mv is a non-relativistic approximation", "At high speed relativistic momentum is greater than mv", "Use relativistic momentum or keep the voltage in a regime where the approximation is valid"], "At a substantial fraction of c, relativistic momentum must be used; p = mv underestimates p and therefore overestimates λ."),
      p("calculation", "deep:quantum4:electron-lambda", "deep:quantum4:electron-lambda:beam", "calculate a non-relativistic electron wavelength from voltage", "Calculate the de Broglie wavelength of an electron accelerated through 150 V. Use e = 1.60×10⁻¹⁹ C, m = 9.11×10⁻³¹ kg and h = 6.63×10⁻³⁴ J s.", 4, ["K = eV = 2.40×10⁻¹⁷ J", "p = √(2mK)", "p ≈ 6.62×10⁻²⁴ kg m s⁻¹", "λ = h/p ≈ 1.00×10⁻¹⁰ m"], "The kinetic energy is 2.40×10⁻¹⁷ J, giving p = √(2mK) ≈ 6.62×10⁻²⁴ kg m s⁻¹. Thus λ ≈ 1.00×10⁻¹⁰ m."),
      p("calculation", "deep:quantum4:crystal-angle", "deep:quantum4:crystal-angle:diffraction", "infer wavelength from a diffraction angle and lattice spacing", "A first-order electron diffraction maximum occurs at 30° from planes spaced 0.20 nm. Using 2d sinθ = nλ, calculate λ.", 2, ["λ = 2d sin30°", "λ = 0.20 nm"], "For n = 1, λ = 2(0.20 nm)(0.5) = 0.20 nm."),
      p("transfer", "deep:quantum4:neutron", "deep:quantum4:neutron:crystal", "transfer electron diffraction reasoning to neutron diffraction", "Why can neutron diffraction reveal crystal structure even though neutrons are not charged?", 3, ["Diffraction depends on wavelength and interaction with the periodic lattice, not charge alone", "Neutrons have λ = h/p and interact through nuclear forces", "Their intensity maxima encode lattice spacing"], "Neutrons have a matter wavelength and scatter from nuclei. A periodic lattice diffracts them, so peak angles reveal spacings without requiring electric charge."),
      p("transfer", "deep:quantum4:macroscopic", "deep:quantum4:macroscopic:interferometer", "transfer inverse-momentum scaling to a macroscopic object", "Explain why a moving dust grain has a de Broglie wavelength too small to observe in an ordinary diffraction experiment.", 3, ["λ = h/p", "The grain's mass makes p = mv large even at modest speed", "The wavelength is far below aperture and detector dimensions"], "The large mass gives a large momentum and hence an extremely small h/p wavelength, far below practical slit or detector scales."),
      p("synoptic", "deep:quantum4:duality-energy", "deep:quantum4:duality-energy:microscope", "combine de Broglie scaling with resolution and energy", "An electron microscope raises accelerating voltage to improve resolution. Explain the wavelength change and one trade-off in the specimen.", 4, ["Higher voltage raises momentum and reduces λ", "A shorter wavelength improves diffraction-limited resolution", "Higher electron energy can increase penetration, damage or charging", "The useful voltage is a compromise between resolution and specimen interaction"], "Higher voltage increases p and shortens λ, reducing the diffraction limit. It can also damage or over-penetrate the specimen, so resolution must be balanced against dose and contrast."),
      p("synoptic", "deep:quantum4:uncertainty", "deep:quantum4:uncertainty:electron", "propagate voltage uncertainty into a matter-wavelength estimate", "For non-relativistic electrons λ ∝ V⁻¹ᐟ². Estimate the percentage wavelength uncertainty when V = 400±8 V.", 3, ["Voltage percentage uncertainty = 8/400×100 = 2%", "The half-power relation gives about half that fractional uncertainty", "Wavelength uncertainty ≈ 1%"], "A 2% voltage uncertainty gives approximately 1% wavelength uncertainty because λ varies as V to the power −1/2."),
    ],
  },
];

export const physicsDepthNearCompleteQuantumQuestions = depthQuestions(ITEMS);
