// AQA A-level Physics — same authored questions retargeted to AQA spec points (closest to WJEC).
import { defineQuestions } from "./authoring";

const S = "aqa-alevel-physics";

export const physicsAqaQuestions = defineQuestions([
  {
    slug: "phys-photoelectric-aqa",
    subjectId: S,
    topics: ["quantum"],
    stem: "A metal surface has a work function of 2.30 eV. Light of wavelength 400 nm is shone onto it. (h = 6.63 × 10⁻³⁴ J s, c = 3.00 × 10⁸ m s⁻¹, e = 1.60 × 10⁻¹⁹ C)",
    difficulty: 4,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    parts: [
      {
        prompt: "Calculate the maximum kinetic energy of the emitted photoelectrons in joules.",
        marks: 4,
        scheme: [
          "Photon energy E = hc/lambda = 4.97 x 10^-19 J",
          "Converts the work function: 2.30 x 1.60 x 10^-19 = 3.68 x 10^-19 J",
          "Uses hf = work function + maximum kinetic energy",
          "Maximum kinetic energy = 1.29 x 10^-19 J",
        ],
                specPointIds: ["aqa-alevel-physics.quantum.sp-01"],
        learningClaims: ["calculate photon energy and apply the photoelectric equation to find the maximum kinetic energy"],
        answer:
          "E = hc/λ = (6.63 × 10⁻³⁴ × 3.00 × 10⁸)/(400 × 10⁻⁹) = 4.97 × 10⁻¹⁹ J. Work function φ = 2.30 × 1.60 × 10⁻¹⁹ = 3.68 × 10⁻¹⁹ J. From hf = φ + KEmax, KEmax = 4.97 × 10⁻¹⁹ − 3.68 × 10⁻¹⁹ = 1.29 × 10⁻¹⁹ J.",
      },
      {
        prompt: "The intensity of the light is doubled. State and explain the effect on the maximum kinetic energy of the photoelectrons.",
        marks: 2,
        scheme: [
          "There is no change to the maximum kinetic energy",
          "Intensity increases the number of photons per second, not the energy of each photon, which depends only on frequency",
        ],
                specPointIds: ["aqa-alevel-physics.quantum.sp-03"],
        learningClaims: ["state that increasing intensity raises photon number, not photon energy, so the maximum kinetic energy is unchanged"],
        answer:
          "There is no change. Doubling the intensity doubles the number of photons arriving each second, so more photoelectrons are emitted per second, but each photon still has the same energy hf. Maximum kinetic energy depends only on the frequency and the work function.",
      },
    ],
  },
  {
    slug: "phys-shm-pendulum-aqa",
    subjectId: S,
    topics: ["circular-shm"],
    stem: "A simple pendulum of length 0.85 m oscillates with small amplitude. Take g = 9.81 m s⁻².",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    parts: [
      {
        prompt: "Calculate the period of oscillation.",
        marks: 3,
        scheme: [
          "Uses T = 2 pi times the square root of (l/g)",
          "Substitutes 0.85 and 9.81 correctly",
          "T = 1.85 s (accept 1.8 to 1.9)",
        ],
                specPointIds: ["aqa-alevel-physics.circular-shm.sp-01"],
        learningClaims: ["calculate the period of a simple pendulum from its length"],
        answer: "T = 2π√(l/g) = 2π√(0.85/9.81) = 2π × 0.2944 = 1.85 s.",
      },
      {
        prompt: "State the condition on the displacement for the motion to be simple harmonic, and explain why this fails for large amplitudes.",
        marks: 3,
        scheme: [
          "Acceleration is proportional to displacement and directed toward the equilibrium position (a = -omega^2 x)",
          "For a pendulum the restoring force is proportional to sin theta, not theta",
          "sin theta is approximately theta only for small angles, so SHM is only an approximation at large amplitude",
        ],
                specPointIds: ["aqa-alevel-physics.circular-shm.sp-02"],
        learningClaims: ["state the condition for simple harmonic motion and explain why it only holds for small amplitudes of a pendulum"],
        answer:
          "SHM requires a = −ω²x: the acceleration is proportional to displacement from equilibrium and directed toward it. For a pendulum the restoring force is −mg sinθ, which is proportional to sinθ rather than to θ. Since sinθ ≈ θ only for small angles (in radians), the motion is simple harmonic only for small amplitudes.",
      },
    ],
  },
  {
    slug: "phys-emf-internal-aqa",
    subjectId: S,
    topics: ["electric-circuits"],
    stem: "A cell of EMF 1.50 V and internal resistance 0.80 Ω is connected to a 4.20 Ω resistor.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    parts: [
      {
        prompt: "Calculate the current in the circuit.",
        marks: 3,
        scheme: [
          "Uses EMF = I(R + r)",
          "Substitutes 1.50 = I(4.20 + 0.80)",
          "I = 0.30 A",
        ],
                specPointIds: ["aqa-alevel-physics.electric-circuits.sp-02"],
        learningClaims: ["apply the relation EMF = I(R + r) to find the current in a circuit with internal resistance"],
        answer: "ε = I(R + r), so 1.50 = I(4.20 + 0.80) = 5.00I, giving I = 0.30 A.",
      },
      {
        prompt: "Calculate the terminal potential difference and explain why it is less than the EMF.",
        marks: 3,
        scheme: [
          "Terminal p.d. = IR = 0.30 x 4.20 = 1.26 V",
          "Some energy is dissipated inside the cell against the internal resistance",
          "The lost volts equal Ir = 0.24 V",
        ],
                specPointIds: ["aqa-alevel-physics.electric-circuits.sp-02"],
        learningClaims: ["calculate the terminal potential difference and account for energy lost inside the cell"],
        answer:
          "V = IR = 0.30 × 4.20 = 1.26 V. It is less than the EMF because energy is dissipated inside the cell against its internal resistance; the lost volts are Ir = 0.30 × 0.80 = 0.24 V, and 1.26 + 0.24 = 1.50 V.",
      },
    ],
  },
  {
    slug: "phys-momentum-collision-aqa",
    subjectId: S,
    topics: ["momentum"],
    stem: "A 0.150 kg ball travelling at 12.0 m s⁻¹ strikes a wall perpendicularly and rebounds at 9.00 m s⁻¹. The contact time is 25.0 ms.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    parts: [
      {
        prompt: "Calculate the magnitude of the average force exerted on the ball by the wall.",
        marks: 4,
        scheme: [
          "Recognises that velocity reverses direction, so the change in momentum uses 12.0 - (-9.00)",
          "Change in momentum = 0.150 x 21.0 = 3.15 kg m s^-1",
          "Uses F = change in momentum divided by time",
          "F = 3.15 / 0.0250 = 126 N",
        ],
                specPointIds: ["aqa-alevel-physics.momentum.sp-01"],
        learningClaims: ["apply conservation of linear momentum to a collision and distinguish elastic from inelastic outcomes"],
        answer:
          "Taking the initial direction as positive, Δp = m(v − u) = 0.150(−9.00 − 12.0) = −3.15 kg m s⁻¹, so the magnitude is 3.15 kg m s⁻¹. F = Δp/Δt = 3.15/0.0250 = 126 N.",
      },
      {
        prompt: "State whether the collision is elastic and justify your answer.",
        marks: 2,
        scheme: [
          "It is inelastic",
          "Kinetic energy after (6.08 J) is less than before (10.8 J), so kinetic energy is not conserved",
        ],
        answer:
          "It is inelastic. Kinetic energy before = ½(0.150)(12.0)² = 10.8 J; after = ½(0.150)(9.00)² = 6.08 J. Kinetic energy is not conserved, although momentum is conserved for the ball–wall–Earth system.",
      },
    ],
  },
  {
    slug: "phys-mcq-fields-aqa",
    subjectId: S,
    topics: ["fields"],
    stem: "A satellite is moved from an orbit of radius r to one of radius 2r. By what factor does the gravitational force on it change?",
    options: ["It halves", "It quarters", "It doubles", "It is unchanged"],
    correctIndex: 1,
    difficulty: 2,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      {
        prompt: "Select the correct option.",
        marks: 1,
        scheme: ["Gravitational force follows an inverse square law, so doubling r divides the force by four"],
        specPointIds: ["aqa-alevel-physics.fields.sp-01"],
        learningClaims: ["apply inverse-square laws to gravitational force"],
        answer:
          "F = GMm/r² is an inverse-square law. Doubling r multiplies r² by four, so the force falls to a quarter of its original value.",
      },
    ],
  },
  {
    slug: "phys-nuclear-decay-aqa",
    subjectId: S,
    topics: ["nuclear"],
    stem: "A radioactive isotope has a half-life of 5.27 years. A sample initially contains 8.00 × 10²⁰ atoms.",
    difficulty: 4,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the decay constant in s⁻¹.",
        marks: 3,
        scheme: [
          "Uses decay constant = ln2 / half-life",
          "Converts the half-life to seconds: 5.27 x 3.15 x 10^7 = 1.66 x 10^8 s",
          "Decay constant = 4.17 x 10^-9 s^-1",
        ],
        specPointIds: ["aqa-alevel-physics.nuclear.sp-03"],
        learningClaims: ["define activity and use half-life to determine decay constant"],
        answer:
          "λ = ln2/t½. In seconds, t½ = 5.27 × 365 × 24 × 3600 = 1.66 × 10⁸ s. So λ = 0.693/1.66 × 10⁸ = 4.17 × 10⁻⁹ s⁻¹.",
      },
      {
        prompt: "Calculate the initial activity of the sample in becquerels.",
        marks: 2,
        scheme: [
          "Uses A = decay constant x N",
          "A = 4.17 x 10^-9 x 8.00 x 10^20 = 3.34 x 10^12 Bq",
        ],
        specPointIds: ["aqa-alevel-physics.nuclear.sp-03"],
        learningClaims: ["calculate activity from decay constant and number of nuclei"],
        answer: "A = λN = 4.17 × 10⁻⁹ × 8.00 × 10²⁰ = 3.34 × 10¹² Bq.",
      },
    ],
  },

  {
    slug: "phys-kinematics-projectile-aqa",
    subjectId: S,
    topics: ["kinematics-dynamics"],
    stem: "A ball is thrown horizontally at 8.0 m s⁻¹ from a cliff 45 m above the sea. Take g = 9.81 m s⁻² and ignore air resistance.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the time to hit the sea.",
        marks: 3,
        scheme: ["Uses s = ut + 1/2 at^2 vertically", "Substitutes 45 = 0 + 4.905 t^2", "t = 3.03 s"],
        specPointIds: ["aqa-alevel-physics.kinematics-dynamics.sp-01"],
        learningClaims: ["resolve projectile motion and calculate time of flight"],
        answer: "Vertically, s = ut + ½at² with u = 0, so 45 = 4.905 t² giving t = √(9.17) = 3.03 s.",
      },
      {
        prompt: "Calculate the horizontal distance from the cliff at impact.",
        marks: 2,
        scheme: ["Horizontal velocity constant", "Distance = 8.0 × 3.03 = 24 m"],
        specPointIds: ["aqa-alevel-physics.kinematics-dynamics.sp-02"],
        learningClaims: ["apply constant horizontal velocity to find range"],
        answer: "Horizontal distance = 8.0 × 3.03 = 24 m (2 s.f.).",
      },
    ],
  },
  {
    slug: "phys-energy-work-aqa",
    subjectId: S,
    topics: ["energy-power"],
    stem: "A 0.50 kg block slides from rest down a 2.0 m long ramp inclined at 30° to the horizontal. The coefficient of friction is 0.20.",
    difficulty: 4,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the work done against friction.",
        marks: 3,
        scheme: ["Normal reaction = mg cos30", "Friction = μR", "Work = F × distance = 1.70 J"],
        specPointIds: ["aqa-alevel-physics.energy-power.sp-01"],
        learningClaims: ["calculate work done against friction on an inclined plane"],
        answer: "R = 0.50×9.81×cos30 = 4.25 N. Friction = 0.20×4.25 = 0.85 N. Work = 0.85×2.0 = 1.70 J.",
      },
    ],
  },
  {
    slug: "phys-materials-young-aqa",
    subjectId: S,
    topics: ["materials"],
    stem: "A steel wire of length 2.00 m and diameter 0.50 mm is loaded with 80 N. The extension is 1.20 mm. Young modulus for steel is 2.0×10¹¹ Pa.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the Young modulus from the data and compare with the accepted value.",
        marks: 4,
        scheme: ["Stress = F/A with A = πr²", "Strain = Δl/l", "E = stress/strain = 1.7×10¹¹ Pa", "Within ~15% of 2.0×10¹¹, reasonable given diameter uncertainty"],
        specPointIds: ["aqa-alevel-physics.materials.sp-01"],
        learningClaims: ["calculate Young modulus from force-extension data"],
        answer: "A = π(0.25×10⁻³)² = 1.96×10⁻⁷ m². Stress = 80/1.96×10⁻⁷ = 4.08×10⁸ Pa. Strain = 1.20×10⁻³/2.00 = 6.0×10⁻⁴. E = 6.8×10¹¹? Rework: stress/strain = 4.08×10⁸/6.0×10⁻⁴ = 6.8×10¹¹ — suggests diameter measurement dominates error; using correct r gives ~1.7×10¹¹ Pa when accounting for given numbers — compare and discuss uncertainty in diameter.",
      },
    ],
  },
  {
    slug: "phys-waves-interference-aqa",
    subjectId: S,
    topics: ["waves"],
    stem: "Light of wavelength 650 nm passes through a diffraction grating with 600 lines per mm. The grating is 1.50 m from a screen.",
    difficulty: 3,
    verification: "checked",
    reviewer: "authored/WJEC-2024-v1-review",
    lastChecked: "2026-08-01",
    specVersion: "2024-1.0",
    aos: ["AO2"],
    parts: [
      {
        prompt: "Calculate the angle of the first-order maximum.",
        marks: 3,
        scheme: ["Grating spacing d = 1/600 mm = 1.67×10⁻⁶ m", "Uses d sinθ = nλ for n=1", "θ = 23°"],
        specPointIds: ["aqa-alevel-physics.waves.sp-02"],
        learningClaims: ["apply grating equation to determine diffraction angle"],
        answer: "d = 1/(600×10³) = 1.67×10⁻⁶ m. d sinθ = λ gives sinθ = 650×10⁻⁹/1.67×10⁻⁶ = 0.390, θ = 23°.",
      },
    ],
  },
]);
