import { qualityItem as q } from "./wjec-quality-authoring";

// Original unreviewed drafts. Official crosswalk and limitations are in the review pack.
export const wjecMathsQualityQuestions = [
  q("maths", "differentiation", 4, "global-candidates", "recall", "bounded-optimisation", "recall candidate comparison on a closed interval",
    "A function is differentiable throughout a closed interval [a,b]. State how to identify its global minimum from its derivative and function values.",
    ["Find stationary points inside the interval by solving f'(x) = 0.", "Evaluate f at these points and at a and b, selecting the smallest value."],
    "Solve f'(x) = 0 inside (a,b), then compare the function values at those points and both endpoints. The smallest is the global minimum."),
  q("maths", "differentiation", 4, "normal-rule", "recall", "normal-slope", "recall perpendicular-gradient relation with its exception",
    "At a point on a curve the tangent has finite non-zero gradient m. State the normal gradient. What form does the normal take when the tangent is horizontal?",
    ["Normal gradient = -1/m.", "For a horizontal tangent the normal is a vertical line."],
    "The normal gradient is -1/m for non-zero m. If the tangent is horizontal, the normal is vertical, so it has no finite gradient."),
  q("maths", "differentiation", 4, "boundary-beats-local", "explanation", "bounded-optimisation", "distinguish local classification from global comparison",
    "For f(x) = x³ - 3x on [0,3], x = 1 is a local minimum. Explain why this fact alone cannot identify the global maximum, and determine that maximum.",
    ["A local minimum does not identify a maximum; endpoints must also be compared.", "The only interior stationary point is x = 1, with f(1) = -2; f(0) = 0 and f(3) = 18.", "The global maximum is 18 at x = 3."],
    "f'(x) = 3x² - 3 vanishes only at x = 1 in the interval's interior. It gives -2, whereas the endpoint values are 0 and 18. Thus the global maximum is f(3) = 18, despite f'(3) being non-zero."),
  q("maths", "differentiation", 4, "rate-units", "explanation", "related-rates", "interpret a derivative as a local rate with correct units",
    "A reservoir's volume V is measured in m³ and time t in hours. At noon dV/dt = -12. Explain what this says about the volume, and why it does not imply that 12 m³ will be lost during the next whole hour.",
    ["The volume is decreasing at an instantaneous rate of 12 m³ h^-1 at noon.", "The rate may change during the following hour, so the total change requires the rate over the interval."],
    "At noon the instantaneous rate of volume loss is 12 m³ h^-1. This describes the local slope, not necessarily an hour's total loss; the rate could vary afterwards."),
  q("maths", "differentiation", 4, "fencing-cost", "application", "constrained-geometry", "translate unequal boundary costs into a one-variable area",
    "A rectangular enclosure has one side along an existing wall. Fencing the opposite side costs £20 per metre and the two perpendicular sides cost £10 per metre each. With £1200 available, find the dimensions giving maximum area. Ignore gate costs.",
    ["For perpendicular length x and opposite length y, 20x + 20y = 1200, so y = 60 - x.", "A = x(60 - x), with 0 < x < 60; A' = 60 - 2x = 0 gives x = 30.", "A'' = -2 and the boundary areas tend to zero; y = 30 m gives maximum area 900 m²."],
    "The cost constraint is 2(10x) + 20y = 1200, so y = 60 - x. Area is 60x - x², a concave quadratic maximised at x = 30. Hence y = 30 m and the largest area is 900 m²."),
  q("maths", "differentiation", 4, "calibration-tangent", "application", "tangent-line", "use the derivative to construct a local linear calibration",
    "A sensor model is y = x² + 2x. Use its tangent at x = 2 to estimate y when x = 2.03, and state whether the estimate is above or below the exact value.",
    ["At x = 2, y = 8 and dy/dx = 2x + 2 = 6.", "Tangent: y = 8 + 6(x - 2), giving 8.18.", "The estimate is below the exact value because the curve is convex; accept exact comparison with 8.1809."],
    "The tangent is y - 8 = 6(x - 2), so it predicts 8.18. The exact value is 8.1809; the positive second derivative means the curve lies above its tangent."),
  q("maths", "differentiation", 4, "infeasible-root", "misconception", "bounded-optimisation", "reject a derivative root outside the stated domain",
    "A production model gives profit P(x) = 40x - x², valid for 0 ≤ x ≤ 12. A student selects x = 20 because P'(20) = 0. Correct the decision and justify the optimum on the stated domain.",
    ["x = 20 is outside the feasible interval.", "P'(x) = 40 - 2x is positive throughout [0,12], so profit increases there.", "Choose x = 12; maximum profit is P(12) = 336 in the model's profit units."],
    "The stationary point is infeasible. P' remains positive up to x = 12, so the greatest permitted x gives the maximum: P(12) = 480 - 144 = 336."),
  q("maths", "differentiation", 4, "negative-reciprocal", "misconception", "normal-slope", "correct a sign-only change in constructing a normal",
    "For y = x² at x = 2 a student writes the normal as y - 4 = -4(x - 2). Identify the error and give the correct normal equation.",
    ["The tangent gradient is 4; perpendicular gradients have product -1, so the normal gradient is -1/4, not -4.", "The normal is y - 4 = -(x - 2)/4; accept an equivalent line equation."],
    "The student changed only the sign. The negative reciprocal of 4 is -1/4. Through (2,4), the normal is y - 4 = -(x - 2)/4, or x + 4y = 18."),
  q("maths", "differentiation", 4, "sphere-rate", "calculation", "related-rates", "chain the volume-radius and radius-time rates",
    "A sphere expands so its radius increases at 0.20 cm s^-1. Given V = 4πr³/3, calculate dV/dt when r = 3.0 cm. Give an exact value and units.",
    ["dV/dr = 4πr².", "dV/dt = (dV/dr)(dr/dt) = 4π × 9 × 0.20.", "dV/dt = 7.2π cm³ s^-1; allow consistent follow-through from a stated derivative."],
    "Using the chain rule, dV/dt = 4πr² dr/dt. At the stated instant this is 4π(3.0)²(0.20) = 7.2π cm³ s^-1."),
  q("maths", "differentiation", 4, "normal-axis-intercept", "calculation", "normal-slope", "combine a normal gradient with an axis intersection",
    "Find the point where the normal to y = x³ at x = 1 meets the x-axis. Show your gradient and line equation.",
    ["At (1,1), tangent gradient is 3 and normal gradient is -1/3.", "Normal equation: y - 1 = -(x - 1)/3.", "Setting y = 0 gives x = 4, so the intercept is (4,0)."],
    "dy/dx = 3x² gives gradient 3 at (1,1). The normal is y - 1 = -(x - 1)/3. Setting y = 0 gives -3 = -x + 1, hence (4,0)."),
  q("maths", "differentiation", 4, "external-tangents", "transfer", "tangent-line", "solve for unknown contact points using an external point",
    "Determine both tangents to y = x² that pass through (0,-4). You may represent the contact point as (a,a²).",
    ["The tangent at (a,a²) is y = 2ax - a².", "Passing through (0,-4) requires a² = 4, so a = ±2.", "The two tangents are y = 4x - 4 and y = -4x - 4."],
    "The contact gradient is 2a, giving y - a² = 2a(x - a). At x = 0 the intercept is -a²; setting it to -4 gives a = 2 or -2. These produce y = 4x - 4 and y = -4x - 4."),
  q("maths", "differentiation", 4, "integer-design", "transfer", "discrete-candidate-comparison", "turn a continuous optimum into an integer design decision",
    "An unfamiliar device's score is S(n) = 20n - 3n², where n must be an integer from 1 to 6. Use calculus to narrow the candidates, then determine the permitted value giving maximum score.",
    ["Treating n as continuous, S' = 20 - 6n = 0 gives n = 10/3; S'' = -6.", "Compare neighbouring permitted integers: S(3) = 33 and S(4) = 32.", "n = 3 is optimal; the concave quadratic decreases away from its vertex, excluding more distant integers."],
    "The continuous vertex is 10/3, between 3 and 4. Concavity reduces the integer comparison to these neighbours. Their scores are 33 and 32, so choose n = 3. Rounding without this comparison would not justify the answer."),
  q("maths", "differentiation", 4, "cone-material", "synoptic", "constrained-geometry", "optimise geometry using a nonlinear volume constraint",
    "A closed cylinder has volume 128π cm³. Its surface area is A = 2πr² + 2πrh. Find the radius and height that minimise area for r > 0, and justify a global minimum.",
    ["πr²h = 128π gives h = 128/r² and A = 2πr² + 256π/r.", "A' = 4πr - 256π/r² = 0 gives r³ = 64, hence r = 4 cm.", "h = 8 cm.", "A'' = 4π + 512π/r³ > 0 for r > 0, so this is the global minimum; accept decreasing/increasing derivative analysis."],
    "Eliminating h gives A(r) = 2πr² + 256π/r. Its derivative vanishes at r = 4 cm, giving h = 8 cm. The second derivative is positive throughout r > 0, so the sole stationary point is a global minimum."),
  q("maths", "differentiation", 4, "moving-rectangle", "synoptic", "related-rates", "combine simultaneous dimension changes using the product rule",
    "At one instant a rectangle is 8 cm long and 5 cm wide. Its length increases at 0.30 cm s^-1 while its width decreases at 0.10 cm s^-1. Determine whether its area is increasing, and explain why multiplying the two dimension rates is incorrect.",
    ["For A = lw, dA/dt = w dl/dt + l dw/dt.", "dA/dt = 5(0.30) + 8(-0.10) = 0.70 cm² s^-1, so area increases.", "Multiplying the dimension rates misses both existing dimensions and gives cm² s^-2 rather than an area rate."],
    "The product rule gives dA/dt = 5 × 0.30 - 8 × 0.10 = 0.70 cm² s^-1. Multiplying 0.30 by -0.10 would give the wrong units and omit the effects of the current length and width."),

  q("maths", "conditional-probability", 1, "conditioning-formula", "recall", "restricted-sample-space", "state conditional probability with its domain restriction",
    "State P(A|B) in terms of P(A ∩ B) and P(B). State the condition needed on P(B).",
    ["P(A|B) = P(A ∩ B)/P(B).", "P(B) > 0."],
    "P(A|B) = P(A ∩ B)/P(B), provided P(B) is positive. Conditioning restricts the sample space to B."),
  q("maths", "conditional-probability", 1, "conditional-path", "recall", "conditional-tree", "recall the general multiplication law without independence",
    "A and B need not be independent. State a formula for P(A ∩ B) using P(A) and a conditional probability. Name that conditional probability in words.",
    ["P(A ∩ B) = P(A)P(B|A).", "P(B|A) is the probability of B given that A has occurred."],
    "Multiply P(A) by P(B|A): the probability of reaching A, then of B conditional on already being in A."),
  q("maths", "conditional-probability", 1, "reverse-conditioning", "explanation", "bayes-base-rate", "explain why reversing a condition changes the denominator",
    "Among 100 students, 20 study Music and 50 study Physics; 15 study both. Explain why P(Music|Physics) and P(Physics|Music) differ, giving both values.",
    ["P(Music|Physics) = 15/50 = 0.30.", "P(Physics|Music) = 15/20 = 0.75.", "The same intersection is divided by different conditioning groups, 50 and 20."],
    "Of the 50 Physics students, 15 take Music, giving 0.30. Of the 20 Music students, 15 take Physics, giving 0.75. Reversing the condition changes the relevant group."),
  q("maths", "conditional-probability", 1, "replacement-explanation", "explanation", "without-replacement", "explain how an observed draw changes later probabilities",
    "A bag contains three red and two blue counters. Two are drawn without replacement. Explain why the probability the second is red changes after being told the first was blue, and calculate the new probability.",
    ["Removing a blue counter leaves three red counters among four counters.", "The conditional probability is 3/4, rather than the original red proportion 3/5."],
    "Given a blue first draw, there are three red and one blue left. The second-red probability is therefore 3/4 because the composition of the bag has changed."),
  q("maths", "conditional-probability", 1, "quality-control", "application", "bayes-base-rate", "combine production shares and defect rates before conditioning",
    "Factory A supplies 70% of components and factory B supplies 30%. Defect rates are 2% at A and 5% at B. A randomly selected component is defective. Find the probability it came from B.",
    ["P(B ∩ defective) = 0.30 × 0.05 = 0.015.", "P(defective) = 0.70 × 0.02 + 0.30 × 0.05 = 0.029.", "P(B|defective) = 0.015/0.029 = 15/29, approximately 0.517."],
    "The defective components comprise probability 0.014 from A and 0.015 from B. B's share among defects is 0.015/0.029 = 15/29, about 0.517."),
  q("maths", "conditional-probability", 1, "club-table", "application", "restricted-sample-space", "condition on an observed subgroup in a two-way table",
    "A survey records 24 cycle owners who commute by bike, 36 cycle owners who do not, 6 non-owners who commute by bike and 34 non-owners who do not. A respondent does not commute by bike. Find the probability that they own a cycle.",
    ["The conditioning group contains 36 + 34 = 70 respondents.", "The probability is 36/70 = 18/35, approximately 0.514."],
    "Restrict attention to the 70 non-commuters. Of those, 36 own a cycle, giving 18/35. Dividing by all 100 respondents would be a joint probability instead."),
  q("maths", "conditional-probability", 1, "disjoint-not-independent", "misconception", "independence-test", "use conditional probability to distinguish exclusion and independence",
    "Events A and B are mutually exclusive and both have positive probability. A student calls them independent because they cannot happen together. Use conditional probability to refute this.",
    ["Mutual exclusion gives P(A ∩ B) = 0, so P(A|B) = 0.", "Since P(A) > 0, P(A|B) differs from P(A); the events are not independent."],
    "Once B has happened, A is impossible: P(A|B) = 0. Independence would require this to equal the positive unconditional probability P(A), so the claim is false."),
  q("maths", "conditional-probability", 1, "two-child-information", "misconception", "information-protocol", "distinguish a named observation from an at-least-one condition",
    "For two births assume independent equally likely girl/boy outcomes. Compare P(both girls | at least one girl) with P(both girls | the older child is a girl). Explain why the conditions cannot be interchanged.",
    ["At least one girl leaves GG, GB and BG, so the first probability is 1/3.", "Older child is a girl leaves GG and GB, so the second probability is 1/2.", "The information removes different outcomes from the ordered sample space."],
    "Among GG, GB, BG and BB, the first condition excludes only BB, whereas the second excludes BG and BB. Thus the probabilities are 1/3 and 1/2 respectively."),
  q("maths", "conditional-probability", 1, "intersection-from-union", "calculation", "set-algebra", "recover an intersection before applying the conditional denominator",
    "P(A) = 0.55, P(B) = 0.40 and P(A ∪ B) = 0.70. Calculate P(A|B) and P(A|B').",
    ["P(A ∩ B) = 0.55 + 0.40 - 0.70 = 0.25.", "P(A|B) = 0.25/0.40 = 0.625.", "P(A|B') = (0.55 - 0.25)/(1 - 0.40) = 0.50."],
    "The intersection is 0.25. Dividing by P(B) gives 0.625. Outside B the A probability mass is 0.30 and the total mass is 0.60, giving 0.50."),
  q("maths", "conditional-probability", 1, "ordered-draws", "calculation", "without-replacement", "sum disjoint orders under a changing composition",
    "A bag contains four red and three blue counters. Two counters are drawn without replacement. Given that the colours differ, find the probability that the first counter was red.",
    ["P(R then B) = (4/7)(3/6) = 2/7.", "P(B then R) = (3/7)(4/6) = 2/7, so P(different) = 4/7.", "The required probability is (2/7)/(4/7) = 1/2."],
    "The two orders RB and BR each have probability 2/7. Conditioning on their union gives RB a share of one half. The initial red proportion 4/7 is not the conditional answer."),
  q("maths", "conditional-probability", 1, "latent-source", "transfer", "bayes-base-rate", "update a hidden source using two observations from that same source",
    "A coin is selected once: with probability 1/2 it is fair, otherwise its head probability is 3/4. Two tosses of that same coin are conditionally independent. Given two heads, find the probability that the selected coin is the fair one.",
    ["P(fair and HH) = (1/2)(1/2)² = 1/8.", "P(HH) = 1/8 + (1/2)(3/4)² = 13/32.", "P(fair|HH) = (1/8)/(13/32) = 4/13."],
    "The two heads have probability 1/4 given the fair coin and 9/16 given the biased coin. Weighting each by 1/2 gives total 13/32; the fair contribution is 4/32. Thus the posterior probability is 4/13."),
  q("maths", "conditional-probability", 1, "selection-protocol", "transfer", "information-protocol", "account for a reporting rule when reconstructing conditional outcomes",
    "A box contains two cards, each independently red or blue with probability 1/2. An operator selects one of the two cards uniformly and reports its colour, without showing it. The report is red. Find the probability both cards are red, and explain why this differs from merely knowing that at least one is red.",
    ["P(both red and red report) = 1/4.", "P(red report) = 1/2, so P(both red|red report) = 1/2.", "A mixed pair produces a red report only half the time; the report protocol weights pairs differently from an at-least-one condition."],
    "RR always reports red, while RB and BR do so with probability 1/2 each. The total red-report probability is 1/4 + 1/8 + 1/8 = 1/2. The RR share is 1/2, not the 1/3 obtained by conditioning only on at least one red card."),
  q("maths", "conditional-probability", 1, "conditional-binomial", "synoptic", "count-distribution", "condition a count distribution after excluding its zero outcome",
    "Three independent components each fail with probability 0.10. Given that at least one fails, find the probability exactly one fails. Show the unconditional probabilities used.",
    ["P(exactly one) = 3(0.10)(0.90)² = 0.243.", "P(at least one) = 1 - 0.90³ = 0.271.", "The conditional probability is 243/271, approximately 0.897."],
    "Let X be the failure count. P(X = 1) = 0.243 and P(X ≥ 1) = 0.271. Since X = 1 implies X ≥ 1, the answer is their ratio, 243/271."),
  q("maths", "conditional-probability", 1, "pooled-association", "synoptic", "stratified-conditioning", "compare conditional rates within strata and after pooling",
    "Of applicants for a demanding course, A has 8 successes from 20 and B has 45 from 100. For an easier course, A has 72 from 80 and B has 19 from 20. Compare the success probabilities for A and B within each course and overall. Explain why the overall ranking reverses.",
    ["Demanding: A = 0.40, B = 0.45; easier: A = 0.90, B = 0.95, so B is higher in both.", "Overall: A = 80/100 = 0.80, B = 64/120 = 8/15, approximately 0.533.", "A's applications are concentrated in the easier course; different course weights change the pooled comparison."],
    "B has the higher conditional success probability in each course, but A's overall probability is 0.80 versus B's 0.533. The mixture weights differ: 80% of A's applications are for the easier course, compared with 1/6 of B's. Pooling conceals that condition."),
];
