import { qualityItem as q } from "./wjec-quality-authoring";

export const wjecChemistryQualityQuestions = [
  q("chemistry", "moles", 6, "equivalence-ratio", "recall", "balanced-ratio", "recall the general stoichiometric relation at equivalence",
    "For a titration reaction aA + bB → products, state the relation between the reacting amounts n(A) and n(B) at equivalence. State why equal amounts of A and B cannot be assumed.",
    ["n(A)/a = n(B)/b, or an equivalent coefficient-ratio relation.", "The balanced coefficients need not be equal."],
    "At equivalence the reacting amounts satisfy n(A):n(B) = a:b. Equal amounts apply only when the stoichiometric ratio is 1:1."),
  q("chemistry", "moles", 6, "aliquot-factor", "recall", "aliquot-scaling", "identify the fraction sampled from a homogeneous solution",
    "A solid is dissolved and made up to 250.0 cm³. A 25.00 cm³ aliquot is titrated. State the factor relating the amount of analyte in the whole flask to that in the aliquot, and the assumption needed.",
    ["Whole-flask amount is ten times the aliquot amount.", "The solution is homogeneous and fully mixed, with the analyte completely dissolved."],
    "Multiply the aliquot amount by 250.0/25.00 = 10. This requires a homogeneous solution containing all the dissolved analyte."),
  q("chemistry", "moles", 6, "wet-pipette", "explanation", "apparatus-bias", "trace an apparatus dilution error through inferred concentration",
    "A pipette used to transfer an unknown alkali is rinsed only with water, leaving droplets inside. Acid of known concentration is then used to titrate the transferred sample. Explain the likely effect on the inferred concentration of the original alkali.",
    ["Residual water dilutes the alkali in the pipette, so fewer moles are delivered in the nominal volume.", "A smaller acid titre is needed.", "Using the nominal aliquot volume leads to an underestimate of the original alkali concentration."],
    "Water in the pipette reduces the alkali concentration of the delivered sample. Less acid is needed, so the calculated concentration is too low for the original stock. Rinsing with the solution to be transferred avoids this dilution."),
  q("chemistry", "moles", 6, "flask-water", "explanation", "amount-conservation", "distinguish dilution of the reaction flask from dilution of the measured aliquot",
    "After a measured acid aliquot is placed in a conical flask, distilled water is added before titration with alkali. Explain why this need not change the equivalence titre, although the acid concentration in the flask falls.",
    ["Adding water does not change the amount in moles of acid already transferred.", "The stoichiometric amount of alkali required is therefore unchanged, assuming no interfering reaction and reliable endpoint detection."],
    "The water increases volume but leaves the acid amount unchanged. Equivalence depends on reacting moles, so the required alkali titre is unchanged under the stated conditions."),
  q("chemistry", "moles", 6, "vinegar-dilution", "application", "aliquot-scaling", "recover a stock concentration after volumetric dilution",
    "10.00 cm³ of a monoprotic acid stock is diluted to 100.0 cm³. A 25.00 cm³ aliquot of the diluted solution requires 20.00 cm³ of 0.1000 mol dm^-3 NaOH. Acid and NaOH react 1:1. Find the stock concentration.",
    ["The aliquot contains 0.1000 × 0.02000 = 0.002000 mol acid.", "Diluted acid concentration = 0.002000/0.02500 = 0.08000 mol dm^-3.", "The tenfold dilution gives stock concentration 0.8000 mol dm^-3; allow consistent ratio follow-through."],
    "The aliquot contains 0.002000 mol. Its concentration is 0.08000 mol dm^-3. The original stock was diluted by a factor of ten, so its concentration was 0.8000 mol dm^-3."),
  q("chemistry", "moles", 6, "mixed-alkali", "application", "two-endpoints", "solve two stoichiometric constraints for a mixture",
    "An aliquot contains only NaOH and Na₂CO₃ as bases. At the first endpoint, added HCl neutralises all OH- and converts CO₃²- to HCO₃-; 15.00 cm³ of 0.1000 mol dm^-3 HCl is used. Complete neutralisation needs a further 5.00 cm³. Find the amounts of NaOH and Na₂CO₃ in the aliquot.",
    ["The second stage uses one further H+ per carbonate: n(Na₂CO₃) = 0.1000 × 0.00500 = 0.000500 mol.", "First-stage acid amount = n(NaOH) + n(Na₂CO₃) = 0.001500 mol.", "n(NaOH) = 0.001500 - 0.000500 = 0.001000 mol."],
    "The extra 0.000500 mol acid converts bicarbonate to carbon dioxide and water, identifying 0.000500 mol original carbonate. Subtract this from the first-stage 0.001500 mol acid to obtain 0.001000 mol NaOH."),
  q("chemistry", "moles", 6, "volume-conversion-error", "misconception", "dimensional-conversion", "locate a factor-of-one-thousand error before a mole ratio",
    "A student calculates the NaOH amount in 20.0 cm³ of 0.150 mol dm^-3 solution as 0.150 × 20.0 = 3.00 mol. Identify the first error, correct the amount, and state the H₂SO₄ amount that would neutralise it. H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O.",
    ["Volume must be converted to 0.0200 dm³ before using n = cV.", "n(NaOH) = 0.00300 mol.", "n(H₂SO₄) = 0.00150 mol; allow follow-through with the correct 1:2 ratio after a stated amount."],
    "The first error is the incompatible volume unit. Correcting it gives 0.150 × 0.0200 = 0.00300 mol NaOH. Half that amount of sulfuric acid is required: 0.00150 mol."),
  q("chemistry", "moles", 6, "equal-titres-not-concentrations", "misconception", "balanced-ratio", "reject an equality of concentrations inferred from equal volumes",
    "Equal volumes of HCl and Ca(OH)₂ solutions neutralise exactly. A student concludes their concentrations are equal. Use Ca(OH)₂ + 2HCl → CaCl₂ + 2H₂O to correct the conclusion.",
    ["Two moles of HCl react per mole of Ca(OH)₂.", "With equal volumes, c(HCl) = 2c(Ca(OH)₂), not equal concentrations."],
    "The reaction consumes HCl and calcium hydroxide in a 2:1 mole ratio. Equal volumes therefore require the HCl concentration to be twice the Ca(OH)₂ concentration."),
  q("chemistry", "moles", 6, "hydrate-assay", "calculation", "hydrate-composition", "combine aliquot stoichiometry with mass balance for hydration",
    "1.430 g of pure Na₂CO₃·xH₂O is dissolved and made up to 250.0 cm³. A 25.00 cm³ aliquot needs 10.00 cm³ of 0.1000 mol dm^-3 HCl for complete reaction. Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂. Use M(Na₂CO₃) = 106.0 and M(H₂O) = 18.0 g mol^-1 to find x.",
    ["Aliquot carbonate amount = (0.1000 × 0.01000)/2 = 0.0005000 mol; whole flask contains 0.005000 mol.", "Anhydrous carbonate mass = 0.005000 × 106.0 = 0.5300 g.", "Water mass = 0.9000 g, giving 0.05000 mol water.", "x = 0.05000/0.005000 = 10."],
    "The acid identifies 0.005000 mol carbonate in the full flask, accounting for 0.5300 g. The remaining 0.9000 g is 0.05000 mol water. The water:carbonate ratio is 10:1, so x = 10."),
  q("chemistry", "moles", 6, "concordant-selection", "calculation", "titre-selection", "select valid concordant data before a concentration calculation",
    "For a 25.00 cm³ monoprotic acid aliquot, a rough NaOH titre is 21.30 cm³. Accurate titres are 20.10, 20.05 and 20.15 cm³. The protocol averages accurate titres agreeing within 0.10 cm³. NaOH is 0.1000 mol dm^-3 and reacts 1:1. Calculate the acid concentration to four significant figures.",
    ["Exclude the rough titre; mean accurate titre = 20.10 cm³.", "Acid amount = 0.1000 × 0.02010 = 0.002010 mol.", "Acid concentration = 0.002010/0.02500 = 0.08040 mol dm^-3."],
    "The three accurate titres span 0.10 cm³ and average 20.10 cm³. Their mean corresponds to 0.002010 mol NaOH and acid. Dividing by 0.02500 dm³ gives 0.08040 mol dm^-3."),
  q("chemistry", "moles", 6, "unknown-redox-ratio", "transfer", "electron-balance", "derive a titration ratio from electrons rather than assume acid-base stoichiometry",
    "In an unfamiliar redox assay, each X ion loses three electrons and each Y ion gains two. A 25.00 cm³ X sample requires 15.00 cm³ of 0.02000 mol dm^-3 Y. Calculate c(X), assuming no other species reacts.",
    ["Electron balance gives 2X per 3Y.", "n(Y) = 0.0003000 mol, hence n(X) = (2/3)n(Y) = 0.0002000 mol.", "c(X) = 0.0002000/0.02500 = 0.008000 mol dm^-3."],
    "Six electrons are transferred by two X ions and accepted by three Y ions. The 0.0003000 mol Y therefore reacts with 0.0002000 mol X, giving c(X) = 0.008000 mol dm^-3."),
  q("chemistry", "moles", 6, "limestone-purity", "transfer", "back-titration", "subtract residual reagent before applying analyte stoichiometry",
    "A 0.500 g sample of CaCO₃ and inert filler reacts with 50.00 cm³ of 0.2000 mol dm^-3 HCl. Remaining acid requires 20.00 cm³ of 0.1000 mol dm^-3 NaOH. CaCO₃ uses two HCl per formula unit; HCl and NaOH react 1:1. With M(CaCO₃) = 100.0 g mol^-1, calculate percentage purity.",
    ["Initial acid = 0.01000 mol; remaining acid = 0.002000 mol.", "Acid consumed = 0.008000 mol, hence carbonate = 0.004000 mol.", "Carbonate mass = 0.4000 g; purity = (0.4000/0.500) × 100 = 80.0%."],
    "Subtract the residual acid, rather than treating all added acid as reacted. This leaves 0.008000 mol HCl consumed, equivalent to 0.004000 mol or 0.4000 g CaCO₃. The sample is 80.0% carbonate by mass."),
  q("chemistry", "moles", 6, "uncertainty-follow-through", "synoptic", "measurement-uncertainty", "combine relative volume uncertainties for a titration ratio",
    "A 1:1 titration calculates c_unknown = c_standard V_titre/V_aliquot. V_titre = 20.00 cm³, from two burette readings each with absolute uncertainty 0.05 cm³. V_aliquot = 25.00 ± 0.06 cm³. Treat c_standard as exact and add absolute uncertainties for subtraction, then percentage uncertainties for division. Find the percentage uncertainty in c_unknown.",
    ["Titre absolute uncertainty = 0.10 cm³, so percentage uncertainty = 0.50%.", "Aliquot percentage uncertainty = (0.06/25.00) × 100 = 0.24%.", "Combined percentage uncertainty = 0.74%; this is the specified worst-case addition convention."],
    "Two readings make the titre uncertainty 0.10 cm³, or 0.50%. The aliquot contributes 0.24%. Adding these relative uncertainties gives 0.74% under the specified convention."),
  q("chemistry", "moles", 6, "gas-cross-check", "synoptic", "independent-mass-balance", "compare a titration-derived amount with an independent gas yield",
    "A carbonate sample consumes 0.00600 mol HCl according to a back titration. Its reaction produces one CO₂ per carbonate and consumes two HCl. A separate gas measurement gives 60.0 cm³ CO₂. At these conditions one mole of gas occupies 24.0 dm³. Calculate the expected gas volume and suggest one experimental explanation for the discrepancy.",
    ["Carbonate and expected CO₂ amounts are 0.00300 mol.", "Expected volume = 0.00300 × 24.0 = 0.0720 dm³ = 72.0 cm³.", "Measured volume is lower; accept CO₂ dissolution, leakage or incomplete gas collection, with a directional explanation."],
    "The titration predicts 0.00300 mol CO₂, corresponding to 72.0 cm³. The measured 60.0 cm³ is smaller. Some CO₂ could have dissolved or escaped collection, reducing recorded gas volume without requiring a different reaction ratio."),

  q("chemistry", "equilibria", 3, "kc-expression", "recall", "equilibrium-expression", "write an expression with stoichiometric powers",
    "For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), write Kc using concentrations in mol dm^-3 and give its units under this concentration convention.",
    ["Kc = [NH₃]²/([N₂][H₂]³).", "Units are dm^6 mol^-2."],
    "Kc is [NH₃]² divided by [N₂][H₂]³. The concentration power is 2 - 4 = -2, giving dm^6 mol^-2."),
  q("chemistry", "equilibria", 3, "partial-pressure", "recall", "partial-pressure-conversion", "recall how mole fraction determines a partial pressure",
    "State how to calculate a gas's partial pressure from its mole fraction and the total pressure of an ideal-gas mixture. State which composition must be used when calculating Kp.",
    ["Partial pressure equals mole fraction multiplied by total pressure.", "Use the equilibrium composition."],
    "p_i = x_i P_total, where x_i is the gas's mole fraction. Kp requires the partial pressures at equilibrium, not the initial mixture."),
  q("chemistry", "equilibria", 3, "catalyst-k", "explanation", "kinetics-versus-equilibrium", "separate faster equilibration from a changed equilibrium ratio",
    "A catalyst is added to a reacting mixture held at constant temperature. Explain why equilibrium is reached sooner but the measured Kc does not change.",
    ["The catalyst provides a pathway with lower activation energy for forward and reverse reactions.", "It changes the approach to equilibrium without changing the equilibrium composition at fixed temperature.", "Kc depends on temperature for the given reaction, not on the catalyst."],
    "Both directions can proceed faster through the catalysed pathway. The final equilibrium ratio remains the same at fixed temperature, so Kc is unchanged even though it is reached sooner."),
  q("chemistry", "equilibria", 3, "volume-cancellation", "explanation", "concentration-volume", "determine when vessel volume cancels from a mole-based expression",
    "For A(g) + B(g) ⇌ C(g), a student substitutes equilibrium mole amounts directly into Kc as n(C)/(n(A)n(B)). Explain the missing factor for a vessel of volume V dm³.",
    ["Each concentration is its amount divided by V.", "Kc = (n(C)/V)/[(n(A)/V)(n(B)/V)] = V n(C)/(n(A)n(B)).", "Volume does not cancel because the total stoichiometric powers differ between numerator and denominator."],
    "There is one concentration factor above and two below. Substituting n/V leaves one factor of V in the numerator: Kc = V n(C)/(n(A)n(B)). Mole amounts alone are insufficient."),
  q("chemistry", "equilibria", 3, "compression-quotient", "application", "reaction-quotient", "predict direction from the immediate change in a reaction quotient",
    "For A(g) ⇌ 2B(g), a mixture is initially at equilibrium. It is suddenly compressed to half its volume at unchanged temperature. Define Qc = [B]²/[A]. Compare Qc immediately after compression with Kc and predict the subsequent net reaction.",
    ["Both concentrations initially double, so Qc becomes (2²/2)Kc = 2Kc.", "Qc exceeds Kc; the net reaction consumes B and forms A until equilibrium is restored."],
    "Before composition can change, concentrations double and Qc doubles. The ratio is too large, so the net reaction goes towards A, the side with fewer gas particles."),
  q("chemistry", "equilibria", 3, "temperature-data", "application", "temperature-dependence", "infer reaction enthalpy sign from equilibrium-constant data",
    "For a particular reaction Kc is 2.0 at 300 K and 8.0 at 350 K. Infer the sign of the forward reaction's enthalpy change and predict how cooling affects its equilibrium product proportion. No phase changes occur.",
    ["Kc increases on heating, so higher temperature favours products and the forward reaction is endothermic.", "Cooling favours the reverse direction, reducing the equilibrium product proportion under otherwise fixed conditions."],
    "Heating increases the product-to-reactant equilibrium ratio, consistent with an endothermic forward reaction. Cooling favours reactants and reduces the equilibrium product proportion."),
  q("chemistry", "equilibria", 3, "reverse-equation", "misconception", "equation-rescaling", "change the equilibrium constant when the reaction is reversed and scaled",
    "At a fixed temperature Kc = 9.0 for A ⇌ 2B. A student uses 9.0 for B ⇌ 0.5A. Find the appropriate Kc and explain both equation changes.",
    ["Reversing A ⇌ 2B gives a reciprocal constant, 1/9.", "Halving all coefficients takes the square root, giving Kc = 1/3; accept 0.33."],
    "First reverse the reaction, giving 1/9 for 2B ⇌ A. Then halve its coefficients, giving (1/9)^(1/2) = 1/3 for B ⇌ 0.5A."),
  q("chemistry", "equilibria", 3, "large-k-fast", "misconception", "kinetics-versus-equilibrium", "reject a rate conclusion drawn from equilibrium favourability",
    "A reaction has Kc = 10^8 at room temperature. A student concludes that it must finish almost instantly. Evaluate the claim, distinguishing equilibrium composition from reaction rate.",
    ["A large Kc indicates a product-favoured equilibrium for the stated expression.", "It does not specify how quickly equilibrium is reached; a large activation barrier can make the reaction slow."],
    "The constant describes the equilibrium ratio, not the time needed to achieve it. A product-favoured reaction may still be extremely slow if its activation barrier is large."),
  q("chemistry", "equilibria", 3, "kc-from-moles", "calculation", "concentration-volume", "convert amounts in a finite vessel before evaluating Kc",
    "At equilibrium in a 2.00 dm³ vessel, A(g) + B(g) ⇌ C(g) has 0.400 mol A, 0.200 mol B and 0.600 mol C. Calculate Kc with units.",
    ["[A] = 0.200, [B] = 0.100 and [C] = 0.300 mol dm^-3.", "Kc = [C]/([A][B]) = 0.300/(0.200 × 0.100).", "Kc = 15.0 dm³ mol^-1."],
    "Dividing amounts by 2.00 dm³ gives 0.200, 0.100 and 0.300 mol dm^-3. Their equilibrium ratio is 15.0 dm³ mol^-1. Substituting amounts without volume would incorrectly give 7.50."),
  q("chemistry", "equilibria", 3, "kp-mixture", "calculation", "partial-pressure-conversion", "calculate pressure-based equilibrium ratio from composition",
    "For N₂O₄(g) ⇌ 2NO₂(g), an equilibrium mixture contains 0.40 mol N₂O₄ and 0.60 mol NO₂ at total pressure 200 kPa. Calculate Kp, using partial pressures in kPa.",
    ["Partial pressures are 80 kPa for N₂O₄ and 120 kPa for NO₂.", "Kp = p(NO₂)²/p(N₂O₄).", "Kp = 120²/80 = 180 kPa."],
    "The total amount is 1.00 mol, so the partial pressures are 0.40 × 200 = 80 kPa and 0.60 × 200 = 120 kPa. Kp = 180 kPa under this pressure convention."),
  q("chemistry", "equilibria", 3, "dissociation-fraction", "transfer", "extent-total-pressure", "track changing total moles when expressing dissociation in terms of alpha",
    "Initially one mole of A(g) is placed in a vessel. It dissociates as A(g) ⇌ 2B(g). A fraction α has dissociated at equilibrium, where total pressure is P. Derive Kp in terms of α and P for an ideal-gas mixture.",
    ["Equilibrium amounts are 1 - α of A and 2α of B, with total 1 + α.", "p(A) = P(1 - α)/(1 + α) and p(B) = P(2α)/(1 + α).", "Kp = p(B)²/p(A) = 4α²P/(1 - α²)."],
    "Dissociation changes the total amount, so mole fractions must use 1 + α. Substituting the partial pressures into p(B)²/p(A) gives 4α²P/[(1 + α)(1 - α)] = 4α²P/(1 - α²)."),
  q("chemistry", "equilibria", 3, "equilibrium-root", "transfer", "extent-root-selection", "solve an equilibrium amount while rejecting an unphysical algebraic root",
    "For A(aq) + B(aq) ⇌ C(aq), initially [A] = [B] = 1.00 mol dm^-3 and [C] = 0. At this temperature Kc = 2.00 dm³ mol^-1. Volume is constant. Find equilibrium [C] and explain why any second algebraic solution is rejected.",
    ["With [C] = x, [A] = [B] = 1 - x and x/(1 - x)² = 2.", "2x² - 5x + 2 = 0 gives x = 0.50 or 2.0.", "Reject x = 2.0 because it gives negative reactant concentrations; [C] = 0.50 mol dm^-3."],
    "The reaction extent x consumes one concentration unit of each reactant per unit product. Solving 2(1 - x)² = x gives roots 0.50 and 2.0. Only 0 ≤ x ≤ 1 is physically allowed, so [C] = 0.50 mol dm^-3."),
  q("chemistry", "equilibria", 3, "ester-titration", "synoptic", "assay-equilibrium", "use an equilibrium assay to reconstruct all reaction amounts",
    "An idealised esterification starts with 1.00 mol acid and 1.00 mol alcohol, with no ester or water. At equilibrium a titration, corrected for catalyst acidity, shows 0.400 mol acid remains in the whole mixture. The reaction is acid + alcohol ⇌ ester + water. Assuming the concentration model and constant volume, calculate Kc.",
    ["The reacted amount is 0.600 mol, leaving 0.400 mol alcohol and forming 0.600 mol each of ester and water.", "Kc = [ester][water]/([acid][alcohol]); equal total concentration powers cancel volume.", "Kc = (0.600 × 0.600)/(0.400 × 0.400) = 2.25, dimensionless under this convention."],
    "Stoichiometry gives equilibrium amounts 0.400, 0.400, 0.600 and 0.600 mol. In this idealised concentration model, vessel volume cancels from Kc, leaving 2.25. Uncorrected catalyst acidity would bias the inferred acid amount."),
  q("chemistry", "equilibria", 3, "inert-gas-constraints", "synoptic", "constraint-sensitive-dilution", "distinguish fixed-volume and fixed-pressure addition of an inert gas",
    "For A(g) ⇌ 2B(g), compare adding an inert gas at constant temperature in two cases: a rigid vessel and a piston maintaining constant total pressure. Assume ideal gases and no chemical interaction with the inert gas. Explain the equilibrium effect in each case using partial pressures.",
    ["In the rigid vessel, reacting amounts, temperature and volume initially stay fixed, so their partial pressures and Qp stay unchanged: no shift.", "At constant total pressure the piston expands; both reacting partial pressures fall by a common factor f < 1.", "Qp = p(B)²/p(A) then becomes fKp < Kp, so net reaction forms more B."],
    "At fixed volume, adding inert gas raises total pressure but does not alter the reacting gases' partial pressures. At fixed total pressure, expansion dilutes them: Qp scales by f because its numerator has one extra pressure power. Qp falls below Kp, so dissociation towards B restores equilibrium."),
];
