import type { LearningDemand } from "@/domain/types";
import { defineQuestion, type PartSpec } from "./authoring";

const SUBJECT = "wjec-alevel-physics";
const sp = (topic: string, point: number) => `${SUBJECT}.${topic}.sp-${String(point).padStart(2, "0")}`;

/**
 * Replacement for the retired 1,512-row template inventory. These are original
 * AI-drafted questions, NOT WJEC questions or human-approved content. Each item
 * supplies the actual observations/data needed to solve it. New ids prevent
 * an old attempt being reinterpreted against a different question.
 * Mapping is to internal curriculum claims; exact board references need review.
 */
interface DeepMove {
  move: string;
}

function item(slug: string, topic: string, point: number, demand: LearningDemand,
  prompt: string, scheme: string[], answer: string, capability?: string,
  extraParts: PartSpec[] = [], moves: DeepMove[] = []) {
  const specId = sp(topic, point);
  const parts: PartSpec[] = [{
    prompt, marks: scheme.length, scheme, answer,
    aos: demand === "recall" ? ["AO1"] : ["transfer", "synoptic"].includes(demand) ? ["AO2", "AO3"] : ["AO2"],
    specPointIds: [specId],
    capabilityIds: [capability ?? `phys.${topic}.sp-${String(point).padStart(2, "0")}`],
  }, ...extraParts];
  const familyId = `physics-quality:${slug}`;
  const defaultMove = AUTHORED_MOVES[slug];
  const moveFor = (index: number): string =>
    moves[index]?.move ?? (index === 0 ? defaultMove : `${AUTHORED_MOVES[slug] ?? "solve the stated physical problem"} (follow-on part)`);
  const annotatedParts = parts.map((part, index) => ({
    ...part,
    learning: part.learning ?? {
      familyId,
      contextId: `${slug}:context-${index + 1}`,
      demand,
      reasoningMoves: [moveFor(index)],
    },
  }));
  return defineQuestion({
    slug: `physics-quality-${slug}`, subjectId: SUBJECT,
    topics: [...new Set([topic, ...extraParts.flatMap((part) => (part.specPointIds ?? []).map((id) => id.split(".").at(-2)!))])],
    kind: extraParts.length ? "structured" : demand === "calculation" ? "calculation" : "short",
    stem: extraParts.length ? "Answer each part. Show your reasoning and numerical working." : prompt,
    parts: annotatedParts, difficulty: ["transfer", "synoptic"].includes(demand) ? 4 : demand === "recall" ? 1 : 3,
    source: "generated", verification: "unverified", reviewer: null, lastChecked: null,
    learning: { demand, familyId: `physics-quality:${slug}`, contextId: slug,
      expectedMinutes: Math.max(1, parts.reduce((sum, part) => sum + part.marks, 0) * 1.5) },
  });
}

/**
 * Authored reasoning move per item: the named cognitive operation the part
 * actually requires. Never the demand category — that would be filler and the
 * quality audit rejects it.
 */
const AUTHORED_MOVES: Record<string, string> = {
  "acceleration-definition": "state a rate-of-change definition and its derived SI unit",
  "parachute-opening": "rebalance drag against weight while tracking the sign of acceleration through a speed change",
  "lift-force-probe": "apply Newton's second law with consistent sign convention before substituting",
  "book-third-law": "separate forces on one body from interaction pairs across two bodies",
  "signed-motion-area": "compute signed area for displacement and sum magnitudes for distance on a split-velocity graph",
  "asteroid-sample-brake": "chain force to acceleration to velocity and test the sign before concluding on direction",
  "runaway-trolley": "track mechanical energy across a dissipative segment and justify which store gains the loss",
  "young-modulus-definition": "chain stress, strain and modulus definitions in the proportional region",
  "wire-diameter-effect": "scale a squared-geometry quantity before applying a material law",
  "spring-zero-offset": "convert loaded length to extension before applying Hooke's law",
  "elastic-nonlinear": "separate elasticity (recovery) from proportionality (Hooke's law)",
  "nonlinear-spring-work": "integrate a piecewise-linear force-extension graph as triangle plus trapezium",
  "tendon-energy": "account for dissipated fraction of stored strain energy on unloading",
  "spring-launch": "transfer stored elastic energy to kinetic energy minus a stated dissipation",
  "coherence-meaning": "state the two-source conditions that keep phase difference fixed",
  "refraction-frequency": "hold the source-fixed quantity constant while speed changes",
  "string-third-harmonic": "count loops as half-wavelengths before applying v = fλ",
  "tir-direction": "check the direction of travel across the boundary before applying the critical-angle condition",
  "grating-wavelength": "invert the grating equation for line density and bound the visible order",
  "noise-cancellation-seat": "convert path difference into a phase relationship and predict interference",
  "grating-photon": "chain a wave-optics result into a photon-energy calculation",
  "work-function": "state the minimum escape energy for a surface electron",
  "threshold-darkness": "apply one-photon-one-electron energy accounting under fixed frequency",
  "stopping-potential-change": "convert maximum kinetic energy changes into stopping-potential differences",
  "brighter-photoelectric": "separate photon energy from photon rate when intensity changes",
  "photoelectron-energy": "apply the photoelectric energy balance with consistent units",
  "uv-surface-sensor": "bracket a threshold between two photon energies to select a coating",
  "electron-diffraction-voltage": "chain energy to momentum to wavelength through a parameter change",
  "emf-definition": "define emf as energy supplied per unit charge by the source",
  "lamp-non-ohmic": "link temperature-dependent scattering to a changing resistance",
  "loaded-divider": "combine parallel resistances before applying the divider ratio",
  "current-used-up": "apply charge conservation to steady series current",
  "cell-internal-resistance": "read emf and internal resistance from a V-I line's intercept and gradient",
  "cold-room-alarm": "predict the sensor direction from the divider ratio change",
  "heater-water": "chain electrical power to thermal energy with a stated efficiency",
  "magnetic-no-work": "use the force-velocity angle to decide work done on kinetic energy",
  "orbit-height-trap": "measure field distance from the centre before applying an inverse-square law",
  "coil-flux-rate": "scale per-turn flux change by turns before dividing by time",
  "mass-spectrometer-ratio": "form a path-radius proportionality in m/q at fixed speed and field",
  "gas-temperature-trap": "convert Celsius to absolute temperature before ratio reasoning",
  "molecular-energy": "invert the mean-energy relation for temperature and scale to a mole",
  "background-decay": "count elapsed half-lives from a decay factor and extrapolate one more",
  "decay-randomness": "distinguish per-nucleus randomness from population halving",
  "rebound-impulse": "reverse one velocity sign before computing momentum change",
  "airbag-force": "separate impulse (fixed) from average force (time-dependent) and name the missing information",
  "shm-sign": "check the direction of acceleration relative to displacement, not only proportionality",
  "shm-period-from-gradient": "read ω² from a gradient and invert to a period",
};

export const wjecPhysicsDeepQuestions = [
  item("acceleration-definition", "kinematics-dynamics", 5, "recall",
    "Define acceleration. State its SI unit.",
    ["Rate of change of velocity.", "m s^-2."],
    "Acceleration is the rate of change of velocity with time. Its SI unit is m s^-2."),
  item("parachute-opening", "kinematics-dynamics", 7, "explanation",
    "A skydiver falls at constant speed before opening a parachute. Immediately after it opens, air resistance is greater than weight. Explain the direction of acceleration and how a new terminal speed is reached.",
    ["The resultant force and acceleration are upward.", "As downward speed decreases, air resistance decreases.", "At the new terminal speed air resistance equals weight, so acceleration is zero."],
    "The resultant force and acceleration are upward, opposing the downward velocity. As downward speed decreases, air resistance decreases. At the new terminal speed air resistance equals weight, so acceleration is zero.", "phys.drag"),
  item("lift-force-probe", "kinematics-dynamics", 4, "application",
    "A lift of mass 600 kg accelerates upward at 0.80 m s^-2. Take g = 9.81 m s^-2. Calculate the cable tension. Neglect other forces.",
    ["T - mg = ma.", "T = 600(9.81 + 0.80) = 6366 N."],
    "Choose upward as positive. T - mg = ma. Hence T = 600(9.81 + 0.80) = 6366 N, approximately 6.4 kN.", "phys.acceleration"),
  item("book-third-law", "kinematics-dynamics", 4, "misconception",
    "A student says the weight of a stationary book and the upward force from a table are a Newton's third-law pair because they are equal and opposite. Explain the error and identify the third-law partner of the table's force on the book.",
    ["Third-law forces act on different bodies; both named forces act on the book.", "The partner is the downward contact force exerted by the book on the table."],
    "Third-law forces act on different bodies; both named forces act on the book. The partner of the table's force is the downward contact force exerted by the book on the table.", "phys.third-law"),
  item("signed-motion-area", "kinematics-dynamics", 2, "calculation",
    "A trolley has velocity +4.0 m s^-1 for 3.0 s and then -2.0 m s^-1 for 2.0 s. Ignore the short reversal interval. Calculate its displacement and total distance travelled.",
    ["Displacement is signed area: 4.0 x 3.0 - 2.0 x 2.0.", "Displacement = +8.0 m.", "Distance = 12.0 + 4.0 = 16.0 m."],
    "Displacement is signed area: 4.0 x 3.0 - 2.0 x 2.0 = +8.0 m. Distance adds the magnitudes: 12.0 + 4.0 = 16.0 m."),
  item("asteroid-sample-brake", "kinematics-dynamics", 4, "transfer",
    "A sample capsule of mass 0.40 kg moves at +6.0 m s^-1 beside an asteroid. A thruster exerts a constant force of -0.80 N for 2.0 s. Other forces are negligible. Determine the final velocity and explain whether the capsule reverses direction.",
    ["a = -0.80 / 0.40 = -2.0 m s^-2.", "v = 6.0 + (-2.0 x 2.0) = +2.0 m s^-1.", "The capsule has not reversed because the final velocity remains positive."],
    "a = -0.80 / 0.40 = -2.0 m s^-2. v = 6.0 + (-2.0 x 2.0) = +2.0 m s^-1. The capsule has not reversed because the final velocity remains positive.", "phys.acceleration"),
  item("runaway-trolley", "energy-power", 6, "synoptic",
    "A 20 kg trolley starts from rest and descends through a vertical height of 1.5 m. It then crosses 4.0 m of rough horizontal track with a constant resisting force of 30 N. Neglect resistance on the slope. Take g = 9.81 m s^-2. Calculate its speed after the rough track and explain why conserving kinetic plus gravitational potential energy throughout would give the wrong answer.",
    ["Initial gravitational energy = mgh = 294.3 J.", "Work against resistance = 30 x 4.0 = 120 J.", "Final kinetic energy = 174.3 J.", "Speed = sqrt(2 x 174.3 / 20) = 4.17 m s^-1.", "Friction transfers mechanical energy to internal energy."],
    "Initial gravitational energy = mgh = 294.3 J. Work against resistance = 30 x 4.0 = 120 J. Final kinetic energy = 174.3 J. Speed = sqrt(2 x 174.3 / 20) = 4.17 m s^-1. Friction transfers mechanical energy to internal energy; mechanical energy alone is not conserved."),

  item("young-modulus-definition", "materials", 1, "recall",
    "Define tensile stress and tensile strain. Use them to define Young modulus in the proportional region.",
    ["Stress is tensile force divided by original cross-sectional area.", "Strain is extension divided by original length.", "Young modulus is stress divided by strain in the proportional region."],
    "Stress is tensile force divided by original cross-sectional area. Strain is extension divided by original length. Young modulus is stress divided by strain in the proportional region."),
  item("wire-diameter-effect", "materials", 1, "explanation",
    "Two wires have the same material and original length. Wire B has twice the diameter of wire A. Explain why B extends one quarter as much under the same small tensile load.",
    ["Cross-sectional area is proportional to diameter squared, so B has four times the area.", "At equal force B has one quarter of the stress.", "Equal Young modulus gives one quarter of the strain and hence extension."],
    "Cross-sectional area is proportional to diameter squared, so B has four times the area. At equal force B has one quarter of the stress. Equal Young modulus gives one quarter of the strain and hence extension."),
  item("spring-zero-offset", "materials", 2, "application",
    "A spring has length 120 mm with no load and 156 mm with a 9.0 N load, within its proportional limit. Calculate its spring constant. State why using 156 mm as the extension is incorrect.",
    ["Extension = 156 - 120 = 36 mm = 0.036 m.", "k = 9.0 / 0.036 = 250 N m^-1.", "Extension is the change in length, not the loaded length."],
    "Extension = 156 - 120 = 36 mm = 0.036 m. k = 9.0 / 0.036 = 250 N m^-1. Extension is the change in length, not the loaded length."),
  item("elastic-nonlinear", "materials", 3, "misconception",
    "A polymer returns to its original length after unloading, but its loading force-extension graph is curved. A student says it cannot be elastic because it does not obey Hooke's law. Evaluate this claim.",
    ["Elastic behaviour means returning to the original dimensions on unloading.", "Hooke's law additionally requires force proportional to extension.", "A material can be elastic without obeying Hooke's law."],
    "Elastic behaviour means returning to the original dimensions on unloading. Hooke's law additionally requires force proportional to extension. A material can be elastic without obeying Hooke's law."),
  item("nonlinear-spring-work", "materials", 4, "calculation",
    "A force-extension graph consists of straight segments joining (0 mm, 0 N), (20 mm, 8.0 N), and (50 mm, 14 N). Calculate the work done stretching from 0 to 50 mm.",
    ["Work is area under the force-extension graph.", "First triangle = 0.5 x 8.0 x 0.020 = 0.080 J.", "Trapezium = 0.5 x (8.0 + 14) x 0.030 = 0.330 J.", "Total work = 0.410 J."],
    "Work is area under the force-extension graph. First triangle = 0.5 x 8.0 x 0.020 = 0.080 J. Trapezium = 0.5 x (8.0 + 14) x 0.030 = 0.330 J. Total work = 0.410 J."),
  item("tendon-energy", "materials", 4, "transfer",
    "A simplified tendon model has a straight loading graph from (extension 0, force 0) to (extension 0.012 m, force 180 N). On unloading, 25% of the input energy is dissipated. Calculate the energy returned to the runner. Explain why force times maximum extension overestimates the input energy.",
    ["Input energy = 0.5 x 180 x 0.012 = 1.08 J.", "Returned energy = 0.75 x 1.08 = 0.81 J.", "The force increases from zero, so its mean is half its maximum."],
    "Input energy = 0.5 x 180 x 0.012 = 1.08 J. Returned energy = 0.75 x 1.08 = 0.81 J. The force increases from zero, so its mean is half its maximum."),
  item("spring-launch", "materials", 4, "synoptic",
    "A horizontal spring of constant 400 N m^-1 is compressed by 0.050 m. It launches a 0.20 kg cart. During launch, 0.10 J is dissipated. Calculate the cart's speed as the spring returns to its natural length.",
    ["Stored energy = 0.5 x 400 x 0.050^2 = 0.50 J.", "Kinetic energy = 0.50 - 0.10 = 0.40 J.", "v = sqrt(2 x 0.40 / 0.20) = 2.0 m s^-1."],
    "Stored energy = 0.5 x 400 x 0.050^2 = 0.50 J. Kinetic energy = 0.50 - 0.10 = 0.40 J. v = sqrt(2 x 0.40 / 0.20) = 2.0 m s^-1."),

  item("coherence-meaning", "waves", 7, "recall",
    "State the two requirements for two sources to be coherent.",
    ["The sources have the same frequency.", "They maintain a constant phase difference."],
    "The sources have the same frequency and maintain a constant phase difference."),
  item("refraction-frequency", "waves", 1, "explanation",
    "Light passes from air into glass where its speed is lower. Explain what happens to its frequency and wavelength.",
    ["Frequency is unchanged because it is fixed by the source.", "From v = f lambda, lower speed at fixed frequency means shorter wavelength."],
    "Frequency is unchanged because it is fixed by the source. From v = f lambda, lower speed at fixed frequency means shorter wavelength."),
  item("string-third-harmonic", "waves", 3, "application",
    "A string fixed at both ends has length 0.90 m. A stationary pattern has three equal loops. Wave speed is 120 m s^-1. Calculate its frequency.",
    ["Each loop spans half a wavelength, so lambda = 2 x 0.90 / 3 = 0.60 m.", "f = 120 / 0.60 = 200 Hz."],
    "Each loop spans half a wavelength, so lambda = 2 x 0.90 / 3 = 0.60 m. f = 120 / 0.60 = 200 Hz."),
  item("tir-direction", "waves", 4, "misconception",
    "A ray travels from air into glass at an incidence angle of 70 degrees. Glass has critical angle 42 degrees at a glass-air boundary. A student predicts total internal reflection because 70 exceeds 42. Explain why this prediction is wrong.",
    ["Total internal reflection requires travel from higher to lower refractive index.", "This ray travels from air into glass, so the critical-angle condition does not apply."],
    "Total internal reflection requires travel from higher to lower refractive index. This ray travels from air into glass, so the critical-angle condition does not apply."),
  item("grating-wavelength", "waves", 2, "calculation",
    "Light of wavelength 520 nm falls on a grating. The second-order maximum appears at 25.5 degrees. Use sin(25.5 degrees) = 0.431. Calculate the number of lines per mm of the grating, and state the highest order visible.",
    ["d = n lambda / sin(theta) = 2 x 520e-9 / 0.431 = 2.41e-6 m.", "Lines per mm = 1/(d x 1000) = 414 lines per mm.", "Highest order: n_max = floor(d/lambda) = floor(4.64) = 4; check sin(theta) stays within 1: n = 4 gives sin(theta) = 4 x 520e-9/2.41e-6 = 0.863, visible."],
    "d = nλ/sinθ = 2 × 520×10⁻⁹/0.431 = 2.41×10⁻⁶ m, giving 1/(2.41×10⁻³ mm) ≈ 414 lines per mm. The highest visible order satisfies d/λ = 4.64, so n = 4 is the highest complete order (sinθ = 0.863 < 1)."),
  item("noise-cancellation-seat", "waves", 7, "transfer",
    "Two in-phase loudspeakers emit sound of wavelength 0.80 m. At one seat their path lengths are 3.2 m and 4.4 m. Assume equal amplitudes at the seat. Predict the sound intensity there relative to either speaker alone, and explain why moving the seat can change it.",
    ["Path difference = 1.2 m = 1.5 wavelengths.", "An odd number of half wavelengths gives destructive interference, ideally zero intensity for equal amplitudes.", "Moving the seat changes path difference and therefore phase difference."],
    "Path difference = 1.2 m = 1.5 wavelengths. An odd number of half wavelengths gives destructive interference, ideally zero intensity for equal amplitudes. Moving the seat changes path difference and therefore phase difference."),
  item("grating-photon", "waves", 2, "synoptic",
    "A grating spacing of 2.00e-6 m gives a first-order maximum with sin(theta) = 0.250. Determine the wavelength.",
    ["lambda = d sin(theta) = 5.00e-7 m."],
    "For first order, lambda = d sin(theta) = 5.00e-7 m.", undefined, [{
      prompt: "Using your wavelength from part (a), determine the photon energy. Use h = 6.63e-34 J s and c = 3.00e8 m s^-1. Show the relationship used.",
      marks: 2, scheme: ["E = hc / lambda.", "E = 3.98e-19 J; allow correct follow-through from part (a)."],
      answer: "E = hc / lambda = 6.63e-34 x 3.00e8 / 5.00e-7 = 3.98e-19 J.",
      specPointIds: [sp("quantum", 1)], capabilityIds: ["phys.quantum.sp-01"], aos: ["AO2"],
    }]),

  item("work-function", "quantum", 1, "recall",
    "Define the work function of a metal.",
    ["The minimum energy needed to remove an electron from the metal surface."],
    "The work function is the minimum energy needed to remove an electron from the metal surface."),
  item("threshold-darkness", "quantum", 2, "explanation",
    "Monochromatic light below a metal's threshold frequency produces no photoelectrons. Explain why increasing its intensity does not cause emission in the single-photon model.",
    ["Photon energy hf is less than the work function.", "One electron absorbs energy from one photon in this model.", "Increasing intensity increases photon number, not individual photon energy."],
    "Photon energy hf is less than the work function. One electron absorbs energy from one photon in this model. Increasing intensity increases photon number, not individual photon energy."),
  item("stopping-potential-change", "quantum", 1, "application",
    "The incident photon energy increases from 4.0 eV to 5.5 eV for a metal with work function 2.0 eV. Determine the change in stopping potential.",
    ["Maximum kinetic energies are 2.0 eV and 3.5 eV.", "Stopping potential increases by 1.5 V."],
    "Maximum kinetic energies are 2.0 eV and 3.5 eV. Since eVs equals maximum kinetic energy, stopping potential increases by 1.5 V."),
  item("brighter-photoelectric", "quantum", 3, "misconception",
    "Light above threshold shines on a metal. Its frequency is fixed while intensity doubles. A student says the fastest emitted electrons have twice the kinetic energy. Correct this claim and predict the saturation current.",
    ["Maximum kinetic energy is unchanged because photon energy and work function are unchanged.", "Twice as many photons arrive each second, so saturation current doubles if collection and efficiency are unchanged."],
    "Maximum kinetic energy is unchanged because photon energy and work function are unchanged. Twice as many photons arrive each second, so saturation current doubles if collection and efficiency are unchanged."),
  item("photoelectron-energy", "quantum", 1, "calculation",
    "Light of frequency 8.00e14 Hz falls on a metal of work function 3.20e-19 J. Calculate the maximum photoelectron kinetic energy. Use h = 6.63e-34 J s.",
    ["Photon energy hf = 5.304e-19 J.", "Maximum kinetic energy = hf - work function.", "Maximum kinetic energy = 2.10e-19 J."],
    "Photon energy hf = 5.304e-19 J. Maximum kinetic energy = hf - work function = 5.304e-19 - 3.20e-19 = 2.10e-19 J."),
  item("uv-surface-sensor", "quantum", 2, "transfer",
    "A vacuum sensor must emit electrons when illuminated at 300 nm but remain inactive at 500 nm. Candidate coatings have work functions 2.0 eV, 3.0 eV and 4.5 eV. Choose a coating and justify it. Use hc = 1240 eV nm and the single-photon model.",
    ["Photon energies are 1240/300 = 4.13 eV and 1240/500 = 2.48 eV.", "Choose the 3.0 eV coating.", "Its work function is below 4.13 eV but above 2.48 eV."],
    "Photon energies are 1240/300 = 4.13 eV and 1240/500 = 2.48 eV. Choose the 3.0 eV coating. Its work function is below 4.13 eV but above 2.48 eV."),
  item("electron-diffraction-voltage", "quantum", 5, "synoptic",
    "Non-relativistic electrons accelerated from rest through voltage V produce a diffraction pattern. The voltage is increased to 4V. Use energy and momentum relationships to predict the factor by which their de Broglie wavelength changes.",
    ["Kinetic energy eV = p^2/(2m).", "Quadrupling V doubles momentum p.", "lambda = h/p, so wavelength halves."],
    "Kinetic energy eV = p^2/(2m). Quadrupling V doubles momentum p. Since lambda = h/p, wavelength halves."),

  item("emf-definition", "electric-circuits", 1, "recall",
    "Define the electromotive force of a source in terms of energy and charge.",
    ["Energy supplied by the source per unit charge passing through it."],
    "Electromotive force is the energy supplied by the source per unit charge passing through it.", "phys.circuit.emf"),
  item("lamp-non-ohmic", "electric-circuits", 5, "explanation",
    "As voltage across a filament lamp rises, current increases less than proportionally. Explain this behaviour in terms of the metal filament.",
    ["The filament temperature rises.", "Greater lattice vibration increases electron scattering.", "Resistance rises, so current is not proportional to voltage."],
    "The filament temperature rises. Greater lattice vibration increases electron scattering. Resistance rises, so current is not proportional to voltage."),
  item("loaded-divider", "electric-circuits", 2, "application",
    "Two 2.0 kilohm resistors are in series across an ideal 12 V supply. A 2.0 kilohm load is connected in parallel with the lower resistor. Calculate the voltage across the load.",
    ["The parallel resistance is 1.0 kilohm.", "Total series resistance is 3.0 kilohm.", "Load voltage = 12 x 1/3 = 4.0 V."],
    "The parallel resistance is 1.0 kilohm. Total series resistance is 3.0 kilohm. Load voltage = 12 x 1/3 = 4.0 V.", "phys.circuit.divider"),
  item("current-used-up", "electric-circuits", 1, "misconception",
    "Two unequal resistors are connected in series to a cell. A student says less current leaves the larger resistor because it uses more current. Explain the error.",
    ["Steady current is the same at every point in a series circuit by charge conservation.", "Resistors transfer energy from charges; they do not consume charge."],
    "Steady current is the same at every point in a series circuit by charge conservation. Resistors transfer energy from charges; they do not consume charge.", "phys.circuit.charge"),
  item("cell-internal-resistance", "electric-circuits", 2, "calculation",
    "A student plots terminal voltage V against current I for a cell and gets a straight line from (0 A, 1.50 V) to (0.60 A, 1.20 V). Using the line's gradient and intercept, determine the cell's emf and internal resistance.",
    ["The intercept at I = 0 is the emf: 1.50 V.", "The gradient magnitude equals r: (1.50 - 1.20)/0.60 = 0.50 ohm."],
    "Using V = emf - Ir, the intercept at I = 0 gives emf = 1.50 V. The gradient is (1.20 - 1.50)/(0.60 - 0) = -0.50 V A^-1. Hence r = -gradient = 0.50 ohm.", "phys.circuit.internal"),
  item("cold-room-alarm", "electric-circuits", 2, "transfer",
    "An ideal 6.0 V supply feeds a series combination of a 4.0 kilohm resistor and a thermistor. An alarm measures voltage across the fixed resistor and triggers below 2.0 V. Thermistor resistance is 2.0 kilohm when warm and 10 kilohm when cold. Predict whether cooling triggers the alarm. Assume the alarm draws negligible current.",
    ["Warm voltage = 6 x 4/(4+2) = 4.0 V.", "Cold voltage = 6 x 4/(4+10) = 1.71 V.", "Cooling triggers the alarm because the cold voltage is below 2.0 V."],
    "Warm voltage = 6 x 4/(4+2) = 4.0 V. Cold voltage = 6 x 4/(4+10) = 1.71 V. Cooling triggers the alarm because the cold voltage is below 2.0 V.", "phys.circuit.divider"),
  item("heater-water", "electric-circuits", 4, "synoptic",
    "A 12 V supply drives a 6.0 ohm immersion heater for 300 s. The heater warms 0.20 kg of water, with 70% of electrical energy reaching the water. Use c = 4200 J kg^-1 K^-1. Calculate the temperature rise.",
    ["Power = V^2/R = 24 W.", "Energy reaching water = 0.70 x 24 x 300 = 5040 J.", "Temperature rise = 5040/(0.20 x 4200) = 6.0 K."],
    "Power = V^2/R = 24 W. Energy reaching water = 0.70 x 24 x 300 = 5040 J. Temperature rise = 5040/(0.20 x 4200) = 6.0 K."),

  item("magnetic-no-work", "fields", 5, "explanation",
    "An electron enters a uniform magnetic field with its velocity perpendicular to the field. Explain why its speed stays constant although it accelerates. Neglect other forces and radiation.",
    ["Magnetic force is perpendicular to velocity.", "The force does no work, so kinetic energy and speed remain constant.", "Velocity direction changes, giving centripetal acceleration."],
    "Magnetic force is perpendicular to velocity. The force does no work, so kinetic energy and speed remain constant. Velocity direction changes, giving centripetal acceleration."),
  item("orbit-height-trap", "fields", 4, "misconception",
    "A satellite orbits at a height equal to Earth's radius R above the surface. A student predicts its gravitational field strength is the surface value g because its height is R. Determine the correct field strength and explain.",
    ["Distance from Earth's centre is 2R.", "Inverse-square dependence gives field strength g/4."],
    "Distance from Earth's centre is 2R. Inverse-square dependence gives field strength g/4."),
  item("coil-flux-rate", "fields", 8, "calculation",
    "A 200-turn coil has flux per turn decreasing uniformly from 3.0e-4 Wb to 1.0e-4 Wb in 0.050 s. Calculate the magnitude of induced emf. State how the induced current's field relates to this change.",
    ["Change in flux linkage = 200 x 2.0e-4 = 0.040 Wb turns.", "Emf magnitude = 0.040 / 0.050 = 0.80 V.", "The induced field opposes the decrease in flux."],
    "Change in flux linkage = 200 x 2.0e-4 = 0.040 Wb turns. Emf magnitude = 0.040 / 0.050 = 0.80 V. The induced field opposes the decrease in flux."),
  item("mass-spectrometer-ratio", "fields", 6, "transfer",
    "Two positive ion species enter the same uniform magnetic field at the same speed, perpendicular to it. Species A has mass m and charge e. Species B has mass 4m and charge 2e. Determine the ratio of their path radii rB/rA.",
    ["Equating qvB = mv^2/r gives r = mv/(qB).", "At fixed speed and field, radius is proportional to m/q.", "rB/rA = 4/2 = 2."],
    "Equating qvB = mv^2/r gives r = mv/(qB). At fixed speed and field, radius is proportional to m/q. rB/rA = 4/2 = 2."),
  item("gas-temperature-trap", "thermal", 3, "misconception",
    "A sealed rigid flask of ideal gas is heated from 20 degrees C to 40 degrees C. A student says the pressure doubles. Calculate the actual pressure ratio and explain the error.",
    ["At fixed amount and volume, pressure is proportional to absolute temperature.", "Temperatures are 293 K and 313 K.", "Pressure ratio = 313/293 = 1.068, not 2."],
    "At fixed amount and volume, pressure is proportional to absolute temperature. Temperatures are 293 K and 313 K. Pressure ratio = 313/293 = 1.068, not 2."),
  item("molecular-energy", "thermal", 5, "calculation",
    "The mean translational kinetic energy of a nitrogen molecule is 6.21e-21 J. Using k = 1.38e-23 J K^-1, find the gas temperature, then determine the total translational kinetic energy of one mole at this temperature (N_A = 6.02e23).",
    ["Rearranging 3kT/2 gives T = 2E/(3k) = 2 x 6.21e-21/(3 x 1.38e-23) = 300 K.", "Total per mole = N_A x 6.21e-21 = 3.74e3 J."],
    "T = 2E/(3k) = 2 × 6.21×10⁻²¹ / (3 × 1.38×10⁻²³) = 300 K. One mole holds N_A × 6.21×10⁻²¹ = 6.02×10²³ × 6.21×10⁻²¹ ≈ 3.74×10³ J of translational kinetic energy."),
  item("background-decay", "nuclear", 3, "calculation",
    "A source's background-corrected count rate is 1600 counts per minute at t = 0. The corrected rate has fallen to 100 counts per minute after 24 minutes. Determine the half-life and the corrected rate at t = 30 minutes.",
    ["The rate falls by a factor of 16 = 2^4, so four half-lives elapse in 24 minutes.", "Half-life = 24/4 = 6 minutes.", "At 30 minutes (five half-lives) the corrected rate is 1600/2^5 = 50 counts per minute."],
    "1600 → 100 is a factor of 16 = 2⁴, so four half-lives pass in 24 minutes: t½ = 6 minutes. At t = 30 minutes, five half-lives have passed and the corrected rate is 1600/2⁵ = 50 counts per minute."),
  item("decay-randomness", "nuclear", 3, "explanation",
    "A sample has a half-life of one hour. Explain why this does not mean that each nucleus decays exactly one hour after it was formed.",
    ["Decay of an individual nucleus is random with constant probability per unit time.", "Half-life describes the expected halving of a large undecayed population."],
    "Decay of an individual nucleus is random with constant probability per unit time. Half-life describes the expected halving of a large undecayed population."),
  item("rebound-impulse", "momentum", 4, "calculation",
    "A 0.060 kg ball approaches a wall at +20 m s^-1 and rebounds at -15 m s^-1. Contact lasts 0.010 s. Calculate the average force on the ball, including its direction.",
    ["Change in velocity = -15 - 20 = -35 m s^-1.", "Change in momentum = 0.060 x (-35) = -2.1 kg m s^-1.", "Average force = -2.1 / 0.010 = -210 N, away from the wall."],
    "Change in velocity = -15 - 20 = -35 m s^-1. Change in momentum = 0.060 x (-35) = -2.1 kg m s^-1. Average force = -2.1 / 0.010 = -210 N, away from the wall."),
  item("airbag-force", "momentum", 4, "transfer",
    "Two restraint designs stop the same test dummy from the same speed without rebound. Design B doubles the stopping time. Explain the effect on impulse and average force. Can you deduce the peak force from this information?",
    ["The momentum change and impulse are the same.", "Doubling time halves the average force.", "Peak force cannot be determined without the force-time profile."],
    "The momentum change and impulse are the same. Doubling time halves the average force. Peak force cannot be determined without the force-time profile."),
  item("shm-sign", "circular-shm", 3, "misconception",
    "An oscillator has acceleration a = +16x, with SI units. A student identifies SHM because acceleration is proportional to displacement. Explain why this is insufficient.",
    ["SHM requires acceleration directed towards equilibrium, opposite to displacement.", "The positive coefficient gives acceleration away from equilibrium, so this is not SHM."],
    "SHM requires acceleration directed towards equilibrium, opposite to displacement. The positive coefficient gives acceleration away from equilibrium, so this is not SHM."),
  item("shm-period-from-gradient", "circular-shm", 4, "calculation",
    "An acceleration-displacement graph for an oscillator is a straight line through the origin with gradient -25 s^-2. Calculate its period.",
    ["The gradient is -omega^2, so omega = 5.0 rad s^-1.", "T = 2 pi / 5.0 = 1.26 s."],
    "The gradient is -omega^2, so omega = 5.0 rad s^-1. T = 2 pi / 5.0 = 1.26 s."),
];
