import type { DoubleMarkedAnswer } from "@/domain/double-marked-corpus";

// Explicitly synthetic rows make the review surface useful without pretending
// that invented marks are teacher or examiner labels. Imported real rows keep
// their own provenance and replace these from the UI.
export const DEMO_DOUBLE_MARKED_ANSWERS: DoubleMarkedAnswer[] = [
  {
    id: "demo:chemistry:001",
    questionId: "demo-q:chemistry-calculation",
    partId: "demo-q:chemistry-calculation:a",
    subjectId: "wjec-alevel-chemistry",
    prompt: "Calculate the concentration of the sulfuric acid.",
    answer: "n = cV = 0.0025 mol, then divide by the titre volume to get 0.0558 mol dm⁻³.",
    maxMarks: 4,
    markerA: { markerId: "marker-a", awarded: 4, note: "Synthetic agreement example." },
    markerB: { markerId: "marker-b", awarded: 4, note: "Synthetic agreement example." },
    provenance: "synthetic-demo",
  },
  {
    id: "demo:chemistry:002",
    questionId: "demo-q:chemistry-equilibrium",
    partId: "demo-q:chemistry-equilibrium:b",
    subjectId: "wjec-alevel-chemistry",
    prompt: "Explain the effect of increasing temperature on the equilibrium yield.",
    answer: "The equilibrium moves because the temperature changes.",
    maxMarks: 3,
    markerA: { markerId: "marker-a", awarded: 1 },
    markerB: { markerId: "marker-b", awarded: 2 },
    provenance: "synthetic-demo",
  },
  {
    id: "demo:physics:001",
    questionId: "demo-q:physics-shm",
    partId: "demo-q:physics-shm:a",
    subjectId: "wjec-alevel-physics",
    prompt: "State the condition for simple harmonic motion.",
    answer: "The acceleration is proportional to displacement and directed towards the equilibrium position.",
    maxMarks: 2,
    markerA: { markerId: "marker-a", awarded: 2 },
    markerB: { markerId: "marker-b", awarded: 2 },
    provenance: "synthetic-demo",
  },
  {
    id: "demo:maths:001",
    questionId: "demo-q:maths-quadratic",
    partId: "demo-q:maths-quadratic:a",
    subjectId: "wjec-alevel-maths",
    prompt: "Show that the quadratic has two distinct real roots.",
    answer: "b² − 4ac = (k + 3)² − 16k = k² − 10k + 9.",
    maxMarks: 3,
    markerA: { markerId: "marker-a", awarded: 3 },
    markerB: { markerId: "marker-b", awarded: 2 },
    provenance: "synthetic-demo",
  },
  {
    id: "demo:biology:001",
    questionId: "demo-q:biology-osmosis",
    partId: "demo-q:biology-osmosis:b",
    subjectId: "wjec-alevel-biology",
    prompt: "Evaluate the reliability of the investigation.",
    answer: "The repeats improve reliability, although the sample is small. Overall the trend is useful but limited.",
    maxMarks: 4,
    markerA: { markerId: "marker-a", awarded: 2 },
    markerB: { markerId: "marker-b", awarded: 3 },
    adjudication: { awarded: 3, note: "Synthetic adjudication example." },
    provenance: "synthetic-demo",
  },
  {
    id: "demo:maths:002",
    questionId: "demo-q:maths-calculus",
    partId: "demo-q:maths-calculus:a",
    subjectId: "wjec-alevel-maths",
    prompt: "Calculate the acceleration of the system.",
    answer: "Using F = ma gives a = 2.4 m s⁻².",
    maxMarks: 2,
    markerA: { markerId: "marker-a", awarded: 2 },
    markerB: { markerId: "marker-b", awarded: 2 },
    provenance: "synthetic-demo",
  },
  {
    id: "demo:biology:002",
    questionId: "demo-q:biology-chi-squared",
    partId: "demo-q:biology-chi-squared:a",
    subjectId: "wjec-alevel-biology",
    prompt: "Calculate the chi-squared value and state the conclusion.",
    answer: "The value is 5.2, so the result is significant.",
    maxMarks: 3,
    markerA: { markerId: "marker-a", awarded: 2 },
    markerB: { markerId: "marker-b", awarded: 1 },
    provenance: "synthetic-demo",
  },
  {
    id: "demo:physics:002",
    questionId: "demo-q:physics-photoelectric",
    partId: "demo-q:physics-photoelectric:a",
    subjectId: "wjec-alevel-physics",
    prompt: "Calculate the maximum kinetic energy of the emitted electrons.",
    answer: "E = hf − φ = 3.1 × 10⁻¹⁹ J.",
    maxMarks: 3,
    markerA: { markerId: "marker-a", awarded: 3 },
    markerB: { markerId: "marker-b", awarded: 3 },
    provenance: "synthetic-demo",
  },
];

